### ISSUE TITLE
[Demo] WPF MediaElement doesn't play video from HTTPS source

### ISSUE THREAD

**Issue by Tyrrrz** [Tyrrrz/YoutubeExplode#1]
... because it sucks.
Apparently it's a known issue and cannot be resolved with the native MediaElement control, because it doesn't support streaming sources over HTTPS and there's no way to set source from a stream.
One option would be to download video before playing, but it's a terrible approach for obvious reasons.
Another (better) option would be to use a different control, for which I'd like to hear suggestions.

**Comment by Tyrrrz** [comment]
Screw it

**Comment by shiregator** [comment]
I'm running into the same problem.  If you found a good solution I'd be interested in learning it.  Thanks!

**Comment by Tyrrrz** [comment]
I've used https://github.com/unosquare/ffmediaelement for a while but then just decided to remove this altogether.

**Comment by shiregator** [comment]
I just found a way to do it using Universal Windows Platform (UWP).  This implementation successfully plays video from an https source.  
https://github.com/kiewic/MediaElementWithHttpClient
