### ISSUE TITLE
'My mix' playlist IDs incorrectly assumed invalid

### ISSUE THREAD

**Issue by abhay991** [Tyrrrz/YoutubeExplode#103]
There is an exception to parse if youtube playlist id contains '-'

Eg:
https://www.youtube.com/watch?v=test123&list=Test123-2B02VY

If I remove - it works well but there is no playlist as of such (though atleast it does send requests as i can see via fiddler). So maybe you have to fix regex.

**Comment by abhay991** [comment]
also will be great if you add property of VideoTitle or VideoName in streamInfoSet.Video

**Comment by Tyrrrz** [comment]
Can you give an example of an actual playlist that causes the issue?

**Comment by abhay991** [comment]
https://www.youtube.com/watch?v=U-ty-2B02VY&list=RDMMU-ty-2B02VY

**Comment by Tyrrrz** [comment]
What kind of playlist is this? My mix?

**Comment by abhay991** [comment]
i guess this is playlist auto made by youtube for most watched songs from my account.

**Comment by Tyrrrz** [comment]
Thanks for the report

**Comment by abhay991** [comment]
can you please add title property within same request of downloading/grabbing video/muxed/audio. (as i am sure it's possible without doing multiple request once to grab link and once to grab title).
Also I have checked YoutubeExtractor and compared it with your library. Difference is YoutubeExtractor sometime fails to extract link for some video and your extract ratio of success is much better but sometimes it's too slow compared to YoutubeExtractor. 

I can't make these small changes even after downloading your source. I can't set framework and have many other issues.

**Comment by Tyrrrz** [comment]
No plans to do that right now, sorry. If you think it's too slow, please raise a separate issue.

**Comment by abhay991** [comment]
Alright and thanks for such a great library.

**Comment by Tyrrrz** [comment]
Thank you for using it.
