### ISSUE TITLE
Add method to check if a video has been country blocked

### ISSUE THREAD

**Issue by Giggitybyte** [Tyrrrz/YoutubeExplode#104]
It would be very useful (for me, anyways) to be able to check if a video has been blocked in my country *before* I attempt to download it. I feel a simple method added to the `Video` class that would return a boolean would do the trick.

I hope you'd be able to do this with relative ease 👍

**Comment by Tyrrrz** [comment]
Apparently, it should be available on watch page:
https://github.com/rg3/youtube-dl/blob/870f3bfc635586ba76a242f1a2f3fbac2c99bad5/youtube_dl/extractor/youtube.py#L1608

**Comment by Giggitybyte** [comment]
Any news on this? It's been a good long while.

**Comment by Tyrrrz** [comment]
Didn't prioritize it yet, mostly because I struggle to find the use case, considering you can always try/catch.
Also, in case you're wondering, #155 does not have `regionsAllowed` anywhere.

**Comment by Giggitybyte** [comment]
Well, my use case has changed in these few months, but basically I'd like to have a way check specifically if a video is country blocked so I could grab the data from the YouTube API instead. The main reason I'd want to do this is because there's currently no way to get information about a video with YoutubeExplode if a video is unavailable; all that is given is an exception.

I suppose this could go in a different issue, but that's all I really want; as much info as possible even if the video is unavailable as well as some sort of way to determine *why* it's unavailable if YouTube provides it for that video. 
Perhaps a solution that is more elegant than #154 with nullable types and such would be the best way to go.

**Comment by Tyrrrz** [comment]
What kind of information do you need? There are certain things that can be obtained even if the video is unavailable.

Regarding edit: good question. Perhaps they're using a different method.

**Comment by Tyrrrz** [comment]
The title and thumbs can be scraped from oembed, not sure about channel name.

YouTube generally doesn't provide much information, but what it does provide is shown in the exception already.

**Comment by Giggitybyte** [comment]
Alrighty then, whatever you can implement then would be great to have.

**Comment by Tyrrrz** [comment]
Closed in favor of #163

**Comment by Giggitybyte** [comment]
Looks like that'd be good enough.
