### ISSUE TITLE
YoutubeClient does not contain a definition for GetVideoInfoAsync

### ISSUE THREAD

**Issue by TEDSON007** [Tyrrrz/YoutubeExplode#105]
I fell at the first hurdle with this error

`string videoId = "3u05B_mUgQU";

 var client = new YoutubeClient();
 var videoInfo = await client.GetVideoInfoAsync(videoId);`

**Comment by Tyrrrz** [comment]
You are probably using an outdated example, there is no `GetVideoInfoAsync` anymore.

**Comment by TEDSON007** [comment]
Thanks, I found GetVideoMediaStreamInfosAsync.
Sorry to waste your time.

**Comment by Tyrrrz** [comment]
Don't worry about it.

**Comment by TEDSON007** [comment]
Are there updated examples?
I cannot find any.

**Comment by Tyrrrz** [comment]
Check the project's readme -- https://github.com/Tyrrrz/YoutubeExplode#usage
