### ISSUE TITLE
Speeds difference

### ISSUE THREAD

**Issue by abhay991** [Tyrrrz/YoutubeExplode#106]
I am not sure but if anyone noticed difference of speed between muxed and only (video/audio) download url. I tried many videos and get only fast speed for muxed videos and very slow (100 - 200kbps) for video or audio only url. I tired with other download manager and still get slow speed but when i tried to get video only url of same links from other source then i get full speed. I am not sure where issue actually is.

**Comment by Tyrrrz** [comment]
Yes, non-muxed streams are rate-limited. Use `DownloadMediaStreamAsync` to circumvent the speed limitations.

**Comment by abhay991** [comment]
Okay I have checked and it's working all good with the way you said but i have made wrapper class for my  download manager (with pause and resume support) so i guess i will have to stick to that as `DownloadMediaStreamAsync` is event-free & without pause/resume functionality. 

I guess i will try to check your source code and see what i can get then.

**Comment by Tyrrrz** [comment]
But is `DownloadMediaStreamAsync` downloading fast for you?

**Comment by abhay991** [comment]
yes it's downloading really fast.

**Comment by Tyrrrz** [comment]
Then you probably didn't set your request up correctly. Did you remember to put the range header in your HTTP request?

**Comment by abhay991** [comment]
I tried to add range & tried without it as well. I am not getting speed at all for any videos. This is only for Videos or Audios not Muxed Urls.

**Comment by Tyrrrz** [comment]
Well it should work, since it does in YoutubeExplode 😛

**Comment by abhay991** [comment]
but then you said speed rate is limited for audio only or video only urls.

**Comment by abhay991** [comment]
imo i am still unable to find proper solution. don't get speed at all.

**Comment by Tyrrrz** [comment]
It should work if you replicate the code properly
