### ISSUE TITLE
Get how long until stream link expires

### ISSUE THREAD

**Issue by TEDSON007** [Tyrrrz/YoutubeExplode#107]
In my efforts, before discovering this superb library, I noticed a parameter in the video page source 'expires=47764674' or similar.

Wondering if that relates to when the access denied page will appear, and if it could be utilized to get an actual timespan.

It would be very useful to me, maybe others.

**Comment by Tyrrrz** [comment]
Yeah I can see why it could be useful. Can you verify the format?

**Comment by abhay991** [comment]
1523027725 is Timestamp when it will expire. To get exact time for it you can use https://www.epochconverter.com/

**Comment by TEDSON007** [comment]
Sorry that's not what you meant is it.

According to https://www.epochconverter.com/

1523027725 converts as a unix timestamp

**Comment by TEDSON007** [comment]
Although I'm unsure how it would work, since the time is an hour before I got it, in uk

**Comment by abhay991** [comment]
https://www.epochconverter.com/clock should be in sync with that time i guess?

**Comment by TEDSON007** [comment]
So in uk it gas offset of +3600 (1 hour) but it still must just be the time from when it will expire.
No indication of expire time. :(

**Comment by TEDSON007** [comment]
Actually we have this expire%26mv%3Dm%26mt%3D1523005960

Friday, April 6, 2018 9:12:40 AM

And this expire%3D1523027725

Friday, April 6, 2018 3:15:25 PM

**Comment by Tyrrrz** [comment]
Be aware when posting steam URLs that it contains your IP address

**Comment by TEDSON007** [comment]
I got a link and kept trying it every hour or so, it played 6 times after the first, so at least 6 hours, access denied after that.

**Comment by Tyrrrz** [comment]
So did it match the expiry date?

**Comment by TEDSON007** [comment]
It did.
In retrospect I should have tested more at the same time, I wil tomorrow.

**Comment by TEDSON007** [comment]
Tested another 10 links, all were dead after timespan between the 2 timestamps.
