### ISSUE TITLE
Grabbing high quality streams with audio AND video track?

### ISSUE THREAD

**Issue by WhiteLionATX** [Tyrrrz/YoutubeExplode#108]
Grabbing a list of muxed streams only returns 720p as max quality result. (Even on 4k videos).
Grabbing a list of video streams returns wished quality but without audio. :(
Whats the solution to get high quality streams with audio? - Do I need to grab video and audio track and mix them together with 3rd party software ? 
Greetings Olli

**Comment by SlowLogicBoy** [comment]
Download Audio and Video separately and combine them using tool such as FFmpeg:
https://gist.github.com/SlowLogicBoy/c6e76e1c4d85cddfe414dd436f5a82d8
Ups.. Looks like I need to update it a bit.

**Comment by Tyrrrz** [comment]
Btw, you can now use [YoutubeExplode.Converter](https://github.com/Tyrrrz/YoutubeExplode.Converter) to simplify muxing. You will still have to redistribute FFmpeg with it though.
