### ISSUE TITLE
Current implementation of GetPlaylistInfoAsync caps out at 200 videos

### ISSUE THREAD

**Issue by Tyrrrz** [Tyrrrz/YoutubeExplode#11]
Looks like the youtube's frontend also caps out at 200 videos on the embed page.
No continuation token.
One test is failing.

**Comment by dr-BEat** [comment]
Do you have an example playlist that contains more then 200 videos + some delete ones?
I want to see how the response for delete videos looks like.

**Comment by Tyrrrz** [comment]
I don't remember which one I used, but here's one I just found: PLJJKlisIfpaZKhQQiewSnzt3eqEtVIsIg
It claims to have 550 videos, but the first batch returns 197.

**Comment by dr-BEat** [comment]
Yeah, there is not hint about the deleted videos at all...
