### ISSUE TITLE
Get Audio MP3

### ISSUE THREAD

**Issue by darkdoctor** [Tyrrrz/YoutubeExplode#111]
Greetings Dear.

I tried to get only the audio stream for youtube videos but till now only succeed with AAC.
AAC seems fine with Android 5.0+ but not with Jelly Bean and Kitkat Devices.

Can you please help me.

**Comment by Tyrrrz** [comment]
What do you mean succeeds?

**Comment by SlowLogicBoy** [comment]
AAC playback is not supported by older android devices I guess what he means.
Youtube doesn't give you MP3 so you will have to convert from format that youtube gives to mp3 yourself.

**Comment by darkdoctor** [comment]
Yeah, formatting I know that. 

But since I saw an option to query the audio == MP3 I thought there is any chance to get formated mp3.

**Comment by Tyrrrz** [comment]
Where did you find that option?

**Comment by darkdoctor** [comment]
var audio = mediaStreamInfo.Audio.FirstOrDefault(x => x.AudioEncoding == AudioEncoding.Aac);
var audio = mediaStreamInfo.Audio.FirstOrDefault(x => x.AudioEncoding == AudioEncoding.Mp3); < ---

**Comment by Tyrrrz** [comment]
Funny, I forgot that existed. 😆 
You can see from [this](https://github.com/Tyrrrz/YoutubeExplode/blob/master/YoutubeExplode/Models/MediaStreams/MediaStreamInfo.cs#L49) table that is only available in the FLV (Flash) format which is now completely deprecated.

**Comment by Tyrrrz** [comment]
According to [this](https://developer.android.com/guide/topics/media/media-formats.html#audio-formats) AAC should be supported, but you can also try Opus or Vorbis.

**Comment by Tyrrrz** [comment]
Do you need any more assistance or can I close this?

**Comment by remiX-** [comment]
Check [Tyrrrz's Sample Mp3 project](https://github.com/Tyrrrz/YoutubeMusicDownloader) too, was great help to get me going :-D
