### ISSUE TITLE
720p Muxed video on Lollipop

### ISSUE THREAD

**Issue by darkdoctor** [Tyrrrz/YoutubeExplode#113]
Hi Tyrrrz.

How are you.

I am doing an app for android and I have a video view on the background and I want to load my video from youtube.

When I set the video quality to 720p ( muxed ) I get this error : "cannot play this video".

I know that there is something about codecs, so do you know how I can play it or even any workaround.

thanks.

**Comment by Tyrrrz** [comment]
Hi
Hm, can you try to play a stream in some other format?

**Comment by darkdoctor** [comment]
There is always only one 720p muxed.

But anyway, thanks for trying to help me.

**Comment by Tyrrrz** [comment]
Hm, I'm not sure then. I  haven't used in an Android app so I don't have any experience to share.
