### ISSUE TITLE
Channel Avatar

### ISSUE THREAD

**Issue by stefancreed37** [Tyrrrz/YoutubeExplode#117]
Channel Avatar to PictureBox?

**Comment by stefancreed37** [comment]
I found the way, but how I can get channel's ID, through the video

**Comment by remiX-** [comment]
Do you mean something like [this](https://github.com/Tyrrrz/YoutubeExplode/blob/master/DemoWpf/ViewModels/MainViewModel.cs#L139)?

That's getting the channel info using the videoId.

**Comment by Tyrrrz** [comment]
Please at least check the demo projects before you ask questions.
