### ISSUE TITLE
Ads of Youtube

### ISSUE THREAD

**Issue by darkdoctor** [Tyrrrz/YoutubeExplode#119]
Greetings Tyrrz.

I am using your library for a long time now.

I am wondering if I can get also ADS from Youtube since I do not want any trouble about streaming Youtube Videos without showing their Ads :/

**Comment by Tyrrrz** [comment]
Hi darkdoctor
No, you can't do that. If you are streaming YouTube videos, you are eligible for getting into trouble anyway, ads won't save you 😉 .
