### ISSUE TITLE
Can you get the channel id from a video?

### ISSUE THREAD

**Issue by Kriste00** [Tyrrrz/YoutubeExplode#121]
Is it currently possible to get the id of the channel that uploaded the video?

If not, could it be added in a further release?

**Comment by Tyrrrz** [comment]
Have you tried `GetVideoAuthorChannelAsync`?

**Comment by Kriste00** [comment]
Oh, did not think of using the method on the client. Ithought it whould be aproperty on the video, but i guss that whould slow down the request. Thanks
