### ISSUE TITLE
Exception escapes try/catch

### ISSUE THREAD

**Issue by AhmadEgb** [Tyrrrz/YoutubeExplode#124]
Hey, when I try to download a restricted video in my country just like this:
["https://www.youtube.com/watch?v=iN8PKcNGcuI"](url)
I get an exception saying "YoutubeExplode.Exceptions.VideoUnavailableException" and the program stops working.
even that I wrote it in (try-catch) how to fix it?
Here is a part of my code(it stops at the last line)
```c#
            try
            {
                //string Path = Directory.GetCurrentDirectory();
                //GrantAccess(Path);
                var url = GetYoutubeUrl();
                if (url != "")
                {
                    var id = YoutubeClient.ParseVideoId(url); // "bnsUkE8i0tU"
                    var client = new YoutubeClient();
                    var streamInfoSet = await client.GetVideoMediaStreamInfosAsync(id);
```

**Comment by remiX-** [comment]
I've also had a few of these which kinda sucks... Can't find a way around it.
As far as I know, you can't download videos that are blocked :/ A VPN could possibly work but I haven't been bothered enough to try

**Comment by AhmadEgb** [comment]
I know, But at least there should be a way to prevent an exception and crash!

**Comment by Tyrrrz** [comment]
An exception can't escape try/catch, unless you're debugging in VS

**Comment by remiX-** [comment]
I have it encapsulated inside a try/catch and it doesn't escape and logs fine so must be another problem your side?

**Comment by SlowLogicBoy** [comment]
how does your catch looks like?

**Comment by AhmadEgb** [comment]
**Notice:**
I tried to run my program normally (Not using visual studio) and it just crashed!

Here is my code...
`        private async void LoadMusic()
        {
            try
            {
                //string Path = Directory.GetCurrentDirectory();
                //GrantAccess(Path);
                var url = GetYoutubeUrl();
                if (url != "")
                {
                    var id = YoutubeClient.ParseVideoId(url); // "bnsUkE8i0tU"
                    var client = new YoutubeClient();
                    var streamInfoSet = await client.GetVideoMediaStreamInfosAsync(id);
                    var streamInfo = streamInfoSet.Audio.WithHighestBitrate();
                    var ext = streamInfo.Container.GetFileExtension();
                    await client.DownloadMediaStreamAsync(streamInfo, Directory.GetCurrentDirectory() + "\\" + id + $".{ext}");
                    //File.WriteAllBytes(Path + video.FullName.Replace('-', '_'), video.GetBytes()
                    var inputFile = new MediaFile { Filename = Directory.GetCurrentDirectory() + "\\" + id + $".{ext}" };
                    var outputFile = new MediaFile { Filename = Directory.GetCurrentDirectory() + "\\" + id + $".{"wav"}" };
                    using (var engine = new Engine())
                    {
                        engine.GetMetadata(inputFile);
                        engine.Convert(inputFile, outputFile);
                    }
                    //axWindowsMediaPlayer1.URL = Directory.GetCurrentDirectory() + "\\" + id + $".{ext}";
                    player.SoundLocation = Directory.GetCurrentDirectory() + "\\" + id + $".{"wav"}";
                    player.Load();
                    if (!StopPlaying) player.Play();
                }
            }
            catch (InvalidCastException e) { MessageBox.Show(e.Message); }
        }`

**Comment by AhmadEgb** [comment]
I did, hope it's more clear now

**Comment by remiX-** [comment]
@SlowLogicBoy yep mine is fine too. my try/catch is same as yours - [pic](https://i.imgur.com/xWa1MTb.png)

**Comment by Tyrrrz** [comment]
Well you are only catching `InvalidCastException`
