### ISSUE TITLE
Infinite waiting

### ISSUE THREAD

**Issue by darkdoctor** [Tyrrrz/YoutubeExplode#126]
Hi Tyrrrz.

Hope you re doing fine.

I am trying to get mediastreaminfo for some videos and the Task will never return a result.

Video id : 8GKIKwAHOuc
                    mediaStreamInfo = new YoutubeExplode.YoutubeClient().GetVideoMediaStreamInfosAsync(videoInfo.YoutubeId).Result;

I keep waiting for minutes ...

**Comment by Tyrrrz** [comment]
Hi
It's probably a deadlock, make sure you `await` the task and not call `.Result`.

**Comment by Tyrrrz** [comment]
Nothing has changed. A lot of people had reported having similar issue and it was always because of deadlock.

e.g. #88 #92

**Comment by darkdoctor** [comment]
Hi.

So how I can avoid Deadlock?
Is it safe to use one YoutubeClient for different Requests?

**Comment by Tyrrrz** [comment]
Yes it's safe.
Can you show the code where you call `Explode.Search(videoId)` method?

**Comment by darkdoctor** [comment]
Hi Tyrrrz.

`            if (mediaStreamInfo == null)
            {
                Toast.MakeText(activity, $"{activity.Resources.GetString(Resource.String.please_wait_c)}",
                    ToastLength.Long).Show();

                Youtube.Explode.Search(videoInfo.YoutubeId).ContinueWith(x =>
                {
                    mediaStreamInfo = x.Result;

                    if (mediaStreamInfo == null) return;

                    activity.RunOnUiThread(() =>
                    {
                        Download(activity, mediaStreamInfo, videoInfo);
                    });
                });
            }`

`   internal static class Explode
    {
        // Static client makes some operations to not repeat, which makes loading faster.
        private static readonly YoutubeClient _client;

        static Explode() => _client = new YoutubeClient();

        internal static async Task<MediaStreamInfoSet> Search(string videoId) => await _client.GetVideoMediaStreamInfosAsync(videoId).ConfigureAwait(false);
    }`

**Comment by Tyrrrz** [comment]
You are calling `x.Result` within the same context, which causes deadlock.
You need to rewrite your code while making use of the away/async pattern instead of `Wait()` and `Result`.
Read here: https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/

**Comment by darkdoctor** [comment]
70% of videos are fine, the rest just does not work. 
Like this video : "JYGZV5FiCUM" 

:/

**Comment by Tyrrrz** [comment]
Ah. `JYGZV5FiCUM` throws an exception and because it doesn't happen on the main thread you don't see it.
This is related to #125

**Comment by darkdoctor** [comment]
YoutubeExplode.Exceptions.VideoUnavailableException: Video [JYGZV5FiCUM] is not available and cannot be processed.
Error code: 150 

Yes, just saw it now,

**Comment by Tyrrrz** [comment]
I'll mark it as duplicate, please wait until #125 is fixed.
