### ISSUE TITLE
Expose root video data

### ISSUE THREAD

**Issue by InkyQuill** [Tyrrrz/YoutubeExplode#127]
Some videos on youtube have data about loudness for normalization purposes.
It would be great if we could read this data. For now it is present in Key-Value collection received from GetVideoInfoRawAsync task, but it is private and isn't exposed in GetVideoInfoAsync task.

Maybe you can expose raw data in Video class (which is bad as Playlists and Search results don't contain this data) or make GetVideoInfoRawAsync public?

**Comment by Tyrrrz** [comment]
Don't think this will happen because this is an implementation detail and there's no guarantee we will still be using that metadata tomorrow.
