### ISSUE TITLE
Video unavailable

### ISSUE THREAD

**Issue by darkdoctor** [Tyrrrz/YoutubeExplode#130]
Hi Tyrrz.

How are you ?

I thought that this issue got fixed maybe a week before.

YoutubeExplode.Exceptions.VideoUnavailableException: Video [ceKiHr4xbe8] is not available and cannot be processed. Code: 150. Reason: <a href="http://www.youtube.com/watch?v=ceKiHr4xbe8&feature=player_embedded" target="_blank">Watch this video on YouTube.</a> Playback on other websites has been disabled by the video owner..

**Comment by Tyrrrz** [comment]
This video is not available in my country. Maybe it's the same for you.

**Comment by remiX-** [comment]
Same for me, not available in my country
