### ISSUE TITLE
 Additional video sorting when searching

### ISSUE THREAD

**Issue by balasratran** [Tyrrrz/YoutubeExplode#133]
Hi,
In url search does it have the option to arrange the video?
`https://www.youtube.com/search_ajax?style=json&search_query={query}&page={page}&hl=en`
For example:
`https://www.youtube.com/search_ajax?style=json&search_query={query}&page={page}&hl=en&sort=date`

**Comment by Tyrrrz** [comment]
No, `sort=date` doesn't do anything and I doubt that endpoint accepts similar options at all.

**Comment by matteofabbri** [comment]
You if there is a way to return all video from a channel ?

**Comment by Tyrrrz** [comment]
@matteofabbri 
[`GetChannelUploadsAsync`](https://github.com/Tyrrrz/YoutubeExplode/blob/54801b5a96f4931260d8e6a407ffccdd7a9f24b1/YoutubeExplode/IYoutubeClient.cs#L82)?
