### ISSUE TITLE
Playing m3u8 files in windows media player.

### ISSUE THREAD

**Issue by Kajirinn** [Tyrrrz/YoutubeExplode#134]
Hey there,

I'm trying to play a livestream directly in windows media player. So far everything went smooth and normal videos are working just fine, but I'm having trouble with m3u8 files. If I try to get a normal audio url from a livestream; it only plays 5 seconds and `mediaplayer.Url = streamInfoSet.HlsLiveStreamUrl;` also isn't working.

Thanks in advance,

Kaji~

**Comment by Kajirinn** [comment]
If that doesn't work, what would be able to play those files?

**Comment by Tyrrrz** [comment]
This question isn't really related to this library. Have you tried other players such as VLC?
