### ISSUE TITLE
Possible Solution for Rate Limited Stream

### ISSUE THREAD

**Issue by SlowLogicBoy** [Tyrrrz/YoutubeExplode#135]
Hey, I found a hacky way that could replace `DownloadMediaStreamAsync` `if(isRateLimited)` clause. (already tested and it works)
https://gist.github.com/SlowLogicBoy/e1e967d68b36288b859960ed427d8863

It joins all Ranged streams into a single one.

This way you will be able to return `Task<Stream>` instead of asking for a stream as a parameter

I just don't know how I feel about `HttpClientEx.GetSingleton().GetStreamAsync(...).Result` part in constructor.

Maybe you'll find how to improve upon this.

**Comment by SlowLogicBoy** [comment]
We could do that, but then again Read is not async unless we could override ReadAsync methods? However only one of them is virtual 🤔

**Comment by Tyrrrz** [comment]
I'm really torn about this approach. On one hand it makes dealing with rate-limited streams easier, but the solution looks dirty to me. The `Stream` class simply represents a continuous sequence of bytes and abstracts away operations required to read through them. Because of that, `ReadAsync` is essentially a wrapper around `Read`, as you can see from their base implementation. What we're trying to do is put an async IO operation (or many of them, the HTTP requests) inside a synchronous read coroutine. On the other hand, we can try to make `ReadAsync` as the first class citizen instead but it seems that breaks the original design of the stream class...

**Comment by SlowLogicBoy** [comment]
then how about:
1. Adding `IsRateLimited` property to `MediaStreamInfo` class.
2. Separate extract body from this if [YoutubeClient.MediaStream.cs#L35](https://github.com/Tyrrrz/YoutubeExplode/blob/master/YoutubeExplode/YoutubeClient.MediaStream.cs#L35) to a separate method like you did with [GetMediaStreamAsync](https://github.com/Tyrrrz/YoutubeExplode/blob/master/YoutubeExplode/YoutubeClient.MediaStream.cs#L14) method?

So that I wouldn't need to copy paste most of the code?
Possibly making some methods overidable 🤔, but then return type wouldn't work for me.

The problem I'm having with this is:
I use Repository pattern for my app/webapi and, I want client side and webapi side Repository interface to match, so I could easily switch implementations (between RestClient and Data):
```csharp
//class YoutubeExplodeRepository : IYoutubeRepository
//class YoutubeWebApiRepository : IYoutubeRepository
interface IYoutubeRepository
{
    Task<YoutubeStream> DownloadVideo(string id, MediaType type);
}
//This is not exactly how this class looks but it conveys the idea
class YoutubeStream
{
    Stream Stream { get; set; }
    string FileName {get; set;}
}
```
REST Client is straight forward since it calls to my webapi implementation, however in webapi this interface is difficult to implement.

of course I can just copy paste and change [DownloadMediaStreamAsync](https://github.com/Tyrrrz/YoutubeExplode/blob/master/YoutubeExplode/YoutubeClient.MediaStream.cs#L25) Method, to match how I need, but if you change something I might not know :).

**Comment by Tyrrrz** [comment]
How do you set the Stream inside YoutubeStream currently?

**Comment by SlowLogicBoy** [comment]
I actually don't, right now I do:
`Task Download(Stream output);`
which makes `YoutubeStream` no longer a model.

**Comment by Tyrrrz** [comment]
So when you said extract to a different method, what signature did you have in mind?
