### ISSUE TITLE
Parse video from search query with date range.

### ISSUE THREAD

**Issue by MeteorBurn** [Tyrrrz/YoutubeExplode#136]
Is there any method to parse video from search query with arguments [publishedAfter] and [publishedBefore] like in API?

The main idea of it to get videos from a query as much as possible.
Usual search returns only limited range of videos about (500 - 800 videos) from a query.

Presently, I use API and arguments [publishedAfter] and [Before], but API have some quota limits as you know.
For me workaround is use several API in my project, but itsn't optimal.

So, question is above.

**Comment by remiX-** [comment]
Could you post an example?

**Comment by Tyrrrz** [comment]
Short answer is no, because the reverse engineered API we use doesn't have that kind of filtering (or it hasn't been found yet).

**Comment by MeteorBurn** [comment]
Thanks!

**Comment by Tyrrrz** [comment]
You are welcome
