### ISSUE TITLE
Download with LowestVideoQuality

### ISSUE THREAD

**Issue by mihxew** [Tyrrrz/YoutubeExplode#137]
Is it possible to download a video with lowest video quality? 

`var streamInfo = streamInfoSet.Video.WithHighestVideoQuality();`

Can I download a video with desired resolution? 

Thanks!

**Comment by Tyrrrz** [comment]
Hi. You can download videos in any quality you like, as long as it exists. Simply use LINQ queries to filter the collections.

**Comment by mihxew** [comment]
Thanks!

**Comment by remiX-** [comment]
Can also use ffmpeg to rescale video
