### ISSUE TITLE
Video quality limitation for muxed streams

### ISSUE THREAD

**Issue by MartiniDry** [Tyrrrz/YoutubeExplode#138]
Hi @Tyrrrz ,

I am wondering why isn't it possible to download FullHD YouTube videos ? I need to download a VEVO clip into MP4 format but the resolution is limited to 720p.
As you wrote into the **ReadMe.md**, highest quality may not be possible for muxed streams : what is the reason for that? Does it come from AJAX requests limitations?

By the way, congratulations for your work :+1:

**Comment by Tyrrrz** [comment]
Hi @MartiniDry,
The limitation comes from YouTube, they don't provide muxed streams in higher quality.

**Comment by MartiniDry** [comment]
OK thank you :)
