### ISSUE TITLE
Downloading audio almost always throws System.Net.Http.HttpRequestException (error 403)

### ISSUE THREAD

**Issue by D0vid** [Tyrrrz/YoutubeExplode#141]
Hi there, first of all I've been using your library since one or two days and so far it's been really great. Really love it :) 

Unfortunately since this morning, almost every DownloadMediaStreamAsync call throws a System.Net.Http.HttpRequestException

I've tried your WPF demo app and the result for audio streams is the same. I also wasn't able to find a similar issue in the past issues hence why I'm posting this

Here is my method using DownloadMediaStreamAsync : 
![image](https://user-images.githubusercontent.com/42772925/44723516-81a82500-aad0-11e8-81e6-26daed23b252.png)

**Comment by Tyrrrz** [comment]
I wonder if this is related to this comment also posted today on my blog:
https://tyrrrz.me/Blog/Reverse-engineering-YouTube#comment-4064514765

**Comment by smartbracker** [comment]
Not working since this morning. 
sample video ID not working -> **0I647GU3Jsc**

**Comment by Haapavuo** [comment]
Same issue here. Not able to download anything. Did they add another security layer to YouTube?

**Comment by luca233** [comment]
the same proble unauthorized

**Comment by Tyrrrz** [comment]
Fixed, thanks to Salguero. Expect new version uploaded very soon.
