### ISSUE TITLE
YoutubeExplode.Exceptions.ParseException: 'Could not find the entry function for signature deciphering.'

### ISSUE THREAD

**Issue by reddy04** [Tyrrrz/YoutubeExplode#144]
Getting '**Could not find the entry function for signature deciphering.**' exception while downloading some video(s). Example: https://www.youtube.com/watch?v=EEbZZkBkBZo
**StackTrace:**
   at YoutubeExplode.YoutubeClient.<GetVideoPlayerSourceAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at YoutubeExplode.YoutubeClient.<GetVideoMediaStreamInfosAsync>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YoutubeDemo.Program.<MainAsync>d__9.MoveNext() in C:\Users\ais\source\repos\YoutubeDemo\YoutubeDemo\Program.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at YoutubeDemo.Program.Main(String[] args)

I tested this in a console application with version **4.3.1**. This issue is occurring from last two days.

**Comment by ComputerMaster1st** [comment]
Hi there,

I'm also experiencing this error. Currently curious if a function has changed names or something within YouTube's source code.

**Comment by DominicMaas** [comment]
Some issue over here.

**Comment by reddy04** [comment]
How this will help us https://github.com/rg3/youtube-dl/commit/9a47fa35dd9dd2d53f4d3f088811ea29295991e5?diff=split

**Comment by reddy04** [comment]
Seems below regex is working:

**Comment by abadprogrammerincsharp** [comment]
The following regex code is working for me, and no slowdowns:
var entryPoint = Regex.Match(sourceRaw, @"yt\.akamaized\.net/\)\s*\|\|\s*.*?\s*c\s*&&\s*d\.set\([^,]+\s*,\s*([a-zA-Z0-9$]+)\(").Groups[1].Value;

**Comment by smartbracker** [comment]
My regex beta version
`var entryPoint = Regex.Match(sourceRaw, @"(\w+)&&(\w+).set\(\w,(\w+)\(\1\)\);return\s+\2").Groups[3].Value;`

**Comment by Tyrrrz** [comment]
Thank you, @smartbracker

**Comment by FaArIsH** [comment]
> 
> 
> My regex beta version
> `var entryPoint = Regex.Match(sourceRaw, @"(\w+)&&(\w+)\.set\(\w+,(\w+)\(\1\)\);return\s+\2").Groups[3].Value;`

how to add this to this php file https://github.com/You2php/you2php/blob/master/YouTubeDownloader.php#L9

**Comment by FilX** [comment]
It occurred again 

https://www.youtube.com/watch?v=m7Bc3pLyij0

**Comment by adavid1** [comment]
I occured for the first time today for me

**Comment by smartbracker** [comment]
Youtube  constantly changing this function, but I've seen few changes in the original key, so I'll try to use the original function to extract.

As the problem has already been solved, if someone wants to use this regex as **fallback**

`var entryPoint = Regex.Match(sourceRaw,
                @"(\w+)=function\(\w+\){(\w+)=\2\.split\(\x22{2}\);.*?return\s+\2\.join\(\x22{2}\)}").Groups[1].Value;`

**Comment by nizata** [comment]
It occurred again:
https://www.youtube.com/watch?v=88SjD4Uhaos

**Comment by Tyrrrz** [comment]
Stop using old version

**Comment by ydobrov** [comment]
Hi!

I have found the same issue right now for a lot of videos.
Example: https://www.youtube.com/watch?v=DTBmQDggJ60

**Comment by nizata** [comment]
> Hi @Tyrrrz !
> 
> I have found the same issue right now for a lot of videos.
> Example: https://www.youtube.com/watch?v=DTBmQDggJ60

@ydobrov you can get info if you update to version 4.7.3 
try update nuget: Install-Package YoutubeExplode -Version 4.7.3

**Comment by nemtajo** [comment]
Same issue for version 4.7.8, using link https://www.youtube.com/watch?v=xjIZv9Y9idQ

**Comment by Tyrrrz** [comment]
Update to 4.7.9
