### ISSUE TITLE
[Question] Decoding of a signature

### ISSUE THREAD

**Issue by retyui** [Tyrrrz/YoutubeExplode#147]
I read you artical https://tyrrrz.me/Blog/Reverse-engineering-YouTube.
Thank you for the details of the player! :+1: 
You can tell how you decode signatures (as a number)

```js
// get_video_info/ response
[
  {
    // ...
    projection_type: 1
    s: 1111
    sp: "signature",
    // ...
  },
  {
    // ...
    projection_type: 1
    s: "F6F619EBC321A7E35649D6360FA50C8AEE4B7ACFC7.17C3B71A310E385C9584BACA34E037026FE88B979E"
    sp: "signature",
    // ...
  }
]
```

For signatures like a string everything works fine,
But if the signature is a number here it's not clear what to do :sos:

**Comment by Tyrrrz** [comment]
I have never seen signatures like that

**Comment by retyui** [comment]
@Tyrrrz 
Sorry. That's my fault
