### ISSUE TITLE
AV1 codec cause ArgumentOutOfRangeException: Unexpected itag

### ISSUE THREAD

**Issue by smartbracker** [Tyrrrz/YoutubeExplode#148]
Youtube is testing **AV1 Codec**, 

https://www.youtube.com/playlist?list=PLyqf6gJt7KuHBmeVzZteZUlNUQAVLwrZS

Try download video this playlist, will cause **ArgumentOutOfRangeException: Unexpected itag** 

Exist many other videos on youtube besides this list, with new  **Itag** range, 
and increased in the last days.

I solve issue, adding temporary fake container to AV1 Codec.
Know new itag range until now **394**,**395**,**396**,**397**,**398**,**399**

**Comment by Tyrrrz** [comment]
Thanks.
I will check into this later today.

**Comment by Tyrrrz** [comment]
If you have time, please try to find out what is the video quality and other properties (although i guess they're all mp4 video, but just in case) of each itag.

e.g.
itag 399
1080p / video / av1 / mp4

**Comment by Tyrrrz** [comment]
Does anyone actually ever use the VideoEncoding/AudioEncoding properties? It would help a lot if they could be removed.

**Comment by SlowLogicBoy** [comment]
No. 
I only use `mediaStreamInfo.Container.GetFileExtension()` which is not related to `*Encoding` what so ever.
If you need that information you can get it from containers themselves (mkv, mp4 etc..) because they need to have that information. So keeping/parsing it is redundant.

**Comment by smartbracker** [comment]
If you want to remove **VideoEncoding / AudioEncoding**, no problem for me.

**Comment by Malediction** [comment]
I use VideoEncoding/AudioEncoding at the moment as I try to select the highest resolution with the best codec (e.g. 1080p video with webm is much smaller and looks better as a VP9 rather than H264)

**Comment by Malediction** [comment]
@Tyrrrz Good point :)

**Comment by Tyrrrz** [comment]
So I guess I will look into removing the `AudioEncoding`/`VideoEncoding` properties and ultimately stop relying on `itag` because it's annoying to maintain. `Container` can be parsed from string for all stream types, while encoding can only be parsed for some and it's not trivial. Will have to decide if we want to have an enum for container type, like we do now, or a string is enough? Maybe an extension method that can potentially return null or something so it will not throw an exception and break the rest of the workflow.

This also means it will have to be a breaking change, so might as well squeeze in some other changes while we're at it.

However, if the time window is small, I might just add itags for AV1 codec and look into refactoring later. Does anyone know when AV1 is going to be prolific?

**Comment by Giggitybyte** [comment]
I use `AudioEncoding`. 
For me, I need to verify that the stream I'm getting can be used with Lavalink. Lavalink can only use containers with specific encodings. I usually get a compatible stream, but it's more peace of mind for me so things don't just break.

**Comment by Tyrrrz** [comment]
Okay, that's important to know. In that case, itags have to stay. I suppose we can go back and re-add `VideoEncoding.Unknown` etc for the cases where YouTube implements something new, but it always felt dirty to me. Does anyone have other suggestions?

**Comment by SlowLogicBoy** [comment]
Leave it breaking. I think getting a bug report and knowing all the cases is better then just "try catching" everything or in this case adding `Unknown`. Like in this case, something new came up, and you are already working on it.

**Comment by Tyrrrz** [comment]
Good point. I also like that it provides the end-user the confidence of knowing that all the data was validated.

**Comment by Tyrrrz** [comment]
Actually, I just realized release builds of YoutubeExplode (which eventually end up on NuGet) already skip unknown itags so in this case it will not throw an exception anyway. 😄

**Comment by Tyrrrz** [comment]
@smartbracker are you sure you've seen itag 394? I haven't seen it. Which video is it used in? And what video resolution is it? 144p?

**Comment by smartbracker** [comment]
yes, it looks like it was 144p

**Comment by Tyrrrz** [comment]
maybe they removed it, let's see if it re-appears

**Comment by Tyrrrz** [comment]
This issue is not relevant anymore, itags are no longer used
