### ISSUE TITLE
Is there a way to get all videos from a youtube user? 

### ISSUE THREAD

**Issue by shaked6540** [Tyrrrz/YoutubeExplode#151]
For example, get all videos from this user https://www.youtube.com/user/ProZD/ 

The library does not treat it as a channel and any parse attempt is failed

**Comment by Tyrrrz** [comment]
It is a channel actually, it's just hard to find the ID. https://www.youtube.com/channel/UC6MFZAOHXlKK1FI7V0XQVeA
One way is to observe what request is sent when pressing Subscribe button, it send the channel ID.

**Comment by Tyrrrz** [comment]
Actually, just go to any video and hover over the author, it shows the link to the channel.
![image](https://user-images.githubusercontent.com/1935960/46172288-c8de2d00-c2ab-11e8-9451-16c9ff460c80.png)

**Comment by Giggitybyte** [comment]
Is it possible to have a method that tries to resolve the channel ID from a `youtube.com/user/*` URL so that we could grab all videos from a channel?

**Comment by smartbracker** [comment]
For small projects, you can use youtube api, I'm using and so far I have **not exceeded the free limit**.
`https://www.googleapis.com/youtube/v3/channels?part=id&forUsername={name_of_user}&fields=items/id&key={yourApiKey}`
Leave this alternative.

**Comment by Tyrrrz** [comment]
I think they exposed an API that worked on a user, but I stopped using it long time ago and don't remember why exactly...

**Comment by Tyrrrz** [comment]
Closed and moved to #158 (as enhancement)
