### ISSUE TITLE
Playlist type that isn't supported (starts with OL) 

### ISSUE THREAD

**Issue by shaked6540** [Tyrrrz/YoutubeExplode#152]
https://www.youtube.com/playlist?list=OLAK5uy_lLeonUugocG5J0EUAEDmbskX4emejKwcM

I tried to parse the playlist id with `YoutubeClient.TryParsePlaylistId`, it returns false even though its a valid playlist (and public)
I've looked in the source code and it seems like you're checking for what the playlist ids start with, I guess there's a reason behind that but I'm wondering why this playlist type isn't supported, is the OL prefix something new that you didn't see yet, or is there a reason why its not supported?

**Comment by Tyrrrz** [comment]
It's a new prefix. I don't understand what makes it different from others, looks like a regular playlist.

**Comment by shaked6540** [comment]
Seems like this playlist type doesn't expose the author of the playlist and does not show the view count
