### ISSUE TITLE
Get videos uploaded to a channel in form of playlist

### ISSUE THREAD

**Issue by SlowLogicBoy** [Tyrrrz/YoutubeExplode#16]
.GetPlaylistInfoAsync neatly returns playlist videos. It would be great to get same/similar info for channels.

Kind of work around is 
You can kind of convert channel to a fake playlist by adding &feature=mfu_in_order&list=UL to one of channel videos urls, but probably that would be a hack since channel also has an id, generated fake playlist id looks like https://www.youtube.com/playlist?list=UL[videoId].

**Comment by Tyrrrz** [comment]
By "similar info for channels", do you mean getting all uploaded videos by channel in a form of playlist?

**Comment by SlowLogicBoy** [comment]
Yes, exactly.

**Comment by Tyrrrz** [comment]
The workaround you suggested and another approach I had in mind both cap out at 100 videos with no support for continuation. :(
It looks like Youtube's iframe API is a lot more limiting than I thought, which sucks because the only other alternative is parsing raw HTML.

**Comment by SlowLogicBoy** [comment]
There is Youtube Data Api way, but it requires api key (https://developers.google.com/youtube/v3/)
`https://www.googleapis.com/youtube/v3/search?key={your_key_here}&channelId={channel_id_here}&part=snippet,id&order=date&maxResults=20`
I think 20 or 100 videos should be enough for start, just to have something and maybe down the line figure out better solution.

**Comment by Tyrrrz** [comment]
I know about Youtube API, but the main goal of this library is to provide an API without keys or quotas, by leveraging their front-end API instead. As such it also exposes some workflows that are not available in the public API such as downloading videos or closed captions.

**Comment by Tyrrrz** [comment]
I did my best  ¯\_(ツ)_/¯
