### ISSUE TITLE
Provide a method that queries basic video info that works on unavailable videos

### ISSUE THREAD

**Issue by Tyrrrz** [Tyrrrz/YoutubeExplode#163]
Use oembed: https://www.youtube.com/oembed?url=https%3A//youtube.com/watch%3Fv%3DM3r2XDceM6A&format=json

**Comment by shaked6540** [comment]
I've made a function for that, but not all videos can be accessed from the oembed url, when I ran the unit tests for the new function I encountered some 401 errors (unauthorized)

After some more research, I think that videos with "embed not allowed (type 2)" are the ones that are causing this problem, for example, this video: `https://www.youtube.com/watch?v=MeJVWBSsPAY`
the oembed url returns 401: `https://www.youtube.com/oembed?url=https%3a%2f%2fwww.youtube.com%2fwatch%3fv%3dMeJVWBSsPAY&format=json`

However, it looks like it works on unavailable videos (as long as embedding is allowed), I checked with the video from #155 and it seems to work for me

**Comment by Giggitybyte** [comment]
Well, that sucks.
Will any of the work you're doing with the refactor branch provide an alternate solution?

**Comment by Tyrrrz** [comment]
Probably not directly, but it will make it easier to maintain complex parsing logic in all parts of the library
