### ISSUE TITLE
RD playlists no longer work

### ISSUE THREAD

**Issue by Tyrrrz** [Tyrrrz/YoutubeExplode#168]
E.g. RD1hu8-y6fKg0, RDMMU-ty-2B02VY, RDEMNJhLy4rECJ_fG8NL-joqsg.
This is also evident because https://www.youtube.com/playlist?list=RD5jc_hytzZa0 also does not work (the `&disable_polymer=1` version shows an error).

**Comment by SlowLogicBoy** [comment]
It looks like RD url's must be within watch path, if I save a mix it redirects to [https://www.youtube.com/**watch**?v=EAYfJckSEN0&list=RDEAYfJckSEN0](https://www.youtube.com/watch?v=EAYfJckSEN0&list=RDEAYfJckSEN0)
and start playing the mix. As where other type of playlists redirect to 
[https://www.youtube.com/**playlist**?list=PLjXThOUbLW06F5aHX8cSFrrdF8N3DjnhX](https://www.youtube.com/playlist?list=PLjXThOUbLW06F5aHX8cSFrrdF8N3DjnhX)
where I can get playlist info and edit it.

Tried other type of url's no luck as of yet.

**Comment by Tyrrrz** [comment]
Love it when issues fix themselves
