### ISSUE TITLE
get video from youtube not work

### ISSUE THREAD

**Issue by ghootifarangi** [Tyrrrz/YoutubeExplode#169]
The application has been experiencing a problem receiving video and has encountered the following error:

Newtonsoft.Json.JsonReaderException
Additional text encountered after finished reading JSON content: }. Path '', line 1, position 15571.

please guide me

**Comment by dedady157** [comment]
this is a dupe, the fix was added, i don't know if it was merged yet. but if it has just update and that should fix

**Comment by dedady157** [comment]
just checked, it was merged, just update my man

**Comment by Tyrrrz** [comment]
Duplicate of #164. The fix is already out.

**Comment by ghootifarangi** [comment]
> Duplicate of #164. The fix is already out.

Has the latest version been modified and the problem has been resolved?

**Comment by Tyrrrz** [comment]
Yes

**Comment by ghootifarangi** [comment]
> Yes

tnx

**Comment by Tyrrrz** [comment]
Please submit a pull request
