### ISSUE TITLE
Any plan for youtube.com/gaming?

### ISSUE THREAD

**Issue by TaoziDB** [Tyrrrz/YoutubeExplode#174]
Such as game category, live streaming ...

**Comment by Giggitybyte** [comment]
I don't think it'd really be necessary. 

For YouTube Gaming as well as YouTube Music, the front end simply gets it's video/streams from the main YouTube site. If you remove `gaming` from a `gaming.youtube.com` URL, it'll point to the same exact thing on the main YouTube site. Same goes for YouTube Music URLs; just remove `music` from the URL and you'll have a URL that YoutubeExplode can process.

**Comment by TaoziDB** [comment]
The problem is how to get game categories for live streaming and live streamers in each game category.

**Comment by SlowLogicBoy** [comment]
This is really similar to #172
