### ISSUE TITLE
"The given key was not present in the dictionary" When trying to download a video

### ISSUE THREAD

**Issue by shaked6540** [Tyrrrz/YoutubeExplode#178]
```cs
var videoId = "U4hMQtcKfQo";
var video = await client.GetVideoAsync(videoId);
```

Throws
```
The given key was not present in the dictionary
    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at YoutubeExplode.YoutubeClient.<GetVideoAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
```

**Comment by patrux** [comment]
![wisdom_of_the_ancients](https://user-images.githubusercontent.com/12746858/56230903-84ff1980-607d-11e9-96e7-9f5572b7f02b.png)

**Comment by Tyrrrz** [comment]
@patrux do you have the same issue? :)

**Comment by BabuBahir** [comment]
same here....what was the solution... i am getting this error

**Comment by Tyrrrz** [comment]
Whatever it was, it's probably not relevant anymore as it was 2 years ago. If you're having consistent errors, raise a new issue.

**Comment by shaked6540** [comment]
I just had a dictionary and tried to get a key that didn't exist in it, the error wasn't related to this library
I didnt post the code that caused it or the soultion afterwards  because it was just a matter of `var a = dict["some value that doesnt exist"]`
