### ISSUE TITLE
some vides cannot play

### ISSUE THREAD

**Issue by luca233** [Tyrrrz/YoutubeExplode#179]
cannot play some videos

**Comment by DominicMaas** [comment]
See this related commit: https://github.com/rg3/youtube-dl/commit/2511eee215c2a66020ae927c86face826f48ba8e

**Comment by DominicMaas** [comment]
I managed to fix the issue in the Dart port of this library, I'd imagine it would be a very similar fix here. https://github.com/SoundByteOSS/youtube-extractor/commit/ce09331f9beabdd99e05cbdb80964282107cca85
