### ISSUE TITLE
Issue parsing DASH manifest on some videos

### ISSUE THREAD

**Issue by ghootifarangi** [Tyrrrz/YoutubeExplode#184]
Get video from youtube for some videos not work.
for example:
https://www.youtube.com/watch?v=RDPB4qgo1oM

Please fix the problem

**Comment by ComputerMaster1st** [comment]
Hi There,

I don't have a stack trace but I hope the following helps a little bit.

```
Value cannot be null.
Parameter name: info
```

**Comment by Tyrrrz** [comment]
Looks like a problem with DASH manifest. It's not consistent though.

**Comment by ComputerMaster1st** [comment]
It appears this issue seems to have resolved itself. Might have been a simple glitch or something on YT's end.

**Comment by ghootifarangi** [comment]
Dear @Tyrrrz 
The problem is still exist. How much time will the problem be solved?

**Comment by Tyrrrz** [comment]
@ghootifarangi unfortunately I can't reproduce this issue.

**Comment by Tyrrrz** [comment]
Can you check on the latest released version (4.6)?

**Comment by ghootifarangi** [comment]
I tested some youtube videos. Apparently the problem has been fixed. 
tnx dear Alexey Golub

**Comment by Tyrrrz** [comment]
Cool!
