### ISSUE TITLE
Getting a video comment

### ISSUE THREAD

**Issue by amirvenus** [Tyrrrz/YoutubeExplode#185]
Is there any method to get comments from a video?

If not, that would be such a nice feature to add.

**Comment by remiX-** [comment]
What is your use case for it?

I guess it would be nice, but don't think Tyrrrz intended it to be within the scope and usage of YE

**Comment by amirvenus** [comment]
Yeah but two features that would make this package really great would be Searching based on keywords and retrieving comments.

**Comment by mbparker** [comment]
> Yeah but two features that would make this package really great would be Searching based on keywords and retrieving comments.

But what is your use case for the comments? Just curious how you intend to use the library.

**Comment by amirvenus** [comment]
I want to display some videos in an app for but would want to moderate comments to ensure there is no offending/spam.

**Comment by Tyrrrz** [comment]
>...that would make this package really great would be Searching based on keywords...
Why is [SearchVideosAsync](https://github.com/Tyrrrz/YoutubeExplode/blob/d6b33d3b76db2759ccb6be30a1c80327f5f400b6/YoutubeExplode/IYoutubeClient.cs#L67) not good enough for you?

@remiX- is right, I think the current feature set is good enough. Remember that adding new features such as this one means that I will have to maintain it and fix it every time it breaks, which happens often.

**Comment by SlowLogicBoy** [comment]
There is [`YoutubeClient`](https://github.com/Tyrrrz/YoutubeExplode/blob/master/YoutubeExplode/YoutubeClient.cs#L18) ctor where you can pass `HttpClient`, use proxy on `HttpClient`.
Note: there are some stuff @Tyrrrz  did on [`HttpClient`](https://github.com/Tyrrrz/YoutubeExplode/blob/master/YoutubeExplode/Internal/HttpClientEx.cs#L20) So you might need to do that too.

**Comment by amirvenus** [comment]
> There is [`YoutubeClient`](https://github.com/Tyrrrz/YoutubeExplode/blob/master/YoutubeExplode/YoutubeClient.cs#L18) ctor where you can pass `HttpClient`, use proxy on `HttpClient`.
> **Note:** there are some stuff @Tyrrrz did on [`HttpClient`](https://github.com/Tyrrrz/YoutubeExplode/blob/master/YoutubeExplode/Internal/HttpClientEx.cs#L20) So you might need to do that too.

Could you please provide an example?

**Comment by SlowLogicBoy** [comment]
```csharp
#r "nuget: YoutubeExplode, *"

using System.Net;
using System.Net.Http;
using YoutubeExplode;
using YoutubeExplode.Models;

HttpMessageHandler CreateProxiedHttpMessageHandler(string proxyServer)
{
    var proxiedHttpClientHandler = new HttpClientHandler
    {
        Proxy = new WebProxy(proxyServer),
        UseProxy = true
    };

    //Stuff from YoutubeExplode library:
    if (proxiedHttpClientHandler.SupportsAutomaticDecompression)
        proxiedHttpClientHandler.AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate;

    proxiedHttpClientHandler.UseCookies = false;
    return proxiedHttpClientHandler;
}

Task<Video> GetVideoInfoThroughProxyAsync(string proxyServer, string videoId)
{
    using (var httpClient = new HttpClient(CreateProxiedHttpMessageHandler(proxyServer), true))
    {
        var youtubeClient = new YoutubeClient(httpClient);
        return youtubeClient.GetVideoAsync(videoId);
    }
}
var proxyServer = "http://localhost:8888";
var videoInfo = await GetVideoInfoThroughProxyAsync(proxyServer, "zyluU2OpqDA");
```

Unless by proxy you meant something else..

**Comment by amirvenus** [comment]
So do I need to modify the library’s code?

Is there any override?

**Comment by SlowLogicBoy** [comment]
> Great example, @SlowLogicBoy!
> Make sure that you await tasks inside `using` blocks, otherwise it will be disposed too early.

Oh right didn't notice that, thanks for the catch.

**Comment by Tyrrrz** [comment]
Then it wouldn't be immutable.

.NET limits to 2 simultaneous connections, so you have to raise that limit using ServivePointManager or using MaxConnectionsPerServer in HttpClientHandler

**Comment by amirvenus** [comment]
I tried that but it is still the same. I can't even use `MaxConnectionsPerServer` because it's not implemented (according to https://github.com/mono/mono/blob/master/mcs/class/System.Net.Http/System.Net.Http/HttpClientHandler.cs). Any other ideas/suggestions? 


Thanks

**Comment by Tyrrrz** [comment]
I decided that comments are out of scope, at least now.
Currently the scope is downloading videos, getting video metadata which is shown on the watch page (which comes from different sources) and getting playlist metadata.
