### ISSUE TITLE
Parse LiveChat Parameters to get chat data and messages 

### ISSUE THREAD

**Issue by MeteorBurn** [Tyrrrz/YoutubeExplode#192]
Hi there!
Is it possible to parse livechat parameter of live broadcasting to get chat messages?
For example this url: https://www.youtube.com/live_chat/get_live_chat?continuation=0ofMyAOEARogQ2c4S0RRb0xNSFJRYkdOdWNIcEVaMjhnQVElM0QlM0Qon_nAy7_13gIwADgAQAFKKQgAEAAYACAAKg5zdGF0aWNjaGVja3N1bToAQABKAFC3lazOv_XeAlgDUMOIg8y_9d4CWJ725MWb9N4CaASCAQQIBBAAiAEAoAHGq7TOv_XeAg==&hidden=false&pbj=1 gets json response with chat data and messages of https://www.youtube.com/watch?v=0tPlcnpzDgo

I'm sorry for russian language.
Привет!
Подскажи, пожалуйста, возможно ли спарсить параметр не своей трансляции для парсинга её чата благодаря YouTube Explode? Хеш чата подгружается во фрейме и как получить его через http-запрос без загрузки страницы мне не понятно. Буду признателен за ответ.
Спасибо!

Ещё раз прошу прощения, что на русском.

**Comment by SlowLogicBoy** [comment]
Hi, 
@Tyrrrz will correct me if I'm wrong, but chat, just like comments, are out of this library scope, because it just adds a lot of complications and it's hard to support it, so if you need to parse chat or comments you'll have to parse it yourself.

**Comment by Tyrrrz** [comment]
Yes, live chat is out of scope for me.
I also don't know how to get the initial continuation token to pass as a parameter to `get_live_chat`.

**Comment by MeteorBurn** [comment]
Thanks for the answer.
I'll try to do it myself.
