### ISSUE TITLE
Invalid URI: The format of the URI could not be determined

### ISSUE THREAD

**Issue by acosano** [Tyrrrz/YoutubeExplode#195]
Hi,

First I like to thanks you for this great Lib. It give me everything I ever waned to get from YouTube.
Every time I use only `Dim streamInfoSet = Await YTClient.GetVideoMediaStreamInfosAsync(VideoID)` as I only one the Audio and Video URL's and have the VideoID of it. I get the error **Invalid URI: The format of the URI could not be determined**. I click OK and everything works, it download with out any issues.
Any help is very much Appreciated.

**Comment by Tyrrrz** [comment]
I'm not sure where it can come from, considering the URI is not validated anywhere. Are you sure it comes from this library?

**Comment by acosano** [comment]
Is happening in the YoutubeClient.cs in the function below.
`private async Task<VideoInfoParser> GetVideoInfoParserAsync(string videoId, string el = "embedded")
        {
            // This parameter does magic and a lot of videos don't work without it
            var eurl = $"https://youtube.googleapis.com/v/{videoId}".UrlEncode();

            var url = $"https://www.youtube.com/get_video_info?video_id={videoId}&el={el}&eurl={eurl}&hl=en";
            var raw = await _httpClient.GetStringAsync(url).ConfigureAwait(false); <-- ERROR 

            return VideoInfoParser.Initialize(raw);
        }`

**Comment by Tyrrrz** [comment]
Weird. What's the video ID that causes it?

**Comment by acosano** [comment]
I found the problem. You gave me the hint when you say about the ID. For some reason I was trimming the last character of the ID in one part of my code. Sorry for the trouble and thanks for the prompt response.

**Comment by Tyrrrz** [comment]
Glad it worked
