### ISSUE TITLE
Enhanced audio quality

### ISSUE THREAD

**Issue by JustTotallyMe** [Tyrrrz/YoutubeExplode#196]
Hi,

great work on the YouTubeExplode.
I used it for a project and it is working create, although it seems that I'm not getting the best audio-quality out of the downloads I do with "streamInfoSet.Audio.WithHighestBitrate();".

I just listened to the webm-file that was put out, but it is really quiet and weak.

I'm I using it wrong? Do I need to convert the webm-file to a better quality file?

Thx in advance and kind regards,

Andy

**Comment by SlowLogicBoy** [comment]
Youtube uses some modifications on audio files while playing, like normalization, and YoutubeExplode does not modify those audio files.

**Comment by Tyrrrz** [comment]
Yeah there's a relative loudness index for each audio stream which I'm assuming is used for normalization during playback, but it's not embedded in the audio file itself.

**Comment by JustTotallyMe** [comment]
Uh ok. Well thanks for the info :)
Now I just need to figure out how I can do that :D

do you guys maybe have a recommendation on how to convert the webm to a mp3 (with good loudness :) )?

**Comment by Tyrrrz** [comment]
Yeah there's a relative loudness index for each audio stream which I'm assuming is used for normalization during playback, but it's not embedded in the audio file itself.

**Comment by Tyrrrz** [comment]
You can use YoutubeExplode.Converter with ffmpeg, but it doesn't do anything with loudness, at least yet.

**Comment by JustTotallyMe** [comment]
uh great thx, I will try that.
