### ISSUE TITLE
Is there any plan to add capability to get the Recommended Videos on homepage?

### ISSUE THREAD

**Issue by Hanzalah-Adalan** [Tyrrrz/YoutubeExplode#197]
as far as I know this awesome library only process public metadata and my aforementioned question is out of scope a bit.. but still I'm just curious.. feel free to close or delete this noob question (* ^ ω ^)

**Comment by Tyrrrz** [comment]
Hi, thanks for using my library.
Probably not, like you said it's a bit out of scope and also doesn't seem easy to implement.

**Comment by Hanzalah-Adalan** [comment]
Owhh I see.. just wanna hear the confirmation from the owner..
