### ISSUE TITLE
Combining 1080p stream and audio track in UWP

### ISSUE THREAD

**Issue by XFox111** [Tyrrrz/YoutubeExplode#198]
Hi, man. Firstly, thanks for your project. It's really cool.
I'm developing UWP YouTube client now and I need to implement support of 1080p and higher quality for my video player. In Issue #108 you've mentioned ffmpeg to bypass this problem. But in UWP it won't work. Is there any another option? Thanks in advance;)

**Comment by Tyrrrz** [comment]
Maybe this can help?
https://blogs.windows.com/buildingapps/2015/06/05/using-ffmpeg-in-windows-applications/#eBGBG2TWFokpI5I5.97

**Comment by XFox111** [comment]
Yes! It's exactly what I needed. I wonder how could I miss it. Thank you)

**Comment by Tyrrrz** [comment]
Glad it helped. :)
