### ISSUE TITLE
How to save audio only C#

### ISSUE THREAD

**Issue by DwainSnickles** [Tyrrrz/YoutubeExplode#199]
I finally figured out how to save the video using a windows form App. 2 questions?
1) how do I save to a different directory?
2) how to save audio only?

**Comment by Tyrrrz** [comment]
1. You can save to any directory you want by specifying the full `filePath` in `DownloadMediaStreamAsync`.
2. Get the appropriate audio-only stream, e.g. `mediaStreamInfoSet.Audio.WithHighestBitrate()`.

**Comment by DwainSnickles** [comment]
Thanks for your help I did get it working however the audio format was not MP3 so after a lot of research I found a way to achieve this I will post the code here for others:
Step 1 
Add Nuget package: https://www.nuget.org/packages/NReco.VideoConverter/ To Convert MP4 to MP3 from your VS windows form program wait for it to fully complete.
Step 2

use the following code
`// Client
            var client = new YoutubeClient();
            var videoId = NormalizeVideoId(txtFileURL.Text);
            var video = await client.GetVideoAsync(videoId);
            var streamInfoSet = await client.GetVideoMediaStreamInfosAsync(videoId);
            // Get the best muxed stream
            var streamInfo = streamInfoSet.Muxed.WithHighestVideoQuality();
            // Compose file name, based on metadata
            var fileExtension = streamInfo.Container.GetFileExtension();
            var fileName = $"{video.Title}.{fileExtension}";
            // Replace illegal characters in file name
            fileName = RemoveIllegalFileNameChars(fileName);
            tmrVideo.Enabled = true;
            // Download video
            txtMessages.Text = "Downloading Video please wait ... ";

            //using (var progress = new ProgressBar())
            await client.DownloadMediaStreamAsync(streamInfo, fileName);

            // Add Nuget package: https://www.nuget.org/packages/NReco.VideoConverter/ To Convert    MP4 to MP3
            if (ckbAudioOnly.Checked)
            {
                var Convert = new NReco.VideoConverter.FFMpegConverter();
                String SaveMP3File = MP3FolderPath + fileName.Replace(".mp4", ".mp3");
                Convert.ConvertMedia(fileName, SaveMP3File, "mp3");
                //Delete the MP4 file after conversion
                File.Delete(fileName);
                LoadMP3Files();
                txtMessages.Text = "File Converted to MP3";
                tmrVideo.Enabled = false;
                txtMessages.BackColor = Color.White;
                if (ckbAutoPlay.Checked) { PlayFile(SaveMP3File); }
                return;
            }`

**Comment by DwainSnickles** [comment]
My checkbox for audio only if not checked continues on as normal to complete the mp4 download not added in code.

**Comment by aherrick** [comment]
I would use the YouTube Converter. Works great! https://github.com/Tyrrrz/YoutubeExplode.Converter
