### ISSUE TITLE
Code Breaks

### ISSUE THREAD

**Issue by spoiledtechie** [Tyrrrz/YoutubeExplode#2]
Since the Youtube updates, your code breaks with certain Youtube videos.

This one included: https://www.youtube.com/watch?v=6MtLqOErEeo

**Comment by Tyrrrz** [comment]
Hm. For the video you linked, it seems there is no JSON-encoded video info to be found on the watch page. Is it something that affects new videos after update?
I've added a fallback mechanism for videos like these, which will try to use an older API. That should help with the errors at least.

**Comment by spoiledtechie** [comment]
Does your fallback work with this video?

**Comment by Tyrrrz** [comment]
With the one you linked - yes
