### ISSUE TITLE
Adding ratebypass to download url

### ISSUE THREAD

**Issue by DavidBarishev** [Tyrrrz/YoutubeExplode#20]
Hello again,
I noticed a very big speed gap between downloads with this library, and youtube dl which i took for reference.
Downloading itag 251, takes about 20 minute for 1 hour video, as with youtube dl - around 9 seconds.

I have dug a bit in their code, and found that an option is missing from the final stream url, which is 'ratebypass=true',and i confirmed that adding it, allows YouTube to send data at constant speed (usually is first 40 seconds at max speed, rest at watching speed).The parameter is present both at dash and non dash streams.

Relevant code in youtube dl - https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/youtube.py#L1644

**Comment by Tyrrrz** [comment]
Thank you for the find
