### ISSUE TITLE
Fails on https://www.youtube.com/watch?v=rsAAeyAr-9Y

### ISSUE THREAD

**Issue by TaoziDB** [Tyrrrz/YoutubeExplode#200]
I used to use the methods in streamlink to get youtube video url, but it can not handle protected videos, so I am thinking to change to youtubeexplode, used nuget v4.6.1 package and tried one video streamlink can not handle: https://www.youtube.com/watch?v=rsAAeyAr-9Y
```
var client = new YoutubeClient();
var streamInfoSet = await client.GetVideoMediaStreamInfosAsync("rsAAeyAr-9Y");
```
in streamInfoSet, audio, video and muxed are all empty, what is wrong?

**Comment by Tyrrrz** [comment]
Uhh. Somehow YouTube reports this video as a live stream so YouTubeExplode ignores the media streams. Is it a recording of a live stream? Have you noticed any other examples of this issue?

**Comment by TaoziDB** [comment]
and all recordings of live stream in playlist "RAW PAST BROADCASTS" on this page:
[https://www.youtube.com/channel/UCv9Edl_WbtbPeURPtFDo-uA/playlists](https://www.youtube.com/channel/UCv9Edl_WbtbPeURPtFDo-uA/playlists)

**Comment by Tyrrrz** [comment]
Fixed
