### ISSUE TITLE
Help my app dont work

### ISSUE THREAD

**Issue by rigorvzla** [Tyrrrz/YoutubeExplode#201]
hello today i update my nugget and dont work more, what happend? why?
Dont obtain information of video

**Comment by Tyrrrz** [comment]
What's the error?

**Comment by rigorvzla** [comment]
![imagen](https://user-images.githubusercontent.com/41328887/50763870-6ea81d00-1247-11e9-8975-4b93d3fdf0de.png)
no continue, is stoped i only update you nugget and not work more

**Comment by rigorvzla** [comment]
my app is working now, i dont know why, but i update framenetwork 4.6.1 before fail.
i have backup and there is framenetwork 4.5.2 and work fine
