### ISSUE TITLE
Some spaces are missing in closed captions

### ISSUE THREAD

**Issue by foadabdollahi** [Tyrrrz/YoutubeExplode#204]
some words in arabic subtitle need space between them. cause is remove some tag for convert to text

**Comment by SlowLogicBoy** [comment]
Can you provide:
1. Youtube video example
2. Expected result
3. Acctual result

Because I'm not familiar with Arabic languages, and how they should be spaced/formatted.

**Comment by foadabdollahi** [comment]
thanks,

var client = new YoutubeClient();
var trackInfos = await client.GetVideoClosedCaptionTrackInfosAsync("_QdPW8JrYzQ");

var trackInfo = trackInfos.First(t => t.Language.Code == "en");
**trackInfo.Url+="&tlang=fa";**
var track = await client.GetClosedCaptionTrackAsync(trackInfo);

var caption = track.GetByTime(TimeSpan.FromSeconds(61));
var text = caption.Text; // "And the game was afoot."

this tube : https://www.youtube.com/watch?v=C6jS7rhMm5Y

fot this link : [link](https://www.youtube.com/api/timedtext?asr_langs=fr%2Cpt%2Ces%2Cnl%2Cja%2Cko%2Cru%2Cde%2Cit%2Cen&caps=asr&key=yttt1&hl=en&v=C6jS7rhMm5Y&xoaf=1&expire=1547210111&sparams=asr_langs%2Ccaps%2Cv%2Cxoaf%2Cxorp%2Cexpire&xorp=True&signature=B9BE0771B1BF91986D5F8DCD7543E6D7C463A65B.7D98C60D34C9E089823E34524023B7747BF7C1B8&kind=asr&lang=en&fmt=srv3&tlang=fa)

after get data from new format from var text = caption.Text; some word hs not space:

orginal in you tube is : 
<p t="7649" d="3481">
<s> می خواهم به شما در مورد </s>
<s p="2">یک</s>
<s> </s>
<s p="1">هوشمند جدید</s>
<s> به </s>
</p>

youtubeexplode reslut is :
4
00:00:07.649 --> 00:00:11.130
 می خواهم به شما در مورد یکهوشمند جدید به 


true is : یک هوشمند and false is یکهوشمند


i hope you can understand problem

**Comment by Tyrrrz** [comment]
`trackInfo.Url+="&tlang=fa";`
this isn't valid because it has no public setter.

[Your link](https://www.youtube.com/api/timedtext?asr_langs=fr%2Cpt%2Ces%2Cnl%2Cja%2Cko%2Cru%2Cde%2Cit%2Cen&caps=asr&key=yttt1&hl=en&v=C6jS7rhMm5Y&xoaf=1&expire=1547210111&sparams=asr_langs%2Ccaps%2Cv%2Cxoaf%2Cxorp%2Cexpire&xorp=True&signature=B9BE0771B1BF91986D5F8DCD7543E6D7C463A65B.7D98C60D34C9E089823E34524023B7747BF7C1B8&kind=asr&lang=en&fmt=srv3&tlang=fa) gives 404 for me.

The video you linked does not have arabic subtitles anyway
![image](https://user-images.githubusercontent.com/1935960/51075421-cef9ed00-1693-11e9-8347-633558a2e377.png)

**Comment by foadabdollahi** [comment]
yes.
if you on auto translate and set any language like persian or arabic. you can see in your inspection one new file load and add to page. this file is translate of subtitle. and in youtubeexplode some <s> </s> remove that is need in arrabic words.
notfound is cause it has some sign with expirtion and after some minutes it lost.

if you check you inspection and network tab. and set on auto translate you can see your link

**Comment by foadabdollahi** [comment]
trackInfo.Url+="&tlang=fa";

i create new object and set this value on that. 
and it was work correct. :D

**Comment by Tyrrrz** [comment]
It seems to be caused by this issue: https://stackoverflow.com/questions/2737636/c-sharp-linq-to-xml-missing-space-character

**Comment by foadabdollahi** [comment]
maybe,
i think for remove other tag inside p tag regex can be helpfull

**Comment by foadabdollahi** [comment]
```
  var tagsExpression = new Regex(@"</?.+?>");
 return tagsExpression.Replace(input, " ");
```
somethig like this

**Comment by Tyrrrz** [comment]
There's apparently an option to preserve whitespace, I fixed it.
