### ISSUE TITLE
256kb AAC Audio?

### ISSUE THREAD

**Issue by mysteryx93** [Tyrrrz/YoutubeExplode#205]
YouTube used to have 256kbps AAC audio stream hidden in his DASH manifest file, which most downloaders are not parsing. Lately I also realized I couldn't get that 256kbps AAC file anymore.

I just wanted to confirm. Has YouTube removed that file stream, or is YoutubeExplode just not parsing it?

**Comment by Tyrrrz** [comment]
What was the last version you were able to get that stream with? Does it still work?

**Comment by mysteryx93** [comment]
I don't know, I was using another downloader library before and modified it to parse the MASH manifest to access that audio stream. I believe your package was also returning that stream but now it's not available anymore. I'm not exactly sure whether YouTube dropped support for it or your library just isn't returning it.

**Comment by Tyrrrz** [comment]
I looked through commit history and couldn't find anything that could affect it, so I guess Google either removed it or it's temporarily unavailable.
