### ISSUE TITLE
How can I get the GUI in screenshots section?

### ISSUE THREAD

**Issue by DannyPDWS0041** [Tyrrrz/YoutubeExplode#208]
Hi, I am new to NuGet.
I would like to know how can I get to the GUI in readme screenshots section and <https://tyrrrz.me/Projects/YoutubeExplode>

![687474703a2f2f7777772e74797272727a2e6d652f50726f6a656374732f596f75747562654578706c6f64652f496d616765732f312e706e67](https://user-images.githubusercontent.com/46824499/51404843-9eccb580-1b8f-11e9-95d8-f5322a7d49fd.png)

**Comment by Tyrrrz** [comment]
This is the WPF demo project -- https://github.com/Tyrrrz/YoutubeExplode/tree/master/DemoWpf

**Comment by DannyPDWS0041** [comment]
Do you offer binaries of the demo project?
If not, how can I build it myself?

**Comment by Tyrrrz** [comment]
You need Visual Studio 2017, simply open the YoutubeExplode.sln in the root of the repository and build DemoWpf project.

**Comment by DannyPDWS0041** [comment]
YoutubeDownloader is what I am looking for.
Thank you for your help.

I am closing the issue.
