### ISSUE TITLE
GetVideoMediaStreamInfosAsync returns null MediaStream

### ISSUE THREAD

**Issue by darkdoctor** [Tyrrrz/YoutubeExplode#209]
Greetings,

Today I am facing an issue to get MediaStreams from GetVideoMediaStreamInfosAsync.
I am getting as a result a NULL Pointer.

Tried with several videos, same result.

Please delete this thread, it was the DEBUG Intellisense that was giving me the reuslt as null.

**Comment by Tyrrrz** [comment]
It can't return null under any condition 😛 
https://github.com/Tyrrrz/YoutubeExplode/blob/99ccc00a2731ca72dd791a7c6d4bb9f2c61e4823/YoutubeExplode/YoutubeClient.Video.cs#L270

**Comment by TranDinhVuong** [comment]
I also face  the same mistake today

**Comment by Tyrrrz** [comment]
You're probably thinking of #229 ?

**Comment by TranDinhVuong** [comment]
> You're probably thinking of #229 ?

Many thanks for that quick response.
