### ISSUE TITLE
I am trying to use Windows Progress Bar With DownloadMediaStreamAsync, but unable to understand get how to supply Progress Bar value?

### ISSUE THREAD

**Issue by this-is-r-gaurav** [Tyrrrz/YoutubeExplode#212]
```
Progress<double> pb= new Progress<double>();
ProgressBar bar = new ProgressBar();
this.downloadTab.Controls.Add(bar);

//progress_count is the value that i want to get
backgroundWorker1.ReportProgress(progress_count); 

backgroundWorker1.RunWorkerAsync();
await client.DownloadMediaStreamAsync(streamInfo, $"{path}\\{id}.{ext}",pb);
```

If the snippet is bit wrong, please forgive. Because I am new to C#.

**Comment by Tyrrrz** [comment]
I don't understand what you are trying to achieve with background worker, etc.
To route `IProgress<double>` to a progress bar, it should be enough to do `var pb = new Progress<double>(p => bar.Value = p)`. Make sure the progress bar's minimum and maximum are set to 0 and 1 respectively.

**Comment by this-is-r-gaurav** [comment]
I am just trying to update the progress bar as soon as the user click on download button to another tab page. and i have seen somewhere progress bar works with background worker if you want to update it asynchronously.

**Comment by this-is-r-gaurav** [comment]
I guess i don't need service worker for this.

**Comment by this-is-r-gaurav** [comment]
`Make sure the progress bar's minimum and maximum are set to 0 and 1 respectively` . But the Progress bar accepts integer value and if i set it to 0 and 1 then how does it going to work instead can't i do this
```
ProgressBar bar = new ProgressBar();

Progress<int> pb= new Progress<int>(p=>bar.Value=p);
this.downloadTab.Controls.Add(bar);

await client.DownloadMediaStreamAsync(streamInfo, $"{path}\\{id}.{ext}",pb);
```

**Comment by Tyrrrz** [comment]
To get an integer (I'm assuming in the 0->100 range) just cast the reported progress to int after multiplying it by 100 -- `p=> bar.Value = (int) 100*p`

**Comment by this-is-r-gaurav** [comment]
Ahh, It didn't clicked to my mind. Thanks  for the help, hope this will resolve It. `100 * int(p)` will suit

**Comment by this-is-r-gaurav** [comment]
Thanks it doesn't give error but , i guess i need to think the logic again to implement dynamically progress bar

**Comment by Tyrrrz** [comment]
You are welcome.
There's an example with progress bar in both DemoWpf and DemoConsole
