### ISSUE TITLE
How to get mpd url?

### ISSUE THREAD

**Issue by Tommy92708** [Tyrrrz/YoutubeExplode#213]
How do I get the mpd url to pass into a mpeg-dash capable player to play? TIA.

**Comment by SlowLogicBoy** [comment]
https://github.com/Tyrrrz/YoutubeExplode/blob/master/YoutubeExplode/Models/MediaStreams/MediaStreamInfo.cs#L20

**Comment by Tyrrrz** [comment]
I think he's taking about Dash manifest. There's no public way to access it. It's also not consistent.

**Comment by Tommy92708** [comment]
Thanks Tyrrrz, yup the dash manifest is what I'm talking about. I'm wondering how the YouTube html player got a hold of the mpd if that link isn't on the html page itself? Maybe it has a back channel communication w/ the YT server?

The reason why having an MPD link is important is because most muxed streams have SD quality. To get HD/4K quality, you will have to do the audio muxing yourself, which can be difficult to do it "live".

**Comment by Tyrrrz** [comment]
What do you mean by "doing it live"?

**Comment by Tommy92708** [comment]
Say I have a web player that takes in a YouTube URL and hit Play to play it. This web player has no time to download all the streams and mux them together. It has to play when the user hit the Play button.

**Comment by Tyrrrz** [comment]
Yeah, that's why you use `GetMediaStreamAsync`

**Comment by Tommy92708** [comment]
Yea but for HD video quality, the audio stream isn’t present so some muxing has to be done manually, no?

**Comment by Tyrrrz** [comment]
If you only need to play it, you can simply play audio and video streams simultaneously. That's what YouTube is doing.

**Comment by Devansh20055** [comment]
any bot or repo for getting mpd url ?? 
plz help me out
