### ISSUE TITLE
Video description is not fully loading

### ISSUE THREAD

**Issue by beqabeqa473** [Tyrrrz/YoutubeExplode#214]
hello.

i am trying to get a video description, but it seems it is not getting full description comparing to a webpage

**Comment by Tyrrrz** [comment]
Can you give an example video, expected results and actual results?

**Comment by beqabeqa473** [comment]
example video
https://www.youtube.com/watch?v=g3IppGISkP0
actual results
For those of you who want to root your Samsung Galaxy S9 or S9 Plus,
here&#39;s a step-by-step tutorial on how to do it. PLEASE
SEE&nbsp;...


expected description is big enough, which you can see on a webpage.

On 2/15/19, Alexey Golub <notifications@github.com> wrote:
> Can you give an example video, expected results and actual results?
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Tyrrrz/YoutubeExplode/issues/214#issuecomment-463993624


-- 
with best regards beqa

**Comment by Tyrrrz** [comment]
Are you getting the description from `SearchAsync`? They are always truncated there.
If you use `GetVideoAsync` or `GetPlaylistAsync` you should get the same as on the watch page.
![image](https://user-images.githubusercontent.com/1935960/52904152-96b87200-3230-11e9-9c99-ea5a26c03e9c.png)

**Comment by Tyrrrz** [comment]
But you made me aware of some other description issues that I just noticed thanks to this issue. :)
