### ISSUE TITLE
How to download a playlist?

### ISSUE THREAD

**Issue by yasha107** [Tyrrrz/YoutubeExplode#215]
I'm making a youtube video downloader program and I want it to have a download all videos in playlist feature. How do I do it?

**Comment by Tyrrrz** [comment]
You can download them using `GetVideoMediaStreamInfosAsync` on each video in the playlist

**Comment by yasha107** [comment]
How do I get the videos from a playlist url so I can do that?

**Comment by Tyrrrz** [comment]
https://github.com/Tyrrrz/YoutubeExplode/blob/master/ReadMe.md#get-playlist-info

**Comment by yasha107** [comment]
Thanks

**Comment by lindomar-marques55** [comment]
`` Private Sub GrabList(ByVal URL As String)
        
        Dim client = New YoutubeExplode.YoutubeClient()
        Dim id = YoutubeClient.ParsePlaylistId(URL)
      
        Dim playlist = client.GetPlaylistAsync(id)
        Dim title = playlist.t...

    End Sub``


I stopped here and can not continue the intellisense does not present playlist.title. Can you help me please?

**Comment by Tyrrrz** [comment]
You need to `await` the task

**Comment by lindomar-marques55** [comment]
'wait' can thus be used in an 'asynchronous' method. consider the tag of this method with the modifier 'async' and a change of the return type to 'task' . 
I do not know how to pass on. I managed to understand the functioning of the api to download individual videos but I can not download playlists.
![Capturar](https://user-images.githubusercontent.com/50804821/60473681-96030400-9c44-11e9-833c-cf7f1e094708.PNG)

**Comment by Tyrrrz** [comment]
I guess you have to learn how to work with async/await
https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/concepts/async/
