### ISSUE TITLE
Found bug

### ISSUE THREAD

**Issue by yasha107** [Tyrrrz/YoutubeExplode#216]
When trying to download this video: https://www.youtube.com/watch?v=C-ZDyOrrgOc
It says error 404 not found. 
This is not because of the lenght of it as I tried downloading 10h one and it worked fine.

**Comment by Tyrrrz** [comment]
I'm not able to replicate this. Can you explain what exactly you are doing and where are you getting 404?

**Comment by yasha107** [comment]
Fixed the issue, `video.Thumbnails.MaxResUrl` was causing it.
