### ISSUE TITLE
Extraction of video comments implementation

### ISSUE THREAD

**Issue by raminrahimzada** [Tyrrrz/YoutubeExplode#217]
Hi, I found this repo very awesome , so I want to contribute in getting comments which is not implemented.
I have my own code  thats getting first 20 comments (yet)
[My Code Snippet Here](https://gist.github.com/raminrahimzada/95b4cf135f7d32cfecc8074391e6a5b4)

Because we get 20 by 20 comments in each request

But code needed to complete with yielding next root comments and also loading sub-comments
I followed chrome debugger in youtube site, and saw all comment loading requests goes the same url 
[youtube.com/comment_service_ajax?action_get_comments=1&pbj=1&ctoken=blabla&continuation=blabla&itct=blabla](#)
but different
parameters - tokens - ctoken , session_token, itct, visitorInfo1Live, continuation , for more pls check the code above .
each of this request is POST and  also contains payload as following:
session_token=blabla
Comment Requests  works as following:
Every Time i request for comments the response contains `continuation`  and `trackingParams` parameter
for the request of the next comments
For the reason of non-completed code (getting only 20 root comments)  
I did not created as a pull-request

**Comment by Tyrrrz** [comment]
Hi @raminrahimzada 
Thank you for your interest in this project!
Getting comments is out of scope for this project, at the very least until `IAsyncEnumerable<T>` becomes widely available.
