### ISSUE TITLE
"Newtonsoft.Json.JsonReaderException" with "GetPlaylistAsync".

### ISSUE THREAD

**Issue by Kajirinn** [Tyrrrz/YoutubeExplode#218]
I'm not sure if I'm the one who's at fault but this is the first time I've seen this issue. Long story short, I'm trying to make a program that downloads every video in a playlist. This succeeded for the most part; until the program refused to download the last 2 files throwing this error;

```
Exception thrown: 'Newtonsoft.Json.JsonReaderException' in mscorlib.dll
Newtonsoft.Json.JsonReaderException: Error reading JToken from JsonReader. Path '', line 0, position 0.
   at Newtonsoft.Json.Linq.JToken.ReadFrom(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JToken.Parse(String json, JsonLoadSettings settings)
   at YoutubeExplode.Internal.Parsers.VideoWatchPageParser.GetConfig()
   at YoutubeExplode.YoutubeClient.<GetPlayerResponseParserAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
```

[The playlist in question.](https://www.youtube.com/playlist?list=PL1Gv-OC8tneodd99wZvmJFm4qs6ABOHIQ)

If you need any further elaboration I'll attempt to provide with the needed info.

Sincerely, Kajirinn.

**Comment by Tyrrrz** [comment]
Not sure what it could be, I just tried that and got full playlist with 155 videos.
![image](https://user-images.githubusercontent.com/1935960/53304287-0f947b00-387c-11e9-959f-fa17508fb559.png)

**Comment by Tyrrrz** [comment]
Nevermind, I misunderstood the original post, I can see now that it fails when downloading videos, not when parsing the playlist.

**Comment by Tyrrrz** [comment]
It appears the videos that fail are unavailable. Will have to look into why the proper exception is not thrown.
![image](https://user-images.githubusercontent.com/1935960/53304373-14a5fa00-387d-11e9-8c8f-d59d94b9920f.png)
