### ISSUE TITLE
Video description does not contain timestamps

### ISSUE THREAD

**Issue by Kriste00** [Tyrrrz/YoutubeExplode#220]
If a video description contains timestamps (Example: `00:45`) it gets turned into a `#` instead of showing the actual timestamp string.

Debugger:
![image](https://user-images.githubusercontent.com/32580874/54479548-20eafa80-481e-11e9-8203-2e427f6d44af.png)

Youtube:
![image](https://user-images.githubusercontent.com/32580874/54479557-2e07e980-481e-11e9-8f3f-c1ffa8d5ef2d.png)

**Comment by Tyrrrz** [comment]
Can you give me the video link?

**Comment by Kriste00** [comment]
`https://www.youtube.com/watch?v=yl8BItZ0Wwo`
