### ISSUE TITLE
Some videos are missing from search results

### ISSUE THREAD

**Issue by Giggitybyte** [Tyrrrz/YoutubeExplode#221]
It would seem that videos that are from topic channels are excluded from the search results. 

[YouTube search results](https://i.imgur.com/3YtoA1p.png).
[YoutubeExplode search results](https://i.imgur.com/033FxJ0.png).

Aside from mixes, playlists, and "related" videos, content from topic channels are just straight up missing from YoutubeExplode search results.

**Comment by SlowLogicBoy** [comment]
Can you give us a link to a video that's missing?
This might be because it's an explicit video and requires you to log in to see it, and/or youtube search is adjusted for your account and that's why results are different.
This is how my youtube search looks like:
![image](https://user-images.githubusercontent.com/3121637/55055241-137a0f80-506b-11e9-97b4-3f995fb83941.png)

**Comment by Giggitybyte** [comment]
A few missing videos:
[Video](https://www.youtube.com/watch?v=KtSpk2pMZrs)
[Video](https://www.youtube.com/watch?v=AdbjDNI0exw)
[Video](https://www.youtube.com/watch?v=04pLNlOcXVE)
[Video](https://www.youtube.com/watch?v=_lVhCamlk2A)

As I said, every it's topic video.
It doesn't matter if I'm signed in or not, I'll get pretty much the same search results from YouTube. 

Example with another search:
[YouTube results](https://i.imgur.com/WlFtI72.png).
[YoutubeExplode results](https://i.imgur.com/yffuRcn.png).
The second result from the YouTube results, which is from a topic channel, is missing from the YoutubeExplode results.

**Comment by Tyrrrz** [comment]
The `SearchVideosAsync` method is actually using YouTube's IFrame API, which is equivalent to opening this embed player in a browser: https://www.youtube.com/embed/?listType=search&list=115 (it used to show the list of videos before but for some reason it doesn't anymore, but you will still get the next video after this one finishes).

This search was known to work differently than the one on the actual website and some of the discrepancies were eventually removed by YouTube itself. I guess the recent introduction of topics in the search results hasn't made it into IFrame player yet.

**Comment by Tyrrrz** [comment]
Also, note that search results are personalized, even in incognito mode.

For example here are my results from (1) YoutubeExplode (2) Incognito search (3) Logged in search. Note the difference between them, but also between my results and your (@Giggitybyte) results -- I don't have any topics.

![image](https://user-images.githubusercontent.com/1935960/55072541-1806ee00-5094-11e9-9205-afb1b11a4a7a.png)
![image](https://user-images.githubusercontent.com/1935960/55072559-2228ec80-5094-11e9-927c-a13b36a9ba70.png)
![image](https://user-images.githubusercontent.com/1935960/55072574-27863700-5094-11e9-8d97-aec81c9de156.png)

**Comment by Giggitybyte** [comment]
I've tried on a few different devices and I get almost the same results, even on my phone browser using 4G. Results from topics must only show in some regions; I'm in the United States.

**Comment by Giggitybyte** [comment]
Is there way to get search data other than the IFrame API short of scraping the search page itself?

**Comment by Tyrrrz** [comment]
I want to know if there is too. Last time I looked into it, I couldn't find anything better than scrapping the page.

**Comment by Giggitybyte** [comment]
Well, if you figure out another way or you end up scraping the page, let me know. I'd love to have those topics results for my users.
