### ISSUE TITLE
Poor performance in GetVideoAsync

### ISSUE THREAD

**Issue by SnGmng** [Tyrrrz/YoutubeExplode#222]
Since Yesterday my application was dead slow. I traced the issue down to the GetVideoAsync call. I updated YoutubeExplode yesterday, but i dont know if it is related to that update tho. I also benchmarked GetVideoAsync:
1139,06ms (average) per call!
You would have to wait 20s to load a 20 video playlist.
The GetPlaylistAsync takes reasonable 239,75ms (average) per call.

This is how i benchmarked:
`YoutubeClient client = new YoutubeClient();`
`Stopwatch stopwatch = new Stopwatch();`
`List<long> lstElapsed = new List<long>();`
`for (int i = 0; i < 100; i++)`
`{`
`    stopwatch.Reset();`
`    stopwatch.Start();`
`    var vid = await client.GetVideoAsync("-7fuHEEmEjs");`
`    stopwatch.Stop();`
`    var mil = stopwatch.ElapsedMilliseconds;`
`    lstElapsed.Add(mil);`
`    Debug.WriteLine("miliseconds elapsed: " + mil);`
`}`
`Debug.WriteLine("avg miliseconds elapsed: " + lstElapsed.Average());`

hope this gets fixed soon 😄

**Comment by Tyrrrz** [comment]
Nothing changed in YoutubeExplode since yesterday, so if anything happened it was on YouTube's side. Also, `GetVideoAsync` is known to be pretty slow, hence why it was decoupled from the rest of the API in 4.0.

If you know how to improve the performance -- feel free to make a PR.

**Comment by SnGmng** [comment]
Ive tested the previous versions and heres what i found:
4.6.7 averages 1139,06ms
4.6.6 averages 1009,46ms
4.6.5 averages 1046,5ms
4.6.4 averages 822,96ms
The time is the average of 30 GetVideoAsync calls.
Versions lower than 4.6.4 have about the same performance as 4.6.4.
In the last 3 versions there is something that slows down the calls by 300ms.
Allthough 300ms is a lot, it still doesnt explain why my application slowed down so much.
I will investigate that issue further.

**Comment by Tyrrrz** [comment]
Hm. According to the [changelog](https://github.com/Tyrrrz/YoutubeExplode/blob/master/Changelog.md), 4.6.5 changed how video descriptions are parsed in [this method](https://github.com/Tyrrrz/YoutubeExplode/blob/73a6ad0bf01bc78f513e64eba52566bd7f390efe/YoutubeExplode/Internal/Parsers/VideoWatchPageParser.cs#L24-79), which could be related.

**Comment by SnGmng** [comment]
Ive found out that ParseDescription is the slowest method in GetVideoAsync with 440ms, followed by GetVideoWatchPageParserAsync (400ms), and GetPlayerResponseParserAsync (230ms).

My PR reduces the execution time of ParseDescription to 200ms. I am surprised that changing that one if statement saved 200ms. Maybe it would be better to use a Regex instead of looped string comparisons. Would this be an option?
