### ISSUE TITLE
Convert from WEBM to MP3

### ISSUE THREAD

**Issue by MidasKing67** [Tyrrrz/YoutubeExplode#224]
Hello, I would like to ask if there is a way to download audio file and save it as .mp3? Because everytime I try to download Audio Only I end up with .webm file which I'm unable to open. Thus I ask if there is a way to download .mp3? Thanks in Advance

**Comment by Tyrrrz** [comment]
Hello. You would need to convert the stream from .webm to .mp3, they don't come as .mp3 unfortunately.

[YoutubeExplode.Converter](https://github.com/Tyrrrz/YoutubeExplode.Converter) will help you with that.

**Comment by MidasKing67** [comment]
> Hello. You would need to convert the stream from .webm to .mp3, they don't come as .mp3 unfortunately.
> 
> [YoutubeExplode.Converter](https://github.com/Tyrrrz/YoutubeExplode.Converter) will help you with that.

If I may ask, how do you convert stream from webm to mp3? I'm a noobie.

**Comment by Tyrrrz** [comment]
With that library you'd use `await converter.DownloadVideoAsync("video id", "output.mp3");`

**Comment by MidasKing67** [comment]
> With that library you'd use `await converter.DownloadVideoAsync("video id", "output.mp3");`

Ok so I went and tried it out, however during the download phase and exception was Thrown. So I tried to use the other Download from Converter DownloadAndProcessMediaStreamsAsync, but the same exception. It says that **System can't find the path to the given file**.

**Comment by Tyrrrz** [comment]
Yes, you also need to have ffmpeg.exe in the same directory as the executable. You can get it from [here](https://github.com/vot/ffbinaries-prebuilt/releases) or use a script like [this one](https://github.com/Tyrrrz/YoutubeExplode.Converter/blob/master/YoutubeExplode.Converter.Tests/DownloadFfmpeg.ps1).

**Comment by MidasKing67** [comment]
> Yes, you also need to have ffmpeg.exe in the same directory as the executable. You can get it from [here](https://github.com/vot/ffbinaries-prebuilt/releases) or use a script like [this one](https://github.com/Tyrrrz/YoutubeExplode.Converter/blob/master/YoutubeExplode.Converter.Tests/DownloadFfmpeg.ps1).

Alright thank you very much for the help. But it's a shame that now youtube provides only webm formats, I remember like a month ago you could have downloaded Audio stream and it would download an .mp3 file.

**Comment by Tyrrrz** [comment]
YouTube hasn't been providing mp3 streams since they discontinued their Flash-based player, IIRC.

You can download files anywhere 😉

**Comment by MidasKing67** [comment]
> YouTube hasn't been providing mp3 streams since they discontinued their Flash-based player, IIRC.
> 
> You can download files anywhere

Yeah I I did it the old traditional way I guess, File.Copy and then File.Delete

**Comment by Tyrrrz** [comment]
How are you putting path?

**Comment by MidasKing67** [comment]
```
await converter.DownloadVideoAsync(videoId, $"{File_Handler.DownloadLocation}\\{title}.{ext}", Progress);
```

**Comment by Tyrrrz** [comment]
What does `File_Handler.DownloadLocation` evaluate to? Does the directory exist?

**Comment by MidasKing67** [comment]
> What does `File_Handler.DownloadLocation` evaluate to? Does the directory exist?

Yep it has to, a user chosen destination. FolderBrowseDialog is used to get users download location, thus it has to exist, and there is also a check if it doesn't the script will create one. 

```
/// <summary>
/// Returns the download location from Configs
/// </summary>
internal static string DownloadLocation
        {
            get
            {
                try
                {
                    List<string> cont = new List<string>(File.ReadAllLines(Configs_));
                    foreach(string s in cont)
                    {
                        if(s.StartsWith("DownloadsLocation"))
                        {
                            string line = Regex.Split(s, "=")[1];
                            Regex.Replace(line, " ", "");
                            return line;
                        }
                    }
                    return null;
                }
                catch
                {
                    return null;
                }
            }
        }
```

**Comment by Tyrrrz** [comment]
When CliWrap throws an exception, what's the value of `exception.ExecutionResult.StandardError` and ``exception.ExecutionResult.StandardOutput`?

**Comment by MidasKing67** [comment]
> When CliWrap throws an exception, what's the value of `exception.ExecutionResult.StandardError` and `exception.ExecutionResult.StandardOutput`?

Aight tried to debug it a little, but unfortunately was unable to get values you asked for.

**All I could Get:**
```
---------------------------
Error Downloading
---------------------------
Underlying process reported a non-zero exit code: 1

Target Site:
Void ValidateExecutionResult(CliWrap.Models.ExecutionResult)

Source:
CliWrap

Inner Exception:


HResult:
-2146233088
---------------------------
OK   
---------------------------

```

**Comment by Tyrrrz** [comment]
Okay, anyway, glad you got it sorted out.

**Comment by MidasKing67** [comment]
Thanks :+1:

**Comment by GabrielAstra** [comment]
This post helped me, thanks from Brazil!
