### ISSUE TITLE
Get song information

### ISSUE THREAD

**Issue by DarkEyeDragon** [Tyrrrz/YoutubeExplode#225]
Is there a way to retrieve the audio information of a video (excuses for it being in dutch)?
![image](https://user-images.githubusercontent.com/6131099/55293041-d195f400-53f1-11e9-8ab3-50cc8c10fcd6.png)

This would be a lot easier than having to filter titles for artist names and such.

**Comment by Tyrrrz** [comment]
I can see how this can be useful, but unfortunately there's no way to do this currently and this is out of scope for this library.

**Comment by DarkEyeDragon** [comment]
I see. Fair enough. Thanks for your amazing library anyway!

**Comment by Tyrrrz** [comment]
I'm glad you enjoy using it. :)
