### ISSUE TITLE
Search that returns playlists, channels and videos instead of just single videos?

### ISSUE THREAD

**Issue by AvocadoArmor** [Tyrrrz/YoutubeExplode#226]
The search only returns a list of videos. If you were to search on YouTube.com, sometimes playlists and even channels would come up (in addition to videos) for a search query. 

Does this seem plausible?

**Comment by Tyrrrz** [comment]
This is related to #221, the reverse-engineered API we use has limited subset of search results compared to search on the website. We will likely have to scrap the search results via HTML, most likely, to get the most accurate representation of search.

**Comment by omarroth** [comment]
If there is a way to allow search params in `/search_ajax` then I think it would be fantastically useful. Unfortunately I haven't found a way to do this, instead Invidious scrapes the page as you suggest. Here's a couple notes I hope will be useful:

Scraping `/results` will get *most* of the content available from the endpoint YouTubeExplode currently uses. You can see an example [here](https://invidio.us/api/v1/search?q=music&type=all&pretty=1). Several fields are missing that are present in `/search_ajax`:
- unavailable:
  - privacy
  - comments
  - keywords
  - likes
  - dislikes
  - rating
  - category_id
- unimplemented:
  - cc_license
  - is_hd
  - is_cc

Although Invidious provides a `published` field, this is calculated from the "6 months ago" text, and so is not consistent with the date provided by the `/search_ajax` endpoint. YouTube does not provide a timestamp or any other way that I know of for providing an accurate upload date.

Invidious scrapes HTML from `/results?search_query=query&disable_polymer=1`, although you can get slightly more information from the `window["ytInitialData"]` included in the polymer redesign, including `estimatedResults`. You can see the code used to scrape the HTML [here](https://github.com/omarroth/invidious/blob/master/src/invidious/helpers/helpers.cr#L172), although it's used for scraping other parts of the site as well so it's a bit messy.

I provide a brief explanation of how to implement search filters in TeamNewPipe/NewPipeExtractor#106, and I'd also recommend taking a look at the relevant [code](https://github.com/omarroth/invidious/blob/master/src/invidious/search.cr#L108). The "token" generated can then be appended as `&sp=AAAA` to the search URL.

**Comment by AlenToma** [comment]
Any update here, i have already created a youtube search that get the html from the search rest and then parse it. But to much information is missing.

I would like to implement it in this library but, will have make more then one http calls to get the information and it will be very bad for performance.

Isnt there any other way to get all the information nedded.

**Comment by Tyrrrz** [comment]
I don't have time to dedicate to this but I'm open for PRs

**Comment by AlenToma** [comment]
Will implement it, and then let you have a look at it. You may make it better then.

**Comment by AlenToma** [comment]
I have create YoutubeSearch, by scraping the html data. 
Have a look [here](https://github.com/AlenToma/YoutubeExplode/blob/master/YoutubeExplode/YoutubeClient.Search.cs) in my youtube-explorer fork. 

Some data is missing, like `Likecount `and `Dislikecount` but now you could search for `Channel` ,'Movie','Playlist', `Video`, `Rating` and also the default which is a `mix`.

Let me know what you think, look at 'SearchVideosByFilterAsync' Method and se if it a good idee to replace `SearchVideosAsync` or simple have at as extra.

**Comment by Tyrrrz** [comment]
What exactly happens when you use SearchFilter.Channel? Because I can see the method still returns `IReadOnlyList<Video>`.

**Comment by AlenToma** [comment]
Yes in Video i added `VideoType` which is the type of the video. the Video object could be `Video`, `Playlist ` or `Channel`

the id of the Video can be a `channelId`, `playlistId `or `Videoid`

Now `SearchFilter` sets the `sp ` of the html url. have a look at [GetYoutubeHtmlResultAsync](https://github.com/AlenToma/YoutubeExplode/blob/master/YoutubeExplode/YoutubeClient.Search.cs#LC24)

**Comment by Hexer10** [comment]
If anyone is interested on how to implement this I added this feature in my dart port of this library, maybe it could be of some use: https://github.com/Hexer10/youtube_explode_dart/blob/search_page/lib/src/reverse_engineering/responses/search_page.dart

**Comment by Tyrrrz** [comment]
Hi.
Unfortunately I have to descope this issue as the project has moved into maintenance mode, which means that new features are unlikely to get implemented.
