### ISSUE TITLE
Java Version?

### ISSUE THREAD

**Issue by darkdoctor** [Tyrrrz/YoutubeExplode#227]
Hi Tyrrz.

Really love this library, so fast and good.

Will there any similar like this library be on JAVA also, would be apprecaited.

Thanks.

**Comment by omarroth** [comment]
Might take a look at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor). It's part of NewPipe, but I believe it can be used as a library.

**Comment by Tyrrrz** [comment]
Thank you.
I don't plan on writing anything in/for Java, so I guess the answer is no, @darkdoctor 
You can check out the library @omarroth suggested or perhaps search for some alternative package. Worst case scenario, you can probaby use youtube-dl for some things.

**Comment by darkdoctor** [comment]
Thanks for quick response.

This library is the only one who has continous support and development and the best :)

**Comment by Tyrrrz** [comment]
😊
