### ISSUE TITLE
streamInfo.Container.GetFileExtension() throws an error

### ISSUE THREAD

**Issue by 7Gaming** [Tyrrrz/YoutubeExplode#233]
I wasn't quite sure what to name this but what seems to be the problem is that "streamInfo.Container.GetFileExtension()" throws an error when I call it: 
![Error](https://user-images.githubusercontent.com/47871969/56401173-a69b0500-6225-11e9-8b4b-29e12b778be2.JPG)

It says "System.NullReferenceException: Object reference not set to an instance of an object" but doesn't point to any of my code. 
My code (The first two lines that are commented out are where the error occurs):
![Method](https://user-images.githubusercontent.com/47871969/56401122-5cb21f00-6225-11e9-972c-0e53e464405b.JPG)

I looked for a little while on my own to try and find a solution but couldn't pin one down. However, I found something weird that may help someone else know what's going on. The thing I thought was weird was how the one line I have in the message box returns zero; "streamInfoSet.Audio.Count" = 0 which only confuses me more. Is there any reason this would return zero? If this is the actual problem, how do I fix it?

Full disclosure: I'm trying to build this on Android, hopefully, that doesn't affect the functionality

And thank you for anyone who replies, I'm very interested and eager to learn!

**Comment by balasratran** [comment]
#229

**Comment by 7Gaming** [comment]
I didn't even realize! They do sound like the same issue, I'll go ahead and close this.
