### ISSUE TITLE
Using YoutubeExplode in Asp.net core 2.2

### ISSUE THREAD

**Issue by farazp** [Tyrrrz/YoutubeExplode#235]
Hi,

any body have using YoutubeExplode in asp.net core 2.x project?

I try download video with requested in webapi control but I got this error:

One or more errors occurred. (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond)

I teted this in my computer and this working fine but when I uploaded to host get this error

```
var client = new YoutubeClient();
var video = await client.GetVideoAsync(videoId: ids);
                            var title = video.Title; // "Infected Mushroom - Spitfire [Monstercat Release]"
                            var author = video.Author; // "Monstercat"
                            var duration = video.Duration; // 00:07:14
                            string caption = String.Format($"Title: {RemoveIllegalPathCharacters(title)} - Author: {author} - Duration: {duration}");
                            var videoContent = await client.GetVideoAsync(ids);
 var streamInfoSet = await client.GetVideoMediaStreamInfosAsync(ids);
 var streamInfo = streamInfoSet.Muxed.WithHighestVideoQuality();
 var fileExtension = streamInfo.Container.GetFileExtension();
 string fileName = RemoveIllegalPathCharacters(title) + fileExtension;
string filepath = Path.Combine(_env.ContentRootPath, "Video", fileName);
```

**Comment by Tyrrrz** [comment]
Perhaps @SlowLogicBoy can help

**Comment by SlowLogicBoy** [comment]
Possibly your hosting provider is blocking connections to Youtube.

**Comment by Zyano** [comment]
I was using youtube explode until it broke about two weeks ago with .net core 2.2 it should be working just fine.

If you can post a full stack trace then we might be able to help little more

**Comment by farazp** [comment]
Hi I update my project to my host and I got this log
`warn: Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository[50]
      Using an in-memory repository. Keys will not be persisted to storage.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[59]
      Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {58e893f2-e5e0-4887-87bf-89198bf36a33} may be persisted to storage in unencrypted form.
Hosting environment: Production
Content root path: E:\HostingSpace\
Now listening on: http://127.0.0.1:25613
Application started. Press Ctrl+C to shut down.
fail: You_V_Bot.Services.UpdateService[0]
      Log Error
System.AggregateException: One or more errors occurred. (A task was canceled.) ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at You_V_Bot.Services.UpdateService.IsValidUri(Uri uri) in \UpdateService.cs:line 164
   at You_V_Bot.Services.UpdateService.EchoAsync(Update update) in \UpdateService.cs:line 54
---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

fail: You_V_Bot.Services.UpdateService[0]
      Log Error
System.AggregateException: One or more errors occurred. (A task was canceled.) ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at You_V_Bot.Services.UpdateService.IsValidUri(Uri uri) in \UpdateService.cs:line 164
   at You_V_Bot.Services.UpdateService.EchoAsync(Update update) in \UpdateService.cs:line 54
---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

Application is shutting down...`

also can you send sample script how to used in asp.net core mvc?

**Comment by farazp** [comment]
> Possibly your hosting provider is blocking connections to Youtube.

I check this hosting provider
