### ISSUE TITLE
Doc Update for How to

### ISSUE THREAD

**Issue by darkdoctor** [Tyrrrz/YoutubeExplode#236]
Hi Tyrrz. Hope you are doing fine on your vacation.

Can you please update this wiki when you have free time.
https://www.tyrrrz.me/Blog/Reverse-engineering-YouTube

I am trying to extract the stream urls (JAVA), but since your library is handling almost all the cases to parse the stream, would be great if you help us by updating the wiki(blog).

**Comment by Tyrrrz** [comment]
Hi,
Thank you. :)
I will try to update it when I have time but for the most part it's still valid.
I will close this issue as it's not related directly to YoutubeExplode, please post a comment on the blog post instead next time.
