### ISSUE TITLE
GetVideoAsync() returns wrong data

### ISSUE THREAD

**Issue by belkin1667** [Tyrrrz/YoutubeExplode#238]
It fails on the video: https://www.youtube.com/watch?v=9b8Kq98G6-Q 

My code: 
```
var id = "9b8Kq98G6-Q";
YoutubeClient client = new YoutubeClient();
var video = await client.GetVideoAsync(id);
var title = video.Title;

```
Expected behavior:
title = "Статус / Екатерина Шульман / Сезон 2. Выпуск 36 // 14.05.19"

Actual behavior:
title = "14.05.19"

**Comment by Tyrrrz** [comment]
I can't seem to reproduce
![image](https://user-images.githubusercontent.com/1935960/57735524-8daf3380-76ad-11e9-825e-0b0ee7b8aba9.png)

**Comment by belkin1667** [comment]
That's strange, probably the problem is on my end, thanks for quick answer

**Comment by Tyrrrz** [comment]
No problem
