### ISSUE TITLE
Error reading JToken from JsonReader. Path '', line 0, position 0.

### ISSUE THREAD

**Issue by yetiks** [Tyrrrz/YoutubeExplode#239]
Hello @Tyrrrz 
Thanks for all Your job!
I still can found a couple of videos which returns error:
Error reading JToken from JsonReader. Path '', line 0, position 0.
Check those movies:
9Iz0-hqfmNw
FFo9f-IgtUo
tYzAboIsUUM
_Ih0Xnps3-c

There are not so much but could you check ?

**Comment by Tyrrrz** [comment]
9Iz0-hqfmNw - looks like the video is blocked in my country, maybe in yours too?
FFo9f-IgtUo - works for me.
tYzAboIsUUM - it's an age restricted AND non-embeddable video, looks like [youtube-dl can't download it either](https://user-images.githubusercontent.com/1935960/57885968-da714680-7834-11e9-972a-a3d0d0719e30.png)
_Ih0Xnps3-c - same as above

I'll work on a better exception so you will know what's wrong
