### ISSUE TITLE
Save video, playlist and channel objects to file

### ISSUE THREAD

**Issue by Rabadation** [Tyrrrz/YoutubeExplode#240]
It would be great if the class of videos, playlists, and channels were marked as serializable for being able to save the metadata directly to a file.

**Comment by Tyrrrz** [comment]
You can use [JSON.net](https://www.newtonsoft.com/json), it doesn't need attributes

**Comment by Rabadation** [comment]
I got an a "System. ArgumentNullException" in the parameter "videoId" with the code:
` //create file
                File.WriteAllText(Directory.GetCurrentDirectory() + "\\data.dat", Newtonsoft.Json.JsonConvert.SerializeObject(data));
                //open file
                data = Newtonsoft.Json.JsonConvert.DeserializeObject<IndexedChannelsAndPlaylists>(File.ReadAllText(Directory.GetCurrentDirectory() + "\\data.dat"));`
(In the IndexedChannelsAndPlaylists class, there's only an object for a channel and its uploaded videos)

**Comment by Rabadation** [comment]
I got an a "System. ArgumentNullException" in the parameter "videoId" with the code:

//create file
File.WriteAllText(Directory.GetCurrentDirectory() + "\data.dat", Newtonsoft.Json.JsonConvert.SerializeObject(data));

//open file
data = Newtonsoft.Json.JsonConvert.DeserializeObject(File.ReadAllText(Directory.GetCurrentDirectory() + "\data.dat"));

(In the IndexedChannelsAndPlaylists class, there's only an object for a channel and its uploaded videos)

**Comment by Tyrrrz** [comment]
Somehow the `videoId` parameter is set to null, make sure it's there in JSON

**Comment by Rabadation** [comment]
```videoId``` isn't there, but there is an ```Id``` 
https://pastebin.com/j2Wh7QjZ

**Comment by Tyrrrz** [comment]
Ah, I see now. It's from Thumbnails, it needs `videoId` as constructor parameter but it doesn't expose it as property.
I think your best bet is to make your own custom Video class and serialize that.

**Comment by Rabadation** [comment]
Ok, I'm going to do that. Thanks.
