### ISSUE TITLE
Some videos url play on local mode debug when publish in producction URL cannot access

### ISSUE THREAD

**Issue by rekiem233** [Tyrrrz/YoutubeExplode#245]
MediaStreamInfo prop URL 
Only i can play video en mode debug when publish on site some URL not play , example

https://r5---sn-hp57ynee.googlevideo.com/videoplayback?expire=1560330240&ei=oGsAXaipH5StwQHgl5CICg&ip=2806%3A10b7%3A1%3Abacd%3A29ac%3A43b7%3A5b28%3A1364&id=o-ABpAXruHTw0XsqfhtD6USd2Ej3syNqUBtz1jnkxt1Moq&itag=18&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-hp57ynee%2Csn-a5mlrn7r&ms=au%2Conr&mv=m&pl=50&usequic=no&gcr=mx&initcwndbps=450000&mime=video%2Fmp4&gir=yes&clen=4962133&ratebypass=yes&dur=260.063&lmt=1518943695858039&mt=1560308472&fvip=5&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&lsparams=mm%2Cmn%2Cms%2Cmv%2Cpl%2Cusequic%2Cinitcwndbps&lsig=AHylml4wRQIhAKZalqy6eTSePCstHqMPrvGXg9BbNrK6fIYHowrNhj51AiB28O-oBmsGNjF-XN-_3TQUJvRNGK0sF9ULnA0p0-LRuQ%3D%3D&sig=ALgxI2wwRgIhAIA0DsRtVtOOixl83R7NJFPLJmMo1VMR7f3jIoQVPEg8AiEAwJh1lRgOwXAorZOSR5oCE2Vuuvp3J0pERA_42yE83ik=

ONLY PLAY ON MODE DEBUG WHEN PUBLISH THIS video "9HNgrCOpd6I" cannot access
can u help me?

**Comment by Tyrrrz** [comment]
There aren't any differences in terms of behavior when it comes to Debug vs Relase

**Comment by luca233** [comment]
I know, but for some reason when I publish the API, some videos do not work, while I clean local if I open the URL of the Info object correctly

**Comment by Tyrrrz** [comment]
Ah. Well the problem is that those URLs are IP-bound. When you are debugging locally, your web server has the same IP as the client.

**Comment by luca233** [comment]
is installed on an EU server and the hosting service has shared ip, in this case what can be done?

**Comment by Tyrrrz** [comment]
Related to #149?

**Comment by Tyrrrz** [comment]
Also same #250
