### ISSUE TITLE
Codec unknown, cause exception in Heuristics.VideoEncodingFromString

### ISSUE THREAD

**Issue by DalilaSilva** [Tyrrrz/YoutubeExplode#246]
Some videos on youtube response, it contains unknow codec, that causes an exception in: **Heuristics.VideoEncodingFromString("unknow")**

know video id with this problem *aEb5gNsmGJ8*

**Comment by Tyrrrz** [comment]
YouTube is returning av1 streams with "unknown" codec, what the fuck
