### ISSUE TITLE
Run the "DemoConsole", get an error

### ISSUE THREAD

**Issue by tiger2014** [Tyrrrz/YoutubeExplode#248]
I input "https://www.youtube.com/channel/UCa6ERCDt3GzkvLye32ar89w" in the console ,and Enter，then get the erro ：
![image](https://user-images.githubusercontent.com/6703612/59553779-f4469c00-8f4e-11e9-856e-3d94afd0f00e.png)

**Comment by Tyrrrz** [comment]
DemoConsole/DemoWpf is only for videos
