### ISSUE TITLE
Could not find signature decipherer function name

### ISSUE THREAD

**Issue by RexfelisLOC** [Tyrrrz/YoutubeExplode#252]
Starting getting this exception this morning.  Looks like YouTube changed again.

**Comment by omarroth** [comment]
Likely related to TeamNewPipe/NewPipe#2415. Mind providing a couple example where you're encountering this, or do the examples provided in the linked issue also fail to load?

**Comment by RexfelisLOC** [comment]
I didn't see that issue and they look to be related (all music).  Here's a couple of examples:

await client.GetVideoMediaStreamInfosAsync("DoU8Mb_5u70")
await client.GetVideoMediaStreamInfosAsync("KvuQNNVrbtM")

**Comment by yetiks** [comment]
@Tyrrrz  I have the same issue

**Comment by omarroth** [comment]
@Tyrrrz I suggested a fix in the NewPipe issue. For this project you might try changing [this line](https://github.com/Tyrrrz/YoutubeExplode/blob/1413f54a97b6852a66f7ec529d4b59b3b55f5e7b/YoutubeExplode/YoutubeClient.Video.cs#L206) to [`^(?<name>[^=]+)=function\(a\){a=a\.split\(""\)/m`](https://github.com/omarroth/invidious/blob/0.18.0/src/invidious/helpers/signatures.cr#L7). See also jdf76/plugin.video.youtube#624 for their fix.

**Comment by wleader** [comment]
The patterns in https://github.com/jdf76/plugin.video.youtube/pull/624 do find a match, but they use regex recursion, which the base .net Regex does not support, so they would have to be re-worked.

The Pattern from invidious  ^(?<name>[^=]+)=function\(a\){a=a\.split\(""\)/m does not find a match when executed by the .Net Regex. (or at least it did not on the video I was testing with: Qdb4NyHdFfE )

On a side note,  By Hephaestus, I hate regex.
