### ISSUE TITLE
The server returned an invalid or unrecognized response

### ISSUE THREAD

**Issue by JoaoZanetti** [Tyrrrz/YoutubeExplode#256]
Hi everyone!

When i try to download [this](https://www.youtube.com/watch?v=w0KPMmWzEJs) video i receive "System.IO.IOException - The server returned an invalid or unrecognized response. ". Others videos seems to be working fine.

Microsoft.NETCore.App - 2.2.0
YoutubeExplode - 4.7.3

Runtime:

> .NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview6-012264
 Commit:    be3f0c1a03

>  Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\

> Host (useful for support):
  Version: 3.0.0-preview6-27804-01
  Commit:  fdf81c6faf

> .NET Core SDKs installed:
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.604 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.2.105 [C:\Program Files\dotnet\sdk]
  2.2.204 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  3.0.100-preview6-012264 [C:\Program Files\dotnet\sdk]

![Screenshot_45](https://user-images.githubusercontent.com/18476803/59979925-cdc6d780-95c4-11e9-9fee-a3f5483db855.png)

My code: 
```var id = Video.YoutubeId;
var infoSet = await Client.GetVideoMediaStreamInfosAsync(id);
var streamInfo = infoSet.Muxed.WithHighestVideoQuality();
this.Video.Extension = streamInfo.Container.GetFileExtension();

Console.WriteLine("VIDEO: " + JsonConvert.SerializeObject(Video, Formatting.Indented));

try
{
    Console.WriteLine("STREAM INFO: " + JsonConvert.SerializeObject(streamInfo, Formatting.Indented));
    await Client.DownloadMediaStreamAsync(streamInfo, $"Videos//video{id}.{Video.Extension}");
}
catch(Exception e)
{
    Console.WriteLine("@@Exception");
    Console.WriteLine(JsonConvert.SerializeObject(e, Formatting.Indented));
    Console.ReadLine();
    System.Environment.Exit(0);
}

**Comment by Tyrrrz** [comment]
It seems the actual exception is

```
System.IO.IOException: 'Unable to read data from the transport connection: The connection was closed.'
```

Seems to be the same as #219, on YouTube's end
