### ISSUE TITLE
Playlists are constructed with a Statistics object for no reason

### ISSUE THREAD

**Issue by YoshiRulz** [Tyrrrz/YoutubeExplode#257]
Using the Android app or web client (even with `disable_polymer=true`), you can't like/dislike user-made playlists (prefix `PL`). Since you also can't like any of the system playlist types, scraping that information isn't necessary.

So this can be just the view count:
https://github.com/Tyrrrz/YoutubeExplode/blob/f45ed44d8469eff400a174207b46f0692806eca0/YoutubeExplode/YoutubeClient.Playlist.cs#L54-L56
And this can be replaced with `long ViewCount`:
https://github.com/Tyrrrz/YoutubeExplode/blob/d56c959023305f09927515efa3a661b632858f30/YoutubeExplode/Models/Playlist.cs#L46

**Comment by Tyrrrz** [comment]
There's no overhead in parsing it. If there will be problems with it, I'll cosinder removing it.
