### ISSUE TITLE
GetChannelUploadsAsync Not Return Any Videos

### ISSUE THREAD

**Issue by hung1xpro** [Tyrrrz/YoutubeExplode#259]
Hello bro, nice to meet you but today i got new bug,
the GetChannelUploadsAsync not return any videos ...

**Comment by Tyrrrz** [comment]
Doesn't work on all channels?

**Comment by hung1xpro** [comment]
idk but i can't find channel can get video ...... all channel that i know still return 0

**Comment by Tyrrrz** [comment]
Do you know if it stopped working today or was it after the last update? Can you check if it works on v4.7.3 instead of v4.7.4?

**Comment by hung1xpro** [comment]
sorry cause i busy, i check ver 4.7.3 and still return 0 bro ... 
like that one: https://www.youtube.com/channel/UC0WP5P-ufpRfjbNrmOWwLBQ

**Comment by Tyrrrz** [comment]
I see, seems YouTube broke something :(

**Comment by hung1xpro** [comment]
so what  now bro ... we can't get that anymore ? :'(

**Comment by Tyrrrz** [comment]
There might be a workaround, but I don't have time to look at it now :(

**Comment by hung1xpro** [comment]
> There might be a workaround, but I don't have time to look at it now :(

oke bro, i can wait, just finish you work than check it late, btw thanks you for help :v

**Comment by hung1xpro** [comment]
the thing is playlistId still work with list_ajax?..., then i think cause you code generate playlistid have some problem, that will help you if i right

**Comment by Tyrrrz** [comment]
Looks like this was broken after #228 was fixed...

**Comment by hung1xpro** [comment]
> Looks like this was broken after #228 was fixed...

Hmm now i can get all channel, but some don't like https://www.youtube.com/channel/UClyA28-01x4z60eWQ2kiNbA

I can get file json but u libary can't get, i think the code u use for get playlist have something wrong.

**Comment by Tyrrrz** [comment]
It returns 80 videos for me, same as https://www.youtube.com/playlist?list=UUlyA28-01x4z60eWQ2kiNbA

**Comment by hung1xpro** [comment]
But this 
` querry = YoutubeClient.ParseChannelId(querry);
                var channel = await _youtubeClient.GetChannelAsync(querry);
                var videos = await _youtubeClient.GetChannelUploadsAsync(querry);
                IReadOnlyList<YoutubeExplode.Models.Video> videoxx = videos;`
Still return 0 with videoxx.Count();

**Comment by Tyrrrz** [comment]
Have you updated to latest version?

**Comment by hung1xpro** [comment]
oh i forgot to check that update, let me try then i will ask you soon bro, thanks you <3

**Comment by hung1xpro** [comment]
It work now, thanks you bro <3, have a good day. :v

**Comment by Tyrrrz** [comment]
I'm glad. You too.
