### ISSUE TITLE
Re-implement GetUserUploadsAsync as GetChannelUploadsAsync using UU playlist

### ISSUE THREAD

**Issue by Tyrrrz** [Tyrrrz/YoutubeExplode#26]
As mentioned in #25.
This will also require static methods to parse/validate channel IDs, similar to ones we already have for video IDs and playlist IDs.

**Comment by Tyrrrz** [comment]
@SlowLogicBoy
The old method used user name instead of channel ID. Using channel ID is more flexible (also because we can syntactically validate it) but do you think there are any downsides to dropping the old method?

**Comment by SlowLogicBoy** [comment]
Only downside would be a breaking change for those who use "that" method, and we can not (at least I don't know how) to get channelId from userId, so it's up to you to leave it or remove it.

**Comment by Tyrrrz** [comment]
When it comes to Youtube, you can always find a channel id but not always find a username. If you go to any video made by a user then the link to the author always leads to the channel, so getting an id should be trivial.

**Comment by SlowLogicBoy** [comment]
I agree

**Comment by Tyrrrz** [comment]
Now live
