### ISSUE TITLE
ParseDateTimeOffset Get exception when retriving playlist

### ISSUE THREAD

**Issue by AlenToma** [Tyrrrz/YoutubeExplode#262]
The parsing of uploaded date gets an exception when trying to parse `"30/06/2008"`. the format you are giving is wrong which is `"M/dd/yy"` since the format gets changed, you need to try and find the correct format.

This is what i did, it may not be good but it works for now and its able to handle changes.

```
     private static List<string> DateFormats = new List<string>() { "M/d/yy", "dd/MM/yyyy", "yyyy/MM/dd", "MM/d/yyyy" };
        public static DateTimeOffset TryParseDateTimeOffset(this string s)
        {
            foreach (var format in DateFormats)
            {
                if (DateTimeOffset.TryParseExact(s, format, DateTimeFormatInfo.InvariantInfo, DateTimeStyles.AssumeUniversal, out var date))
                    return date;

            }
            return DateTime.Now;
        }
```

**Comment by AlenToma** [comment]
Sorry made an erro its "30/06/2008" and not "30/15/2008" :)

**Comment by Tyrrrz** [comment]
Can you give me the playlist ID/URL?

**Comment by Tyrrrz** [comment]
I have tested it on a playlist that contained a video from 2005 and it works fine

**Comment by AlenToma** [comment]
Ok the playlist id you could test with is `PLC0w3lEHx2SF3NsbnqnLbWBWyF_3g0cjZ` The added json value you should get is `05/08/2010` and that will fail the parsing in `GetPlaylistAsync`

**Comment by Tyrrrz** [comment]
Ha, weird, that seems to work too. Maybe you're being routed to another version of the API.
Can you copy/paste the raw json it gets in `GetPlaylistJsonAsync`?

**Comment by AlenToma** [comment]
Well i have already repleaced it with my own version above, but this line is what cases the problem 

`var videoUploadDate = videoJson.SelectToken("added").Value<string>().ParseDateTimeOffset("M/d/yy");`

`ParseDateTimeOffset` will get a format exception becouse its not a try parse method so if it fail it will throw an exception.

**Comment by Tyrrrz** [comment]
Most likely fixed by recent update (although I've never managed to reproduce it). Can you check?

**Comment by AlenToma** [comment]
Sorry, Im using my own version now. 
But if you can't reproduce and no one else reported it. 

Then i think you can close this for now.

**Comment by Tyrrrz** [comment]
Okay :)
