### ISSUE TITLE
Issue with the videos sound 

### ISSUE THREAD

**Issue by Hamza-Almass** [Tyrrrz/YoutubeExplode#265]
Thank you very much for your work 
but i have got the issue when downloaded the video i have get it without the sound 
please if you can check it and i hope fix it

**Comment by SlowLogicBoy** [comment]
[#150](https://github.com/Tyrrrz/YoutubeExplode/issues/150#issuecomment-424203407) - Your answer

**Comment by Tyrrrz** [comment]
Also, read the readme
