### ISSUE TITLE
Value cannot be null. Parameter name: value

### ISSUE THREAD

**Issue by rekiem233** [Tyrrrz/YoutubeExplode#266]
Value cannot be null.
Parameter name: value 

error today

**Comment by Nox152** [comment]
same error
worked just fine until now

**Comment by wesbyte** [comment]
Same here!

**Comment by tmalcolm-0607** [comment]
This line is throwing the error:
sts = playerConfigJson.SelectToken("sts").Value<string>();

the config json no longer contains "sts",and it fails

**Comment by AlenToma** [comment]
They have made changes to thair Json output structure.

From `sts` to `args` and then `cvr `

the `assets.js` is also changed to `assets` then `js`

Made those changes and everythings working now :)

**Comment by zjjohncq** [comment]
it works for me when change the sts 
sts = playerConfigJson.SelectToken("args.cver").Value();

**Comment by Hamza-Almass** [comment]
same error

**Comment by Tyrrrz** [comment]
Will look into it tomorrow

**Comment by xamarin-enthusiast** [comment]
Is this bug the cause of [this problem](https://github.com/Tyrrrz/YoutubeDownloader/issues/41)?

**Comment by HamzaAnis** [comment]
> Is this bug the cause of [this problem](https://github.com/Tyrrrz/YoutubeDownloader/issues/41)?

Yes.

**Comment by Tyrrrz** [comment]
Fix should be on nuget soon
