### ISSUE TITLE
Results in nothing (not even error) client.GetVideoMediaStreamInfosAsync

### ISSUE THREAD

**Issue by JustMeDaFaq** [Tyrrrz/YoutubeExplode#269]
Hi, 
using following 2 lines results in nothing. The function doesnt get executed after "GetVideoMediaStreamInfosAsync" anymore and doesnt throw an error.
Installed the latest package via nuget.

var client = new YoutubeClient();
var streamInfoSet = await client.GetVideoMediaStreamInfosAsync("bnsUkE8i0tU");

**Comment by Tyrrrz** [comment]
Closed as duplicate of #266
