### ISSUE TITLE
Get Video Metadata from GetPlaylistInfo

### ISSUE THREAD

**Issue by SlowLogicBoy** [Tyrrrz/YoutubeExplode#27]
When I use GetPlaylistInfo I get only videoId list, but in response there are also video metadata, that could be returned as well.
Because right now I need to use GetPlaylistInfo and run GetVideoInfo for every video, when I could get Video Metadata with GetPlaylistInfo, without streams, that would save me so many unnecessary requests.

**Comment by Tyrrrz** [comment]
Also applies to `GetUserUploadsAsync` and `SearchAsync`

**Comment by Tyrrrz** [comment]
`GetPlaylistInfoAsync` now returns videos as composite objects with some metadata to them. I didn't add stuff like `timecreated` and `comments` because those aren't available in the full `VideoInfo` so it would be weird to put it there.

**Comment by Tyrrrz** [comment]
Now live
