### ISSUE TITLE
await new YoutubeClient().GetChannelAsync() executes for 30 seconds

### ISSUE THREAD

**Issue by XFox111** [Tyrrrz/YoutubeExplode#271]
Hi! After last update I noticed that `YoutubeClient.GetChannelAsync()` executes in 30 seconds on average! Since YouTube doesn't provide channel icons for video items I need this feature. I use it like this `new BitmapImage((await new YoutubeClient().GetChannelAsync(item.Snippet.ChannelId)).LogoUrl.ToUri())`

Thanks in advance)

**Comment by Tyrrrz** [comment]
I'm not able to reproduce this, I'm getting it loaded in 1 second. Can you give me the channel ID?

**Comment by XFox111** [comment]
Here it is.
[Elapsed request time]: [Video ID]

```
00:00:42.9989921: nFnIz0Lzm5s
00:00:43.0358172: e7c_ZEwr59E
00:00:42.9948305: 4UaYMPfOMGI
00:00:43.1685793: JQd1FlWdvVU
00:00:43.2051456: ICLsMfb-WDs
00:00:42.7994429: BKQlqjBDF8Q
00:00:42.9489855: KdZ4HF1SrFs
00:00:43.2444992: QyEz2lxs834
00:00:43.1167654: MsbL8lFHrZI
00:00:43.0602169: sx6eoXg-19k
00:00:43.0475431: yMwZQFDmrMQ
00:00:42.8283840: wfg8Mr-Ygcg
00:00:43.2109058: -gGLSxmw3jo
00:00:43.0544612: pYHghnU4DFY
00:00:43.2338415: PVOVNyImeps
00:00:43.0365748: NgfLaOdyXIw
00:00:43.1591146: u5llXjTXcwA
00:00:42.8414781: TVhc7hvUvnU
00:00:43.1380103: zA0H2HCZthI
00:00:43.2255174: fJYpKsGroio
00:00:43.2165036: p6yi7gq8Jno
00:00:42.8723436: szmLr2nExIQ
00:00:43.2969912: NRNG0ZpFAq8
00:00:43.1716176: uMFOSvXz80I
00:00:43.3161679: bERpabyZ7Rk
```

**Comment by Tyrrrz** [comment]
Hmm. These don't look like valid channel IDs?

**Comment by XFox111** [comment]
Oops. Accidentally sent Video ID. Here's channels:

```
00:00:43.8923703: UCx2StD8gHd_-nRo5z1qcJ8g
00:00:44.7789686: UCgoJVq3Q10Ri_cW5s4m05VQ
00:00:45.0185829: UC4omkhNHsYLagT1o6hnmKQw
00:00:44.8420404: UCzxRv9BtqrM946JmaMLtv_w
00:00:45.2506175: UC6cqazSR6CnVMClY0bJI0Lg
00:00:45.6737712: UCwRCXoecsYoN7Gr0zB8oxww
00:00:45.6710297: UCVbz7l0COUdLupcY4YtYH0w
00:00:45.4539239: UC0e3QhIYukixgh5VVpKHH9Q
00:00:45.5207455: UCK7OXr0m5mnM1z9p7n_Bwfw
00:00:45.8661028: UCvUO8JDs1eTW7kM55FQY_lw
00:00:46.2064969: UC-b89a0Fw6pNoP-g-_qLeiw
00:00:46.2885833: UC-b89a0Fw6pNoP-g-_qLeiw
00:00:46.8322268: UCf31Gf5nCU8J6eUlr7QSU0w
00:00:47.0608782: UCq7JZ8ATgQWeu6sDM1czjhg
00:00:47.1400272: UCbKWv2x9t6u8yZoB3KcPtnw
00:00:48.9182845: UC-b89a0Fw6pNoP-g-_qLeiw
00:00:49.1958408: UC-b89a0Fw6pNoP-g-_qLeiw
00:00:49.3685027: UCf31Gf5nCU8J6eUlr7QSU0w
00:00:49.1932793: UCq7JZ8ATgQWeu6sDM1czjhg
00:00:49.3217535: UCVU6tIQ0oeue08KmRJdMIAA
00:00:49.0619873: UC-b89a0Fw6pNoP-g-_qLeiw
00:00:48.9956967: UCBGbTTcgn8AVEsEWdT3tI3Q
00:00:49.2787866: UCq7JZ8ATgQWeu6sDM1czjhg
00:00:49.4061702: UCq7JZ8ATgQWeu6sDM1czjhg
00:00:49.0401483: UCq7JZ8ATgQWeu6sDM1czjhg
```

**Comment by Tyrrrz** [comment]
Tried some of the channels you listed, it seems fine for me. Could it be a local issue? Does the page load quickly if you open it in browser? E.g.: https://www.youtube.com/channel/UCx2StD8gHd_-nRo5z1qcJ8g

![image](https://user-images.githubusercontent.com/1935960/61122951-c603a000-a4ab-11e9-991f-1637d42c9ff8.png)

**Comment by Tyrrrz** [comment]
Also, which update do you mean by last update? There were no changes in regards to channels in the last update.

**Comment by XFox111** [comment]
Yes. Through a browser it works fine. But it's not a local issue. My users also experience this problem.
4.7.6

P.S. Hmm. It seems to work slow when I'm trying to get 25 items at one. And it's strange because it worked earlier

**Comment by Tyrrrz** [comment]
Maybe YouTube throttles you when you open up 25 simultaneous connections?

**Comment by XFox111** [comment]
Maybe it so. Ok. Then I'll use additional YouTube API request to get a thumbnail

**Comment by Tyrrrz** [comment]
Why not make those 25 requests sequentional instead? :) If it takes ~1 sec per request, I don't think you would reap much benefit from parallelizing it.

**Comment by XFox111** [comment]
Yeah. Maybe you are right. I'll think about it. Thanks

**Comment by Tyrrrz** [comment]
You're welcome
