### ISSUE TITLE
Muxed.WithHighestVideoQuality(); Always download a low quality video

### ISSUE THREAD

**Issue by ImSteph** [Tyrrrz/YoutubeExplode#272]
Code used:

private async void Btn_Download_Click (object sender, RoutedEventArgs e)
{
            var url = tb_URL.Text;
            var id = YoutubeClient.ParseVideoId(url);
            var client = new YoutubeClient();
            var video = await client.GetVideoAsync(id);
            var streamInfoSet = await client.GetVideoMediaStreamInfosAsync(id);
            var streamInfo = streamInfoSet.Muxed.WithHighestVideoQuality();
            var ext = streamInfo.Container.GetFileExtension();
            await client.DownloadMediaStreamAsync(streamInfo, $"downloaded_video.{ext}");
}

I always get a video with low quality, no matter what link I use

**Comment by Tyrrrz** [comment]
What quality did you expect?

**Comment by ImSteph** [comment]
With Highest Video Quality I was expecting the maximum video quality available on youtube, for example if  a video can go up to 1080p, you download a 1080p video

**Comment by Tyrrrz** [comment]
Unfortunately, YouTube doesn't provide high quality muxed streams, they are capped at 720p30 and sometimes even lower than that, depending on a video.
You can read about it in readme: https://github.com/Tyrrrz/YoutubeExplode#usage

**Comment by ImSteph** [comment]
Ok thank you!

**Comment by Tyrrrz** [comment]
You're welcome!
