### ISSUE TITLE
429 Error

### ISSUE THREAD

**Issue by ComputerMaster1st** [Tyrrrz/YoutubeExplode#273]
Hi There,

I've started receiving 429 errors. The only exception message I'm seeing is `Response status code does not indicate success: 429 (unknown).` This is occurring for YT ID `-retejC9qeU` as far as I know.

I'm unable to provide a stacktrace sadly.

**Comment by Hanzalah-Adalan** [comment]
`-retejC9qeU` works just fine in my case here in Malaysia :)

**Comment by Tyrrrz** [comment]
429 stands for "too many requests", could it be that you were making too many requests?

**Comment by ComputerMaster1st** [comment]
Hi There,

It was only requested twice within the space of a few minutes as far as I know. I've got a discord bot which uses this library and logs command usage & other things. The server location is in Netherlands. Might have been a temporary network glitch or something as it's all normal now.

This issue can be closed. :)

**Comment by Tyrrrz** [comment]
Alright :)

**Comment by haichay88** [comment]
it seem issue from youtube limit rate, i have same issue 
"message":"Response status code does not indicate success: 429 (unknown)."
although one request only
