### ISSUE TITLE
Closed Captions into Sentences/Paragraphs?

### ISSUE THREAD

**Issue by GlennIM** [Tyrrrz/YoutubeExplode#275]
Is there a way or even using a different library that is out there to take all the closed captions from a video and make intelligent sentences and paragraphs from them to use as the basis for an article?

**Comment by Tyrrrz** [comment]
You can extract closed captions as shown here https://github.com/Tyrrrz/YoutubeExplode#extract-closed-captions.

When it comes to intelligent senteces, well it comes down to what you consider intelligent sentences. You may process the captions in any way you want though.

**Comment by GlennIM** [comment]
Thanks... Also, using your library, is there a way to get images from youtube videos?

**Comment by Tyrrrz** [comment]
Which images do you mean? Thumbnails?

**Comment by GlennIM** [comment]
Yes,,, Thumbnails

**Comment by Tyrrrz** [comment]
Yes, you can access them on `Video.Thumbnails`
