### ISSUE TITLE
IProgress<double> is sometimes incorrect

### ISSUE THREAD

**Issue by BlauFx** [Tyrrrz/YoutubeExplode#276]
It happens **sometimes** when I try do download a playlist (works especially when one video is large)

Here's an example:

```
private static IProgress<double> prog = new Progress<double>(HandleProgress);

await converter.DownloadAndProcessMediaStreamsAsync(mediaStreamInfos, "path", "mp4", prog);

private static void HandleProgress(double progress) 
{
	Console.WriteLine(progress.ToString()
}
```

The result:
https://gist.github.com/BlauFx/1fbefc1bfc5d5faeac2ceb7a31a2f941#file-result-L1622

As you can see at line 1622 or at 3332
the number 1 is twice there

**Comment by Tyrrrz** [comment]
Hi,
First of all, this is presumably an issue related to https://github.com/Tyrrrz/YoutubeExplode.Converter.
Second, that's true, there could be duplicate progress values reported. `IProgress<T>` doesn't guarantee that there will be no duplicates.

**Comment by BlauFx** [comment]
alright then I'm going to open an issue at https://github.com/Tyrrrz/YoutubeExplode.Converter.
