### ISSUE TITLE
Value can not be null

### ISSUE THREAD

**Issue by VitalieStirbu** [Tyrrrz/YoutubeExplode#278]
I am getting an error "Value can not be null; Parameter name: Value" when I run
` var a = await client.GetVideoMediaStreamInfosAsync("SQQQ9kmbp_w");`

It was working before, but 2-3 weeks ago it started to throw this error.

**Comment by Tyrrrz** [comment]
Can't seem to reproduce this one. Are you running the latest version?

**Comment by VitalieStirbu** [comment]
@Tyrrrz  no, I am running 4.7.3

**Comment by VitalieStirbu** [comment]
It's fixed in 4.7.6

**Comment by Tyrrrz** [comment]
Ok good. Make sure you're always running the latest version.
