### ISSUE TITLE
Cannot download some videos

### ISSUE THREAD

**Issue by Hamza-Almass** [Tyrrrz/YoutubeExplode#279]
when i try to download some videos i got the access denied? is this from library?
thank you

**Comment by Tyrrrz** [comment]
Maybe. Do you have example video IDs?

**Comment by Hamza-Almass** [comment]
The following is my code which i used in my app:

`var id = YoutubeClient.ParseVideoId(url);
            var youtubeClient = new YoutubeClient();
            var videoInfo = await youtubeClient.GetVideoAsync(id);
            if (videoInfo == null)
            {
                return Ok(new {  Error = "Video info is not available, try again later."});
            }

            var VideoLink = await youtubeClient.GetVideoMediaStreamInfosAsync(id);
            return Ok(VideoLink);`

**Comment by Tyrrrz** [comment]
Can you share the video ID?

**Comment by Hamza-Almass** [comment]
this is ids which I got access denied when I try to download it

rYEDA3JcQqw
h_D3VFfhvs4
cMydOQEqhqE

**Comment by Tyrrrz** [comment]
I seem to be able to download the videos without problem. What error are you getting?

**Comment by Hamza-Almass** [comment]
i got the following message after download some videos 
Access to r4---sn-ab5l6ndr.googlevideo.com was denied

**Comment by Tyrrrz** [comment]
Ah, you're probably experiencing the same problem as in #149, #245, #250

**Comment by Hamza-Almass** [comment]
I will check with those problems 

thank you

**Comment by Tyrrrz** [comment]
You're welcome

**Comment by Hamza-Almass** [comment]
hi please I try all other comments which are related with my issue but also I can not to solve this problem 
any advice from you give me for solving it or should i leave it as this state?

thank you

**Comment by Tyrrrz** [comment]
The problem is, the URLs are valid for specific IP, and when your web app requests the `MediaStreamInfoSet` object, it's tied to the IP of the web server. In order to expose the stream to your users, you need to return the actual stream as part of the response, i.e. get it using `GetMediaStreamAsync` and return as `FileStream`.

**Comment by Tyrrrz** [comment]
This should help: https://github.com/SlowLogicBoy/YoutubeExplode.AspNetCore.Mvc/blob/master/Controllers/YoutubeController.cs

**Comment by Hamza-Almass** [comment]
thank you
 i am do it like your advice in localhost it's work and i got the file response
 but in my server i got the code 500 internal server error is this issue from the server ?

**Comment by Tyrrrz** [comment]
Yes, 500 means something broke on the server

**Comment by Hamza-Almass** [comment]
thank you very much

**Comment by Tyrrrz** [comment]
No problem
