### ISSUE TITLE
Play Video and Control Playback? 

### ISSUE THREAD

**Issue by GlennIM** [Tyrrrz/YoutubeExplode#280]

**Comment by GlennIM** [comment]
Does this library have methods to Play a YouTube Video and control it's playback (start, stop, rewind) ?

**Comment by Tyrrrz** [comment]
This library returns a raw `Stream` that you can process as you want.

**Comment by GlennIM** [comment]
Actually, all I need is the audio of the video. Is it possible to get just the raw audio stream and put it into a .NET control to control the playback of the audio?

**Comment by Tyrrrz** [comment]
Yeah you can get the `MediaStreamInfoSet` and then use `MediaStreamInfoSet.Audio`

**Comment by GlennIM** [comment]
Thanks... Do you know of a standard Visual Studio plugin that I can use to use MediaStreamInfoSet.Audio with to play, stop, pause, rewind the audio with?

**Comment by GlennIM** [comment]
Also, I tried the following code and an exception gets thrown one the first line. Please advise.

var mediaStreamInfoSet = await client.GetVideoMediaStreamInfosAsync("p2DX0blaEyY");
var streamInfo = mediaStreamInfoSet.Audio;

Exception: "Video [p2DX0blaEyY] is unavailable."

**Comment by Tyrrrz** [comment]
#281

**Comment by Tyrrrz** [comment]
One of the controls I used in the past in WPF was https://github.com/unosquare/ffmediaelement, it's better than regular WPF MediaElement, but requires FFMpeg to run.

**Comment by Tyrrrz** [comment]
But if you can download the stream before playing (as opposed to playing and downloading simultaneously), you can use even the standard MediaElement and just play from file.
