### ISSUE TITLE
Seems like YouTube's changing something in the backend again...

### ISSUE THREAD

**Issue by Montegro** [Tyrrrz/YoutubeExplode#281]
![image](https://user-images.githubusercontent.com/1057035/62084561-9d0f3900-b227-11e9-8103-460af8b52540.png)
Seems like when a search is performed now and contains anything in the URL past the VideoID, the parse method messes up somehow? Because when I removed the "&t=0s" afterwards, I got it to load the video just fine.
![image](https://user-images.githubusercontent.com/1057035/62084796-20308f00-b228-11e9-86d3-06dca5806ac6.png)

**Comment by Montegro** [comment]
I just tried it with another video, that one rejected me earlier too with an additional "&t=28" after, but this time it went through? So I tried the original video again and it still fed me back the same message.
Curious thing is I have plenty of Try Catches to prevent it within my own software, so this crash might be happening within YouTube Explode?

**Comment by Giggitybyte** [comment]
Having a very similar issue.

**Comment by BlauFx** [comment]
same here

**Comment by zjjohncq** [comment]
They have remove video_id in the first level return result. So if we just remove the check of if video_id existency,it will working. This can be a temporary solution.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by thanhnv128** [comment]
same issue

**Comment by rifrif14** [comment]
same issue

**Comment by Henry84** [comment]
I have the same problem.
It come from YoutubeClient.Video -> GetVideoInfoDicAsync() ->
// If video ID is not set - throw if (result.GetValueOrDefault("video_id").IsNullOrWhiteSpace()) throw new VideoUnavailableException(videoId, $"Video [{videoId}] is unavailable.");

Seems like video_id is not in get_video_info response.
I've commented it and still working.

**Comment by Tyrrrz** [comment]
Good morning to you too

**Comment by andrew-mi** [comment]
@Tyrrrz Good Morning .... and thanks again for the library & the quick fix

**Comment by ShimmyMySherbet** [comment]
Has this been fixed yet? If it has, the NuGet package hasn't been updated yet.

**Comment by andrew-mi** [comment]
@ShimmyMySherbet For now download from here: https://ci.appveyor.com/project/Tyrrrz/youtubeexplode/build/artifacts
I am not sure how long/when a nuget.org release is

**Comment by Tyrrrz** [comment]
It was uploaded, it takes some time to get indexed
https://ci.appveyor.com/project/Tyrrrz/youtubeexplode/builds/26339237

**Comment by ShimmyMySherbet** [comment]
Oh ok, thanks.

**Comment by almudy** [comment]
Thanks mate. Works like a charme now!

**Comment by Tyrrrz** [comment]
😄

**Comment by Montegro** [comment]
I'm still having a little bit of an issue... it works fine when I launch it from Visual Studio and build my project, but when I use the executable outside of VS it crashes my program when simply collecting info. Do I need to rework how I fetch info? 
![image](https://user-images.githubusercontent.com/1057035/62148139-20cc3280-b2c7-11e9-8a8c-de21d1046e81.png)

**Comment by Montegro** [comment]
Nevermind I was in a slightly wrong directory

**Comment by ThomasMasuth** [comment]
This happens with video_id = "A_MjCqQoLLA". In YoutubeExplode.Internal.HttpClientEx in Line 61 
public static async Task<Stream> GetStreamAsync(this HttpClient client, string requestUri,
            long? from = null, long? to = null, bool ensureSuccess = true)

Http Response Code is forbidden 403
