### ISSUE TITLE
Video is unavailable

### ISSUE THREAD

**Issue by Marly212** [Tyrrrz/YoutubeExplode#284]
Since Yesterday every Video I try to download gets me the Error Video [here is the ID] is unavailable.
I didn't change anything in my Programm. 
Did Youtube change anything?

![grafik](https://user-images.githubusercontent.com/42452096/62291473-50647180-b464-11e9-994f-40a6d588800a.png)

**Comment by romidi** [comment]
> Since Yesterday every Video I try to download gets me the Error Video [here is the ID] is unavailable.
> I didn't change anything in my Programm.
> Did Youtube change anything?
> 
> ![grafik](https://user-images.githubusercontent.com/42452096/62291473-50647180-b464-11e9-994f-40a6d588800a.png)

take latest version 4.7.7 this issue is fixed there

**Comment by Marly212** [comment]
> 
> 
> > Since Yesterday every Video I try to download gets me the Error Video [here is the ID] is unavailable.
> > I didn't change anything in my Programm.
> > Did Youtube change anything?
> > ![grafik](https://user-images.githubusercontent.com/42452096/62291473-50647180-b464-11e9-994f-40a6d588800a.png)
> 
> take latest version 4.7.7 this issue is fixed there

Ah yes Thanks a lot
