### ISSUE TITLE
403 on some videos

### ISSUE THREAD

**Issue by ac-lap** [Tyrrrz/YoutubeExplode#289]
On certain videos I am getting 403 when trying to download from the url. Even the 'DemoWpf' app fails to download these videos with same 403 error.

These videos are not age-restricted.

Sample videos-
https://www.youtube.com/watch?v=5pEAuMSSq3M
https://www.youtube.com/watch?v=-wc1tiPGKqM

**Comment by Kajirinn** [comment]
Same, 90% of my 200 ish [playlist ](https://www.youtube.com/playlist?list=PL1Gv-OC8tneodd99wZvmJFm4qs6ABOHIQ)is giving me a 403 (without a proper error).

**Comment by Tyrrrz** [comment]
From your description it looks like YTE fails to decipher a signature. Does it happen all the time?

I can't reproduce it so it may be that they have some region-specific ciphering logic.

**Comment by Tyrrrz** [comment]
Nevermind, I can actually reproduce it.

**Comment by roberth11** [comment]
algunas solucion

**Comment by Tyrrrz** [comment]
Looks like YouTube changed something again, will look into it, no estimate yet.

**Comment by Tyrrrz** [comment]
Ha, fixed it

**Comment by lentro759** [comment]
@Tyrrrz 
Hello. I've received this exception too. Yesterday, after few video and audio downloads, I started to receive the same error, after nearly a hour, this problem had gone and all were good. Today is the same situation, think this is youtube's bug or maybe some download restriction, maybe we need to use something like bypass to get rid of this exception.
