### ISSUE TITLE
Anyone else running into an issue fetching a Channel's videos?

### ISSUE THREAD

**Issue by Montegro** [Tyrrrz/YoutubeExplode#293]
Whenever I try to import a channel ID to fetch its uploads as a playlist, my program just seems to sit there without fetching anything. Fetching a playlist still seems to work.

The way I've got it set up I haven't changed in a while, but it parses the ChannelID from the channel link, it then substitutes the UC at the beginning of the ID with UU, and then attempts to fetch all the videos.

It doesn't throw back invalid playlist identifier or anything like that, it just seems to sit there.

**Comment by Tyrrrz** [comment]
>The way I've got it set up I haven't changed in a while, but it parses the ChannelID from the channel link, it then substitutes the UC at the beginning of the ID with UU, and then attempts to fetch all the videos.

Do you do this manually or use `client.GetChannelUploadsAsync()`?

**Comment by Montegro** [comment]
I had been doing it manually, but to test out the other way after making this post I ran through GetChannelUploadAsync, fetched the video list, and tried to have it spit back the first result's name and then break out of the foreach loop, but no such luck, same kind of just sitting. I'll be trying again shortly.

**Comment by Montegro** [comment]
![image](https://user-images.githubusercontent.com/1057035/64020412-906c5200-caff-11e9-8b2a-d5c9d7784728.png)
![image](https://user-images.githubusercontent.com/1057035/64020427-9bbf7d80-caff-11e9-8466-0f82628cf6bb.png)
Nope, I'm still feeding back nothing, and since my code never leaves the foreach loop and gets to the DebugInfoUpdate("Here."); line, I think it's simply getting stuck trying to fetch the channel upload list.

**Comment by Tyrrrz** [comment]
It seems that the tests are succeeding.
Can you do a minimal repro? Create a console application and replace the main method with this:

```c#
public static Task Main()
{
   var channelId = YoutubeClient.ParseChannelId("<CHANNEL_ID>");
   var videos = await new YoutubeClient().GetChannelUploadsAsync(channelId);
   
   foreach (var video in videos)
      Console.WriteLine(video);
}
```

**Comment by Montegro** [comment]
Took a little while, but it worked.

**Comment by Montegro** [comment]
Okay, it does absolutely work, I've just been impatient with it, sorry to bother you, thanks for helping me figure this out.

**Comment by Tyrrrz** [comment]
It could be slow if the channel has a lot of videos. You can limit the output to a specific number of pages using one of the overloads.

Np, glad it worked. :)

**Comment by Montegro** [comment]
> 
> 
> It could be slow if the channel has a lot of videos. You can limit the output to a specific number of pages using one of the overloads.
> 
> Np, glad it worked. :)

Ooo, which overload should I use?

**Comment by Tyrrrz** [comment]
https://github.com/Tyrrrz/YoutubeExplode/blob/986be8ab7774387197f0b92eb655cc4cffeb138c/YoutubeExplode/IYoutubeClient.cs#L83-L92

**Comment by Montegro** [comment]
Thank you very much.

**Comment by Montegro** [comment]
Just tried it out, made it work instantly, thank you again.

**Comment by Tyrrrz** [comment]
You're welcome
