### ISSUE TITLE
Progress Tracking

### ISSUE THREAD

**Issue by insanityrains** [Tyrrrz/YoutubeExplode#295]
How can I track the download via a progress bar?

**Comment by Tyrrrz** [comment]
Looks like you've found the answer?

**Comment by insanityrains** [comment]
Yuuuup. I’m just an idiot is all.

Sent from my iPhone

On Sep 11, 2019, at 10:47 AM, Alexey Golub <notifications@github.com<mailto:notifications@github.com>> wrote:


Looks like you've found the answer?
