### ISSUE TITLE
GetVideoMediaStreamInfosAsync() seems to be broken

### ISSUE THREAD

**Issue by jungjanos** [Tyrrrz/YoutubeExplode#296]
Hi Alexey!

I have tried YoutubeExplode 4.7.9 both on Windows desktop as well as on Xamarin. The `GetVideoAsync` call seems to be working (though this one I only tried on Windows) but `GetVideoMediaStreamInfosAsync() ` seems to be broken. It returns a `MediaStreamInfoSet ` object with empty- [0]  - stream arrays for all three types of streams. The "ValidUntil" property seems to be valid though.

BR
Janos

**Comment by AnonymusRaccoon** [comment]
Agreed, it stopped working in the last 20 minutes.

**Comment by omarroth** [comment]
Breaking change by YouTube. See also fent/node-ytdl-core#486, TeamNewPipe/NewPipe#2615.

Looking at [this](https://github.com/Tyrrrz/YoutubeExplode/blob/8ac957d35030c12148f75c5e8bfb85f4d760349d/YoutubeExplode/YoutubeClient.Video.cs#L187) line, YouTube has moved `adaptive_fmts` and `url_encoded_fmt_stream_map` into `playerResponseJson` as `streamingData.adaptiveFormats` and `streamingData.formats` respectively.

**Comment by Tyrrrz** [comment]
Will look into it as soon as I can

**Comment by Y0GAAAA** [comment]
Same issue here ! thank you for being that responsive :)

**Comment by Tyrrrz** [comment]
Is this still not working? Can someone give me a video ID?

**Comment by omarroth** [comment]
YouTube has reverted the above change, see TeamNewPipe/NewPipe#2623. I would still recommend supporting `streamingData.formats` (maybe as a fallback), but the current version should still work :).

**Comment by Tyrrrz** [comment]
@omarroth 
It's not the first time they reverted it, YoutubeExplode was using streamingData.formats for almost a year until they went back to url-encoded format.

Closing for now as the issue was resolved on its own.
