### ISSUE TITLE
Search options? (upload date, sort by)?

### ISSUE THREAD

**Issue by HubKing** [Tyrrrz/YoutubeExplode#297]
Both the mobile version and the web version have search options. But in this library, I only see "query".  How to apply date and order? There are other conditions I can live without, but date and order are kind of crucial for search.

![image](https://user-images.githubusercontent.com/10900489/64962189-f6afed80-d8d1-11e9-8c6d-45b996285e84.png)

**Comment by Tyrrrz** [comment]
It's not using the same search functionality so it's a bit limited

**Comment by Tyrrrz** [comment]
Related to #226

**Comment by badijm** [comment]
hi, I can work on that

**Comment by Tyrrrz** [comment]
@badijm 

> upd: It could be some sort of expandable panel (which only show up when need) for additional search parameters.

What are you referring to? This issue concerns only the request/parsing part.

**Comment by badijm** [comment]
@Tyrrrz The plant - is to add `<DatePicker/>` conroller to UI and then use this selected date when calling YoutubeAPI. If I get it correctly.

**Comment by Tyrrrz** [comment]
This is a library, are you referring to [YoutubeDownloader](https://github.com/Tyrrrz/YoutubeDownloader)?

**Comment by Tyrrrz** [comment]
Hi.
Unfortunately I have to descope this issue as the project has moved into maintenance mode, which means that new features are unlikely to get implemented.
