### ISSUE TITLE
Can't extract closed captions

### ISSUE THREAD

**Issue by bitov27** [Tyrrrz/YoutubeExplode#298]
Hi! I have a problem with Extract closed captions.

If I use code from example:
----------------------------------
var client = new YoutubeClient();
var trackInfos = await client.GetVideoClosedCaptionTrackInfosAsync("_QdPW8JrYzQ");
var trackInfo = trackInfos.First(t => t.Language.Code == "en");
var track = await client.GetClosedCaptionTrackAsync(trackInfo);
var caption = track.GetByTime(TimeSpan.FromSeconds(61));
var text = caption.Text; // "And the game was afoot."
----------------------------------
Then I can't compiller code, because functions GetVideoClosedCaptionTrackInfosAsync , GetClosedCaptionTrackAsync - not found!!!

If  I use code like this:
----------------------------------
 var client = new YoutubeClient();
 var trackInfos = await client.GetVideoInfoAsync("_QdPW8JrYzQ");
------------------
I've got an exception   "An object reference does not indicate an instance of an object" in this line:
var trackInfos = await client.GetVideoInfoAsync("_QdPW8JrYzQ");

Can anybody help me? Thanks!

**Comment by Tyrrrz** [comment]
What version of YoutubExplode are you using...?

**Comment by bitov27** [comment]
> What version of YoutubExplode are you using...?

I use Version  1.1.0, I've installed it using nuget packages

**Comment by Tyrrrz** [comment]
You are using a 2.5 years old version, you need to update to latest.

**Comment by bitov27** [comment]
> You are using a 2.5 years old version, you need to update to latest.

ok, Thank you very much! I've updated to latest version!Everything work fine!!!

**Comment by Tyrrrz** [comment]
Great :)
