### ISSUE TITLE
Error while sending request on some videos

### ISSUE THREAD

**Issue by ahmar20** [Tyrrrz/YoutubeExplode#299]
I am having a strange error on some videos. For example 'Y_LYehunMbE'.

The error says: "Error while sending request" and inner exception says "Remote address could not be found". The error occurs on MediaStreamInfos function. While the above video is able to load through youtube website, YTExplode thinks otherwise. Why would that be an issue?

Video 2: IL5iR1z4Maw
Video 3: xLY_k6-Y6YY

**Comment by Tyrrrz** [comment]
Can't seem to reproduce this issue

**Comment by ahmar20** [comment]
So after your comment I tried to reload those videos several times and it seems I am able to download/play the streams but after several failed attempts. What could be the issue? Maybe geo restrictions?

**Comment by Tyrrrz** [comment]
It's hard to say, I don't know. Never personally had that issue.

**Comment by Tyrrrz** [comment]
I'll close for now, comment if this comes back.
