### ISSUE TITLE
Container does not contain defenation of GetFileExtension()

### ISSUE THREAD

**Issue by azizullah-masology** [Tyrrrz/YoutubeExplode#30]
Hi,

I installed YoutubeExplode in my project and coped Download media stream sample code from the repo. I am having that error with this code
`video.Container.GetFileExtension();

`
And also container does not have any other methods

**Comment by SlowLogicBoy** [comment]
`using YoutubeExplode.Models;`

**Comment by azizullah-masology** [comment]
Thanks for you replay...
now another issue..  This is my sample code: 

`var client = new YoutubeClient();

            // Get video info
            string videoId = "";
            if (!YoutubeClient.TryParseVideoId(videoUrl, out videoId))
                videoId = videoUrl;

            var videoInfo = await client.GetVideoInfoAsync(videoId);`
When it comes to this line `var videoInfo = await client.GetVideoInfoAsync(videoId)` then program breaks and stops and does not move one another step after that.

**Comment by SlowLogicBoy** [comment]
If it breaks there, that means it has thrown an exception and visual studio then shows which exception was thrown.

**Comment by Tyrrrz** [comment]
It doesn't accept urls, but the following
````c#
string videoId = "";
if (!YoutubeClient.TryParseVideoId(videoUrl, out videoId))
    videoId = videoUrl;
````
Tries to extract id from url and if it fails - just return the input string. So it's possible the ID is also invalid.

Like SlowLogicBoy said, we need to know the exact exception.

**Comment by azizullah-masology** [comment]
Actually the reason is that.... It throw no exception. I put that line in try catch also... but no exception.
And another thing... I am using vs2013, is that a problem? because as far as I know this library is written in .net core

**Comment by Tyrrrz** [comment]
It can't break without an exception, unless you have a breakpoint there.
