### ISSUE TITLE
How to choose quality on youtube video

### ISSUE THREAD

**Issue by mhadji05** [Tyrrrz/YoutubeExplode#300]
how can i choose the quality video plays?

![image](https://user-images.githubusercontent.com/22151801/65335420-0fb7e780-dbcd-11e9-89fb-77ed0ef5a02c.png)

**Comment by Tyrrrz** [comment]
From [readme](https://github.com/Tyrrrz/YoutubeExplode)

### Download video

If you want to download a video, you first need to get info on all its streams using `GetVideoMediaStreamInfosAsync`, then choose the stream you want to download, then pass it to `DownloadMediaStreamAsync` method. You can also use `GetMediaStreamAsync` to get the stream itself.

Keep in mind that the streams are split into Muxed (audio+video), Audio (audio only) and Video (video only).

```c#
var client = new YoutubeClient();

// Get metadata for all streams in this video
var streamInfoSet = await client.GetVideoMediaStreamInfosAsync("bnsUkE8i0tU");

// Select one of the streams, e.g. highest quality muxed stream
var streamInfo = streamInfoSet.Muxed.WithHighestVideoQuality();

// ...or highest bitrate audio stream
// var streamInfo = streamInfoSet.Audio.WithHighestBitrate();

// ...or highest quality & highest framerate MP4 video stream
// var streamInfo = streamInfoSet.Video
//    .Where(s => s.Container == Container.Mp4)
//    .OrderByDescending(s => s.VideoQuality)
//    .ThenByDescending(s => s.Framerate)
//    .First();

// Get file extension based on stream's container
var ext = streamInfo.Container.GetFileExtension();

// Download stream to file
await client.DownloadMediaStreamAsync(streamInfo, $"downloaded_video.{ext}");
```

**Comment by mhadji05** [comment]
i dont need to download the video. I need to play stream 360video in game engine but the quality is very bad if i try to select:
var streamInfo = streamInfoSet.Muxed.WithHighestVideoQuality();

i try this:
var streamInfo = streamInfoSet.Video.FirstOrDefault(s => s.VideoQualityLabel == "1080p");
and the quality of my video is pretty good now but there is no sound.
what can i do for this?

**Comment by Tyrrrz** [comment]
You can do
`var videoStreamInfo = streamInfoSet.Video.FirstOrDefault(s => s.VideoQualityLabel == "1080p");`
and
`var audioStreamInfo = streamInfoSet.Audio.WithHighestBitrate();`
and play them at the same time. You will have video + audio.

**Comment by mhadji05** [comment]
i m trying to do that on Unity game engine on video player.
what is the line to play the audioStreamInfo ?
i need to sync video and audio

**Comment by Tyrrrz** [comment]
You would use `var stream = await client.GetMediaStreamAsync(videoStreamInfo); // or audioStreamInfo` to get the `Stream` object

**Comment by mhadji05** [comment]
doesent work because i have only 1 video player.

i choose this in `public static class Extensions:`
```

public static MuxedStreamInfo WithHighestVideoQualitySupported(this IEnumerable<MuxedStreamInfo> streamInfos)
        {

            if(streamInfos == null)
                throw new ArgumentNullException(nameof(streamInfos));
            return streamInfos
                .Where(info => info.Container == Container.Mp4)
                .Select(info => info).OrderByDescending(s => s.VideoQuality == VideoQuality.High1080).FirstOrDefault();

        }
```

But i havent HD why?

**Comment by mhadji05** [comment]
in the code below can somewhere add the audio too?

```
var streamInfo = streamInfoSet.Video
                   .Where(s => s.Container == Container.Mp4)
                   .OrderByDescending(s => s.VideoQuality == VideoQuality.High1440)
                   .ThenByDescending(s => s.Framerate)
                   .FirstOrDefault();
```

**Comment by Tyrrrz** [comment]
Muxed streams go up to 720p, the highest qualities are provided as separate video-only/audio-only streams. Your best bet is playing the two streams simultaneously.

**Comment by mhadji05** [comment]
how can i Sync 2 videos?

**Comment by mhadji05** [comment]
how can i Sync 2 videos? or how can i play something else (no Muxed stream) other stream that can play audio and video together?

**Comment by Tyrrrz** [comment]
I've no idea how to do this in Unity but you'll probably need 2 video players

**Comment by mhadji05** [comment]
Can i play something else (no Muxed stream) other stream that can play audio and video together?

**Comment by Tyrrrz** [comment]
Unfortunately YouTube doesn't provide any alternatives

**Comment by mhadji05** [comment]
How can i take a stream of 144p video? (Image && Audio)

**Comment by Tyrrrz** [comment]
`var streamInfo = streamInfoSet.Video.OrderBy(s => s.VideoQuality).FirstOrDefault();`

or

`var streamInfo = streamInfoSet.Muxed.OrderBy(s => s.VideoQuality).FirstOrDefault();`

**Comment by Tyrrrz** [comment]
No, that's still not possible unfortunately
