### ISSUE TITLE
How to choose video quality

### ISSUE THREAD

**Issue by HdSonu** [Tyrrrz/YoutubeExplode#301]
Thanks for developer. 
from web https when we get info from youtube URL we get different URLS with different quality  like 720P , 360P , 
Please add option to get Selected URL in place of Top Quality and there is one more issue we cant get Top Quality video URL , Max Quality I had get 720P only , not able to get 2k, 4k or 8k that available in Youtube ...

**Comment by Tyrrrz** [comment]
Media streams come in 3 forms -- `Muxed` (video & audio), `Audio` (audio only) and `Video` (video only). Highest qualities are not available in muxed streams so you'll have to download separate streams and multiplex them yourself using tools like [ffmpeg](https://www.ffmpeg.org/).

Muxed streams go up to 720p30.

You can also use [YoutubeExplode.Converter](https://github.com/Tyrrrz/YoutubeExplode.Converter) to take care of multiplexing for you.

If you want to download a video, you first need to get info on all its streams using `GetVideoMediaStreamInfosAsync`, then choose the stream you want to download, then pass it to `DownloadMediaStreamAsync` method. You can also use `GetMediaStreamAsync` to get the stream itself.

Keep in mind that the streams are split into Muxed (audio+video), Audio (audio only) and Video (video only).

```c#
var client = new YoutubeClient();

// Get metadata for all streams in this video
var streamInfoSet = await client.GetVideoMediaStreamInfosAsync("bnsUkE8i0tU");

// Select one of the streams, e.g. highest quality muxed stream
var streamInfo = streamInfoSet.Muxed.WithHighestVideoQuality();

// ...or highest bitrate audio stream
// var streamInfo = streamInfoSet.Audio.WithHighestBitrate();

// ...or highest quality & highest framerate MP4 video stream
// var streamInfo = streamInfoSet.Video
//    .Where(s => s.Container == Container.Mp4)
//    .OrderByDescending(s => s.VideoQuality)
//    .ThenByDescending(s => s.Framerate)
//    .First();

// Get file extension based on stream's container
var ext = streamInfo.Container.GetFileExtension();

// Download stream to file
await client.DownloadMediaStreamAsync(streamInfo, $"downloaded_video.{ext}");
```

**Comment by HdSonu** [comment]
How to download High  Resolution video only and Audio only i will manage mixing , can you guide me ?

**Comment by Tyrrrz** [comment]
It's right there above you:

```
var audioInfo = streamInfoSet.Audio.WithHighestBitrate();
var videoInfo = streamInfoSet.Video
    .Where(s => s.Container == Container.Mp4)
    .OrderByDescending(s => s.VideoQuality)
    .ThenByDescending(s => s.Framerate)
    .First();

var audioFileName = $"audio.{audioInfo.Container.GetFileExtension()}";
var videoFileName = $"audio.{audioInfo.Container.GetFileExtension()}";

await client.DownloadMediaStreamAsync(audioInfo, audioFileName);
await client.DownloadMediaStreamAsync(videoInfo, videoFileName);
```

**Comment by Tyrrrz** [comment]
Cross-related to #300

**Comment by Tyrrrz** [comment]
@OND10 try this:

```csharp
// Selects highest quality below or equal to 720p
var videoStreamInfo = streamManifest
    .GetVideoStreams()
    .Where(s => s.VideoQuality.MaxHeight <= 720)
    .MaxBy(s => s.VideoQuality);
```
