### ISSUE TITLE
Error when GetVideoMediaStreamInfosAsync() on some videos

### ISSUE THREAD

**Issue by PhapHanh** [Tyrrrz/YoutubeExplode#303]
VideoId: **eHei739O3jw**
```
var client = new YoutubeClient();
var streamInfoSet = await client.GetVideoMediaStreamInfosAsync("eHei739O3jw");
```
Debug Error in YoutubeClient.Video.cs at line 441:
`var itag = streamInfoDic["itag"].ParseInt();`

Now, I resolved by add code:
```
if (streamInfoDic.Count > 0)
{
    var itag = streamInfoDic["itag"].ParseInt();
```

**Comment by Tyrrrz** [comment]
This video seems to only have one stream but I can't reproduce this issue.

**Comment by Tyrrrz** [comment]
Is this still reproducible for you?

**Comment by PhapHanh** [comment]
Thank you !!! In new version code, everything's ok.

**Comment by Tyrrrz** [comment]
Great :)
