### ISSUE TITLE
Can't download some videos

### ISSUE THREAD

**Issue by Antikue** [Tyrrrz/YoutubeExplode#307]
Do you have any idea of why some videos are not getting downloaded? I'm using the NuGet package. [4.7.10]

`using (var progress = new InlineProgress())
                  await client.DownloadMediaStreamAsync(streamInfo, YourPath + title + "." + ext, progress);`

Thanks 😄

**Comment by Antikue** [comment]
Fixed it, I read more of your code. Thanks! <3

**Comment by Tyrrrz** [comment]
Glad the issue was solved :)
