### ISSUE TITLE
Demo's broken?

### ISSUE THREAD

**Issue by NoobInTraining** [Tyrrrz/YoutubeExplode#31]
The console demo is broken for me.
What is broken you might ask?

- doesnt have a field called id
- char - does not contain a .Repeat() method (try "".PadRight(100, '-'); instead)
- filename = filename.exept cannot be converted. A string.Join([the linq statement]); is needed

**Comment by SlowLogicBoy** [comment]
Have you restored all your nuget packages?
>char - does not contain a .Repeat() method (try "".PadRight(100, '-'); instead)
>filename = filename.exept cannot be converted. A string.Join([the linq statement]); is needed

Install-Package Tyrrrz.Extensions
using Tyrrrz.Extensions; 

>doesnt have a field called id

Install-Package YoutubeExplode
using YoutubeExplode;
using YoutubeExplode.Models;

**Comment by NoobInTraining** [comment]
> Install-Package Tyrrrz.Extensions
> using Tyrrrz.Extensions;

Should explain the issue.
I was not aware of the need to install `Tyrrrz.Extensions` aswell i thought only `YoutubeExplode`.

Thanks for the quick reply.

**Comment by SlowLogicBoy** [comment]
```
if (!YoutubeClient.TryParseVideoId(input, out string id))
                id = input;
```
for this to work you need C# 7 i think

**Comment by NoobInTraining** [comment]
i just added a field:

`string id;

            if (!YoutubeClient.TryParseVideoId(input, out id))
                id = input;

            return id;`

**Comment by Tyrrrz** [comment]
@NoobInTraining yeah both demos use some extra dependencies, they should be resolved with package restore.
The examples in https://github.com/Tyrrrz/YoutubeExplode/wiki/Usage-examples on the other hand can be freely copy-pasted straight away.
