### ISSUE TITLE
GetVideoMediaStreamInfosAsync() seems to be broken

### ISSUE THREAD

**Issue by TwentyFourMinutes** [Tyrrrz/YoutubeExplode#310]
Basically I have the same issue as described in #296. This happens on me as soon as I try to download multiple audio streams in parallel, is this just not supported or not intended?

**Comment by Tyrrrz** [comment]
What error are you getting?

**Comment by TwentyFourMinutes** [comment]
Well the same as described in #296, there isn't an error, the collections are just straight up empty.

**Comment by Tyrrrz** [comment]
Sorry for late reply, can you provide some example videos as well?

**Comment by TwentyFourMinutes** [comment]
Well it is not actually about the videos itself, it is just when using the YoutubeExplode instance multi-threaded. Is this even supported thought?

**Comment by Tyrrrz** [comment]
It's supported by the library, whether or not YouTube will behave differently is up to them

**Comment by dangtaikhtn** [comment]
@Tyrrrz Hi, I just deployed on Azure cloud but it could not get stream url from copyright video (such as Memories https://www.youtube.com/watch?v=SlPhMPnQ58k). Can you help me to check it? Thank you.

**Comment by SnGmng** [comment]
Same issue. Sometimes it works, sometimes the collections are empty. GetVideoMediaStreamInfosAsync is really unreliable.

**Comment by Montegro** [comment]
I'm having the same issue with videoids:
AQy6DJhVBrc
A-2ATa1gtjI
A21XpvDE2mM
Might this have to do with the prep for the COPPA change maybe? Could have something to do with videos identified as For Kids or something like that? I say that because one of those videos pertains to Pokemon...

**Comment by hsallander** [comment]
We're experiencing problems with this method as well, we get no muxed, no audio, and no video for the following videoIDs:
Bpcnej8y--g
BgfzAv5BI6o

Response: streamInfo is null. streamInfoSet.Muxed.Count = 0 streamInfoSet.Audio.Count = 0 streamInfoSet.Video.Count = 0

Is this related to this issue?

**Comment by bkolo** [comment]
Same issue using videoID   ARMYtj3SXOo
Using latest 4.7.10

**Comment by Tyrrrz** [comment]
I've more or less identified the issue, I'm going to have some time this weekend so I will try to fix it then.

**Comment by nizata** [comment]
same issue with id video: AMzF_nmRq2o
function GetVideoMediaStreamInfosAsync() return empty

**Comment by omansak** [comment]
I found  a possible solution at libvideo. maybe you can use.

if `url_encoded_fmt_stream_map `is null then try get `player_response `that is a json string and has urls but i dont know that urls need decryprt

`Alr26K0F4EQ `works fine this video

(my solution)
![image](https://user-images.githubusercontent.com/14445821/70854962-363ba500-1ed4-11ea-956a-f56d019f84e1.png)

**Comment by dangtaikhtn** [comment]
@Tyrrrz Hi, I already deployed to Heroku (https://taine.herokuapp.com/api/values/SlPhMPnQ58k) but It only works on local. Can you help me on this issue?

**Comment by Tyrrrz** [comment]
@dangtaikhtn most likely because it's bound to your server's IP address, see `&ip=54.84.189.171` in the URL

**Comment by dangtaikhtn** [comment]
@Tyrrrz Do you know how to fix this issue? I already tried to deploy on Azure cloud and it still not working.

**Comment by dangtaikhtn** [comment]
I can get the root cause now, I have checked the &ip=54.84.189.171 and it belong to US region, when I request from Vietnam region then it does not work.

**Comment by Tyrrrz** [comment]
You can't really get around it afaik.
#149 #245 #250

**Comment by hsallander** [comment]
Thanks for the fix @Tyrrrz ! It works fine now on the video IDs we previously had problems with.

**Comment by Tyrrrz** [comment]
Great :)
