### ISSUE TITLE
SearchVideosAsync Visual Studio.net

### ISSUE THREAD

**Issue by hunterofsouls** [Tyrrrz/YoutubeExplode#314]
Hi, I am trying to implement YoutubeExplode for a desktop application using vb.net, I have changed the code to adapt it to the language. but I get the following error. please support

I get the following error:
Unhandled exception of type 'System.AggregateException' in mscorlib.dll

Additional information: One or more errors have occurred.

regards

Imports System
Imports System.Collections.Generic
Imports System.Linq
Imports System.Text.RegularExpressions
Imports System.Threading.Tasks
Imports Newtonsoft.Json.Linq
Imports YoutubeExplode.Internal
Imports YoutubeExplode.Models
Imports System.Net.Http
Public Class YoutubeSearch
    Private Async Function GetSearchResultsJsonAsync(ByVal query As String, ByVal page As Integer) As Task(Of JToken)
        Dim http As New HttpClient
        Dim url = "https://youtube.com/search_ajax?style=json&search_query={query.UrlEncode()}&page={page}&hl=en"
        Dim raw = Await http.GetStringAsync(url).ConfigureAwait(False) ' don't ensure success but rather return empty list
        Return JToken.Parse(raw)
    End Function

    Public Async Function SearchVideosAsync(ByVal query As String, ByVal maxPages As Integer) As Task(Of IReadOnlyList(Of Video))
        'query.(NameOf(query))
        'maxPages.GuardPositive(NameOf(maxPages))
        Dim videos = New List(Of Video)()

        For page = 1 To maxPages
            Dim resultsJson = Await GetSearchResultsJsonAsync(query, page).ConfigureAwait(False)
            Dim countDelta = 0

            For Each videoJson In resultsJson.SelectToken("video").Values
                Dim epoch = New DateTimeOffset(1970, 1, 1, 0, 0, 0, TimeSpan.Zero)
                Dim videoId = videoJson.SelectToken("encrypted_id").Value(Of String)()
                Dim videoAuthor = videoJson.SelectToken("author").Value(Of String)()
                Dim videoUploadDate = ""
                Dim videoTitle = videoJson.SelectToken("title").Value(Of String)()
                Dim videoDescription = videoJson.SelectToken("description").Value(Of String)()
                Dim videoDuration = TimeSpan.FromSeconds(videoJson.SelectToken("length_seconds").Value(Of Double)())
                Dim videoViewCount = ""
                Dim videoLikeCount = videoJson.SelectToken("likes").Value(Of Long)()
                Dim videoDislikeCount = videoJson.SelectToken("dislikes").Value(Of Long)()
                Dim videoKeywordsJoined = videoJson.SelectToken("keywords").Value(Of String)()
                Dim videoKeywords = Regex.Matches(videoKeywordsJoined, """[^""]+""|\S+").Cast(Of Match)().[Select](Function(m) m.Value).Where(Function(s) Not s.Trim).[Select](Function(s) s.Trim(""""c)).ToArray()
                Dim videoStatistics = New Statistics(videoViewCount, videoLikeCount, videoDislikeCount)
                Dim videoThumbnails = New ThumbnailSet(videoId)
                videos.Add(New Video(videoId, videoAuthor, videoUploadDate, videoTitle, videoDescription, videoThumbnails, videoDuration, videoKeywords, videoStatistics))
                countDelta += 1
            Next

            If countDelta <= 0 Then Exit For
        Next

        Return videos
    End Function
    Public Function SearchVideosAsync(ByVal query As String) As Task(Of IReadOnlyList(Of Video))
        Return SearchVideosAsync(query, Integer.MaxValue)
    End Function

       
Public Class Form1
    Dim search As New YoutubeSearch
    Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
        RadListView1.DataSource = search.SearchVideosAsync("green day", 2).Result
    End Sub
End Class

**Comment by Tyrrrz** [comment]
Were you able to find the answer?

**Comment by hunterofsouls** [comment]
Hello, problem solved, thanks for your interest. and congratulations on the project.
