### ISSUE TITLE
url_encoded_fmt_stream_map is null

### ISSUE THREAD

**Issue by omansak** [Tyrrrz/YoutubeExplode#317]
Video works normally but url_encoded_fmt_stream_map is empty/null

Id : AYmeJlm7Gcg

**Comment by Tyrrrz** [comment]
Duplicate of #310 by the looks of it

**Comment by omansak** [comment]
Test Values :
Normal : Alr26K0F4EQ
Encrypted : ADxntEqPysA

**Comment by Tyrrrz** [comment]
Try updating to 4.7.11

**Comment by omansak** [comment]
@Tyrrrz yes i know you updated i just gived test values for future
