### ISSUE TITLE
Is it possible to change the bitrate of an audio?

### ISSUE THREAD

**Issue by nyhead** [Tyrrrz/YoutubeExplode#318]
I am trying to download audio, and I need and audio file to take as little space possible. I have tried change the bitrate, but there is only one method ".WithHighestBitrate()".

**Comment by Tyrrrz** [comment]
You can do `.OrderBy(s => s.Bitrate)`

**Comment by nyhead** [comment]
Thank you very much! I used ".OrderBy(s => s.Bitrate).First()" and it worked!

**Comment by Tyrrrz** [comment]
You're welcome!
