### ISSUE TITLE
"The given key was not present in the dictionary" on specific videos

### ISSUE THREAD

**Issue by ColorTwist** [Tyrrrz/YoutubeExplode#319]
Is there a reason I am getting this error on specific videos like A8PNce_LIig while on youtube it seems to be working just fine: https://www.youtube.com/watch?v=A8PNce_LIig

**Comment by ColorTwist** [comment]
i think it's my issue, i used a different versions. closing,

**Comment by Tyrrrz** [comment]
Ok, good to know, thank you.
