### ISSUE TITLE
Extract all available video qualities

### ISSUE THREAD

**Issue by Lelyou** [Tyrrrz/YoutubeExplode#32]
How i can loop trough the available Video Qualities in the VideoInfo the right way? 

I want to check it against a fixed array of qualities and decide if a checkbox is enabled or not.

someone can give me a hint for the right linq to use ?

**Comment by Tyrrrz** [comment]
This should return the list of available video qualities in a video info:

```c#
public IEnumerable<VideoQuality> GetAvailableVideoQualities(VideoInfo videoInfo)
{
    var mixedQualities = videoInfo.MixedStreams.Select(s => s.VideoQuality);
    var pureQualities = videoInfo.VideoStreams.Select(s => s.VideoQuality);
    return mixedQualities.Concat(pureQualities).Distinct().OrderBy(q => q);
}
```

Haven't tested it myself, but should work

**Comment by Lelyou** [comment]
ok i will test it later.

is it possible that the highest quality of mixedstreams cant get higher than 720p ? 

i tested it with a simple foreach loop that hints me message boxes:

```
                var videoinfo = await client.GetVideoInfoAsync("theVideoID");

                var streaminfo = videoinfo.MixedStreams.ToArray();

                foreach(MixedStreamInfo info in streaminfo)
                {
                    MessageBox.Show(info.VideoQuality.ToString());
                }
```

**Comment by Tyrrrz** [comment]
Just tested my snippet, it works correctly.

Yes, mixed streams only go as high as 720p 30fps. Youtube only gives higher qualities as separate streams.

**Comment by Lelyou** [comment]
ok thank you for that reply :) 

your snippet works like a charm !

**Comment by Tyrrrz** [comment]
No problem ;)
