### ISSUE TITLE
How to use YouTubeExplode on VB.net

### ISSUE THREAD

**Issue by shannonfonseka** [Tyrrrz/YoutubeExplode#320]
Hello, I am building a YouTube Video Downloader software (a WPF Application), but the programming language I use is VB.net

YouTubeExplode uses C#, but I have no idea about C#.

How to represent "Parse ID from URL, Get video info, Download video, Extract closed captions, Get playlist info" in VB.net?

**Comment by Tyrrrz** [comment]
Not sure, I've never written in VB.net

**Comment by shannonfonseka** [comment]
If that's the case, then OK....
