### ISSUE TITLE
Could not get video information

### ISSUE THREAD

**Issue by zjjohncq** [Tyrrrz/YoutubeExplode#322]
I have several videos cannot get video information.
my log shows:
Find url: https://www.youtube.com/watch?v=AgxAwtFbFD0
Start download https://www.youtube.com/watch?v=AgxAwtFbFD0
Obtaining general video info... AgxAwtFbFD0
> 《味道》 20191214 我的家乡菜·乐山篇（上）| 美食中国 Tasty China by 美食中国 Tasty China

Obtaining media stream info set... 
> 0 muxed streams, 0 video-only streams, 0 audio-only streams

Can you please help? Thanks,

**Comment by Tyrrrz** [comment]
Have you updated to the latest version?

**Comment by zjjohncq** [comment]
Yes. I tried to debug the source code. But get ask error at VS2017 and VS2019 complaint the project file.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Tyrrrz** [comment]
Works for me, make sure you're on 4.7.11
![image](https://user-images.githubusercontent.com/1935960/70864365-cbcd4800-1f59-11ea-80d2-e1a679a357cc.png)

**Comment by zjjohncq** [comment]
Thanks. In early morning just see 4.7.10

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by zjjohncq** [comment]
looks it is working on 4.7.11. thanks

**Comment by Tyrrrz** [comment]
Great :)
