### ISSUE TITLE
Drop .NET Standard 1.1

### ISSUE THREAD

**Issue by Tyrrrz** [Tyrrrz/YoutubeExplode#323]
Since 2017, YoutubeExplode has been targeting .NET Standard 1.1 in addition to other frameworks. This has now become a hindrance as the project can't depend on many other libraries which have moved on from .NET Standard 1.1 a long time ago.

The suggestion is to drop .NET Std 1.1 altogether or replace it with .NET Std 1.6.

Please leave a reaction with your vote:

- 👍 = drop .NET Std 1.1
- 👎 = keep .NET Std 1.1 (and explain in the comments why you need it)
- 😕 = drop .NET Std 1.1 and add .NET Std 1.6 target (and explain in the comments why you need it)
- 👀 = I don't care

**Comment by Tirraon** [comment]
My project still targets older UWP SDK versions, which don't support NetStandard2.0 or even 1.6 - only 1.4.
On other hand, I can't force to keep NS1.4 or lower. In past I have tried to return it to other libs (like AngleSharp or LiteDB), but their count is increased.

I need to find solution on my side to drop off versions older then 16299, so it will allow me to use a lot of cool stuff from netstandard2.0. Or at least use backported slice of YoutubeExplode in my project.

**Comment by jasonspar** [comment]
Even AngleSharp doesn't work properly. I target .net 4.5.

**Comment by Zyano** [comment]
For those interested EOL timeline for .net framework can be found here:
https://support.microsoft.com/en-us/help/17455/lifecycle-faq-net-framework

Here is a page with a good overview of the windows OS EOL which .net framework is tied to:
https://www.mirazon.com/a-comprehensive-guide-to-microsoft-end-of-support/

EOL list for .net core :
https://dotnet.microsoft.com/platform/support/policy/dotnet-core

.NET Standard support list:
https://github.com/dotnet/standard/blob/master/docs/versions.md
