### ISSUE TITLE
Is there an example for selecting revolution for videos?

### ISSUE THREAD

**Issue by songshizhao** [Tyrrrz/YoutubeExplode#324]
I have tried a lot and only this works
This is a treasure
I even used FFMPEG (uwp) to play online ,awesome
This is a small problem
I'm using Nuget version of this.
Can you tell me how to choose the resolution of the video.

**Comment by Tyrrrz** [comment]
Hi, check out the example in readme (commented out lines)
https://github.com/Tyrrrz/YoutubeExplode#download-video
