### ISSUE TITLE
Load more videos from search as needed

### ISSUE THREAD

**Issue by VideoAppsNet** [Tyrrrz/YoutubeExplode#326]
I would like to load more videos from search as needed. For example I would like to load 1 page and when user wants to see more videos for that same search term then I can load the second page and so on. I looked at the source code and I can see that the function = SearchVideosAsync always starts on page 1. Is there a way to fix this? Maybe Im missing something? Would be great to have a loadMore() for the search term. Thank you.

**Comment by Tyrrrz** [comment]
Hi, this will be changed in the next major release when YoutubeExplode targets .Net Standard 2.1.
These methods will return `IAsyncEnumerable` which you will be able to traverse as you see fit.

Kinda related to #90

**Comment by VideoAppsNet** [comment]
Thank you for that info. If you can also make it keep track of what the previous page loaded. So that after a while of loading more pages it does not loose track and does not double load the same search result. Sometimes people scroll to the 100+ video in the search stack when by default youtube gives 10 results per search. I know I can increase that but I want to keep it at 10 results per search. And one more question. When is the next update scheduled? Thanks.

**Comment by Tyrrrz** [comment]
>If you can also make it keep track of what the previous page loaded.

This would make the client stateful which is best to avoid as the contents of those pages may change.

>When is the next update scheduled? Thanks.

There is no schedule. Some time when I feel like it :)

**Comment by VideoAppsNet** [comment]
Will it be able to remember that it loaded page one before and it would just load page 2 when I call update()? Or is it going to be hard coded where I send a request for search("Search Term" , 8);
In this case getting results for page 8. Thanks for your work.

**Comment by Tyrrrz** [comment]
You will most likely be able to specify the page to start from. Other than that, you'll get an `IAsyncEnumerable` which you can `await foreach` over and break early if you need to.

**Comment by VideoAppsNet** [comment]
Ok sounds good. Thank you.
