### ISSUE TITLE
Cannot parse playlist URL

### ISSUE THREAD

**Issue by jasonspar** [Tyrrrz/YoutubeExplode#327]
Here is a URL that the library (ver 4.7.11.0) could not parse:

https://www.youtube.com/watch?v=sjrp1FEHnyA&list=TLPQMjIxMjIwMTmllz9Xdzg0vg

I am using YoutubeClient.TryParsePlaylistId (url, out id) API for this. It works for pretty much everything. Not sure why it doesn't like this one.

**Comment by Tyrrrz** [comment]
It doesn't look like it's a valid playlist ID. I don't see any playlist-related controls on the page you linked (e.g. next video, video list, etc) and the [following link](https://www.youtube.com/playlist?list=TLPQMjIxMjIwMTmllz9Xdzg0vg) confirms it doesn't exist.

**Comment by jasonspar** [comment]
This is the original link and it does work in my browser:

https://www.youtube.com/watch?v=sjrp1FEHnyA&list=TLPQMjIxMjIwMTmllz9Xdzg0vg&index=9

**Comment by Tyrrrz** [comment]
Does this link work for you? https://www.youtube.com/playlist?list=TLPQMjIxMjIwMTmllz9Xdzg0vg

**Comment by jasonspar** [comment]
No that one comes up as invalid.

**Comment by jasonspar** [comment]
Can you step thru the TryParsePlaylistId and see if it fails during validation or API to the youtube?
If it's the youtube, then that's something else.

**Comment by Tyrrrz** [comment]
Yeah, it fails during validation. Every playlist has a type which is detected using those two first letters. I went through to see what kind of playlist it is to add it but found that YouTube says the playlist doesn't exist. In other words, even if there were no validation, it would have thrown an error later in `GetPlaylistAsync`.

Can you somehow find the playlist this video is part of and link it to me?

**Comment by jasonspar** [comment]
https://www.youtube.com/watch?v=sjrp1FEHnyA&list=TLPQMjIxMjIwMTmllz9Xdzg0vg
https://www.youtube.com/playlist?list=TLPQMjIxMjIwMTmllz9Xdzg0vg

Looks like the one that has playlist? does not work, but the one with watch? works fine.

**Comment by jasonspar** [comment]
I see what you mean. The lists should start with PL. Not sure why this is TLP

**Comment by Tyrrrz** [comment]
There are some that don't start with PL but those are special playlists, not created by YouTube users.

For example, I can't find this video in any of the playlist on the author's channel:
https://www.youtube.com/channel/UCETveVX7TPauIupxYz6sFtA/playlists

**Comment by jasonspar** [comment]
Here is another one that is not parsed:

https://www.youtube.com/watch?v=PIb6AZdTr-A&list=RDCLAK5uy_lf8okgl2ygD075nhnJVjlfhwp8NsUgEbs&index=3
