### ISSUE TITLE
The app returns error

### ISSUE THREAD

**Issue by ghootifarangi** [Tyrrrz/YoutubeExplode#328]
Hi

I have a website and my it uses this app for get videos from youtube. When users use this app for get videos, the app returns this error:

Response status code does not indicate success: 429 (Too Many Requests).

Please help me to resolve this problem.

**Comment by Tyrrrz** [comment]
Duplicate of #292

**Comment by ghootifarangi** [comment]
Apparently, youtube block this url (https://youtube.com/get_video_info?). Do you change this part of your app and get important data from source of video page (https://www.youtube.com/watch?v=)?

**Comment by ghootifarangi** [comment]
test picofile.com

**Comment by ghootifarangi** [comment]
test www.picofile.com

**Comment by ghootifarangi** [comment]
test www.namasha.com

**Comment by Tyrrrz** [comment]
Not sure what the question is
