### ISSUE TITLE
Can not parse URL

### ISSUE THREAD

**Issue by dangtaikhtn** [Tyrrrz/YoutubeExplode#329]
Hi @Tyrrrz , Can you take a look with the video id mN3rDTAdM2o (https://www.youtube.com/watch?v=mN3rDTAdM2o)?. Now I can not parse a data to get the link to stream, it always return me a file to download.

**Comment by Tyrrrz** [comment]
Seems to work:
![image](https://user-images.githubusercontent.com/1935960/71446115-a5ad6200-2728-11ea-9d02-233ae78a29bb.png)

**Comment by dangtaikhtn** [comment]
It returned to me the link but can not get the link to play.
https://r5---sn-42u-8j5e.googlevideo.com/videoplayback?expire=1577302384&ei=EGUDXr_uKIKg4QKjjZDgAQ&ip=1.54.175.236&id=o-AGpDzE-5l4zxyWouBamiSfBjUNZhSW584MwjZpQvlZjg&itag=43&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-42u-8j5e%2Csn-42u-nbos6&ms=au%2Crdu&mv=m&mvi=4&pl=23&gcr=vn&initcwndbps=1418750&mime=video%2Fwebm&gir=yes&clen=24261056&ratebypass=yes&dur=0.000&lmt=1576410594804691&mt=1577280700&fvip=5&fexp=23842630&c=WEB&txp=5511222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRAIgf9jjxGOCSF6BKVQwo8geM4hwDbHCJlZ-U8ZOmFmp-JYCIBNF_HTbbpgRWfxFrJ3BSgz-ZzE8M46HbD4P-UPrEQzv&sig=ALgxI2wwRAIgR_hmX82f5SuTGO602NwDyjdFw7k89eW5Xjrw_3p2ntQCIENqAcw76TYVqqSisOYlTBIvVI2WLI18mhkb6r3tdhxE

**Comment by Tyrrrz** [comment]
Are you trying to play the stream on the same machine you resolved it? Is 1.54.175.236 your IP?

**Comment by dangtaikhtn** [comment]
Yes, I was trying on the same machine. The IP is not mine but it in my region (Vietnam) and other video still working fine.

**Comment by Tyrrrz** [comment]
What exact error code are you getting?

**Comment by dangtaikhtn** [comment]
Let me check again, some machine can play but It can not on my machine.
Anyway thanks for your response quickly.

**Comment by dangtaikhtn** [comment]
Maybe my IP address was banned by Google :D
