### ISSUE TITLE
Can't get Timestamped URLs to work

### ISSUE THREAD

**Issue by Stureplan** [Tyrrrz/YoutubeExplode#330]
Hi @Tyrrrz!

I'm experimenting with your code a bit, trying to use URL's which have the added timestamps to them (example: **&t=5** for a 5 second offset).

Can't really get it to work. Here's a sample URL which I've been trying (been trying many different other ones too)
timestamped: https://www.youtube.com/watch?v=zOWJqNPeifU&t=5
naked: https://www.youtube.com/watch?v=zOWJqNPeifU

I've tried appending the &t=5 string to the videoId at different spots but none of them really seem to work. Getting "Invalid YouTube video ID" but even tried adding the append to after the validation check, doesn't seem to do anything about the time offset, just loads the video normally.

**Comment by Tyrrrz** [comment]
Hey there.

This won't have any effect.  On the frontend side of things, YouTube just seeks the stream to the specified position.

What you need to do is get the media stream and use its `Seek` method. It accepts a `long` byte offset which you can derive from time and bitrate. I don't have the formula at hand but I'm sure you can find it.

**Comment by Stureplan** [comment]
Gotcha. I was using your code and plugging it into Unity's native VideoPlayer component. It just expects an URL and then "magic box"-style plays it. I ended up just using:
VideoPlayer.time = (fullDuration) * 0.5f

It allowed me to skip to halfway through a video instead of at the start. Thanks for your help.

**Comment by Tyrrrz** [comment]
Great 👍
