### ISSUE TITLE
No LtGt.Models.HtmlDocument type

### ISSUE THREAD

**Issue by SarkonCovasko** [Tyrrrz/YoutubeExplode#331]
I recently have been getting an issue where trying to call `GetVideoMediaStreamInfosAsync(id)` results in an exception: 

`Could not load type 'LtGt.Models.HtmlDocument' from assembly 'LtGt, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null'`

After looking around in the code, I could only find a reference to the hinted type, but couldn't find an actual declaration of it anywhere. I also noticed that I don't even have an `LtGt.Models` included in my assembly (LtGt v2.0.1.0). I did, however, notice an `LtGt.HtmlDocument` type. Is this supposed to take the place of `LtGt.Models.HtmlDocument`? Any ideas how I can get around this issue? This wasn't happening until the most recent updates.

**Comment by Tyrrrz** [comment]
You probably updated LtGt to v2, keep it at v1.

**Comment by SarkonCovasko** [comment]
That did it. Thanks!
