### ISSUE TITLE
Empty list of streams

### ISSUE THREAD

**Issue by SneakyTactician** [Tyrrrz/YoutubeExplode#333]
Hi,

Often times when I use this line to get a Youtube video's audio, I get an exception. This used to never happen, now its 3/4ths of the time:
`MemoryStream audioData = this.Tube.GetAudioAsync(track.VideoId).Result`

System.ArgumentNullException, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e:
Help link: 
Error code: -2147467261
Message: Value cannot be null. (Parameter 'info')
Source: YoutubeExplode
Stack trace: 
   at YoutubeExplode.Internal.Guards.GuardNotNull[T](T o, String argName)
   at YoutubeExplode.YoutubeClient.DownloadMediaStreamAsync(MediaStreamInfo info, Stream output, IProgress`1 progress, CancellationToken cancellationToken)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

Any ideas?

Thanks!

**Comment by Tyrrrz** [comment]
Judging by the error, `info` is null.

**Comment by SneakyTactician** [comment]
I have verified that the video ID that is passed in is not null when the error happens...

**Comment by Tyrrrz** [comment]
Sure, but whatever is calling `DownloadMediaStreamAsync` is passing null as the first argument.

**Comment by SneakyTactician** [comment]
My apologies, I had forgotten that I had written that part. I believed that was this API. 

The real issue here is

`MediaStreamInfoSet streamInfoSet = await this.TubeClient.GetVideoMediaStreamInfosAsync(videoId);`

The IReadonlyList<AudioStreamInfo> contained within doesn't contain any available options. "The sequence is empty". What does this mean? 
Is there no audio available for this video?

**Comment by Tyrrrz** [comment]
Sometimes it's possible that a video may not have audio-only streams. What's the video URL?

**Comment by SneakyTactician** [comment]
https://www.youtube.com/watch?v=bOfnRoi4TkA

**Comment by Tyrrrz** [comment]
Seems to work for me...
![image](https://user-images.githubusercontent.com/1935960/72179458-98ad9580-33ed-11ea-946f-eedb87f6c602.png)

Seems related to an issue someone reported long time ago that I couldn't reproduce :/

**Comment by Tyrrrz** [comment]
Looks like CI is having the same issues lately: https://github.com/Tyrrrz/YoutubeExplode/commit/8ad5cee1eb90a5f553e515245d260b68d57b4aa5/checks?check_suite_id=394278555

**Comment by Jabroni** [comment]
Any update on this issue? Im experiencing the something similar, audioStreamInfo and videoStreamInfos returns null/empty... the wierd thing its that if I try to download that same video using the YoutubeDownload 1.7.3 it works. I double checked and I have the 4.7.13 from nuget (c# asp.net app)

**Comment by Tyrrrz** [comment]
@Jabroni is the asp.net app hosted locally or on a different IP?

Also, what code is returning `null`?

**Comment by Jabroni** [comment]
Im testing locally with my ISP, have 2 different ips and same result. 

streamInfoSet returns Audio, Muxed, and Video [0] results. So when i try to select audio and video streams it throws an exception that the list is empty.

I did a test on a clean project and it worked, so im wondering if there is a broken/old/new dependency that is making the YoutubeExplode dll misbehave like that?

**Comment by Tyrrrz** [comment]
Is this still happening?

**Comment by Jabroni** [comment]
> Is this still happening?

Not on my end... for me it was an issue having multiple projects on my solution, and for some reason it was loading an old YoutubeExplorer dll that was a leftover on another project
