### ISSUE TITLE
Download Video from Browser Not Working

### ISSUE THREAD

**Issue by VideoAppsNet** [Tyrrrz/YoutubeExplode#334]
Hello. Thanks for your work. I was wondering how do you download the url from youtube in asp.net / Blazor? I got it all working where I got the url and can watch the video from the browser but I can not download it unless I open the link in the browser. its loads the standard html5 player and from their I can click download. Is there a way that I can download from YouTubeExplode class? I searched around and could not find anything. Looks like this works for Desktop apps and UWP apps but not for the web. Thank you.

**Comment by Tyrrrz** [comment]
Hello
Have you tried `GetVideoMediaStreamInfosAsync`/`DownloadMediaStreamAsync`? https://github.com/Tyrrrz/YoutubeExplode#download-video

**Comment by Tyrrrz** [comment]
You should take a look at [the readme](https://github.com/Tyrrrz/YoutubeExplode#download-video).

`MediaStreamInfoSet` contains many different `MediaStreamInfo`s, you will want to choose one (or two, if you're multiplexing them) based on properties like quality, bitrate, etc.

`GetMediaStreamAsync` can be used to resolve a `Stream` using its `MediaStreamInfo`. You can then either download it or stream it as a response from the web server (with correct MIME type).

**Comment by Tyrrrz** [comment]
I don't know what you would do in blazor, but in typical ASP.NET Core scenarios you will want to respond with the `FileActionResult`. Here's an example (old but the idea is the same):

https://github.com/SlowLogicBoy/YoutubeExplode.AspNetCore.Mvc/blob/15107cea8c8dec631c27a79235269b32db9a2591/Controllers/YoutubeController.cs#L1-L23

**Comment by alexmartyniuk** [comment]
Hi! I have a similar problem trying to fetch video info from the Blazor WebAssembly app. As the code is executed in the browser it is not allowed to fetch data from Youtube due to CORS policy. When I am trying to do this:

```c#
 var video = await Youtube.Videos.GetAsync($"https://youtube.com/watch?v={videoId}");
```
In the browser console I see this error:
```
Access to fetch at 'https://youtube.com/list_ajax?style=json&action_get_list=1&list=RDy6lQMPE6MVE&index=0&hl=en' from origin 'https://localhost:5001' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

I think it is nothing to do with the YoutubeExplode library it is the issue with the browser and [CORS](https://uk.wikipedia.org/wiki/Cross-Origin_Resource_Sharing).

**Comment by Tyrrrz** [comment]
> Hi! I have a similar problem trying to fetch video info from the Blazor WebAssembly app. As the code is executed in the browser it is not allowed to fetch data from Youtube due to CORS policy. When I am trying to do this:
> 
> ```cs
>  var video = await Youtube.Videos.GetAsync($"https://youtube.com/watch?v={videoId}");
> ```
> 
> In the browser console I see this error:
> 
> ```
> Access to fetch at 'https://youtube.com/list_ajax?style=json&action_get_list=1&list=RDy6lQMPE6MVE&index=0&hl=en' from origin 'https://localhost:5001' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
> ```
> 
> I think it is nothing to do with the YoutubeExplode library it is the issue with the browser and [CORS](https://uk.wikipedia.org/wiki/Cross-Origin_Resource_Sharing).

Indeed, the browser will deny requests to external resources in such cases. Note that CORS is made to protect the users of your site/app, rather than YouTube. This means that you should be able to disable CORS on your end if you want.

I don't know how to achieve this with Blazor, but with standard `fetch` API you would set `mode` to `no-cors`:

https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch

![image](https://user-images.githubusercontent.com/1935960/111797221-a30cce80-88d1-11eb-93b0-7d629e9da3c2.png)

**Comment by alexmartyniuk** [comment]
Thanks for your answer. It is impossible to disable the CORS from the client-side. If you specify `mode: no-cors` for fetch function it will only make this request `opaque`, so the response will be accessible by service workers but not by the javascript on the page as I understood [this article](https://developers.google.com/web/ilt/pwa/working-with-the-fetch-api#cross-origin_requests). But there is nothing to do with your client. I think you did great work and this restriction is a browser security restriction and we can nothing to do with this.

**Comment by Tyrrrz** [comment]
> Thanks for your answer. It is impossible to disable the CORS from the client-side. If you specify `mode: no-cors` for fetch function it will only make this request `opaque`, so the response will be accessible by service workers but not by the javascript on the page as I understood [this article](https://developers.google.com/web/ilt/pwa/working-with-the-fetch-api#cross-origin_requests). But there is nothing to do with your client. I think you did great work and this restriction is a browser security restriction and we can nothing to do with this.

Interesting, I did not know that 🤔 
Yeah unfortunately we can't really do anything from YoutubeExplode's end to fix this.
