### ISSUE TITLE
Not getting highest quality video returned?

### ISSUE THREAD

**Issue by bkolo** [Tyrrrz/YoutubeExplode#336]
Using this video (and many others)
https://www.youtube.com/watch?v=nYAvRP1jne0

GetVideoMediaStreamInfosAsync() is returning a max video size (muxed) of 1280 width but there is clearly a 1920 width available on the site.

**Comment by Headhuntez** [comment]
Присоединяюсь к данной проблеме.
https://github.com/Tyrrrz/YoutubeExplode/issues/335#issuecomment-580752504

**Comment by Tyrrrz** [comment]
Looks like the additional streams are resolved but the URLs are broken and result in 404 for some reason.

**Comment by Tyrrrz** [comment]
It seems that to solve this, we need #159.
