### ISSUE TITLE
Download only a part of video

### ISSUE THREAD

**Issue by KrSiddharth** [Tyrrrz/YoutubeExplode#339]
Is there a way by which I can download only a part of the video, maybe by mentioning start & end time?

**Comment by Tyrrrz** [comment]
Hi!

There is a way to download a part of the video stream but it's pretty low-level.
You need to use `GetMediaStreamAsync` and use the stream's seeking functionality to read a specific part. You will have to calculate the byte offset by multiplying bitrate and the offset duration.

![image](https://user-images.githubusercontent.com/1935960/74366493-cca71c80-4dd8-11ea-9189-62f476f90f0b.png)
Source: https://blog.frame.io/2017/03/06/calculate-video-bitrates/#formulasTarget

**Comment by KrSiddharth** [comment]
@Tyrrrz Can you please write a short snippet for that? I'm having a hard time implementing that since I'm new to .NET & C#. TIA

**Comment by Tyrrrz** [comment]
Something like this works, but the video is not playable unless it starts at the beginning. My guess is that there headers in the first few bytes of data, which you will have to copy regardless or recreate yourself somehow, according to Mp4/WebM spec. Also, the cut off time doesn't seem to be very accurate, it stops at around 2min50 instead of 3 minutes.

Anyway, this turned out to be a non-trivial task. Hopefully this snippet would help you somehow.

```csharp
await using var output = File.Create(fileName);
await using var input = await client.GetMediaStreamAsync(streamInfo);

var startTime = TimeSpan.Zero;
var duration = TimeSpan.FromMinutes(3);

var bytesStartTime = (long) (streamInfo.Bitrate * startTime.TotalMinutes * 0.0075 * 1000 / 2);
var bytesDuration = (long) (streamInfo.Bitrate * duration.TotalMinutes * 0.0075 * 1000 / 2);

var bytesRemaining = bytesDuration;
input.Seek(bytesStartTime, SeekOrigin.Begin);

var buffer = new byte[82960];
var bytesRead = 0;
while ((bytesRead = await input.ReadAsync(buffer, 0, buffer.Length)) > 0)
{
    var bytesCopy = Math.Min((int) bytesRemaining, bytesRead);
    await output.WriteAsync(buffer, 0, bytesCopy);
    bytesRemaining -= bytesCopy;

    if (bytesRemaining <= 0)
        break;
}
```

**Comment by tuhin24** [comment]
@KrSiddharth , Have you ever figured this out? The above code sample was very helpful, but the video is not playable unless it starts at the beginning. Thanks

**Comment by alexrainman** [comment]
It is actually very easy.

```cs
var ffmpeg = @"\PATH_TO_FFMPEG\ffmpeg.exe";
var arguments = $"-ss 00:00:00.00 -i \"{streamInfo.Url}\" -t 00:00:10.00 -c copy \"\\DOWNLOAD_PATH\\{videoId}.mp4\"";

using (Process p = new Process())
{
    p.StartInfo.FileName = ffmpeg;
    p.StartInfo.Arguments = arguments;
    p.StartInfo.UseShellExecute = false;
    p.StartInfo.CreateNoWindow = true;
    p.StartInfo.RedirectStandardOutput = true;
    p.Start();
    p.WaitForExit();

    var output = p.StandardOutput.ReadToEnd();
}
```

**Comment by Dan1ve** [comment]
Based on @alexrainman 's answer and in case you are using [FFMpegCore](https://github.com/rosenbjerg/FFMpegCore) , here is a version using the API wrappers:

``` cs
string videoKey = "JkYagMMPScY";
var fromTimspan = TimeSpan.FromSeconds(5);
var toTimespan = TimeSpan.FromMinutes(1);

// ----

TimeSpan cutDuration = toTimespan - fromTimspan;

var youtubeClient = new YoutubeClient();
StreamManifest streamManifest = await youtubeClient.Videos.Streams.GetManifestAsync(videoKey);

IStreamInfo streamInfo = streamManifest.GetMuxedStreams().GetWithHighestBitrate();
var outputFile = videoKey + "-output.mp4";
FFMpegArguments
        .FromUrlInput(new Uri(streamInfo.Url))
        .OutputToFile(outputFile, false, options =>
               options.WithCustomArgument($"-ss {fromTimspan.ToString()} -t {cutDuration.ToString()}")
         )
        .ProcessSynchronously();
```
