### ISSUE TITLE
Problem with downloading

### ISSUE THREAD

**Issue by hosseinpanahi** [Tyrrrz/YoutubeExplode#34]
Downloading from youtube almost not working always. 

Wanted video exists but Youtube client says video not found

`string request = $"https://www.youtube.com/get_video_info?video_id={videoId}&el=info&ps=default";`

**Comment by mnakka9** [comment]
It's working, verified with a normal & Vevo video.
Can you please include more info on this.

**Comment by hosseinpanahi** [comment]
thanks for response

here is a link that does not work for me

https://www.youtube.com/watch?v=7l_wqo3jbwe

i have tested it in 2 PC's from 2 different countries with different internet connections and with different youtube links

9 times out of 10 this error happens:
YoutubeClient.cs
Line 206
```
            if (videoInfoDic.ContainsKey("errorcode"))
            {
                int errorCode = videoInfoDic.Get("errorcode").ParseInt();
                string errorReason = videoInfoDic.GetOrDefault("reason") ?? "<no reason>";
                throw new VideoNotAvailableException(errorCode, errorReason);
            }
```

**Comment by mnakka9** [comment]
Hi ,
For the video URL, the video is unavailable.
![image](https://user-images.githubusercontent.com/26427477/27633337-5e567eac-5c1c-11e7-85d7-cd05226ae6a8.png)

**Comment by hosseinpanahi** [comment]
Yes but whatever youtube link that i will try to download this thing happens! The video will go to unavailable state!
I think youtube have added a new security layer or something

**Comment by SlowLogicBoy** [comment]
I don't have such problem :)

**Comment by Tyrrrz** [comment]
The error by that code block is produced when the video is unavailable. Are you sure it happens on literally every video? If you also can't open it in browser it probably means something else is at fault...

**Comment by hosseinpanahi** [comment]
Yes literally all videos! 
Would you please put here some youtube links that works for you? i'm sure after me trying to download you are not able to download it too!

**Comment by Tyrrrz** [comment]
Just downloaded [this](https://www.youtube.com/watch?v=-F_MoNbzlrM).
The video didn't become unavailable after I did it either.

**Comment by hosseinpanahi** [comment]
Try now! this could be hacking tools!

**Comment by TheInsaneBro** [comment]
For me its still available

**Comment by hosseinpanahi** [comment]
Try it now. i think there is a timer or something

**Comment by Tyrrrz** [comment]
I feel like you're not serious

**Comment by hosseinpanahi** [comment]
I'm serious, https://www.youtube.com/watch?v=-f_monbzlrk not working for me even in a browser

**Comment by Tyrrrz** [comment]
Well yeah. The capitalization is wrong.

**Comment by Tyrrrz** [comment]
https://www.youtube.com/watch?v=**-F_MoNbzlrM**
vs
https://www.youtube.com/watch?v=**-f_monbzlrk**

**Comment by hosseinpanahi** [comment]
You are correct, Thanks. sorry

**Comment by Tyrrrz** [comment]
Glad we got that conspiracy sorted out. ;)

**Comment by thetungng** [comment]
I have error in line. can you help me
![Annotation 2020-04-03 232907](https://user-images.githubusercontent.com/52435413/78383714-09d2a280-7603-11ea-817f-27032aa0dcdc.png)
