### ISSUE TITLE
Flush not supported, no waiting for Stream

### ISSUE THREAD

**Issue by VoltexRB** [Tyrrrz/YoutubeExplode#340]
I tried to implement this Code into my Discord Bot for playing Audio From Youtube. I can get the Video, get its Audio Stream and get the Audio Stream from my Bot thats sending the actual audio, I can get both matched to the same bitrate but I cant for the life of me wait for the transmission to be over before continuing because the Flush method seems Deprecated
```
            try { inputStream.CopyTo(audio.CreatePCMStream(AudioApplication.Music,(int)bestMediaStream.Bitrate)); }
            catch { }
            finally
            {
                //WAIT FOR THE STREAM TO END, NO FLUSH
                VideoEnded();
            }
```

Thats all I try to do

**Comment by Tyrrrz** [comment]
Well, if you read all bytes from the stream then the stream is over?

**Comment by VoltexRB** [comment]
Sure, but it does that as fast as it can and instantly continues without waiting, while it should be synchronous

**Comment by Tyrrrz** [comment]
You will have to post a more specific example, I don't see YoutubeExplode anywhere in the picture, so I have no idea what's going on. YoutubeExplode's streams are read-only anyway so `Flush()` doesn't make sense for them.
