### ISSUE TITLE
From March 2020 YouTube removes old design completely

### ISSUE THREAD

**Issue by MeteorBurn** [Tyrrrz/YoutubeExplode#341]
Hi there!
YouTube said it will stop supporting the old design from March.

In YouTubeExplode, I saw the use of the parameter "disable_polymer", which may not cause any effect in future.

Will there be updates in YouTubeExplode for a new design?

**Comment by Tyrrrz** [comment]
Thank you for letting me know. Yes, I will make sure to remember this for the next update.
I'll mark it as "bug" so it stands out for me.
