### ISSUE TITLE
List of playlists  for a given channel

### ISSUE THREAD

**Issue by Vasilut** [Tyrrrz/YoutubeExplode#342]
Hi. I saw that there is a method only for getting all the videos for a given channel (channelid). Is there a possibility to get all the playlists for a channel (channelId)? Does this seem plausible to be implemented ?  Thanks in advance :)

**Comment by Tyrrrz** [comment]
Hi.
Currently this is not possible and I doubt support for this will be added because it's already hell to maintain as it is. :(
