### ISSUE TITLE
Getting 403 on some videos

### ISSUE THREAD

**Issue by shaked6540** [Tyrrrz/YoutubeExplode#343]
most videos in this playlist return 403 https://www.youtube.com/playlist?list=PLoXL8KeHXDAvYjd8SNhPkT7ob3LvbqTEz

The exception is thrown when awaiting DownloadMediaStreamAsync

The videos play just fine in the browser

**Comment by ShimmyMySherbet** [comment]
I am also receiving this issue. It's when I'm attempting to download an audio stream, It fails, leaving me with an empty file. After opening the URL to it, I got the 403 Access Denied error.

**Comment by shaked6540** [comment]
Seems like this issue was resolved, maybe youtube reverted a change they made.

**Comment by Tyrrrz** [comment]
Yeah sometimes this happens
