### ISSUE TITLE
Don't know how to compile. Can you please make it simple. Maybe make a .cia.

### ISSUE THREAD

**Issue by calegxm999** [Tyrrrz/YoutubeExplode#345]
I wish i could figure out how to install it. It's very confusing and there's no clear instructions on the internet. Could you turn it into a .cia to save a lot of useless effort,

**Comment by Tyrrrz** [comment]
What's a .cia?
Anyway, tell me what you did and where you got stuck, maybe I can help you.

**Comment by Tyrrrz** [comment]
Also, why do you need to compile this?
