### ISSUE TITLE
DownloadMediaStreamAsync 403 (Forbidden)

### ISSUE THREAD

**Issue by darianbenito** [Tyrrrz/YoutubeExplode#347]
Hi! I get a 403 (Forbidden) after the call DownloadMediaStreamAsync method. It happens with all the videos that I tried. Is It a YouTube temporary issue? 
I am using YoutubeExplode 4.7.12

Thanks.

**Comment by Tyrrrz** [comment]
Hey. You need to update to 4.7.15.

**Comment by darianbenito** [comment]
> Hey. You need to update to 4.7.15.

Ok. But I do not think that this is the problem.

**Comment by Tyrrrz** [comment]
What do you think is the problem?

**Comment by darianbenito** [comment]
Maybe it's my fault. I will see the server firewall configuration. Thanks!

**Comment by Tyrrrz** [comment]
It's likely not you fault. There was a breaking change on YouTube's side that was fixed in YoutubeExplode in version 4.7.15.

**Comment by darianbenito** [comment]
Great, Thanks. What about YoutubeExplode dependencies? I am using the follow packages version: <package id="LtGt" version="1.0.2" targetFramework="net452" />
<package id="Newtonsoft.Json" version="12.0.3" targetFramework="net452" />

**Comment by Tyrrrz** [comment]
You don't have to update them.

**Comment by darianbenito** [comment]
Thanks. Update YoutubeExplode to 4.7.15 fix de issue.

**Comment by darianbenito** [comment]
Hi. It is happend again.
