### ISSUE TITLE
Forbidden on some videos

### ISSUE THREAD

**Issue by TheTrigger** [Tyrrrz/YoutubeExplode#349]
Some videos throws 403 Forbidden http exception, 
I tried to pass by constructor a new HttpClient with the right cookies to be loggedin.

Random video from logs: `LanCLS_hIo4`, `9ssRfVj92OA`, 

Any workaround?

Thanks
```
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at YoutubeExplode.Internal.HttpClientEx.GetStreamAsync(HttpClient client, String requestUri, Nullable`1 from, Nullable`1 to, Boolean ensureSuccess)
   at YoutubeExplode.Internal.SegmentedHttpStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at YoutubeExplode.Internal.Extensions.CopyToAsync(Stream source, Stream destination, IProgress`1 progress, CancellationToken cancellationToken, Int32 bufferSize)
   at YoutubeExplode.YoutubeClient.DownloadMediaStreamAsync(MediaStreamInfo info, Stream output, IProgress`1 progress, CancellationToken cancellationToken)
   at YoutubeExplode.YoutubeClient.DownloadMediaStreamAsync(MediaStreamInfo info, String filePath, IProgress`1 progress, CancellationToken cancellationToken)
   at YoutubeExplode.Converter.YoutubeConverter.DownloadAndProcessMediaStreamsAsync(IReadOnlyList`1 mediaStreamInfos, String filePath, String format, IProgress`1 progress, CancellationToken cancellationToken)
```

![image](https://user-images.githubusercontent.com/6072718/76836910-e2718c80-6831-11ea-9551-36ba49163644.png)

**Comment by Tyrrrz** [comment]
Which version of YTE are you using?

**Comment by TheTrigger** [comment]
Latest `4.7.16`

**Comment by derech1e** [comment]
> YoutubeExplode: `4.7.16`
> YoutubeExplode.Converter: `1.4.3`

You can download the second Video with the Version 4.7.15 of YoutubeExplode
@TheTrigger

**Comment by sskodje** [comment]
It seems Youtube has made changes that makes the old way of using embed to bypass age check not work any more. When using embed, the video now returns 403 error. There are similar issues with other programs, like [youtube-dl](https://github.com/ytdl-org/youtube-dl/issues/24320).

As such, i think the whole [method that uses embed](https://github.com/Tyrrrz/YoutubeExplode/blob/293def8994e4609e28fc9fa90921b01ef1d5e776/YoutubeExplode/YoutubeClient.Video.cs#L61) is no longer working, and indeed, if you remove [this line](https://github.com/Tyrrrz/YoutubeExplode/blob/293def8994e4609e28fc9fa90921b01ef1d5e776/YoutubeExplode/YoutubeClient.Video.cs#L211), all videos except age restricted videos work again.

I'm not sure if there is a solution atm for age restricted videos, apart from logging in.

**Comment by Tyrrrz** [comment]
Yeah, I know. Currently, v4.7.15 should work because it doesn't use embed page. I will invest some time into this issue later next week.

**Comment by booonzo** [comment]
v4.7.15 not works in all videos. It worsk in most videos but i found many examples where it also returns 403 - check those for example: z0NfI2NeDHI or d_k5DUi_FqE 

I've also noticed that in some videos it not returns any video and audio streams:
m3I2maZOCfs, 64e9-y9gphE

XD3M5JN1uhg - this video returns message: Video [XD3M5JN1uhg] is unplayable beacuse it requires purchase, but i am not sure if you are able to fix this.

But the most important is 403 on many videos. I hope you will have some time son to fix it :)

Cheers!

**Comment by Tyrrrz** [comment]
Yeah, it doesn't work on age restricted videos. Not 100% sure the fix will help with that. I know the youtube-dl project decided not to work around age restrictions and just not support them in general.

**Comment by booonzo** [comment]
Do you mean two first videos with 403 ? or you mean videos where no streams are returned ?

**Comment by resulozlu** [comment]
I think a lot of people are waiting for his recovery. I am also a victim of this current youtube-dl

**Comment by Tyrrrz** [comment]
The first two videos @booonzo.
Not sure what causes empty streams.

**Comment by booonzo** [comment]
@Tyrrrz hmmm but this video (**https://www.youtube.com/watch?v=d_k5DUi_FqE**) require age restriction ?

**Comment by Tyrrrz** [comment]
Indeed it appears not. Only the first one is age restricted.

**Comment by booonzo** [comment]
Hey
I found a couple of next videos and some bugs. Maybe you could check this in next updates
.
1. I found some videos where no streams are returned but it throws exception with messages:
**_OTpbqtW5cY** - Unterminated string. Expected delimiter: ". Path 'args.player_response', line 1, position 64182
**FJYcURdWtMo** - Unterminated string. Expected delimiter: ". Path 'args.player_response', line 1, position 52815., lang: AR
**TWo3bkPNhuo** - Unterminated string. Expected delimiter: ". Path 'args.player_response', line 1, position 66670
**8OpY1fh8PmI** - Unexpected end of content while loading JObject. Path 'args', line 1, position 71512
**cEltMkG6auQ** - Unexpected end of content while loading JObject. Path 'args', line 1, position 74353
**VJy8qZ77bpE** - Unexpected end of content while loading JObject. Path 'args', line 1, position 102055
**hjGrY4dKofI** - Unterminated string. Expected delimiter: ". Path 'args.player_response', line 1, position 47346
**huF4FWbAioY** - Unterminated string. Expected delimiter: ". Path 'args.player_response', line 1, position 85960

2. In some videos there are also no streams and there is no age restriction:
7Gzc-qQaB8g, AdCWZ7Z2hek, dAwP9Yk0Kv0, Q2vR21RrtbU 

3. Some Videos returns 403. YT Explode returns streams but can't download them (and also there is no age restriction)

There isn't much videos from 1st and 2nd point, but i am letting you to know. I am not sure how much videos returns 403 and dont want download.

**Comment by ac-lap** [comment]
I am also getting this 403 on bunch of videos, do let me know if anyone needs more example urls.

**Comment by MeteorBurn** [comment]
> Hey
> I found a couple of next videos with some errors. Maybe you could check this in next updates
> .
> 
> 1. I found some videos where no streams are returned but it throws exception with messages:
>    **_OTpbqtW5cY** - Unterminated string. Expected delimiter: ". Path 'args.player_response', line 1, position 64182
>    **FJYcURdWtMo** - Unterminated string. Expected delimiter: ". Path 'args.player_response', line 1, position 52815., lang: AR
>    **TWo3bkPNhuo** - Unterminated string. Expected delimiter: ". Path 'args.player_response', line 1, position 66670
>    **8OpY1fh8PmI** - Unexpected end of content while loading JObject. Path 'args', line 1, position 71512
>    **cEltMkG6auQ** - Unexpected end of content while loading JObject. Path 'args', line 1, position 74353
>    **VJy8qZ77bpE** - Unexpected end of content while loading JObject. Path 'args', line 1, position 102055
>    **hjGrY4dKofI** - Unterminated string. Expected delimiter: ". Path 'args.player_response', line 1, position 47346
>    **huF4FWbAioY** - Unterminated string. Expected delimiter: ". Path 'args.player_response', line 1, position 85960
> 2. In some videos there are also no streams and there is no age restriction:
>    7Gzc-qQaB8g, AdCWZ7Z2hek, dAwP9Yk0Kv0, Q2vR21RrtbU
> 3. Some Videos returns 403. YT Explode returns streams but can't download them (and also there is no age restriction)
> 
> There isn't much videos from 1st and 2nd point, but i am letting you to know. I am not sure how much videos returns 403 and dont want download.

cEltMkG6auQ - 403
VJy8qZ77bpE - 403
hjGrY4dKofI - 403
**The rest of the videos are OK!**

I think this is a problem with parameter parsing.
Because with Save From these videos can be downloaded, it link returns video page and not 403.

**Comment by booonzo** [comment]
How is your health @Tyrrrz ? I hope you don't have coronavirus...
Will you find some time this week ?

**Comment by booonzo** [comment]
> 
> 
> I am also getting this 403 on bunch of videos, do let me know if anyone needs more example urls.

send some examples

**Comment by HelgeStiemerling** [comment]
zO6UMuLr7t8

can't download (403), but 5 minutes later download ok

???

need list with 403? i have 80+

**Comment by booonzo** [comment]
@HelgeStiemerling Hej, i've also noticed that some videos which were undowloadable because of 403, later when i've checked i to was ok... hmm so sometimes it is 403 and sometimes is not on the same video ? Send please some examples of videos... i will also check.

**Comment by HelgeStiemerling** [comment]
@booonzo 
Hi, i have 2 zip-files: url_list_error_403.zip, here are a list of files with 403 error, in the file logging.zip is a logging file, here are in the top area 3 files with error 403, 17 minutes later the files are downloaded with no 403-error in the bottom area!
nobody know why

[logging.zip](https://github.com/Tyrrrz/YoutubeExplode/files/4419001/logging.zip)
[url_list_error_403.zip](https://github.com/Tyrrrz/YoutubeExplode/files/4419002/url_list_error_403.zip)

**Comment by HelgeStiemerling** [comment]
since this morning (3.4.2020) downloads works again

**Comment by mirushas** [comment]
@HelgeStiemerling not for me unfortunately. 
But all of my downloads fail and they don't suddenly succeed after a few min.

**Comment by HelgeStiemerling** [comment]
@mirushas OK, have you links for me?

**Comment by mirushas** [comment]
@HelgeStiemerling  Yes, sure

34FFj_60q1U
b2DDrgm-9LE
LdU_Do8wDgA

Do you need more?

**Comment by HelgeStiemerling** [comment]
@mirushas I can all 3 files download, but i download only the audiotrack with a combination with my own software and save it as mp3

**Comment by mirushas** [comment]
@HelgeStiemerling Thx for trying.

I also try to download only the audio using
 var streamInfoSet = await client.GetVideoMediaStreamInfosAsync(id);
 var streamInfo = streamInfoSet.Audio.OrderByDescending(s => s.Bitrate).First();

**Comment by HelgeStiemerling** [comment]
@mirushas the code is identical

**Comment by mirushas** [comment]
@HelgeStiemerling 
But when I use DownloadMediaStreamAsync(streamInfo, path) it just takes forever without doing anything or it instantly returnes 403. Do you have any suggestions? I'm using the newest version.

**Comment by HelgeStiemerling** [comment]
@mirushas without the complete code its difficult to say where is the error

**Comment by Tyrrrz** [comment]
It's likely that whether or not someone gets 401 is dependent on their geolocation.

**Comment by mirushas** [comment]
@HelgeStiemerling it's literally just the following:

var client = new YoutubeClient();
var id = YoutubeClient.ParseVideoId(url);
var streamInfoSet = await client.GetVideoMediaStreamInfosAsync(id);
var streamInfo = streamInfoSet.Audio .OrderByDescending(s => s.Bitrate) .First();
await client.DownloadMediaStreamAsync(streamInfo, path + fileName);

@Tyrrrz I'm from Germany and I can watch these videos on youtube or download them using other tools.

**Comment by HelgeStiemerling** [comment]
@mirushas I have see 1 difference:
var streamInfo = streamInfoSet.Audio.WithHighestBitrate();

**Comment by mirushas** [comment]
@HelgeStiemerling 
Oh, didn't know that this existed, but it's doing the same just with FirstOrDefault.

But I don't seem too get 403 anymore just endlessly stuck downloads.

**Comment by booonzo** [comment]
Soo @Tyrrrz will you try to fix this ?

**Comment by Tyrrrz** [comment]
Will try on the weekend.

**Comment by resulozlu** [comment]
We look forward to hearing from you.

**Comment by resulozlu** [comment]
> Will try on the weekend.

We look forward to hearing from you.

**Comment by MeteorBurn** [comment]
> > Will try on the weekend.
> 
> We look forward to hearing from you.

Don't annoy! Expect with patience. Nobody owes anything to anyone here.

**Comment by Tyrrrz** [comment]
Thanks @MeteorBurn

I've looked into it, I think I have an idea how to solve this. The issue is that to accommodate the changes, I have to rework some parts in the library. I have already started working on it, will hopefully finish it next week if I will have the time.

**Comment by HelgeStiemerling** [comment]
yesterday and today works, no 403! No changes!

**Comment by mirushas** [comment]
Yeah no 403, but sadly my downloads are still stuck endlessly
