### ISSUE TITLE
No sound in some videos

### ISSUE THREAD

**Issue by ValGuibs** [Tyrrrz/YoutubeExplode#350]
Hello everybody,

I would like your help on this great library.
I typed the code to take GetVideoMediaStreamInfosAsync.
When I check the variable (var.Muxed), I only have 1 video, only the video in 360p.
I also check (var.Video) and here, I have multiple videos, but all of them are without sound.

So when I call (var.Muxed.WithHighestVideoQuality()), I take the only video in 360p. I can't take other videos.

Do you have a solution please ?

**Comment by Tyrrrz** [comment]
Media streams come in 3 forms -- `Muxed` (video & audio), `Audio` (audio only) and `Video` (video only). Highest qualities are not available in muxed streams so you'll have to download separate streams and multiplex them yourself using tools like [ffmpeg](https://www.ffmpeg.org/).

You can also use [YoutubeExplode.Converter](https://github.com/Tyrrrz/YoutubeExplode.Converter) to take care of multiplexing for you.
