### ISSUE TITLE
Download fail

### ISSUE THREAD

**Issue by booonzo** [Tyrrrz/YoutubeExplode#352]
Hello guys!

Are you able to download this video: PMivT7MJ41M using 4.7.16 ?

**Comment by darianbenito** [comment]
+1

**Comment by mirushas** [comment]
+1 every download is failing.
31h ago everything worked fine.

**Comment by Tyrrrz** [comment]
Hey guys. Try using the previous version.

**Comment by mirushas** [comment]
Hey @Tyrrrz ,
I've already encounted this problem a few days ago, then I updated to the newest version this fixed the issue until 31h ago. Now it doesn't work with both versions.

**Comment by booonzo** [comment]
Hey. I confirmed that version 4.7.15 seem to work fine.

**Comment by uponatime2019** [comment]
I have to downgrade to 4.7.14

**Comment by Tyrrrz** [comment]
There seem to be videos that work with 4.7.15, some that work with 4.7.16, and some that work with neither.

Closing as duplicate of #349 as it's really the same issue. Open for help because I can't dedicate time to it in the near future because I'm ill.
