### ISSUE TITLE
Doesn't seem to work, it returns empty response

### ISSUE THREAD

**Issue by wesbyte** [Tyrrrz/YoutubeExplode#353]
GetVideoMediaStreamInfosAsync doesn't return any result, please advise.

**Comment by mrklintscher** [comment]
YouTube changed their deciphering method. We have to reengineer it.

**Comment by wesbyte** [comment]
@mrklintscher Thanks for this, any ideas when this could be done?

**Comment by Tyrrrz** [comment]
Working on it.
Duplicate of #333.
