### ISSUE TITLE
How do you get the number of videos in playlist?

### ISSUE THREAD

**Issue by jasonspar** [Tyrrrz/YoutubeExplode#356]
How can I get the total number of videos in a playlist?

client.Playlists.GetVideosAsync (id) doesn't seem to support ToListAsync ()

This is necessary because I want to set a max limit since some lists are huge.
If it's a reasonable number, then I show the list.

Can this be added to the Playlist metadata?
Something like this:

   Playlist pll = await client.Playlists.GetAsync (id);
   if (pll.Count > MAX_PCOUNT) {
     return (ERROR_TOO_MANY);
   }

**Comment by wesbyte** [comment]
@Tyrrrz  I updated my project with your latest NeGut, it doesn't seem to work with all the videos.

**Comment by Tyrrrz** [comment]
https://github.com/Tyrrrz/YoutubeExplode#working-with-playlists

Also [Ix.NET](https://www.nuget.org/packages/System.Interactive/) contains many extensions.
