### ISSUE TITLE
No way to try parse IDs from links

### ISSUE THREAD

**Issue by shaked6540** [Tyrrrz/YoutubeExplode#357]
The library used to provide ways to parse\TryParse ids from links, the ability was removed in version 5.

Is there a reason why this was removed? I'm talking specifically about the methods that used to be in YoutubeClient.Static (https://github.com/Tyrrrz/YoutubeExplode/pull/354/files#diff-91d17c9a613386db634fcac91ac4c745)

**Comment by Tyrrrz** [comment]
Hi.
These methods are no longer needed, you can provide both URLs or IDs interchangeably:

```csharp
var videoById = await youtube.Videos.GetAsync("bnsUkE8i0tU");

var videoByUrl = await youtube.Videos.GetAsync("https://youtube.com/watch?v=bnsUkE8i0tU");
```

**Comment by shaked6540** [comment]
I see, thanks. Although, in my use case I want to check if a url is a video\channel\playlist and is valid or not, and not immediately fetch information about it. I will just copy the static methods and use them in my project.

It might also be nice if you add the methods in a utility class, but that's up to you

**Comment by Tyrrrz** [comment]
I see, cool. You can also wrap the constructor in `try { ... } catch (ArgumentException) { }`. As long as it's not on critical path, performance difference should be negligible.
