### ISSUE TITLE
Youtube proxy addresses to download lots of videos

### ISSUE THREAD

**Issue by resulozlu** [Tyrrrz/YoutubeExplode#358]
Some videos are protected on YouTube after downloading. I want to use proxy for this, but I could not find a solution even though I tried many companies. Do you have a proxy address for suggestions that download a large number of videos and are not within limits?

**Comment by resulozlu** [comment]
public static HttpMessageHandler HttpMessageHandler()
{
            var result = new HttpClientHandler();
            var proxy = new WebProxy("http://173.232.7.15:xxxx")
             {
                            BypassProxyOnLocal = false,
                            UseDefaultCredentials = false
             };
            result = new HttpClientHandler
            {
                Proxy = proxy,
                UseProxy = true
            };
}

var httpClient = new HttpClient(handler: HttpMessageHandler(true), disposeHandler: true);
var client = new YoutubeClient(httpClient);

**Comment by Tyrrrz** [comment]
I don't have any recommendations

**Comment by resulozlu** [comment]
I noticed that my server did not download videos again what is the solution? Proxy ?

**Comment by Tyrrrz** [comment]
Depends on the reason

**Comment by resulozlu** [comment]
YouTube is blocking. when I switch to another server it gets better and it gets stuck again. youtube notices this

**Comment by Tyrrrz** [comment]
In that case yes, use as many proxies as possible.

**Comment by resulozlu** [comment]
There must be a problem with the proxy structure. I am entering the correct proxy address, but it does not work within the previously blocked server.

**Comment by resulozlu** [comment]
I can share the proxy addresses I have received with you.

**Comment by MeteorBurn** [comment]
> I noticed that my server did not download videos again what is the solution? Proxy ?

One more solution is add YouTube logged cookies to your custom http client.

Using cookies you can avoid 429 error and it is more trusted than proxy.

**Comment by resulozlu** [comment]
> > Sunucum tekrar video indirmedi fark ettim çözüm nedir? Proxy?
> 
> Bir çözüm daha, özel http istemcinize YouTube tarafından kaydedilen çerezleri eklemektir.
> 
> Çerezleri kullanarak 429 hatasını önleyebilirsiniz ve proxy'den daha güvenilirdir.

the problem is, youtube is blocked when you want to download multiple times to a single server and it fixes itself after the time has passed. Looks like which server we are requesting from

**Comment by resulozlu** [comment]
Failed to perform an HTTP request to YouTube because of rate limiting.
This error indicates that YouTube thinks there were too many requests made from this IP and considers it suspicious.
To resolve this error, please wait some time and try again -or- try injecting an HttpClient that has cookies for an authenticated user.
Unfortunately, there's nothing the library can do to work around this error.

Request: Method: GET, RequestUri: 'https://youtube.com/get_video_info?video_id=yezDEWako8U&el=embedded&eurl=https://youtube.googleapis.com/v/yezDEWako8U&hl=en&sts=', Version: 1.1, Content: <null>, Headers:
{
}

Response: StatusCode: 429, ReasonPhrase: 'unknown', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
 Alt-Svc: quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,h3-T050=":443"; ma=2592000
 Date: Thu, 23 Apr 2020 18:54:27 GMT
 Content-Length: 1103
 Content-Type: text/html; charset=UTF-8
}

> Bu durumda evet, mümkün olduğunca çok proxy kullanın.

**Comment by resulozlu** [comment]
> > I noticed that my server did not download videos again what is the solution? Proxy ?
> 
> One more solution is add YouTube logged cookies to your custom http client.
> 
> Using cookies you can avoid 429 error and it is more trusted than proxy.

Can you give me an example, a huge problem

**Comment by satish2832** [comment]
> > I noticed that my server did not download videos again what is the solution? Proxy ?
> 
> One more solution is add YouTube logged cookies to your custom http client.
> 
> Using cookies you can avoid 429 error and it is more trusted than proxy.

How to use this . can u describe ur solution pls

**Comment by Tyrrrz** [comment]
https://stackoverflow.com/questions/12373738/how-do-i-set-a-cookie-on-httpclients-httprequestmessage

You would presumably extract the cookies from an authenticated session.

**Comment by resulozlu** [comment]
> https://stackoverflow.com/questions/12373738/how-do-i-set-a-cookie-on-httpclients-httprequestmessage
> 
> You would presumably extract the cookies from an authenticated session.

I tried too much, but I couldn't. can you prepare us an example related to this?

**Comment by satish2832** [comment]
Yes, Please prepare some example

**Comment by Tyrrrz** [comment]
This question seems to have pivoted into "how to inject cookies" which appears to have been answered here: #376

**Comment by JohnWeisz** [comment]
It doesn't matter, you can't work around this from a single server, because YouTube has rate limiting. They are very well aware of scraping attempts, and everything that's unreasonably far beyond presumed normal use will be blocked.

The limit is very high in my experience not to affect normal users (e.g. you can play dozens of videos in parallel if you want), but it will quickly become a problem when scaling an automated scraper with an increasing number of users.

The limit is even higher with cookies, but still insufficient for robust scraping for many users on the same server.

**You need an extensive proxy network, there is no alternative.**

**Comment by tinazhe** [comment]
> > https://stackoverflow.com/questions/12373738/how-do-i-set-a-cookie-on-httpclients-httprequestmessage
> > You would presumably extract the cookies from an authenticated session.
> 
> I tried too much, but I couldn't. can you prepare us an example related to this?

did you find a solution on how to do it? set cookies on outgoing request

**Comment by RoyRobotnik** [comment]
[[](https://github.com/Tyrrrz/YoutubeExplode/issues/358#issuecomment-615857134)](url)
