### ISSUE TITLE
Package YoutubeExplode 5.0.1 is not compatible with uap10.0.10240

### ISSUE THREAD

**Issue by booonzo** [Tyrrrz/YoutubeExplode#359]
Hey,

I have this message when i trying to update to 5.0.1:
Error	NU1202	Package YoutubeExplode 5.0.1 is not compatible with uap10.0.10240 (UAP,Version=v10.0.10240). Package YoutubeExplode 5.0.1 supports:
  - net461 (.NETFramework,Version=v4.6.1)
  - netcoreapp3.0 (.NETCoreApp,Version=v3.0)
  - netstandard2.0 (.NETStandard,Version=v2.0)
  - netstandard2.1 (.NETStandard,Version=v2.1)

So the question is. Is there any way to use newes version (5.0.1) of YouTubeExplode with Targeting min version 10240 ? If no, then which minimal version is required ?

**Comment by Tyrrrz** [comment]
Minimal UAP version now is 10.0.16299

**Comment by booonzo** [comment]
So there isn't any way to still use min 10240 ? I am asking because i think there still can be much users below Fall Creators Update so i don't want to lose them. Do you have any global information/stats how many users using which version of windows ?

**Comment by Tyrrrz** [comment]
This was discussed in https://github.com/Tyrrrz/YoutubeExplode/issues/323 and nobody voted to keep the older frameworks.

**Comment by booonzo** [comment]
I see thanks. Anyway do you have any global information/stats how many users using which version of windows ?

**Comment by Tyrrrz** [comment]
Unfortunately, I don't. I don't develop UAP app.

**Comment by booonzo** [comment]
Understood, thanks.

**Comment by booonzo** [comment]
Hey btw.. one more question. Is there any informations how to use search engiene with new YTExplode ?

**Comment by Tyrrrz** [comment]
Yes, the same way as the playlists. It's in the readme.

**Comment by booonzo** [comment]
I see thanks... just two more questions :) Sory if those questions were already here.
1. Is search videos also working in previous versions ? 4.7.15 ?
2. Did you handle YouTube captcha somehow when using search queries ?

**Comment by Tyrrrz** [comment]
> Is search videos also working in previous versions ? 4.7.15 ?

Yes. It was a different API though.

> Did you handle YouTube captcha somehow when using search queries ?

No.

**Comment by booonzo** [comment]
@Tyrrrz is trending also working ?

**Comment by Tyrrrz** [comment]
No.
