### ISSUE TITLE
Some videos have deleted or moved streams

### ISSUE THREAD

**Issue by TheInsaneBro** [Tyrrrz/YoutubeExplode#36]
When using some specific videos I get a `System.Net.Http.HttpRequestException` comming from the `YoutubeClient.GetContentLengthAsync` method. More specifically the implemented `HttpService` throws because the http status code is 401.

Here are some example videos:
- [A2eRPIQ5B-k](https://www.youtube.com/watch?v=A2eRPIQ5B-k)
- [FygqyL-znrw](https://www.youtube.com/watch?v=FygqyL-znrw)
- [aqnPQXczisE](https://www.youtube.com/watch?v=aqnPQXczisE)
- [7dW1v7ov2Bk](https://www.youtube.com/watch?v=7dW1v7ov2Bk)
- [12Qjjsn_9PE](https://www.youtube.com/watch?v=12Qjjsn_9PE)
- [Fi1ltabZhqM](https://www.youtube.com/watch?v=Fi1ltabZhqM)
- [yYr-Lni3eco](https://www.youtube.com/watch?v=yYr-Lni3eco)

Haven't made out what's so special about them.

**Comment by Tyrrrz** [comment]
I get
Error 404 -> Video 1,2,4
Error 410 -> Video 3,5,6,7
Looks like some of the streams were deleted for whatever reason but the references still remain in the `get_video_info` API.
The only thing the videos seem to have in common is that they all have very few available qualities - either 144p and 240p or only 360p.

**Comment by Tyrrrz** [comment]
I really don't want to add try/catch blocks to the HTTP requests... Maybe we can just add a `IHttpService.PingAsync(string url)` and use it to see if the stream is alive?

**Comment by TheInsaneBro** [comment]
Actually, instead of using `response.EnsureSuccessStatusCode();` we can maually check if `response.IsSuccessStatusCode` and then act accordingly. I'd say just drop the stream (since it's not available anymore), but I haven't decided on what's the best implementation of this.

**Comment by Tyrrrz** [comment]
You mean like returning `null` from those methods if the code doesn't signify success? The problem is then `IHttpService` cannot guarantee all its implementation will follow that guideline. We can also just return `HttpResponse` to callers but I feel like it's an overkill, considering this is (so far) the only place where this would be needed. I think it's fine that they throw exceptions and then we can use `bool CheckSuccessAsync(string url)` only when we actually expect some url not to work (but still able to continue execution).

**Comment by TheInsaneBro** [comment]
I do belive we can't get arround a (specific) try-catch, since

1. As you said, we don't need to implement magic return values or out parameters
2. Thats the purpose of those exceptions, to handle exceptions

**Comment by Tyrrrz** [comment]
Where exactly and what exception are you suggesting to catch?

**Comment by TheInsaneBro** [comment]
Oh, I was wrong. I thought the http status code is in the exception data included.
When do you mean we should execute `bool CheckSuccessAsync(string url)`? Befor every time we execute `IHttpService.GetHeadersAsync`?

**Comment by Tyrrrz** [comment]
No, just for the streams I think

**Comment by TheInsaneBro** [comment]
That's what I mean, currently it's every time ^^ But now I see what you are going for. I think you are talking about the mixed stream for loop in it's whole.
Hm, could be possible to do so

**Comment by Tyrrrz** [comment]
Oh yeah, I meant inside that loop instead of inside GetHeadersAsync or GetContentLengthAsync

**Comment by TheInsaneBro** [comment]
But I'm still not sure about that exception design. I think there are many more error sources on some videos out there, we never can cover all posibilities. But when an error occured and from the `GetVideoInfoAsync(id)`-method just comes a `HttpRequestException` for example, I as library user would have no idea what to do to fix it. I think there should be at least a hint or something that's saying in which part of processing an error occured.

**Comment by Tyrrrz** [comment]
The thing is, if they are not using the default `HttpService` they might have a different exception and then `YoutubeClient` won't be able to handle it. :/

**Comment by Tyrrrz** [comment]
For example, if someone implements `WebClientHttpService : IHttpService` that uses `WebClient` instead of `HttpClient`, which would then throw `WebException` instead of `HttpRequestException`

**Comment by TheInsaneBro** [comment]
Wouldn't it become an inner exception anyways?

**Comment by Tyrrrz** [comment]
Hmm. I meant that doing this:
```c#
try
{
    long contentLength = await GetContentLengthAsync(url).ConfigureAwait(false);
}
catch (HttpRequestException)
{
}
```
...isn't really safe because there's no guarantee the supplied `_httpService` will actually throw that exact exception on failure.

**Comment by Tyrrrz** [comment]
Ok on the second thought, sending `CheckSuccessAsync` on every stream is probably a bad idea. It's going to significantly increase the time it takes to do `GetVideoInfoAsync`...
