### ISSUE TITLE
It would be great passing video info as parameter to YoutubeClient

### ISSUE THREAD

**Issue by nebmesemaou** [Tyrrrz/YoutubeExplode#360]
https://github.com/Tyrrrz/YoutubeExplode/blob/155bab29ba83bfe4b38b1a98c7bce5cc43046c90/YoutubeExplode/ReverseEngineering/Responses/VideoInfoResponse.cs#L127

We have a similar code just like yours and it's a bit hard for us to maintenance. Using it on our digital signage application.

In my experience: On server side, after some request, youtube block this url to get video info like 'too many requests'.

In our case we decided to get videoinfo from client side and pass to server then we've never get blocked.
I know there is a proxy solution here but not option for us.

**Comment by Tyrrrz** [comment]
Unfortunately it's not an option for this library since `VideoInfoResponse` is an implementation detail and is not surfaced to the user for good reason.
