### ISSUE TITLE
SearchClient can not work with cyrillic letters

### ISSUE THREAD

**Issue by KonstantinBobrosvki** [Tyrrrz/YoutubeExplode#362]
After calling the construction
`SearchClient search = YoutubeClient.Search;`
            
            var task = search.GetVideosAsync(name);
          
            var songs = task.BufferAsync(count).Result;

With english letters i receive some result, but it did not work with russian songs count is 0.

**Comment by MeteorBurn** [comment]
Did you try url encode?

**Comment by KonstantinBobrosvki** [comment]
I tried with "блог" and that doesnt work.I use my library in XamarinForms app. Maybe this is the reason?

**Comment by Tyrrrz** [comment]
I think the endpoints just don't work with non-ascii characters

**Comment by Tyrrrz** [comment]
This might have gotten fixed by the latest update.
