### ISSUE TITLE
Could not load type 'YoutubeExplode.YoutubeClient' from assembly 

### ISSUE THREAD

**Issue by ftppro** [Tyrrrz/YoutubeExplode#363]
I am using .NET Framework 4.6.1. I used NuGet to install YoutubeExplode. 
The following code compiles without error: 
```
private async void cmdDoIt_Click(object sender, EventArgs e)
	string sTest = "";
	var youtube = new YoutubeClient();
}

```
When I run the Windows Form App, and put a breakpoint on the line "string sTest", the following error is shown before the "var youtube" line is executed:
`System.TypeLoadException: 'Could not load type 'YoutubeExplode.YoutubeClient' from assembly 'YoutubeExplode, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.'
`
The error is thrown after I click the "DoIt" button. The error occurs in Form1.cs, on the line "Application.Run(new Form1());" .

Do I need to add any "using" commands, to use the "Downloading a video stream" sample code shown?

**Comment by Tyrrrz** [comment]
It looks like you're referencing YoutubeExplode v1.0.0 while it should be v5.0.1

**Comment by ftppro** [comment]
The problem was caused by naming my project "YoutubeExplode". When I created a new project with the namespace "YT_Explode" the error was not shown.

Is "using YoutubeExplode;" the only "using" command I need to add to use the "Downloading a video stream" sample code shown?

**Comment by Tyrrrz** [comment]
Probably also `using YoutubeExplode.Videos.Streams`, but you shouldn't worry too much as the IDE should suggest to add missing usings automatically.

**Comment by ftppro** [comment]
That is the fastest support I've ever received. You should work for Soundcloud.

For anyone else reading this, don't use YouTubeExtractor (a different library), it doesn't work. 

This library (YoutubeExplode) is great. Just don't name your project YoutubeExplode!

**Comment by Tyrrrz** [comment]
You're welcome :)
