### ISSUE TITLE
Channels.GetUploadsAsync doesn't fetch uploads that are added directly to a playlist

### ISSUE THREAD

**Issue by FlexXx1212** [Tyrrrz/YoutubeExplode#365]
So if i immediately add a Video to a playlist during Upload, the Channels.GetUploadsAsync(channelID) does not recognize the Video.
If you first upload it, and then add it to a playlist, it will recognize it.

I can get the video with Playlists.GetVideosAsync(playlistID) tho.
It would be a hassle to always check each Playlist, just to get the newest video of a channel.
I cant really show you an example, but i have 2 Videos uploaded, and only one video is listed in the Channels.GetUploadsAsync(channelID).

**Comment by FlexXx1212** [comment]
okey i figured out that you use the public Uploads playlist UU + rest of channelID.
and if i go to that URL using a non-logged in browser, i also only see the one video.
So its a problem with youtube. But sadly i cant work with that, so i have to rewrite some parts of YoutubeExplode in order to achieve always retrieving the newest video.
Because of course if you go to the channel and click on uploads, you can see the video perfectly fine

**Comment by Tyrrrz** [comment]
If that's how YouTube returns the data, unfortunately there's not much we can do.
