### ISSUE TITLE
StreamsClient.Videos.Streams.GetManifestAsync method too slow

### ISSUE THREAD

**Issue by satish2832** [Tyrrrz/YoutubeExplode#366]

**Comment by KonstantinBobrosvki** [comment]
The method is working but with speed about 16s.

**Comment by Tyrrrz** [comment]
That sounds abnormal.
Can you use Fiddler or something to see which request takes so long?

**Comment by KonstantinBobrosvki** [comment]
> 
> 
> That sounds abnormal.
> Can you use Fiddler or something to see which request takes so long?

https://github.com/KonstantinBobrosvki/PirateMusic/commit/7f5d5074bfd55c056ab1d3019aa67d126b753ad4    . In YoutubeMusicProvider Method called  GetSongs

**Comment by satish2832** [comment]
It's working fine now, Not sure the exact reason. But I initialized the YoutubeClient object within the method body Before it was at the global level and within the constructor.
It's returning the results with 1 or 2 sec only now.

**Comment by Tyrrrz** [comment]
If you're having issues with performance, please inspect HTTP traffic and see which requests takes the longest.
