### ISSUE TITLE
can i know where is the new deciper method 

### ISSUE THREAD

**Issue by developerss** [Tyrrrz/YoutubeExplode#367]
i searched hole project but still can not find the method

**Comment by Tyrrrz** [comment]
https://github.com/Tyrrrz/YoutubeExplode/blob/edc45969b6e2227b3b9749183f1d8a9594fb5bcc/YoutubeExplode/ReverseEngineering/Responses/PlayerSource.cs#L22

**Comment by developerss** [comment]
you made the project is very complex a simple thing .
