### ISSUE TITLE
youtube.Playlists.GetVideosAsync(playlist.Id) is not enumerable

### ISSUE THREAD

**Issue by mon3104** [Tyrrrz/YoutubeExplode#370]
using Demo code:

Type 'System.Collections.Generic.IAsyncEnumerable<YoutubeExplode.Videos.Video>' is not enumerable.

**Comment by Tyrrrz** [comment]
Don't forget `await`

**Comment by mon3104** [comment]
still won't compile.

I used the same exact code from "Home page". Won't compile.

setting await gives 'Cannot resolve symbol 'GetAwaiter'.

**Comment by Tyrrrz** [comment]
It works.
Make sure you have `using YoutubeExplode` and your project is targetting C# 8

**Comment by mon3104** [comment]
Thanks for the heads up. However I'm building a WInForm application (which from what I read) only support up to C# 7.3. There seems to be a work around by modifing the .csproj file however I can't seem to have this working.

Any idea how to solve?

**Comment by mon3104** [comment]
Thanks. I'm using .net FrameWork, therefore I have to convert to .net Core 3.x in order to use C#8.

**Comment by Tyrrrz** [comment]
Just put `<LangVersion>latest</LangVersion>` in your project file

**Comment by mon3104** [comment]
again.. thank you.
