### ISSUE TITLE
"Playlist response is broken."

### ISSUE THREAD

**Issue by tmontney** [Tyrrrz/YoutubeExplode#371]
Tried query "Bush Machine Head". Same query can sometimes fail.

```
Dim ytc As New YoutubeExplode.YoutubeClient
Dim results = ytc.Search.GetVideosAsync(searchQuery)
results.GetAwaiter().OnCompleted(Sub()
      Try
            Dim js As New JavaScriptSerializer
            IO.File.WriteAllText(queryPath, js.Serialize(results.GetAwaiter().GetResult()))
       Catch ex As Exception                                                                       
       End Try
End Sub)
```

The performance is also much slower than I expected. One query can take ~20 seconds to complete (success or failure).

**Comment by Tyrrrz** [comment]
Is the error consistent?

> One query can take ~20 seconds to complete (success or failure).

If you're getting all videos in a playlist, the performance will depend on the number of videos.

**Comment by tmontney** [comment]
Sorry, I missed your response. I moved on to another section of this project that didn't involve YouTube.

It happens with individual videos, seems consistent. I'll try testing it again.
