### ISSUE TITLE
Add synchronous methods

### ISSUE THREAD

**Issue by tmontney** [Tyrrrz/YoutubeExplode#372]
For instance, the search function only offers async. This doesn't work well when offering it through a REST server. It forces design to be more complicated. If forced to use async, the query system must be like a job processor: POST to create the job and send an ID, and then periodically query the GET route to see if it's done. A really efficient system, web push would have to be added (making it even more complicated).

The official YouTube API offers sync and async: https://developers.google.com/youtube/v3/docs/search/list#parameters

**Comment by maxkatz6** [comment]
I am not author of the library, but have some thought.

> This doesn't work well when offering it through a REST server
Why REST server doesn't work well with async?

> It forces design to be more complicated. If forced to use async
HTTP requests are async IO operations, so they **should** by async.

By the way, I understand benefits of Job-like system. And with current YoutubeExplode implementation you can use that like job system with starting task and checking IsComplete. Of course it will not use special YouTube api.

**Comment by Tyrrrz** [comment]
The underlying transport protocol (HTTP) is asynchronous by nature so the whole library is asynchronous too as a result. There's no point in adding a synchronous layer that would just wrap the asynchronous API (you can do that yourself anyway).

> This doesn't work well when offering it through a REST server. It forces design to be more complicated. If forced to use async, the query system must be like a job processor: POST to create the job and send an ID, and then periodically query the GET route to see if it's done.

No, you literally just use `async`/`await`. It's not 2010's anymore.

**Comment by tmontney** [comment]
> Why REST server doesn't work well with async?
The REST server itself is indeed async, but it's the HTTP portion that needs to be synchronous. I cannot respond to a request I have not finished.
> HTTP requests are async IO operations, so they **should** by async.
The parts that matter are. There's no difference between telling the client the job failed versus throwing an upstream timeout error while the client waits. The former is just more complicated, and unnecessary.

**Comment by tmontney** [comment]
> The underlying transport protocol (HTTP) is asynchronous by nature so the whole library is asynchronous too as a result. There's no point in adding a synchronous layer that would just wrap the asynchronous API (you can do that yourself anyway).

This isn't something that impedes the entire server from accepting simultaneous requests.

> No, you literally just use `async`/`await`. It's not 2010's anymore.

Just because it's 2020 doesn't imply everything must be async. Disappointing.

**Comment by Tyrrrz** [comment]
> ...but it's the HTTP portion that needs to be synchronous. I cannot respond to a request I have not finished.

This is just false. Example: https://docs.microsoft.com/en-us/aspnet/core/web-api/action-return-types?view=aspnetcore-3.1#asynchronous-action

> The parts that matter are. There's no difference between telling the client the job failed versus throwing an upstream timeout error while the client waits. The former is just more complicated, and unnecessary.

There are no jobs involved. Just promises (tasks in .NET) that the language natively supports.

> This isn't something that impedes the entire server from accepting simultaneous requests.

Not sure what's the point here.

> Just because it's 2020 doesn't imply everything must be async. Disappointing.

It doesn't imply that. But just because it's 2020, it implies that people shouldn't be expressing inherently async operations using synchronous paradigms.

**Comment by tmontney** [comment]
> This is just false. Example: https://docs.microsoft.com/en-us/aspnet/core/web-api/action-return-types?view=aspnetcore-3.1#asynchronous-action

That is what I am currently doing and what I am annoyed by. Rather than holding the request in memory, I must now store it somewhere for later retrieval. The endpoint must also periodically query until told it is done or failed.

> The parts that matter are. There's no difference between telling the client the job failed versus throwing an upstream timeout error while the client waits. The former is just more complicated, and unnecessary.

> Not sure what's the point here.

I think we're having a disconnect between design and technical concepts. Really, I want the functionality of using await. I'm aware of how to use await, but would require a decent amount of rework on my end (so I wanted to fallback to blocking commands). Perhaps it won't be as big of deal as it appears.

**Comment by Tyrrrz** [comment]
> That is what I am currently doing and what I am annoyed by. Rather than holding the request in memory, I must now store it somewhere for later retrieval. The endpoint must also periodically query until told it is done or failed. This complicates things for no benefit.

That's also not true. There is no "periodic querying". Where did you get that idea from?

> I think we're having a disconnect between design and technical concepts. Really, I want the functionality of using await. I'm aware of how to use await, but would require a decent amount of rework on my end (so I wanted to fallback to blocking commands). Perhaps it won't be as big of deal as it appears.

If you really want it to be blocking, you can call `SomeMethodAsync().GetAwaiter().GetResult()`.

**Comment by tmontney** [comment]
> That's also not true. There is no "periodic querying". Where did you get that idea from?

If it's non-blocking, you must send a response. Once that response is consumed, you can't respond to it again.

> If you really want it to be blocking, you can call `SomeMethodAsync().GetAwaiter().GetResult()`.

I had tried that but didn't appear to block (note #371). I'll try it again and see.

**Comment by Tyrrrz** [comment]
> If it's non-blocking, you must send a response. Once that response is consumed, you can't respond to it again.

First of all, that doesn't answer the question of why you think there is periodic querying. Second of all, HTTP is asynchronous, there's no blocking. When you get a request there's not necessarily a dedicated thread serving that response, there may very well be just a single thread. Once the response is ready, you just send the corresponding packet via the open connection. Because HTTP is inherently asynchronous, using the non-blocking approach is actually more efficient because it can re-use idle threads. In C# and most modern languages, you don't have to worry about that yourself, you just write `await` and the compiler generates the state machine for you. And web frameworks such as ASP.NET Core fully support asynchronous controller actions (as shown in the example).

> I had tried that but didn't appear to block (note #371). I'll try it again and see.

That retries an `IAsyncEnumerable`. You would need to do `GetVideosAsync().BufferAsync().GetAwaiter().GetResult()` if you really want to block on it.

> I realize this is trending towards being outside the project's scope. I don't wish to muddy this section unless you wish to continue.

We can stop now.
