### ISSUE TITLE
ValidUntil property is missing from StreamManifest

### ISSUE THREAD

**Issue by XFox111** [Tyrrrz/YoutubeExplode#374]
It's quite a useful info which helps me automatically renew links when the old ones are expired. The property is presented in `MediaStreamInfoSet` before v5 but not presented in `StreamManifest` in v5

**Comment by Tyrrrz** [comment]
I found that the value was always the same and the manifest expired in 6 hours. You can safely hardcode it to 5 hours 40 mins or something like that.

**Comment by XFox111** [comment]
Ok, I see. But I think it will be better if you add it like a constant or a default value.

**Comment by alexrainman** [comment]
Use expire query string variable (6 hours) in the streamInfo url.

**Comment by Tyrrrz** [comment]
Going to descope this one also as I want a minimal API surface to reduce exposure to breaking changes. The fewer things we need to extract from the stream manifest, the easier it is to maneuver and introduce workarounds for specific video types.

For now, the recommendation is to use 6 hours as it's unlikely to change or parse the value from the URL like @alexrainman said.
