### ISSUE TITLE
C# MVC 5 takes forever to load

### ISSUE THREAD

**Issue by leetkrew** [Tyrrrz/YoutubeExplode#379]
here's my code sample. 
am I missing something? thanks

`
        public ActionResult Test()
        {
            var t = GetTitleAsync();
            return Content(t.Result);
        }

        public async System.Threading.Tasks.Task<string> GetTitleAsync()
        {
            var ytClient = new YoutubeExplode.YoutubeClient();
            var vid = await ytClient.Videos.GetAsync("https://youtube.com/watch?v=bnsUkE8i0tU");
            return vid.Url;
        }

        public ActionResult Test2()
        {
            HttpClient hClient = new HttpClient();
            var ytClient = new YoutubeExplode.YoutubeClient(hClient);
            var vid = ytClient.Videos.GetAsync("https://youtube.com/watch?v=bnsUkE8i0tU");
            return Content(vid.Result.Title);
        }

        public ActionResult Test3()
        {
            var ytClient = new YoutubeExplode.YoutubeClient();
            var vid = ytClient.Videos.GetAsync("https://youtube.com/watch?v=bnsUkE8i0tU");
            return Content(vid.Result.Title);
        }`

**Comment by Tyrrrz** [comment]
For starters, you should be using `async`/`await` and probably avoid MVC 5 altogether.

Does it work fine in a console application?

**Comment by leetkrew** [comment]
it works fine with a console application.
yes, I also tried async / await

**Comment by Tyrrrz** [comment]
No idea then. Try profiling and see what is taking so long.

**Comment by leetkrew** [comment]
finally it works with this method
`public ActionResult Test4()
        {
            var ytClient = new YoutubeExplode.YoutubeClient();
            var exResult = Task.Run(async ()=>
                await ytClient.Videos.GetAsync("https://youtube.com/watch?v=bnsUkE8i0tU")
            ).Result;

            return Json(exResult, JsonRequestBehavior.AllowGet);
        }`
