### ISSUE TITLE
Occasionally GetVideoInfoAsync throws "Could not get video context"

### ISSUE THREAD

**Issue by Tyrrrz** [Tyrrrz/YoutubeExplode#38]
Seems to be random and very rare. I wonder what's going on.

**Comment by SlowLogicBoy** [comment]
I noticed that too, however I wasn't able to catch on which videos and why yet.

**Comment by Tyrrrz** [comment]
Just set a breakpoint on the exception and started querying video infos in an endless loop. Came back from lunch to check what's wrong. Looks like it can't extract the player version.
https://pastebin.com/V71jRCYx <- here's the HTML of the /embed/ watch page.
Youtube basically shows an error and suggests to watch the video on its full watch page. We use the embed watch page because it circumvents age-restrictions and other blocks.

**Comment by Tyrrrz** [comment]
The actual player version doesn't seem to be there when the error happens.

**Comment by Tyrrrz** [comment]
One solution I see is to keep refreshing the page until it doesn't show an error (the error seems to be rare anyway) or until it hits an internal limit of retries (like 10 or something).
@TheInsaneBro do you have any input on this?

**Comment by TheInsaneBro** [comment]
Uhm, yeah. I once had a parse exception on like three videos. I don't really know why, but when I wanted to create an issue, the error was no more in these video ids. Sounds quite similar, however it hasn't said anything about the video context if I remember correctly.

**Comment by Tyrrrz** [comment]
Hmm. I hope it's the same error.
I'll "fix" it by requesting the page a few times before giving up, then run the endless loop again and see how it holds up.

**Comment by Tyrrrz** [comment]
Ok it works fine. It never exceeds two retries and the retries seem to occur about once in 20 requests.
