### ISSUE TITLE
System.ArgumentException: 'Unrecognized video quality label '360s'.

### ISSUE THREAD

**Issue by ALSULTAN** [Tyrrrz/YoutubeExplode#382]
public static VideoQuality GetVideoQuality(string label)
        {
            if (label.StartsWith("144p", StringComparison.OrdinalIgnoreCase))
                return VideoQuality.Low144;
            if (label.StartsWith("240p", StringComparison.OrdinalIgnoreCase))
                return VideoQuality.Low240;
            if (label.StartsWith("360p", StringComparison.OrdinalIgnoreCase))
                return VideoQuality.Medium360;
            if (label.StartsWith("480p", StringComparison.OrdinalIgnoreCase))
                return VideoQuality.Medium480;
            if (label.StartsWith("720p", StringComparison.OrdinalIgnoreCase))
                return VideoQuality.High720;
            if (label.StartsWith("1080p", StringComparison.OrdinalIgnoreCase))
                return VideoQuality.High1080;
            if (label.StartsWith("1440p", StringComparison.OrdinalIgnoreCase))
                return VideoQuality.High1440;
            if (label.StartsWith("2160p", StringComparison.OrdinalIgnoreCase))
                return VideoQuality.High2160;
            if (label.StartsWith("2880p", StringComparison.OrdinalIgnoreCase))
                return VideoQuality.High2880;
            if (label.StartsWith("3072p", StringComparison.OrdinalIgnoreCase))
                return VideoQuality.High3072;
            if (label.StartsWith("4320p", StringComparison.OrdinalIgnoreCase))
                return VideoQuality.High4320;
            // Unrecognized
            throw new ArgumentException($"Unrecognized video quality label '{label}'.", nameof(label));
        }

**Comment by ALSULTAN** [comment]
360s unknown

**Comment by ALSULTAN** [comment]
also 2160s

**Comment by Tyrrrz** [comment]
Hm, is that new? What videos did you find that on?

**Comment by Hexer10** [comment]
It is for the 360 videos ie where you can rotate the device, such as https://youtu.be/-xNN-bJQ4vI

**Comment by ALSULTAN** [comment]
Thanks man, it is fixed :)
