### ISSUE TITLE
Receiving an error from nuget: "dotnet" Unknown command

### ISSUE THREAD

**Issue by glen4cindy** [Tyrrrz/YoutubeExplode#384]
I'm sure I am leaving a step out but the error I am receiving from NuGet is that "dotnet" is an unknown command.

I would appreciate some direction to show me where I am going wrong.

Thanks in advance.

**Comment by Tyrrrz** [comment]
Do you have .NET Core SDK installed?

**Comment by glen4cindy** [comment]
Thanks for your reply.

I was apparently missing the SDK. The install ran and didn't say it was already installed.

The other issue is I was issuing the command incorrectly. I was typing "nuget dotnet add package........"

I left off the nuget and it tries to run now but cannot find the package:


**Downloads>dotnet add package YoutubeExplode
Could not find any project in `C:\Users\Trainer 1\Downloads\`.
Usage: dotnet add <PROJECT> package [options] <PACKAGE_NAME>

Arguments:
  <PROJECT>        The project file to operate on. If a file is not specified, the command will search the current directory for one.
  <PACKAGE_NAME>   The package reference to add.

Options:
  -h, --help                          Show command line help.
  -v, --version <VERSION>             The version of the package to add.
  -f, --framework <FRAMEWORK>         Add the reference only when targeting a specific framework.
  -n, --no-restore                    Add the reference without performing restore preview and compatibility check.
  -s, --source <SOURCE>               The NuGet package source to use during the restore.
  --package-directory <PACKAGE_DIR>   The directory to restore packages to.
  --interactive                       Allows the command to stop and wait for user input or action (for example to complete authentication).

C:\Users\Trainer 1\Downloads>**

I have the youtubeexplode.5.0.5.nupkg in the download directory and am running this command in an elevated command prompt window.

Thanks for getting me a step closer.

**Comment by Tyrrrz** [comment]
You need to do that in a directory which contains your `csproj` file. If you don't have one, you need to create a project first, either through your IDE or via `dotnet new console -o MyProject` (for example).

**Comment by glen4cindy** [comment]
Ok. 

I must be missing something. I do not have an IDE or console.

There is a development SDK that I should have downloaded?

**Comment by Tyrrrz** [comment]
Ok, can we backtrack a bit. What is it you're trying to do? Do you want to build an app that uses YoutubeExplode?

**Comment by Tyrrrz** [comment]
This is a library that you would use in a programming project. Maybe you want an app that downloads videos instead? In that case this is probably what you need: https://github.com/Tyrrrz/YoutubeDownloader

**Comment by glen4cindy** [comment]
Ok. Sorry. I'm enjoying your other app, YouTube Downloader.

I saw this and had an interest in trying to use it to pull closed caption streams from YouTube videos.

I'm not really trying to build an app. From the screenshots, I thought this was an app already.

**Comment by Tyrrrz** [comment]
Ah. The screenshots are from a demo project inside of the repository. If you already have the .NET Core SDK, you can go to `YoutubeExplode.DemoWpf` and type `dotnet run`.

**Comment by glen4cindy** [comment]
Ok. Thanks for all your attention.

The downloader is awesome.

I'm going to have to buy you a coffee. I've been paying a yearly fee for an app that does this.

I never knew there was something on GitHub. I wouldn't be surprised if they didn't get the code for their app right here.

Thanks again.

**Comment by Tyrrrz** [comment]
>  I've been paying a yearly fee for an app that does this.

My condolences :joy:

Thanks!
