### ISSUE TITLE
Search specify max number of pages

### ISSUE THREAD

**Issue by marf** [Tyrrrz/YoutubeExplode#385]
Hello,
in the previous versions, there was an option to specify the max number of pages that we want in the search, while in this version there is not this option.

Can we add it again, please?

Thank you,
Marco

**Comment by Tyrrrz** [comment]
The concept of pages is gone now, but you can iterate over the videos and just get the portion that you need.

**Comment by marf** [comment]
The problem is that now it takes more time because it is searching through all the pages, isn't there a way to limit the results?

**Comment by Tyrrrz** [comment]
https://github.com/Tyrrrz/YoutubeExplode#working-with-playlists

```csharp
// Enumerate through playlist videos
await foreach (var video in youtube.Playlists.GetVideosAsync(playlist.Id))
{
    var videoTitle = video.Title;
    var videoAuthor = video.Author;
}
```

**Comment by marf** [comment]
Thank you, I adapted it to the YouTube search without playlists and it seems to work.
I thought that it was valid only for search inside playlists and not also on the normal search on YouTube.

**Comment by Tyrrrz** [comment]
Yeah, they work the same.
