### ISSUE TITLE
Limit how many page should be loaded upon search

### ISSUE THREAD

**Issue by PoLaKoSz** [Tyrrrz/YoutubeExplode#389]
Lets assume this scenario:
- YouTube currently returns 20 results/page
- i hard code `.BufferAsync(20)` to my code

Two weeks later:
- YouTube decide to return only 15 results/page
- i forgot to check this library so the library will do 2 requests which will return 30 results but i only be able to access the 20 results.
or
- YouTube decide to return 25 results/page
- i forgot to check this library so the library will return 25 results but i only be able to access the 20 results.

I assume that the YouTube search results are ordered by relevance. Probably i only need the first 4-5 video, but the library already sent one request why not save the remaining results too? (This is my opinion).

What about this?
```c#
namespace YoutubeExplode.Search
{
    public class SearchClient
    {
        [Obsolete("Will be removed in the next major release (6.0)! Please use For() method instead.", false)]
        public async IAsyncEnumerable<Video> GetVideosAsync(string searchQuery) { ... }

        public SearchRequest For(string searchQuery) => new SearchRequest(_httpClient, searchQuery);
    }

    public class SearchRequest
    {
        private readonly YoutubeHttpClient _httpClient;
        private readonly string _searchQuery;

        public SearchResult(_httpClient, string searchQuery)

        public async IAsyncEnumerable<Video> GetVideosAsync() { ... }

        public async Task<IReadOnlyList<Video>> GetVideosAsyncAt(int pageNumber)
        {
            var response = await PlaylistResponse.GetSearchResultsAsync(_httpClient, searchQuery, page);

            ...
        }
    }
}
```
```c#
YoutubeClient youtube = new YoutubeClient();
SearchRequest searchRequest = youtube.Search.For("Tyrrrz");
IAsyncEnumerable<Video> allResults = searchRequest.GetVideosAsync();
IReadOnlyList<Video> only30Results = searchRequest.GetVideosAsync().BufferAsync(30);
IReadOnlyList<Video> resultsAtFirstPage = searchRequest.GetVideosAsyncAt(pageNumber: 1);
```

_**Code sample just a pseudocode**_

**Comment by PoLaKoSz** [comment]
If You have time @Tyrrrz, can You give me some feedback on this because i would like to implement it.

**Comment by Tyrrrz** [comment]
I would probably just add an overload to `GetVideosAsync` with parameters that allow the user to specify starting page and maximum pages. Maybe then `BufferAsync` will become unnecessary and we can suggest people to install `system.interactive.async` instead.

It has to be pointed out that pages are implementation-specific so relying on them is not recommended and it's not unlikely that there might be a breaking change between non-major versions there.

**Comment by PoLaKoSz** [comment]
Is this method signature good?
``` c#
Task<IReadOnlyList<Video>> GetVideosAsync(string searchQuery, int startingPage, int maximumPage = int.MaxValue)
```
or be consistent and return `IAsyncEnumerable<Video>`?

**Comment by Tyrrrz** [comment]
Keep `IAsyncEnumerable` because the user might still not want to go through all pages anyway.

**Comment by Beblia** [comment]
Good day. It would be an awesome addition to have the GetVideosAsync return certain amount of results by maybe passing it an interger. So 10 would give back 10 results, and if it would also have a auto load 10 more on command. What im trying to do is auto load some videos initially and as the user scrolls down it would keep loading the the amount I want so 10 videos. Can you please add this feature? Currently for some search results Im getting back 500+ results. This causes the load time to be slow. Would like to start at 10 or 20 results and then add more as the user scrolls. Thanks.

**Comment by Tyrrrz** [comment]
@Beblia this feature already exists in a way. You want to use the `IAsyncEnumerable<Video>` to progressively load videos.

**Comment by Beblia** [comment]
Thank you.
