### ISSUE TITLE
Can't build on Visual Studio 2013

### ISSUE THREAD

**Issue by dev45** [Tyrrrz/YoutubeExplode#39]
Hi Men! I hav a problem with source code.

when i try to compile, It give me this error [Image (http://imgur.com/a/eAyvM)]()

i'm using visual studio 2013 with .net 4.5

can you help me? please!

**Comment by Tyrrrz** [comment]
You need Visual Studio 2017 to build it, because it uses the .NET core csproj format.

**Comment by dev45** [comment]
So i can't rebuild it in 2013 in another way?
