### ISSUE TITLE
How could you find the search_ajax link? and how sort it video?

### ISSUE THREAD

**Issue by isinstance** [Tyrrrz/YoutubeExplode#395]
In PlaylistResponse class, line 136, there is a link like this.

> https://youtube.com/search_ajax?style=json&search_query={queryEncoded}&page={page}&hl=en

How could you find or get this link? I was inspired by this code while I was building a YouTube parser.

**Comment by isinstance** [comment]
And this json search is sorted differently than a normal YouTube search. The video that usually appears first is the 8th to 10th. How it does work?

**Comment by 64km** [comment]
Buenas:
sigue funcionando ese enlace?

https://youtube.com/search_ajax?style=json&search_query={queryEncoded}&page={page}&hl=en
