### ISSUE TITLE
Description not working correctly when using client.Search.GetVideosAsync

### ISSUE THREAD

**Issue by Afy65** [Tyrrrz/YoutubeExplode#399]
When using the following code:

                    YoutubeClient client = new YoutubeClient();
                    var youTubeVideos= await client.Search.GetVideosAsync(TextBoxSearchYoutubeTxt.Text.Trim()).BufferAsync(100);

                    foreach (var youTubeVideo in youTubeVideos) {
                        Video video = new Video();
                        video.VideoName = youTubeVideo.Title;
                        video.VideoUploadedDate = youTubeVideo.UploadDate.DateTime;
                        video.VideoKey = youTubeVideo.Id;
                        video.VideoThumbnailPath = youTubeVideo.Thumbnails.StandardResUrl;
                        video.VideoDescription = youTubeVideo.Description;
                        Video.Videos.Add(video);
                    }

youTubeVideo.Description; is not correct - does not give the whole description and shows special character codes and description seems to stop at the first nbsp; ?

Thanks for the great work so far  - love it :)

Daniel :)

**Comment by Tyrrrz** [comment]
Yeah it's a known issue. For some reason that endpoint only returns truncated description.

**Comment by Afy65** [comment]
Hi is this gonna be fixable or is it just one of those things

Kind regards

Daniel

**Comment by Tyrrrz** [comment]
Probably the latter...

**Comment by Tyrrrz** [comment]
Looks like this was fixed when we changed to a new endpoint in #502
We did lose a lot of other data in the process though 😅
