### ISSUE TITLE
Video is unavailable

### ISSUE THREAD

**Issue by AbbasBHF** [Tyrrrz/YoutubeExplode#400]
Video 'nd0y_iiajns' is unavailable.
In most cases, this error indicates that the video doesn't exist, is private, or has been taken down.
If you can however open this video in your browser in incognito mode, it most likely means that YouTube changed something, which broke this library.
Please report this issue on GitHub in that case.

I tried many videos, but for all of them, I get this exception.

**Comment by PoLaKoSz** [comment]
I opened the video from Brave browser from a hungarian IP and the video unavailable for me too.

**Comment by Tyrrrz** [comment]
Reminds me of #34.
Are you sure it's not the same problem? :)
