### ISSUE TITLE
Playlist downloading same video or audio

### ISSUE THREAD

**Issue by Eavileswayce** [Tyrrrz/YoutubeExplode#401]
I'm new to GitHub so sorry if this is the wrong place to post this but I haven't changed any of my code and now the playlists don't work. 
It goes through the playlist and gets every video normally, but it downloads the same thing for each video/audio.
The titles are different so that works yet the audio is just the same for each.

**Comment by Tyrrrz** [comment]
Can you post the code?

**Comment by Eavileswayce** [comment]
Yeah, apologies that the code is probably incredibly inefficient and messy, it's the first program I have written.

`public async Task DownloadPlaylistAudio(string link, string name)
        {
            token = tokenSource.Token;

            var youtube = new YoutubeClient();
            var converter = new YoutubeConverter(youtube);
            var playlist = await youtube.Playlists.GetAsync(link);

            // Get Playlist Metadata
            var title = playlist.Title;
            var author = playlist.Author;

            // Enumerate Through Playlist Videos
            await foreach (var video in youtube.Playlists.GetVideosAsync(playlist.Id))
            {
                // Get Playlist
                var videoID = video.Id;
                var streamManifest = await youtube.Videos.Streams.GetManifestAsync(videoID).ConfigureAwait(true);
                var videoTitle = video.Title;

                // Gets Audio
                var playlistAudio = streamManifest.GetAudioOnly().WithHighestBitrate();

                // Progress Bar
                var progress = new Progress<double>(percent =>
                {
                    progressBarPlaylist.Value = Convert.ToInt32(percent * 100.00f);
                });

                playlistTitle.Text = ("Playlist Title: " + title);
                playlistAuthor.Text = ("Playlist Author: " + author);
                playlistVideoTitle.Text = ("Downloading File: " + videoTitle);

                if (folderName.Text == "")
                {
                    await converter.DownloadVideoAsync(link, $"{playlistFolderPath + @"\" + video.Title.Replace("\"", "'").Replace("\\", "").Replace("/", "").Replace(":", "").Replace("*", "").Replace("?", "").Replace("<", "").Replace(">", "").Replace("|", "")}.mp3", "mp3", progress, token);
                }
                else
                {
                    System.IO.Directory.CreateDirectory(playlistFolderPath + @"\" + folderName.Text);
                    await converter.DownloadVideoAsync(link, $"{playlistFolderPath + @"\" + folderName.Text + @"\" + video.Title.Replace("\"", "'").Replace("\\", "").Replace("/", "").Replace(":", "").Replace("*", "").Replace("?", "").Replace("<", "").Replace(">", "").Replace("|", "")}.mp3", "mp3", progress, token);
                }
            }

            downloadPlaylist.Enabled = true;
            folderName.Enabled = false;
            playlistStatus.Text = ("Task Completed.");
            System.Media.SystemSounds.Beep.Play();
            MessageBox.Show("Task Completed", "YouTube Downloader", MessageBoxButtons.OK, MessageBoxIcon.Information);
            playlistLink.Text = "";
            folderName.Text = "";
        }`

**Comment by Tyrrrz** [comment]
You're getting `playlistAudio` but are not actually using it anywhere.

Here:

```csharp
await converter.DownloadVideoAsync(link, $"{playlistFolderPath + @"\" + video.Title.Replace("\"", "'").Replace("\\", "").Replace("/", "").Replace(":", "").Replace("*", "").Replace("?", "").Replace("<", "").Replace(">", "").Replace("|", "")}.mp3", "mp3", progress, token);
```

You're just downloading the original link, which also contains ID of the first video inside of it, so you're essentially downloading the same video every time.

**Comment by Eavileswayce** [comment]
But if I put that variable inside the await like this:

`await converter.DownloadVideoAsync(playlistAudio, $"{playlistFolderPath + @"\" + video.Title.Replace("\"", "'").Replace("\\", "").Replace("/", "").Replace(":", "").Replace("*", "").Replace("?", "").Replace("<", "").Replace(">", "").Replace("|", "")}.mp3", "mp3", progress, token);`

I get a few errors saying cannot convert from 'YouTubeExplode.Videos.Streams.IStreamInfo' to 'YouTubeExplode.Videos.Streams.StreamManifest'

**Comment by Tyrrrz** [comment]
Replacing with `videoID` should work, but then you don't need the `playlistAudio` at all.
If you want to use that however, you will need to use the approach described in this example: https://github.com/Tyrrrz/YoutubeExplode.Converter#download-and-mux-specific-streams

**Comment by Eavileswayce** [comment]
Yeah I use that for if you want to download a playlist of videos, it's not needed for just audio is it?

**Comment by Tyrrrz** [comment]
Not sure what you mean.

**Comment by Eavileswayce** [comment]
It's alright it should be fine from now on thank you for the help
