### ISSUE TITLE
How to prevent youtube limit request. How to be authenticated?

### ISSUE THREAD

**Issue by MohammadSadeghSalimian** [Tyrrrz/YoutubeExplode#402]
During downloading a playlist, my IP addressed was banned, and they suspected me due to many requests. How can I overcome this problem?

**Comment by maxkatz6** [comment]
@MohammadSadeghSalimian see https://github.com/Tyrrrz/YoutubeExplode/issues/358

@Tyrrrz I think, some kind of issue template with little FAQ can help with duplicated questions.

**Comment by Tyrrrz** [comment]
@maxkatz6 thanks. The wiki is open for edits so if someone finds time to add a FAQ page, it would be great.
