### ISSUE TITLE
Cancel download

### ISSUE THREAD

**Issue by anonymuspro** [Tyrrrz/YoutubeExplode#404]
Hi, I am making an application for xamarin  using your library, is it possible to cancel the download?

**Comment by Tyrrrz** [comment]
Yes, using `CancellationToken`.
https://docs.microsoft.com/en-us/dotnet/api/system.threading.cancellationtoken?view=netcore-3.1

**Comment by anonymuspro** [comment]
Why Progress the class is still called after canceling the download, in my method this causes an error

**Comment by Tyrrrz** [comment]
Cancellation is co-operative and asynchronous by nature so it doesn't happen instantly.

**Comment by anonymuspro** [comment]
I finish the download using: 1, but it continues to the end (40 seconds)
