### ISSUE TITLE
Some youtube videos provide 404 media streams

### ISSUE THREAD

**Issue by udi12** [Tyrrrz/YoutubeExplode#407]
Hi there.

Please take a look at this YT url: 
/watch?v=Zy0mvygY3VM

All Urls extracted into streamInfoProviders are 404 bad urls...

Can you please take a look what is wrong?

Thanks

**Comment by Tyrrrz** [comment]
Looks like an error on YouTube's side

**Comment by udi12** [comment]
Hello again.
I do not think its a YouTube's issue.
With YouTube's UI you have all the resolutions available for selection.
For example, i have chosen to watch the video with 1080p quality, and youtube supplied that request with those 2 streams (Audio & Video):

https://r5---sn-cx1x9-ua86.googlevideo.com/videoplayback?expire=1593997121&ei=4CICX5rxNpfa1wbDpozIBQ&ip=79.183.6.41&id=o-AKxVaArKt9SPX_4W06HLOk8k4gC4alTfKckSahp_PXJB&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&mh=dZ&mm=31%2C29&mn=sn-cx1x9-ua86%2Csn-hgn7rnee&ms=au%2Crdu&mv=m&mvi=4&pl=24&initcwndbps=1060000&vprv=1&mime=video%2Fmp4&gir=yes&clen=244823854&otfp=1&dur=614.513&lmt=1593969953922517&mt=1593975395&fvip=5&keepalive=yes&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cotfp%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAI2HEiRHrs8wpEY0DbKt-mEE7lS-xDMtyqWzOhi8NU9CAiEAqoa59wuipa-y_rcDzUW9qETXjqzAZ0WgmARi6QL0K4E%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAK7sU1FF76p86hzufdYl61RQ0-c-bv8dOUyz3bwpWvw-AiEAupy46yiH_z4b3IGZ38xJMPXe9Qdr1s19pdzn8gMxXrk%3D&alr=yes&cpn=Sx-j74DIvWjVfIdG&cver=2.20200701.03.01&range=113585614-115715024&rn=68&rbuf=50057


https://r5---sn-cx1x9-ua86.googlevideo.com/videoplayback?expire=1593997121&ei=4CICX5rxNpfa1wbDpozIBQ&ip=79.183.6.41&id=o-AKxVaArKt9SPX_4W06HLOk8k4gC4alTfKckSahp_PXJB&itag=251&source=youtube&requiressl=yes&mh=dZ&mm=31%2C29&mn=sn-cx1x9-ua86%2Csn-hgn7rnee&ms=au%2Crdu&mv=m&mvi=4&pl=24&initcwndbps=1060000&vprv=1&mime=audio%2Fwebm&gir=yes&clen=10425116&otfp=1&dur=614.541&lmt=1593603357811883&mt=1593975395&fvip=5&keepalive=yes&c=WEB&txp=6211222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cotfp%2Cdur%2Clmt&sig=AOq0QJ8wRQIgHMyPoyK4fqtb3ahj8q35jGhVuaBe8NVVYA71xEVjLXkCIQDl95FRXYGNYLoFxdNSU_6cyyMg76TQNqSX1j_D4abIRg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAK7sU1FF76p86hzufdYl61RQ0-c-bv8dOUyz3bwpWvw-AiEAupy46yiH_z4b3IGZ38xJMPXe9Qdr1s19pdzn8gMxXrk%3D&alr=yes&cpn=Sx-j74DIvWjVfIdG&cver=2.20200701.03.01&range=4917104-5082421&rn=69&rbuf=52198


On the other hand, YouTubeExplode project gave 20 streams in which 18 of them get 404 error and the other 2 streams are muxed with lower resolutions.

**Comment by Tyrrrz** [comment]
The 1080p stream on that video seems to work for me. In fact, I don't seem to be getting 404 from neither of them.

**Comment by Isayso** [comment]
Got some not working Video link too
await _youtube.Videos.Streams.GetManifestAsync(videoId)  with videoId = https://www.youtube.com/watch?v=-EXFovGlS5A

Error: 
"Could not find signature decipherer definition body. In most cases, this error indicates that YouTube most likely changed something, which broke the library. If this issue persists, please report it on the project's GitHub page."

**Comment by Isayso** [comment]
Update: Your latest fix got rid of this error, but the result of 
await _youtube.Videos.Streams.GetManifestAsync(videoId) with videoId = https://www.youtube.com/watch?v=-EXFovGlS5A

does not contain the HD resolutions. Only up to 360p. 
Please can you take a look?
Thank you!

**Comment by Tyrrrz** [comment]
The issue here can be probably considered closed. The missing resolutions is a different problem, tracked in #410.
