### ISSUE TITLE
get_video_info request parameters

### ISSUE THREAD

**Issue by nu8** [Tyrrrz/YoutubeExplode#408]
I see here:

https://tyrrrz.me/blog/reverse-engineering-youtube

that you have a result similar to this:

~~~
status=ok
view_count=24022293
muted=0
use_cipher_signature=True
iurl=https://i.ytimg.com/vi/e_S9VvJM1PI/hqdefault.jpg
iurlhq720=https://i.ytimg.com/vi/e_S9VvJM1PI/hq720.jpg
video_id=e_S9VvJM1PI
~~~

but Im not understanding what you did to get that type of result. Neither of
these requests return the `iurlhq720` parameter, for example:

- <https://www.youtube.com/get_video_info?video_id=e_S9VvJM1PI&sts=17488&hl=en&el=detailpage>
- <https://www.youtube.com/get_video_info?video_id=e_S9VvJM1PI&sts=17488&hl=en>

**Comment by Tyrrrz** [comment]
HI

Please ask questions related to the article using the comments section below the article, not here.

It was written in 2017 so that field might no longer exist.
