### ISSUE TITLE
Compile Source Code in Windows Form

### ISSUE THREAD

**Issue by dev45** [Tyrrrz/YoutubeExplode#41]
Hi Again My Friend!! I want to ask you if i can use the same source to do it in a windows forms

**Comment by Tyrrrz** [comment]
Yes, why wouldn't it?

**Comment by dev45** [comment]
cause I have a problem with expander. i don't know how to do download expander in windows forms and how to insert the same list on it

**Comment by Tyrrrz** [comment]
why do you need the expander? it's a WPF control

**Comment by dev45** [comment]
yeah i know that but I mean which control can I use to do that part in windows forms? Which fulfills the same function 

for example can I do this with a combobox or listbox?

**Comment by SlowLogicBoy** [comment]
UserControl Visible = true/false with Button on Click event

**Comment by Tyrrrz** [comment]
This question isn't related to YoutubeExplode, so I'm closing it.
