### ISSUE TITLE
1080p video only streams are not available for some videos

### ISSUE THREAD

**Issue by cihanuygun** [Tyrrrz/YoutubeExplode#410]
Hello There,

I came across with a buggy behavior for 5.1.1. Video only streams for 1080p quality are not available for some videos, for example when I try to get stream info for the video VTK-2atS5pk YoutubeExplode only provides 360p stream. And same code block succesfully gets 1080p stream for 7OwbuLn-INE

All the best

**Comment by Tyrrrz** [comment]
> buggy behavior for 5.1.1

**Comment by cihanuygun** [comment]
Sorry for poor information, my bad. 
I just started to use 5.x so i dont have any information about previous 5.x versions. It used to work on 4.x version but i think youtube changed something which cause 4.x fail to fetch streams so i upgraded the library to 5.x

**Comment by Tyrrrz** [comment]
This is probably fixed by #159 as I suspect that's where YouTube gets those qualities from when they're not in `adaptive_fmts` list.
