### ISSUE TITLE
Custom path for downloaded video?

### ISSUE THREAD

**Issue by marcus-pw** [Tyrrrz/YoutubeExplode#411]
instead of saving to the bin, it would be nice to have an option to save to a specific path/folder

**Comment by PoLaKoSz** [comment]
You can customize the save path.

https://github.com/Tyrrrz/YoutubeExplode/blob/0472a220ab946bc0ff8d9c4434e14144894cb005/YoutubeExplode.DemoConsole/Program.cs#L34-L43

Change the code to this:

**_I didn't compiled this code:_**
``` c#
// Compose file name, based on metadata 
var fileName = $"{videoId}.{streamInfo.Container.Name}"; 
fileName = System.IO.Path.Combine(
    System.Environment.GetFolderPath(System.Environment.SpecialFolder.Desktop),
    fileName);
```

**Comment by marcus-pw** [comment]
Thank you, very helpful! :))))))))
