### ISSUE TITLE
Displaying the progress of the Video

### ISSUE THREAD

**Issue by Thulana2006** [Tyrrrz/YoutubeExplode#415]
Is there's a way to show the progress of the downloading video

**Comment by Tyrrrz** [comment]
Yes.

**Comment by Thulana2006** [comment]
What is it?

**Comment by Thulana2006** [comment]
Can you please send me the code?

**Comment by Thulana2006** [comment]
> Yes.


> Check out the demo projects, they both have progress reporting.

Thank you.
