### ISSUE TITLE
'Handle is Invalid' Exception is occurring.

### ISSUE THREAD

**Issue by Thulana2006** [Tyrrrz/YoutubeExplode#416]
<code>
var youtube = new YoutubeClient();
var video = await youtube.Videos.GetAsync(txtURL.Text);
var streamManifest = await youtube.Videos.Streams.GetManifestAsync(video.Id);
var streamInfo = streamManifest.GetMuxed().WithHighestVideoQuality();

                    if (streamInfo != null)
                    {
                        var stream = await youtube.Videos.Streams.GetAsync(streamInfo);
                        using (var progress = new InlineProgress())
                        {
                            await youtube.Videos.Streams.DownloadAsync(streamInfo, txtDestination.Text + VideoTitle + $".{ streamInfo.Container}",progress);
                        }
                    }
</code>
This gives me "Handle is Invalid Exception"

**Comment by Tyrrrz** [comment]
This exception is not on the library's side. The error is probably somewhere else in your code.
