### ISSUE TITLE
Downloading specific bitrate

### ISSUE THREAD

**Issue by Eavileswayce** [Tyrrrz/YoutubeExplode#418]
Hi, is it possible to download audio streams at specific bitrate? The code I used looks like this:

`var streamAudio = streamManifest.GetAudioOnly().FirstOrDefault(s => s.Bitrate.KiloBitsPerSecond == 192);`

This doesn't seem to work though, I just get the error "Object reference not set to an instance of an object,"

Thanks

**Comment by Tyrrrz** [comment]
You can, but there might not be a stream with that specific bitrate. Also, you're comparing it to exactly 192, which is nearly impossible in reality as bitrates will have fractional parts as well.

**Comment by Eavileswayce** [comment]
Oh so the stream is only available in certain bitrates? Apologies, I thought you might be able to use Youtube Explode Converter to download in whatever bitrate you wanted. Is this possible? If not that's okay. 

Thanks

**Comment by Tyrrrz** [comment]
No, that's not possible, at least currently.

**Comment by Eavileswayce** [comment]
Alright no problem thanks for the help

**Comment by Tyrrrz** [comment]
You're welcome!
