### ISSUE TITLE
Add CancellationToken param to Search.GetVideosAsync

### ISSUE THREAD

**Issue by UnoPromilo** [Tyrrrz/YoutubeExplode#419]
#It should be used as the second param in HttpClient.GetAsync. It should be easy to provide them from the GetVideosAsync method.

**Comment by Tyrrrz** [comment]
Do you have an actual use case for this? Why specifically for `Search.GetVideosAsync`?

**Comment by UnoPromilo** [comment]
I'm trying to create a search box that updates after a keystroke. If someone has typed the next key faster than previous results arrived I want to cancel previous search task.

**Comment by Tyrrrz** [comment]
Are you debouncing the input?

**Comment by UnoPromilo** [comment]
Yes, I have 200ms delay.

**Comment by Tyrrrz** [comment]
I would not advise to query it so often regardless, but instead use a button (just like YouTube does). If you send too many requests in a short period, YouTube will start throttling your IP and potentially request a captcha which breaks everything.

Additionally, I doubt adding cancellation to `SendAsync`/`GetAsync` would really help as that would only cancel only the initial phase of the request, i.e. DNS, handshake, sending headers, whatever. You would need to also implement cancellation for reading the content, most likely by using `content.ReadAsStreamAsync` and reading it in chunks with cancellation, as opposed to `content.ReadAsStringAsync` which doesn't accept cancellation. You can see where this is going.

You can try forking and implementing it to see if it makes a difference, but I strongly believe it will be much more cost-efficient to not search for videos until a designated button is pressed.
