### ISSUE TITLE
Could not find signature decipher definition body

### ISSUE THREAD

**Issue by IhabSaeed** [Tyrrrz/YoutubeExplode#421]
That Error Suddenly Occurs any help with that ?!

**Comment by jasonspar** [comment]
The same problem here. Just started happening today. They must have changed something.

**Comment by Eavileswayce** [comment]
Got the same issue too

**Comment by juliussss** [comment]
+1 experiencing the same issue

**Comment by Liuhuifeng** [comment]
Got the same issue too

**Comment by itsliamprowse** [comment]
Been the same for me since this morning

**Comment by hintdesk** [comment]
I have the same issue too

**Comment by balasratran** [comment]
I have the same issue too

**Comment by IhabSaeed** [comment]
Thank You Tyrrrz For your quick actions :) <3 @Tyrrrz
