### ISSUE TITLE
Cannot fetch video or muxed streams for seemingly anything new

### ISSUE THREAD

**Issue by Montegro** [Tyrrrz/YoutubeExplode#423]
Went to go ahead and archive a few channel's new uploads last night and every video returned no streams for both video and muxed, I thought maybe I'll try again tomorrow morning and here I am, same issue. Here are a list of the IDs I've tried...

CT4vOdje50E
HnjUmugKQuk
DQ0XNEJdMTA
xQXPau_NeMY
xZGa3Zm1zHE

**Comment by hunterofsouls** [comment]
Hi, I have the same problem. Regards

**Comment by mon3104** [comment]
confirmed. youtube change something. youtube.Videos.Streams.GetManifestAsync() is broken. Could not find signature decipherer definition Body.

**Comment by Tyrrrz** [comment]
@mon3104 update to latest version.

**Comment by Montegro** [comment]
Looks like 5.1.2 does it. Thank you!
