### ISSUE TITLE
Blazor Server BufferAsync Does Not Exist

### ISSUE THREAD

**Issue by Beblia** [Tyrrrz/YoutubeExplode#424]
Thanks for all your work. I have an issue in Blazor Server where the BufferAsync does not exist when searching for videos. When I try searching in playlist, search or uploads from youtube the BufferAsync does not exist. Everything works fine for UWP with the same exact code but when I try the code in blazor server I get a definition does not exist. What im trying to do is to return a certain amount of results rather then all the results at once. In my case I want to return 100 results.  Here is some code == 
var results = await yT_Client.Search.GetVideosAsync(searchQuery).BufferAsync(100);
Thank you.

**Comment by Tyrrrz** [comment]
Do you have `using YoutubeExplode;`?

**Comment by Beblia** [comment]
I have added that and it fixed the issue. Weird that Visual Studio would not give me any hints as to why there is an error. Working now.

**Comment by Beblia** [comment]
I also have another question if you can help me out. So its working good and Im able to get a certain amount of videos. But how do I request to get the next videos in the list? So if there are over 1000 results and I only want to load 40 results per load. How would I load the next 40? And the next after that and so on? Here is my code so far for getting the first 40 results to load = 

youTubeClient_LIST = await yT_Client.Search.GetVideosAsync(searchQuery).BufferAsync(40);

Im thinking to just call a function when the user scrolls to the bottom of the page and there I would call for the next 40 results. But I dont know how should I do this? Is there another method to get the next 40 from the buffer? If you can please post a snippet that would be awesome. Thanks.

**Comment by PoLaKoSz** [comment]
The easiest way would be to use this method:

https://github.com/Tyrrrz/YoutubeExplode/blob/dcfbb08b7ffc94a82eca32b7bdcbc0c02634e366/YoutubeExplode/Search/SearchClient.cs#L24-L30

But if You use this you will have no controll (YouTube sometimes returns 20-22 Videos) how many results will be loaded when you request for the next page.

**Comment by Tyrrrz** [comment]
If you don't have specific page/number of pages in mind, the best approach is to iterate with a `foreach`, i.e.:

```csharp
await foreach (var video in youtube.Search.GetVideosAsync("foo bar"))
{
    // ...
}
```
