### ISSUE TITLE
Small amount of url's not downloading

### ISSUE THREAD

**Issue by xander123cool** [Tyrrrz/YoutubeExplode#425]
I've succesfully used YoutubeExplode so far but i noticed some songs not downloading. So i tried using the Youtube Downloader app and that succesfully downloaded the same song. The only thing i could find that stands out from other songs that actually do download is that the status says "Faulted" from the type System.Threading.Tasks.TaskStatus instead of saying "WaitingForActivation".
Some songs that cause the "Faulted" status:
https://www.youtube.com/watch?v=ru0K8uYEZWw
https://www.youtube.com/watch?v=l482T0yNkeo
https://www.youtube.com/watch?v=LogL2pUiQmg

**Comment by xander123cool** [comment]
Noticed i didn't look deep enough and found out that all of those songs had a / in the title so i will now convert that to a underscore and i wil leave this here so that anyone can fix this for themselves when they get the same issue

**Comment by Tyrrrz** [comment]
FYI, you can inspect the Task's exact exception to see what went wrong. Or better, wrap it in try/catch.
