### ISSUE TITLE
Make the library fakeable

### ISSUE THREAD

**Issue by PoLaKoSz** [Tyrrrz/YoutubeExplode#431]
I use this library in an application and i would like to test it without sending any request towards YouTube. [I made a branch](https://github.com/PoLaKoSz/YoutubeExplode/tree/feature/client-interfaces) for a PR but i have a question first:
In [YoutubeClient](https://github.com/PoLaKoSz/YoutubeExplode/blob/feature/client-interfaces/YoutubeExplode/YoutubeClient.cs) and [VideoClient](https://github.com/PoLaKoSz/YoutubeExplode/blob/feature/client-interfaces/YoutubeExplode/Videos/VideoClient.cs) there are properties that i can't change to their inherited interface. What should i do? Implement for each property a method to return only an interface?

**Comment by Tyrrrz** [comment]
You shouldn't fake objects that you don't own, instead create an abstraction around YoutubeExplode (e.g. `YoutubeService`) with the methods you are interested in and fake that in your tests.

Example:

```csharp
public class YoutubeService : IYoutubeService
{
    private readonly YoutubeClient _youtube = new YoutubeClient();

    public async Task<Video> GetVideoAsync(string videoId) =>
        await _youtube.Videos.GetAsync(videoId);
}
```

You can use data models, i.e. `Video`, `Playlist`, etc. in your domain as they only contain data and no logic.

**Comment by PoLaKoSz** [comment]
Yes that is a good point.
- Implementing a service class like You suggested looks really good, my only concern is that i need to implement most of the method that in this library so the service class will be a god object.
- Another reson why i don't like this approach is that if i use this service in a class than that class can access every method in it. Yes i can use interfaces but then i will make almost the same interfaces as in my linked branch. Yes, i can do that but then comes a new person who wants to stub out this library too so (s)he will need to code probably the same as i have to.

If this library just exposes interfaces instead of concrete classes (for the `...Client` objects) than testing will be easier for everybody (Moq, NSubstitute, etc) without any wrapping code.

Maybe i am just simply lazy, sorry about that :smile:

**Comment by Tyrrrz** [comment]
> Implementing a service class like You suggested looks really good, my only concern is that i need to implement most of the method that in this library so the service class will be a god object.

It won't be a god object if all those methods are relevant to your domain. It's possible that your domain is just complex. But if you want, you can create multiple such services if you want as well.

> Another reson why i don't like this approach is that if i use this service in a class than that class can access every method in it. Yes i can use interfaces but then i will make almost the same interfaces as in my linked branch. Yes, i can do that but then comes a new person who wants to stub out this library too so (s)he will need to code probably the same as i have to.

Such is life :) All software is nothing but abstractions on top of abstractions. Logically, each new abstraction is bound to have a smaller API surface and less complex implementation, so it gets easier with each layer.

This library (and my other libraries) used to expose autotelic interfaces for every class but I eventually decided for myself that it's doing more bad than good. It puts constraints on how the API can be designed, which parts can be encapsulated, etc. On top of that, the interfaces will need to be backwards compatible and, for example, adding a new method breaks existing implementations. Basically, there is a lot of overhead and I've decided that it is not worth it.
