### ISSUE TITLE
Exception "playlist response is broken" is thrown when searching for videos

### ISSUE THREAD

**Issue by ThomasMasuth** [Tyrrrz/YoutubeExplode#438]
Exception thrown:

at "YoutubeClient.Search.GetVideosAsync("Blue Magic Guess Who").BufferAsync()"

Message: 
Playlist response is broken. In most cases, this error indicates that the problem is on YouTube's side and this is not a bug in the library. To resolve this error, please wait some time and try again. If this issue persists, please report it on the project's GitHub page.

StackTrace:
   bei YoutubeExplode.ReverseEngineering.Responses.PlaylistResponse.Parse(String raw)
   bei YoutubeExplode.ReverseEngineering.Responses.PlaylistResponse.<>c__DisplayClass12_0.<<GetSearchResultsAsync>b__0>d.MoveNext()
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei YoutubeExplode.Internal.Retry.<WrapAsync>d__1`1.MoveNext()
   bei YoutubeExplode.Internal.Retry.<WrapAsync>d__1`1.MoveNext()
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei YoutubeExplode.ReverseEngineering.Responses.PlaylistResponse.<GetSearchResultsAsync>d__12.MoveNext()
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei YoutubeExplode.Search.SearchClient.<GetVideosAsync>d__2.MoveNext()
   bei System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.GetResult(Int16 token)
   bei YoutubeExplode.Search.SearchClient.<GetVideosAsync>d__2.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
   bei YoutubeExplode.Internal.Extensions.AsyncEnumerableExtensions.<ToListAsync>d__1`1.MoveNext()
   bei YoutubeExplode.Internal.Extensions.AsyncEnumerableExtensions.<ToListAsync>d__1`1.MoveNext()
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei YoutubeExplode.AccessibilityExtensions.<BufferAsync>d__0.MoveNext()
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Threading.Tasks.ValueTask`1.get_Result()
   bei System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()

**Comment by Hexer10** [comment]
I'm experiencing this issue as well, seems like youtube removed this `endpoint` 
```
https://youtube.com/search_ajax
```
and now returns `404` for every request that is sent (with a valid payload or not).

**Comment by MeteorBurn** [comment]
Same issue for me.

**Comment by Tyrrrz** [comment]
Looks like 'search' is still shown as an available list type on the [iframe reference page](https://developers.google.com/youtube/player_parameters).
![image](https://user-images.githubusercontent.com/1935960/92933886-80e05280-f44f-11ea-80f7-7bcddc0c01d9.png)

I wonder if the URL changed?

**Comment by Hexer10** [comment]
> Looks like 'search' is still shown as an available list type on the [iframe reference page](https://developers.google.com/youtube/player_parameters).
> ![image](https://user-images.githubusercontent.com/1935960/92933886-80e05280-f44f-11ea-80f7-7bcddc0c01d9.png)
> 
> I wonder if the URL changed?

I just found out that the url is not changed, but now these headers:
```
    'x-youtube-client-name': '56',
    'x-youtube-client-version': '20200911',
```
are required  to make the search work, otherwise it will always return an error 404

**Comment by Tyrrrz** [comment]
Nice find! If someone wants to make a PR, you're welcome. Otherwise I'll commit a fix tomorrow.

**Comment by ThomasMasuth** [comment]
**Thanx a lot!!!** Works like a charme. Tested with 57 Videos.
