### ISSUE TITLE
Suggestion: break it in smaller packages

### ISSUE THREAD

**Issue by alexrainman** [Tyrrrz/YoutubeExplode#443]
I will love this package to be separated in smaller, functional packages.

By this ctor:

```cs
internal YoutubeClient(YoutubeHttpClient httpClient)
{
    Videos = new VideoClient(httpClient);
    Playlists = new PlaylistClient(httpClient);
    Channels = new ChannelClient(httpClient);
    Search = new SearchClient(httpClient);
}
```

We will end up with 4 packages:

```cs
YouTubeExplode.Videos
YouTubeExplode.Playlists
YouTubeExplode.Channels
YouTubeExplode.Search
```

It will be easier to use and maintain.

**Comment by Tyrrrz** [comment]
How are 4 separate packages easier to use and maintain?

**Comment by alexrainman** [comment]
For developers, they can use Videos without the need to install everything else. If something gets broken on Videos, you can update that package without  the risk of breaking something else. 

It is called "Separation of concerns".

**Comment by Tyrrrz** [comment]
Thanks for suggestion, but I will pass.

**Comment by alexrainman** [comment]
I will try to do it myself and make a PR.

**Comment by Tyrrrz** [comment]
Please don't. Splitting packages means splitting development and deployment cycles which is something I would prefer to avoid. Separation of concerns is good where the time and place is right, but here it's not worth it.
