### ISSUE TITLE
How to implement cancellation of download?

### ISSUE THREAD

**Issue by cvdevol** [Tyrrrz/YoutubeExplode#444]
Hope this isn't the wrong place to ask, but how to implement cancellation of a download when using youtube.Videos.Streams.DownloadAsync? I see that there is an optional cancellationtoken in the method header, but I am not a good enough programmer to figure out how to use it. I want to have a cancel button on the download progress window.

**Comment by Tyrrrz** [comment]
Duplicate of #404
