### ISSUE TITLE
Add interfaces to the library to make the nuget mockable per default

### ISSUE THREAD

**Issue by BrayanKhosravian** [Tyrrrz/YoutubeExplode#447]
From MVVM point of view it makes sense to extract interfaces from most of the classes as http interactions should be mocked away for testing.

It is ofc possible to inherit the `YoutubeClient` and use the `decorator pattern` to extract and apply interfaces.
But I think its better to make a PR.

That should be very easy to implement.
Do you accept a PR regarding this request.

**Comment by Tyrrrz** [comment]
Hi.

YoutubeExplode does not provide autotelic interfaces by design to discourage bad testing practices. If you want to establish a layer of indirection between YoutubeExplode and your application, create an interface that encapsulates functional behaviors relevant to your domain.

**Comment by BrayanKhosravian** [comment]
thanks
