### ISSUE TITLE
How to obtain file size

### ISSUE THREAD

**Issue by rigorvzla** [Tyrrrz/YoutubeExplode#449]
hello , im update youtubeexplode and now cant see , i cant obtain the size file , in old version is easy, `var video = await YoutubeClient.Videos.Size;` 
and now i dont know, sorry for my english

**Comment by Tyrrrz** [comment]
It's still there on all media streams:

https://github.com/Tyrrrz/YoutubeExplode/blob/6a1dacea77b420fdb80ecebd3550bf16a3ad5da2/YoutubeExplode/Videos/Streams/IStreamInfo.cs#L28-L31

**Comment by rigorvzla** [comment]
thanks, but i dont know how to used, you can show me a example

**Comment by Tyrrrz** [comment]
```csharp
var youtube = new YoutubeClient();
var streamManifest = await youtube.Videos.Streams.GetManifestAsync("bnsUkE8i0tU");
var streamInfo = streamManifest.GetMuxed().WithHighestVideoQuality();

var fileSize = streamInfo.Size;
```

**Comment by rigorvzla** [comment]
thanks so much!
