### ISSUE TITLE
Exception "Could not find key [is_listed]"

### ISSUE THREAD

**Issue by SlowLogicBoy** [Tyrrrz/YoutubeExplode#45]
Repo:
Example Video: https://www.youtube.com/watch?v=30yWTDSrZvE
Basically any unlisted video

Stacktrace:
   at YoutubeExplode.Internal.Extensions.Get[TKey,TValue](IDictionary`2 dic, TKey key)
   at async YoutubeExplode.YoutubeClient.GetVideoInfoAsync(?)
   ... (removed my apps stacktrace)

**Comment by Tyrrrz** [comment]
Good catch. I guess we didn't have any unlisted videos in tests. 🤔

**Comment by Tyrrrz** [comment]
This is fixed in the updated nuget package now

**Comment by SlowLogicBoy** [comment]
just updated, thanks.
