### ISSUE TITLE
Error: Too many request

### ISSUE THREAD

**Issue by MuhamedRaafat** [Tyrrrz/YoutubeExplode#453]
I am trying to download a lot of videos per day but then it causes this exception:

> Failed to perform an HTTP request to YouTube because of rate limiting.
> This error indicates that YouTube thinks there were too many requests made from this IP and considers it suspicious.
> To resolve this error, please wait some time and try again -or- try injecting an HttpClient that has cookies for an authenticated user.

I know it means that I have exceeded the limit of downloads, and youtube track that I am a machine not human, so please do you have any idea how I can face this problem ??

Thanks in advance.

**Comment by Tyrrrz** [comment]
No, there's not much you can do.
#436 #376
