### ISSUE TITLE
Playlist response is broken

### ISSUE THREAD

**Issue by duckieu1989** [Tyrrrz/YoutubeExplode#457]
Error:
{"message":"Playlist response is broken.\r\nIn most cases, this error indicates that the problem is on YouTube's side and this is not a bug in the library.\r\nTo resolve this error, please wait some time and try again.\r\nIf this issue persists, please report it on the project's GitHub page."}

This My code:
public async Task<IHttpActionResult> GetSearch()
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            try
            {
                var y = DateTime.Now.ToString("yyyy");
                var query = $"music {y}";
                var yt = new YoutubeClient();
                var list = await yt.Search.GetVideosAsync(query, 1, 1);
                return Ok(
                    new
                    {
                        isSuccess = true,
                        message = "OK",
                        data = list
                    }
                );
            }
            catch (Exception e)
            {
               return Ok(new {message = e.Message});
            }
        }

**Comment by Tyrrrz** [comment]
Which playlist?

**Comment by duckieu1989** [comment]
I dont know, i call search func seach but log from catch is:
Playlist response is broken.\r\nIn most cases, this error indicates that the problem is on YouTube's side and this is not a bug in the library.\r\nTo resolve this error, please wait some time and try again.\r\nIf this issue persists, please report it on the project's GitHub page.

My code use:
try
        {
            var y = DateTime.Now.ToString("yyyy");
            var query = $"music {y}";
            var yt = new YoutubeClient();
            var list = await yt.Search.GetVideosAsync(query, 1, 1);
            return Ok(
                new
                {
                    isSuccess = true,
                    message = "OK",
                    data = list
                }
            );
        }
        catch (Exception e)
        {
           return Ok(new {message = e.Message});
        }

**Comment by Tyrrrz** [comment]
I see. Which version are you using?

**Comment by duckieu1989** [comment]
My Using Latest version: 5.1.7.

I buil and run local okie , but deploy to hosting not ok .

**Comment by Tyrrrz** [comment]
Weird :/

**Comment by duckieu1989** [comment]
![image](https://user-images.githubusercontent.com/35229997/96361164-967f2100-114d-11eb-9293-38ba3c0d7009.png)

i sent result. 
Enviroment  deploy and local.

**Comment by duckieu1989** [comment]
Okie

**Comment by johndillonuk** [comment]
Ive got the same issue did anyone establish what this was please? Im calling var playlist = await youtube.Playlists.GetAsync(playlistId); with what I know is a valid playlistid

Exception: Playlist response is broken.
In most cases, this error indicates that the problem is on YouTube's side and this is not a bug in the library.
To resolve this error, please wait some time and try again.
If this issue persists, please report it on the project's GitHub page.

Im using latest version of code.

THanks

**Comment by Wayneos1000** [comment]
I've got the same issue whist calling 

var videos = await youtube.Search.GetVideosAsync(searchTerms, 0, 2);

It was working fine until about 2 weeks ago and this error now occurs.

thanks in advance,

Wayne

**Comment by Themodem** [comment]
Most of this lib uses endpoints like `https://youtube.com/search_ajax` and `https://youtube.com/list_ajax`

They are now returning 404 so im guessing they have been completely removed

**Comment by Wayneos1000** [comment]
Hi,
Ah, that explains it! Ok thanks for letting me know.
Cheers
Wayne
    On Wednesday, 17 February 2021, 08:47:21 pm GMT, Lee <notifications@github.com> wrote:  
 
 


Most of this lib uses endpoints like https://youtube.com/search_ajax and https://youtube.com/list_ajax

They are now returning 404 so im guessing they have been completely removed
