### ISSUE TITLE
VideoClient.GetAsync is extremely slow

### ISSUE THREAD

**Issue by MichalPetryka** [Tyrrrz/YoutubeExplode#459]
While profiling our youtube playback code i've noticed that VideoClient.GetAsync takes about 2.3 seconds to complete (as you can see on this screenshot in the last column). 
![image](https://user-images.githubusercontent.com/35800402/96620438-b9553500-1307-11eb-8f63-903daf7a29cd.png)

Playback dely resulting from this is quite noticeable and really impacts user experience.
We can reproduce this behaviour on every try.

**Comment by Tyrrrz** [comment]
Performance improvements are always welcome.

**Comment by Tyrrrz** [comment]
Can someone profile this with clear separation between CPU-bound operations and IO-bound operations? I want to know how much of the time is actually taken by tasks we can optimize vs just network requests to YouTube which are likely unavoidable.

**Comment by MichalPetryka** [comment]
Doing `time youtube-dl https://www.youtube.com/watch?v=dQw4w9WgXcQ --get-title --skip-download` takes 1.55s, this includes whole python interpreter startup, just `time youtube-dl` takes it 0.7s to print a no url error, so the request itself seems to take about 0.8.
Meanwhile this code:
```cs
private static async Task Main(string[] args)
{
    YoutubeClient client = new();
    Stopwatch sw = Stopwatch.StartNew();
    Video video = await client.Videos.GetAsync(args[0]);
    Console.WriteLine(sw.Elapsed.ToString());
    Console.WriteLine(video.Title);
}
```
with the same video provided takes 4.7s just to do the GetAsync (time from the stopwatch, so it doesn't include whole runtime startup), so I'd say there must be a lot of room for improvements.

**Comment by Tyrrrz** [comment]
Try the new version, I removed a lot of code from this flow. It should be faster now.
