### ISSUE TITLE
ParsePlaylistId does not work on mixes based on music artists

### ISSUE THREAD

**Issue by NoamHerry** [Tyrrrz/YoutubeExplode#46]
Would be nice to have a ParseMixId(string url) and an event when a channel uploads a video.

Thank you.

**Comment by SlowLogicBoy** [comment]
To get a mix:
```CSharp
private string ParseVideoId(string videoUrl)
{
	if (YoutubeClient.TryParseVideoId(videoUrl, out var videoId))
		return videoId;
	return videoUrl;
}
var pl = await client.GetPlaylistInfoAsync($"RD{ParseVideoId(videoIdorUrl)}");
```

**Comment by Tyrrrz** [comment]
>an event when a channel uploads a video.

How would that work?

**Comment by Tyrrrz** [comment]
Also I'm not sure what `ParseMixId(string url)` is supposed to be doing, because a mix is just a playlist, so you can use `ParsePlaylistId(string url)`. If you intend to create a mix from a video, you just need to add RD to the id, like @SlowLogicBoy showed.

**Comment by NoamHerry** [comment]
> How would that work?

I have no idea. But it would be useful.

Gonna try the mix soon. Thank you

**Comment by NoamHerry** [comment]
> mix is just a playlist

Last time I checked it couldn't get the ID

**Comment by Tyrrrz** [comment]
What URL were you trying to parse?

**Comment by NoamHerry** [comment]
https://www.youtube.com/watch?v=x2ZRoWQ0grU&list=RDEMNJhLy4rECJ_fG8NL-joqsg

**Comment by Tyrrrz** [comment]
Hm, you're right. The parsing fails because the resulting ID is 26 characters long, which is irregular. 🤔 
Apparently some RD mixes based on something like musical artists have longer IDs than normal.

**Comment by NoamHerry** [comment]
Are you able to solve it?

**Comment by Tyrrrz** [comment]
Mhm, just give me a few minutes.

**Comment by NoamHerry** [comment]
Alright. Thank you :)

**Comment by NoamHerry** [comment]
Let me know what it's fixed :)

**Comment by Tyrrrz** [comment]
Done
