### ISSUE TITLE
Age-restricted videos don't return any streams

### ISSUE THREAD

**Issue by Gpd1969** [Tyrrrz/YoutubeExplode#460]
I'm getting an error when pulling the stream manifest due to age restriction(s). If I log in to YouTube the issue is resolved. I cannot guarantee a user is going to be logged on to YT. Is there a work around for this?

                  // Video ID: "q5nQyoo1LwY"
                    var youtube = new YoutubeClient();

                    // Read the video ID
                    // Get media streams
                    var streams = await youtube.Videos.Streams.GetManifestAsync(youTubeVidID);// **_crashes here_**
                  
                    if(streams!=null)
                    {
                        var streamInfo = streams.GetMuxed().OrderBy(i => i.Bitrate).ToList();
                        youTubeVidPath = streamInfo[0].Url.Trim();
                    }

Debug INFO:
"Video 'q5nQyoo1LwY' is unplayable.\r\nStreams are not available for this video.\r\nIn most cases, this error indicates that there are some restrictions in place that prevent watching this video.\r\n\r\nReason:"

**Comment by Gpd1969** [comment]
This is not fixed but I wrote a kludge/hack/workaround that gets around the issue temporarily until I can find another way around detecting adult content. Since no response from the httpClient indicates a problem. I just do a search for the prompt to the user that content is adult. I know not elegant and prone to error and global language differences,  but it does get around the stream object crashing.

Workaround:

`  	isTrailerAdult= await IsTrailerAdult(youTubeVidID);

                if (movieQuery.HasVideos && !isTrailerAdult)
                {

                    // "q5nQyoo1LwY" PROBLEMATIC VID ID
                    var youtube = new YoutubeClient();
                    var streams = await youtube.Videos.Streams.GetManifestAsync(youTubeVidID);

                    if(streams!=null)
                    {
                        var streamInfo = streams.GetMuxed().OrderBy(i => i.Bitrate).ToList();
                        youTubeVidPath = streamInfo[0].Url.Trim();
                    }

                }
    public async Task<bool> IsTrailerAdult(string vidId)
    {
        HttpClient httpClient = new HttpClient();
        httpClient.BaseAddress = new Uri("https://www.youtube.com/watch?v=");
        HttpResponseMessage httpResponse = await httpClient.GetAsync(httpClient.BaseAddress + youTubeVidID, HttpCompletionOption.ResponseHeadersRead);
        string content = await httpClient.GetStringAsync(httpClient.BaseAddress + vidId);
        bool b1 = content.ToUpper().Contains("HAS BEEN RATED");
        bool b2 = content.ToUpper().Contains("INTENDED FOR MATURE AUDIENCES"); 
        httpClient.Dispose();
        if (b1&&b2)
        {

            return true;
        }

        return false;
    }`

**Comment by Gpd1969** [comment]
Yes, I have pulled the latest version from GITHUB. I have used older versions as well. I have tried versions, 4.xx to 5.xx.

**Comment by derech1e** [comment]
Is there an option, where you can login to your account? So you have no problems then? Correct?

**Comment by Gpd1969** [comment]
If I log in personally the error for age restricted content goes away. However, other users that use the application will not likely be logged in to YouTube nor can I force them to do so. 

Also I am getting another failure for videos that have been removed by YouTube. Vid ID(Rieq_TR7cV0) this is not pertaining to age restriction(s), it's because the video is gone. So I'm doing a check for that "video unavailable on the page.  

Is there no way to get status of the video via a query string or some other means,
`var streams = await youtube.Videos.Streams.GetManifestAsync(youTubeVidID);`

Thanks
