### ISSUE TITLE
JSON extracted from embed page is malformed

### ISSUE THREAD

**Issue by Tyrrrz** [Tyrrrz/YoutubeExplode#462]
![image](https://user-images.githubusercontent.com/1935960/97054966-7c4ea400-158e-11eb-90ef-6f558ae8df31.png)
https://www.youtube.com/watch?v=PJA2N3A3kLs

**Comment by thebitbrine** [comment]
Can't reproduce this bug.
It certainly fails to fetch metadata from the embed page and goes on and fetches it from the watch page,
but I could not get it to fail over parsing JSON.
YouTube has some kind of bot protection called "BotGuard" that encrypts the player's configs when detects that no JS has been running and the same client is repeatedly hitting the same video a few times a minute.

I would be thankful if you could post the JSON that it tries to parse so we could dig a little deeper.

**Comment by Tyrrrz** [comment]
Fixed in last release.
