### ISSUE TITLE
Unhandled Exception: NoSuchMethodError: The getter 'js' was called on null.

### ISSUE THREAD

**Issue by garlicgit** [Tyrrrz/YoutubeExplode#463]
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The getter 'js' was called on null.
Receiver: null
Tried calling: js
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _PlayerConfig.sourceUrl (package:youtube_explode_dart/src/reverse_engineering/responses/watch_page.dart:156:61)
#2      StreamsClient._getStreamContextFromWatchPage (package:youtube_explode_dart/src/videos/streams/streams_client.dart:95:58)
<asynchronous suspension>
#3      StreamsClient.getManifest (package:youtube_explode_dart/src/videos/streams/streams_client.dart:223:21)
<asynchronous suspension>
#4      main (package:testing/main.dart:21:18)
<asynchronous suspension>

Works up until last print statement, but then gets error above:

void main() async {

  var yt = YoutubeExplode();
  var video =
  await yt.videos.get('https://www.youtube.com/watch?v=P-9A8_SoZjc');

  print('Title: ${video.title}');
  print('Title: ${video.duration}');
  print('Title: ${video.id}');
  print('Title: ${video.author}');
  print('Title: ${video.description}');
  print('Title: ${video.channelId}');
  print('Title: ${video.uploadDate}');
  print('Title: ${video.url}');

  var manifest =  await yt.videos.streamsClient.getManifest(video.id);

**Comment by Tyrrrz** [comment]
Sounds like you got the wrong project

https://github.com/Hexer10/youtube_explode_dart

**Comment by garlicgit** [comment]
Sorry, and thank you.
