### ISSUE TITLE
YoutubeClient does not contain a definition for ParsVideoId

### ISSUE THREAD

**Issue by yigithanagkoc** [Tyrrrz/YoutubeExplode#472]
ERROR LİST

Error	CS0117	'YoutubeClient' does not contain a definition for 'ParseVideoId'	YouTubeDownloader

Error	CS1061	'YoutubeClient' does not contain a definition for 'GetVideoMediaStreamInfosAsync' and no accessible extension method 'GetVideoMediaStreamInfosAsync' accepting a first argument of type 'YoutubeClient' could be found (are you missing a using directive or an assembly reference?)

Error	CS1061	'YoutubeClient' does not contain a definition for 'GetVideoAsync' and no accessible extension method 'GetVideoAsync' accepting a first argument of type 'YoutubeClient' could be found (are you missing a using directive or an assembly reference?)

	

![image](https://user-images.githubusercontent.com/63478914/98181597-b4ea6800-1f14-11eb-8269-44bc0cd39b1f.png)

**Comment by Tyrrrz** [comment]
Read the readme https://github.com/Tyrrrz/YoutubeExplode#getting-metadata-of-a-video
