### ISSUE TITLE
Method not found exception

### ISSUE THREAD

**Issue by ComputerMaster1st** [Tyrrrz/YoutubeExplode#473]
Hi There,

We're receiving this exception when we try to grab a stream.

`---> System.MissingMethodException: Method not found: 'YoutubeExplode.Videos.Streams.StreamsClient YoutubeExplode.Videos.VideoClient.get_Streams()'.`

I believe it's happening when we try to call "await _client.Videos.Streams.GetAsync(info);". Info being the audio stream info. I'm not sure if it's an issue on our side or within the library.

I await for a response.

**Comment by Tyrrrz** [comment]
This sounds like it comes from YoutubeExplode.Converter. Make sure you're using latest versions of both YoutubeExplode and YoutubeExplode.Converter.
