### ISSUE TITLE
Parse Custom URLs Like 'https://www.youtube.com/c/<custom_name>'

### ISSUE THREAD

**Issue by ALSULTAN** [Tyrrrz/YoutubeExplode#474]
Youtube now support Custom URL like 'youtube.com/c/YouTubeCreators' and youtubeexplode can't parse that URLs.
Is there a way to support parsing such URLs?

Example URLs: 
https://www.youtube.com/c/aljazeera
https://www.youtube.com/c/SteveTurton

Look At Page https://support.google.com/youtube/answer/6180214?hl=en
That explains my issue

**Comment by charconstpointer** [comment]
what about URLs like these https://www.youtube.com/user/xxxx ? they also aren't correctly parsed, I could try to expand the parser to support such cases

**Comment by Tyrrrz** [comment]
> what about URLs like these https://www.youtube.com/user/xxxx ? they also aren't correctly parsed

They should be. What's incorrect about it?

**Comment by qtlin** [comment]
[Workaround](https://github.com/i3arnon/YouCast/issues/64) for /c/customaname

**Comment by Tyrrrz** [comment]
If anyone wants to implement it, I assume the steps would be:

1. Create `ChannelName` type similarly to existing `UserName`

2. Add `GetByNameAsync` here: https://github.com/Tyrrrz/YoutubeExplode/blob/9e53d0f7dd6c155af449ed537b239367dea26981/YoutubeExplode/ReverseEngineering/Responses/ChannelPage.cs#L39-L65

3. Add `GetByNameAsync` here: https://github.com/Tyrrrz/YoutubeExplode/blob/9e53d0f7dd6c155af449ed537b239367dea26981/YoutubeExplode/Channels/ChannelClient.cs#L26-L52
