### ISSUE TITLE
System.IO.IOException The server returned an invalid or unrecognized response. When try dowload muxed streams

### ISSUE THREAD

**Issue by minskowl** [Tyrrrz/YoutubeExplode#475]
For some videos can't download some Muxed Streams

        public async Task Download()
        {
            var client = new YoutubeClient();
            var videoId = VideoId.TryParse("https://www.youtube.com/watch?v=kUok7mvWgjk");
            Assert.NotNull(videoId);

            const string filePath = "c:\\1.avi";
            if (File.Exists(filePath))
            {
                File.Delete(filePath);
            }

            var manifest = await client.Videos.Streams.GetManifestAsync(videoId.Value);
            var tracks=manifest.GetMuxed().ToList();
            var streamInfo = tracks.First(e => e.VideoQuality == VideoQuality.High720);
            await client.Videos.Streams.DownloadAsync(streamInfo, filePath );

        }

Another videos with same problem
https://www.youtube.com/watch?v=6HsC9fNcZE8
https://www.youtube.com/watch?v=2NxT64tVRf0
https://www.youtube.com/watch?v=6LGO6XoWJLY
https://www.youtube.com/watch?v=ekdwu-oDH9g

**Comment by Tyrrrz** [comment]
If it's on YouTube's end, there's nothing we can do.

**Comment by minskowl** [comment]
probably incorrect handle streams in  YoutubeExplode.ReverseEngineering.YoutubeMediaStream.ReadAsync( ??

**Comment by Tyrrrz** [comment]
You can check, but I doubt it.
