### ISSUE TITLE
How to download such video https://www.youtube.com/watch?v=ZMrb6E7m2YI

### ISSUE THREAD

**Issue by minskowl** [Tyrrrz/YoutubeExplode#476]
//I try 
            var client = new YoutubeClient();
            var videoId = VideoId.TryParse("https://www.youtube.com/watch?v=ZMrb6E7m2YI");

// both  calls throws VideoUnplayableException
      var manifest = await client.Videos.Streams.GetManifestAsync(videoId.Value);
var url = await client.Videos.Streams.GetHttpLiveStreamUrlAsync(videoId.Value);

How to download this video?

**Comment by derech1e** [comment]
You cant download this Video, because it isn't a Video. It's an ongoing Livestream, so you need to wait until its end.
