### ISSUE TITLE
How to play Live stream videos?

### ISSUE THREAD

**Issue by vinayak-vc** [Tyrrrz/YoutubeExplode#477]
When I try to play this video "https://www.youtube.com/watch?v=XBPjVzSoepo" which is a Livestream video then the plugin throws this error.

`VideoUnplayableException: Video 'XBPjVzSoepo' is an ongoing live stream.
Streams are not available for this video.
Please wait until the live stream finishes and try again.
YoutubeExplode.Videos.Streams.StreamClient+<GetStreamContextFromWatchPageAsync>d__4.MoveNext () (at <1bb2d25c2a5f4a34b9b261f72723a3f7>:0)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <fb001e01371b4adca20013e0ac763896>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <fb001e01371b4adca20013e0ac763896>:0)
YoutubeExplode.Videos.Streams.StreamClient+<GetManifestAsync>d__6.MoveNext () (at <1bb2d25c2a5f4a34b9b261f72723a3f7>:0)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <fb001e01371b4adca20013e0ac763896>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <fb001e01371b4adca20013e0ac763896>:0)
YoutubePlayer.YoutubePlayer+<PlayVideoAsync>d__13.MoveNext () (at Assets/WebBrowser/Youtube/YoutubePlayer/Scripts/YoutubePlayer.cs:116)
UnityEngine.Debug:LogException(Exception)
YoutubePlayer.<PlayVideoAsync>d__13:MoveNext() (at Assets/WebBrowser/Youtube/YoutubePlayer/Scripts/YoutubePlayer.cs:137)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetException(Exception)
YoutubeExplode.Videos.Streams.<GetManifestAsync>d__6:MoveNext()
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetException(Exception)
YoutubeExplode.Videos.Streams.<GetStreamContextFromWatchPageAsync>d__4:MoveNext()
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetResult(PlayerSource)
YoutubeExplode.ReverseEngineering.Responses.<GetAsync>d__5:MoveNext()
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetResult(PlayerSource)
YoutubeExplode.Internal.<WrapAsync>d__1`1:MoveNext()
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetResult(PlayerSource)
YoutubeExplode.ReverseEngineering.Responses.<<GetAsync>b__0>d:MoveNext()
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetResult(String)
YoutubeExplode.ReverseEngineering.<GetStringAsync>d__6:MoveNext()
UnityEngine.UnitySynchronizationContext:ExecuteTasks()
`

Is there any way to play the Livestream?

**Comment by Tyrrrz** [comment]
Via HLS URL:
https://github.com/Tyrrrz/YoutubeExplode/blob/7c6ecbaa5b6193af52abd45eec6c766227b602f1/YoutubeExplode.Tests/StreamsSpecs.cs#L138-L150
