### ISSUE TITLE
How do you use Async without Microsoft.Bcl.Async?

### ISSUE THREAD

**Issue by mysteryx93** [Tyrrrz/YoutubeExplode#48]
I'm looking into your code and have a question... I see no reference to Microsoft.Bcl.Async, so how do you manage to use Async?

**Comment by Tyrrrz** [comment]
async is part of .net45+, netstandard1.0+ and .netcore1.0+

**Comment by mysteryx93** [comment]
Oh. Good to know. I had to reference it everywhere because one project had it so all other projects complained about it. I removed them all and it compiles fine.

**Comment by mysteryx93** [comment]
btw I love the way you structure your code. Very professional. It makes me realize that although I've had a lot of experience with .NET, my knowledge of WPF is lagging behind.

**Comment by Tyrrrz** [comment]
Thank you. Although the library doesn't have anything to do with WPF. :p
