### ISSUE TITLE
Why different URLs on debug and on release

### ISSUE THREAD

**Issue by luca233** [Tyrrrz/YoutubeExplode#480]
debug url
https://r1---sn-hxb5j5cax-j8ws.googlevideo.com/videoplayback?expire=1605784145&ei=8f21X56EE4qC2_gPmYCg4AY&ip=2806%3A265%3A3403%3A9350%3A8859%3A6b23%3Afc28%3Ae6c&id=o-ADvfHJgasr5O8mM9TUIHZfnr8heZcfywKv_nFvFmARIN&itag=18&source=youtube&requiressl=yes&mh=NV&mm=31%2C29&mn=sn-hxb5j5cax-j8ws%2Csn-q4flrn7k&ms=au%2Crdu&mv=m&mvi=1&pcm2cms=yes&pl=40&gcr=mx&initcwndbps=635000&vprv=1&mime=video%2Fmp4&gir=yes&clen=22819507&ratebypass=yes&dur=251.890&lmt=1434709649656123&mt=1605762393&fvip=1&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgOyAypQ0zft7P7n8OJ2nc39izhDIHno6xTYK7kVe4tzQCIQCdhqNU5HncjVDac-gJ0kX9FhZBUDeDk9NICHVdmDyDfA%3D%3D&sig=AOq0QJ8wRQIhAIqggmrieAKMSZvRrEUvSDj4GOVkyqnbH3hbBdKnsIPCAiAYLfyKKsilLR2CPpNIcWERjm_e4tNmZBz-gr6gMntaEw==

release url

https://r6---sn-5ualdn76.googlevideo.com/videoplayback?expire=1605784145&ei=IP61X_rFEZeZkwagt7boBw&ip=2806%3A265%3A3403%3A9350%3A8859%3A6b23%3Afc28%3Ae6c&id=o-ADvfHJgasr5O8mM9TUIHZfnr8heZcfywKv_nFvFmARIN&itag=18&source=youtube&requiressl=yes&mh=NV&mm=31%2C29&mn=sn-hxb5j5cax-j8ws%2Csn-q4flrn7k&ms=au%2Crdu&mv=m&mvi=1&pl=24&gcr=us&vprv=1&mime=video%2Fmp4&gir=yes&clen=22819507&ratebypass=yes&dur=251.890&lmt=1434709649656123&mt=1605762182&fvip=6&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl&lsig=AG3C_xAwRAIgRN_N2W3ny4OUfPb8594QE1yZ07WBwt5EcCzlXkpQoSUCIBzqL3lV0XoOvsduxjL-GyT64vpzXCigyX0HWRZaxzfC&sig=AOq0QJ8wRgIhAP5PPV-FF9Vg4IWh8h2JXzGnQR2zRStRma8q-PqNT6BXAiEAqK5WpYJui3U90m2Zz1RWipmnd_vy2GxDOsWfQH6rNVY=&pcm2cms=yes

someone can help me?

**Comment by luca233** [comment]
i will try run under blazor client

**Comment by Tyrrrz** [comment]
Are you hosting this on the same machine in both debug and release?

**Comment by Tyrrrz** [comment]
There shouldn't be any difference between running on debug or on release, but if your release build is not running on the same environment as the debug build, then there will be differences obviously.

**Comment by luca233** [comment]
> Are you hosting this on the same machine in both debug and release?

yes
