### ISSUE TITLE
Too few muxed stream options?

### ISSUE THREAD

**Issue by TheFizz** [Tyrrrz/YoutubeExplode#484]
For every video I get only 2 muxed options: 720p@22FPS and 360p@18FPS, however, video-only streams come in all quality options. Is this intended?

If so, should I get both video and audio separately and combine them in my app?

Bonus question: How would I track download progress?

**Comment by Tyrrrz** [comment]
> Is this intended?

You'd have to ask YouTube that, but most likely yes. They themselves are not using muxed streams (except the mobile youtube site), so there's probably no reason to keep them around.

> How would I track download progress?

Check the demo projects.
