### ISSUE TITLE
CORS error from net core blazor

### ISSUE THREAD

**Issue by luca233** [Tyrrrz/YoutubeExplode#485]
i get this message from request from blazor to youtbexploder

has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled

can any help me ?

thanks

**Comment by Tyrrrz** [comment]
This is not related to the library.
