### ISSUE TITLE
error on published app

### ISSUE THREAD

**Issue by luca233** [Tyrrrz/YoutubeExplode#486]
i get this message when app is published in iis
"'a' is an invalid start of a property name. Expected a '\"'. LineNumber: 0 | BytePositionInLine: 1.System.Collections.ListDictionaryInternal   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)\r\n   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()\r\n   at System.Text.Json.Utf8JsonReader.Read()\r\n   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack)\r\n   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedBytes)\r\n   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 json, JsonDocumentOptions options)\r\n   at System.Text.Json.JsonDocument.Parse(String json, JsonDocumentOptions options)\r\n   at YoutubeExplode.Internal.Json.Parse(String source) in 

can any ideas?

**Comment by Gabo-7** [comment]
See here: https://github.com/Tyrrrz/YoutubeExplode/issues/479
