### ISSUE TITLE
Large memory increase when getting a video and stream manifest

### ISSUE THREAD

**Issue by madmagic007** [Tyrrrz/YoutubeExplode#487]
using the visual studio debugger i found that when i get a video using `YoutubeClient#Videos.GetAsync()` and stream manifest 
 with `YoutubeClient#Videos.Streams.GetManifestAsync()`, there is around 30MB increase in memory usage. I go from 16MB to 50, and after a forced gc it drops to around 46 and it stays at that usage. When ran again in thesame session it goes up to 50 and drops to 46 where it stays just like before.

**Comment by Tyrrrz** [comment]
I don't know what to advise here or what can be done about it. .NET memory management is a black box implementation detail for the most part, so I wouldn't worry about it unless it actually starts leaking.
