### ISSUE TITLE
YouTube rejects DemoConsole connection from Windows but allows from Linux

### ISSUE THREAD

**Issue by qtlin** [Tyrrrz/YoutubeExplode#489]
On Windows 7 x86 testing DemoConsole results in `YoutubeExplode.Exceptions.RequestLimitExceededException` while on CentOS 7 on exact same IP address there is no exception and any video is successfully downloaded. Both system use freshly downloaded dotnet sdk 5.0

**Comment by Tyrrrz** [comment]
Might be a coincidence and your throttling ran out. Or it might be that YouTube takes user agent into account besides IP.

**Comment by qtlin** [comment]
I've been using YoutubeExplode backend for several years, downloading about a dozen videos per week on average. Suddenly it stopped working and only DemoConsole showed root cause. BTW, DemoWpf silently crashed without showing any exceptions.

When error occurs the DemoConsole prints all request details but nothing on success.
Questions:
1. how to unconditionally display request details in DemoConsole?
2. how to randomize or change user agent since one used on Windows 7 clearly draw suspicion for some reason...

UPD: No longer reproducible. I suppose YouTube dropped RequestLimit against IP/user-agent combination.

**Comment by Tyrrrz** [comment]
> how to unconditionally display request details in DemoConsole?

there is no way, but you can put a debug breakpoint somewhere in the code

> how to randomize or change user agent since one used on Windows 7 clearly draw suspicion for some reason...

you can inject your own custom `HttpClient` into `YoutubeClient` and set user-agent as you see fit.
