### ISSUE TITLE
Difference between sample and NuGet package

### ISSUE THREAD

**Issue by mysteryx93** [Tyrrrz/YoutubeExplode#49]
In the GitHub code and sample, VideoInfo contains Streams. In the NuGet package, however, it instead contains MixedStreams, AudioStreams and VideoStreams. Why the discrepancy?

**Comment by SlowLogicBoy** [comment]
Probably forgot to update samples? Since there were a lot of changes recently

**Comment by Tyrrrz** [comment]
Where can you see it saying "Streams"?

**Comment by mysteryx93** [comment]
Somehow I didn't have the latest code from GitHub. Now I got the latest.
