### ISSUE TITLE
Returned video URLs are different depending upon the location?

### ISSUE THREAD

**Issue by severino65** [Tyrrrz/YoutubeExplode#490]
Hello,

I've created an ASP.NET application based upon the latest version of your library and all works like a charm: for each video on YouTube I can obtain many information like thumbnails, author, etc. and the URL for each audio and video stream. Now the strange thing: if I run the ASP.NET application locally on my PC (in Italy) returned URLs are correct and I can use them for downloading the file. If I run the exact same ASP.NET application hosted on a Windows server located in the USA, while all of the other info are the same, the URL returned is different and, when used for downloading, YouTube returns an error 403. Do you have any idea about the reason for YouTube returning different URLs while the code is the same in both places?

Kind Regards

Severino

**Comment by severino65** [comment]
Hello again, I've the doubt that the URL returned by Youtube could be fixed for the IP of the client which generated the request because the IP of the client seems to be part of the URL's parameters: could this be the issue?

Kind regards

Severino

**Comment by Tyrrrz** [comment]
Yes, the URLs are bound to IP.

**Comment by severino65** [comment]
Thanks for confirming and keep up the good work :-)

Kind regards

Severino
