### ISSUE TITLE
Downloading audio only

### ISSUE THREAD

**Issue by kloinfa** [Tyrrrz/YoutubeExplode#491]
I'm using AudioOnly Stream to download and save audio from video on android, but after that, android recognize this file as a video. Am i doing something wrong?

StreamManifest streamManifest = await MainActivity.youtube.Videos.Streams.GetManifestAsync(VideoId);               
                var streamInfoAudio = streamManifest.GetAudioOnly().Where(x=>x.Container==Container.)
                if (streamInfoAudio != null)
                {
                    if (!Directory.Exists(download_path))
                        Directory.CreateDirectory(download_path);
                    string regexSearch = new string(Path.GetInvalidFileNameChars()) + new string(Path.GetInvalidPathChars());
                    Regex r = new Regex(string.Format("[{0}]", Regex.Escape(regexSearch)));
                    Title = r.Replace(Title, "");
                    string path = download_path + @"/" + Title + ".mp3";
                    var stream = await MainActivity.youtube.Videos.Streams.GetAsync(streamInfoAudio);
                    await MainActivity.youtube.Videos.Streams.DownloadAsync(streamInfoAudio, path);
                    PathS = path;
                    this.TextView.SetTextColor(Color.Green);
                    return true;
                }

**Comment by Tyrrrz** [comment]
The audio only stream are still encoded in multimedia containers like mp4 and webm.
With mp4 you can just safely rename the file to m4a and it should play just fine.
For webm I believe you need conversion.
For all other formats you will also need conversion.
