### ISSUE TITLE
Having issue with pulling a vids info

### ISSUE THREAD

**Issue by t3knical** [Tyrrrz/YoutubeExplode#492]
https://www.youtube.com/watch?v=iT8gd4NUUpU <- is the culprit

i thought it was something in my code, but even the demo can't load it on the newest version that's buildable, any thoughts?

System.Net.Http.HttpRequestException: 'No such host is known. (r5---sn-vgqsrn76.googlevideo.com:443)' <- is what I get thrown back. however using another api 'VideoLibrary' I'm able to play the mp4 video back fine, however I like yours better cause my project requires only audio.

for now my temp fix was a try/catch statement in the StreamClient.cs GetManifestAsync function within the foreach part, so it could get what it could and ignore the rest, cause after some digging i saw that it was getting quiet a few valid links, just one or a couple were causing the issue. Wish you the best of luck on fixing this one, and thank you so much for such a godly api.

**Comment by Tyrrrz** [comment]
Hi.
Sorry for late reply, only got around to it now.
I tried and it seems to work now. Note that YouTube is generally very inconsistent, so such errors may happen on their side occasionally. The best solution is just to retry or try another stream.
