### ISSUE TITLE
In StreamExtensions.cs, shouldn't there also be an additional check on the cancellationToken?

### ISSUE THREAD

**Issue by StefH** [Tyrrrz/YoutubeExplode#493]
Like this?
``` c#
} while (!cancellationToken.IsCancellationRequested && bytesRead > 0);
```

**Comment by Tyrrrz** [comment]
Do you mean here?
https://github.com/Tyrrrz/YoutubeExplode/blob/f800021e2be16b6aeed1bb3bbda1d3d79a331fe7/YoutubeExplode/Internal/Extensions/StreamExtensions.cs#L19-L31

The cancellation token is already checked in one of the invoked methods anyway.

**Comment by StefH** [comment]
I guess the `CopyBufferedToAsync` will return 0 when cancellation is requested, so the `while` will stop on that criteria.

**Comment by Tyrrrz** [comment]
It will just throw an exception.
