### ISSUE TITLE
Generate playlist question

### ISSUE THREAD

**Issue by Kajirinn** [Tyrrrz/YoutubeExplode#494]
Hi there,

I'd prefer not to make this a standalone question, but I can no longer find this feature for the life of me.
Back in the day, there used to be an option (I think within a video if I recall correctly), to generate a playlist based on a video.
Is there still a way to do this within this package, or has it been completely removed?

Thank you in advance,

Kajirinn.

**Comment by Tyrrrz** [comment]
Hi @Kajirinn.

It was removed because it was a bit inconsistent due to there being many different ways a mix playlist could be generated.
You can do it yourself, however:

```csharp
var playlist = await youtube.Playlists.GetAsync("RD" + videoId);
```

**Comment by Kajirinn** [comment]
Thank you for the quick response per usual! That did the trick 👍
