### ISSUE TITLE
Explode the URL

### ISSUE THREAD

**Issue by spoiledtechie** [Tyrrrz/YoutubeExplode#50]
Hey, I won't mind pushing a PR myself, but wondering if you are still accepting them?  Or you can do it yourself?

On this method, can you please return the URL of the downloadable video?

GetVideoInfoAsync

I don't want the streams, I simply want the URL to download it myself.  Make sense?  Just add it to the VideoInfo object.  If you reply and let me know you can't or don't have time, Ill do it.  Just wondering if you would be willing to do it first?

**Comment by Tyrrrz** [comment]
Hi.
I don't get what's a "URL of the downloadable video"?

**Comment by spoiledtechie** [comment]
from only reviewing the code on Github, please correct me if I am wrong, but this url you use is defined here:

string url = streamDic.Get("url");

line 250: https://github.com/Tyrrrz/YoutubeExplode/blob/93b4834aa6fccdc99bbca6ec1b28853a8a42db04/YoutubeExplode/YoutubeClient.cs

Is this the URL that is used to pull the video down?

**Comment by Tyrrrz** [comment]
Yes. And in fact that's an URL of one of the streams.

**Comment by spoiledtechie** [comment]
Oh, is it just the video stream?  If thats the case, is there another url that has both the video and audio combined?

BTW, thanks for responding so quickly.

**Comment by Tyrrrz** [comment]
Yeah, MixedStreams are the ones that have both.
You can read a bit more on the topic [here](https://github.com/Tyrrrz/YoutubeExplode/wiki/FAQ#q-why-are-there-multiple-types-of-streams-mixed-audio-and-video).

**Comment by spoiledtechie** [comment]
oh, this is interesting.  So on the new YT stuff, you can't actually use a single URL for their videos...

**Comment by Tyrrrz** [comment]
Yep. Most videos still have MixedStreams, but they are limited in quality to 720p30fps.

**Comment by spoiledtechie** [comment]
So, are you able to put the URL into one of the objects, passing it back out within the video, after received?  If the video does have a mixed stream?

**Comment by Tyrrrz** [comment]
```c#
var videoInfo = await GetVideoInfoAsync("your_video");
string url = videoInfo.MixedStreams.OrderBy(s => s.VideoQuality).Last(); // take the highest quality mixed stream
```

**Comment by Tyrrrz** [comment]
Is the question answered?

**Comment by spoiledtechie** [comment]
thanks, that greatly helps!
