### ISSUE TITLE
Error "too many requests" from Youtube

### ISSUE THREAD

**Issue by Isayso** [Tyrrrz/YoutubeExplode#500]
![Screenshot (142)](https://user-images.githubusercontent.com/35309607/106353297-ce1f6c80-62e9-11eb-9ada-f51fd778c631.jpg)
Got this today on all attempts to get something. Jdownloader and youtube-dl has the same issue, Youtube Kodi addon not. 

Any idea what to do?

**Comment by Isayso** [comment]
Update: After requesting new IP, the error is gone, but this is strange, because my browser and kodi device worked, so looks like some anonymous access is blocked? Missing cookie ?

**Comment by Tyrrrz** [comment]
Duplicate: #453 #376 #292 #312 #273 #436 #321 #470
