### ISSUE TITLE
YoutubeClient.Channels.GetUploadAsync() not working anymore?

### ISSUE THREAD

**Issue by midnight-cigarettes** [Tyrrrz/YoutubeExplode#507]
Been using it without issues back in 2020, and I came to use it again today. Seems like the underlying request though doesn't work anymore.

![Screenshot 2021-02-26 213914](https://user-images.githubusercontent.com/65785136/109307262-4fcbd100-787b-11eb-8f49-301d989d5e8d.png)

Trying that request just results on a 404. Tried it in my browser too and indeed it does.
Here's a quick one for test if it works on any of your end: https://www.youtube.com/list_ajax?style=json&action_get_list=1&list=UU4xKdmAXFh4ACyhpiQ_3qBw&index=0&hl=en

If it doesn't then does anyone knows an alternative way of getting all the details of all videos on a channel?

**Comment by Tyrrrz** [comment]
Related to #501 most likely.
Try the pre-release version for now.

**Comment by midnight-cigarettes** [comment]
Hey thanks @Tyrrrz , I'll try this out.
I've read the issue you linked too, and indeed it seems like the same problem.
I'll close this now.
