### ISSUE TITLE
youtube.Videos.GetAsync("...."); does not work anymore

### ISSUE THREAD

**Issue by DarioDusper1992** [Tyrrrz/YoutubeExplode#509]
var video = await youtube.Videos.GetAsync("https://www.youtube.com/watch?v=_OowcbKuacM");

Exception thrown: 'System.Text.Json.JsonReaderException' in System.Text.Json.dll
Exception thrown: 'System.Text.Json.JsonReaderException' in System.Text.Json.dll
Exception thrown: 'System.Text.Json.JsonReaderException' in System.Text.Json.dll
Exception thrown: 'YoutubeExplode.Exceptions.TransientFailureException' in YoutubeExplode.dll
Exception thrown: 'YoutubeExplode.Exceptions.TransientFailureException' in mscorlib.dll
Exception thrown: 'System.Text.Json.JsonReaderException' in System.Text.Json.dll
Exception thrown: 'System.Text.Json.JsonReaderException' in System.Text.Json.dll
Exception thrown: 'System.Text.Json.JsonReaderException' in System.Text.Json.dll
Exception thrown: 'YoutubeExplode.Exceptions.TransientFailureException' in YoutubeExplode.dll
Exception thrown: 'YoutubeExplode.Exceptions.TransientFailureException' in mscorlib.dll
Exception thrown: 'System.Text.Json.JsonReaderException' in System.Text.Json.dll
Exception thrown: 'System.Text.Json.JsonReaderException' in System.Text.Json.dll
Exception thrown: 'System.Text.Json.JsonReaderException' in System.Text.Json.dll
Exception thrown: 'YoutubeExplode.Exceptions.TransientFailureException' in YoutubeExplode.dll
Exception thrown: 'YoutubeExplode.Exceptions.TransientFailureException' in mscorlib.dll
Exception thrown: 'System.Text.Json.JsonReaderException' in System.Text.Json.dll
Exception thrown: 'System.Text.Json.JsonReaderException' in System.Text.Json.dll
Exception thrown: 'System.Text.Json.JsonReaderException' in System.Text.Json.dll
Exception thrown: 'YoutubeExplode.Exceptions.TransientFailureException' in YoutubeExplode.dll
Exception thrown: 'YoutubeExplode.Exceptions.TransientFailureException' in mscorlib.dll
Exception thrown: 'System.Text.Json.JsonReaderException' in System.Text.Json.dll
Exception thrown: 'System.Text.Json.JsonReaderException' in System.Text.Json.dll
Exception thrown: 'System.Text.Json.JsonReaderException' in System.Text.Json.dll
Exception thrown: 'YoutubeExplode.Exceptions.TransientFailureException' in YoutubeExplode.dll
Exception thrown: 'YoutubeExplode.Exceptions.TransientFailureException' in mscorlib.dll
Exception thrown: 'System.Text.Json.JsonReaderException' in System.Text.Json.dll
Exception thrown: 'System.Text.Json.JsonReaderException' in System.Text.Json.dll
Exception thrown: 'System.Text.Json.JsonReaderException' in System.Text.Json.dll
Exception thrown: 'YoutubeExplode.Exceptions.TransientFailureException' in YoutubeExplode.dll
Exception thrown: 'YoutubeExplode.Exceptions.TransientFailureException' in mscorlib.dll
Exception thrown: 'YoutubeExplode.Exceptions.TransientFailureException' in YoutubeExplode.dll
Exception thrown: 'YoutubeExplode.Exceptions.TransientFailureException' in mscorlib.dll
Exception thrown: 'YoutubeExplode.Exceptions.TransientFailureException' in mscorlib.dll
Exception thrown: 'YoutubeExplode.Exceptions.TransientFailureException' in mscorlib.dll

**Comment by Tyrrrz** [comment]
Seems to work on CI. Can you retrieve the specific exception message and stack trace?
