### ISSUE TITLE
How do I use the progress bar with this API?

### ISSUE THREAD

**Issue by pgh268400** [Tyrrrz/YoutubeExplode#51]
I want to create a YouTube download program with a progress bar.
After seeing the wiki, I knew how to download it, but I do not know how to add a progress bar.

The source of GitHub is an error and can not be opened.
Could you give me an example of how to make it?

I am sorry for my poor English ability.
I do not know if I can upload here, but if not, I'm sorry :(

**Comment by Tyrrrz** [comment]
안녕하세요

You can use one of the overloads and supply a `progress` handler. The progress is a double value ranging from 0 to 1 (0% to 100%).

- [Here's an example in the console demo](https://github.com/Tyrrrz/YoutubeExplode/blob/5d227a0d4709ab0825440c796b21fcbd36f52983/DemoConsole/Program.cs#L78). It shows progress in the window title.
- [Here's an example in the WPF demo](https://github.com/Tyrrrz/YoutubeExplode/blob/5d227a0d4709ab0825440c796b21fcbd36f52983/DemoWpf/ViewModels/MainViewModel.cs#L132). It shows progress using WPF progress bar.

By the way, what error do you get when trying to compile the source?

**Comment by Gokujo** [comment]
![error](https://user-images.githubusercontent.com/19776684/29658954-0214eff2-88bd-11e7-8e72-ff320dddcd15.png)
как можно исправить эту ошибку? пишет, что не возвращает значения

**Comment by Tyrrrz** [comment]
нужен Visual Studio 2017, C#7

**Comment by Gokujo** [comment]
@Tyrrrz т.е. на 2015 не пойдёт?

**Comment by Tyrrrz** [comment]
нет, к сожалению

**Comment by Gokujo** [comment]
@Tyrrrz решил немного иначе
добавил **Xceed.Wpf.Toolkit**
`buzzy.IsBusy = true;
                buzzy.BusyContent = string.Format("Datei \"" + fileName + "\" wird geladen! Bitte warten!");
                await client.DownloadMediaStreamAsync(streamInfo, out);
                buzzy.IsBusy = false;`
