### ISSUE TITLE
Every download bitrate is 124kbs 

### ISSUE THREAD

**Issue by stevetheski** [Tyrrrz/YoutubeExplode#512]
downloading audio only MP3 StreamManifest.GetAudioOnly().WithHighestBitrate(); returns all files at 124kbs I have downloaded and compiled youtube downloader and I get the same results with every video

**Comment by stevetheski** [comment]
Lossless URL (so they claim) https://www.youtube.com/watch?v=_20nkqX8rps
you will also notice the bitrate doesn't match the actual bitrate with .ogg
![Capture](https://user-images.githubusercontent.com/80420017/110682748-4ad71d80-81a9-11eb-8fd7-96b1dbdbfa20.PNG)

**Comment by Tyrrrz** [comment]
Unless something changed, YouTube caps their audio bitrate at around 126 kbps.
The video may have been lossless at some point, but once it was uploaded to YouTube it definitely became lossy.

**Comment by stevetheski** [comment]
tyrrrz,
this is an actual video that will play lossless on youtube. https://www.youtube.com/watch?v=J0a2Prc_MQ you can hear the clipping if you download the mp3 or ogg somewhere between 2:20 and 2:30. This might help. when i recorded it with audacity and WASAPI then converting to mp3 i was able to get 160k; a little better than 124but still not where it should be.

**Comment by Tyrrrz** [comment]
It says video is unavailable.

![image](https://user-images.githubusercontent.com/1935960/110841154-3a5c9b00-82ae-11eb-93aa-c3adc59fd1ec.png)
