### ISSUE TITLE
Possible solution to download age-restricted videos

### ISSUE THREAD

**Issue by derech1e** [Tyrrrz/YoutubeExplode#513]
Hey, I discovered for me this way to watch age restricted videos without signing in.

Via the [VLC Media Player](https://www.videolan.org/) it is possible to play age restricted videos.

### Steps to do:

1. Copy the restricted video link
2. Open VLC and click on Media>Open Network Stream>Paste the Link>PlayOpen Network Stream VLC
3. VLC will automatically bypass the video restriction and start playing it.

So its an Github Project. Maybe it is possible to find out how they did it: https://github.com/videolan/vlc

**Comment by Tyrrrz** [comment]
Worth looking into this with Fiddler :+1:
Does this work consistently? Even with YoutubeExplode you can download age-restricted videos once in a few attempts.

**Comment by Tyrrrz** [comment]
Just tried it, couldn't get it to work with VLC.

**Comment by derech1e** [comment]
> Just tried it, couldn't get it to work with VLC.

It looks like the bug has been fixed. The last time I tested it, it still worked.
Maybe we can close this issue here.
