### ISSUE TITLE
The playlist download seems to be broken....

### ISSUE THREAD

**Issue by MikeGitIt** [Tyrrrz/YoutubeExplode#514]
This is the Exception Message which I receive (I have tried several playlists thus far and the error persists)...

**Playlist response is broken. In most cases, this error indicates that the problem is on YouTube's side and this is not a bug in the library. To resolve this error, please wait some time and try again. If this issue persists, please report it on the project's GitHub page.**

I am running this in LinqPad 6 and as well, Visual Studio 2019 on the latest build of Windows 10.

**Comment by jakedacatman** [comment]
Can confirm this with video searching as well.

**Comment by raelb** [comment]
See #511

**Comment by Tyrrrz** [comment]
Are you using the latest pre-release version? https://www.nuget.org/packages/YoutubeExplode/6.0.0-alpha
Duplicate of #457
