### ISSUE TITLE
Extract approximate upload date for videos in playlists and search results

### ISSUE THREAD

**Issue by docsteve57** [Tyrrrz/YoutubeExplode#515]
In #501 it stated:'The only currently available replacement features date in a form of "3 days ago".'
I installed 6.0.0a - but I can't see anything corresponding in the Intellisense. Will this be added? It seems that something is better than nothing, and in fact Youtube does this because that is the level of info that most people want/need.

Thanks.

**Comment by Tyrrrz** [comment]
Most likely not.
Some context: https://github.com/Tyrrrz/YoutubeExplode/pull/502#issuecomment-788931387

**Comment by docsteve57** [comment]
My thought is that returning this as a string would have very little extra 'cost'. I think it is still useful info - specifically as a context for the view count. A video that got 10k views and is a few hours old is popular - the same number over a couple of years - well...

**Comment by Tyrrrz** [comment]
There is a cost associated with maintaining the code that extracts that string. YouTube has a tendency of changing things often, so it's not unlikely that the date string may move to a different part of the payload or be removed entirely. By adding it to the model, we provide certain guarantees that it's always going to be there and it's always going to be valid. I'm not convinced that this piece of data is worth the effort, to be honest. I may change my mind in the future though.

**Comment by Tyrrrz** [comment]
Decided against it because I don't like exposing raw strings like that with non-deterministic format.
