### ISSUE TITLE
TransientFailureException: Video watch page is broken.

### ISSUE THREAD

**Issue by L0um15** [Tyrrrz/YoutubeExplode#521]
Hi, when i was working on my application few minutes ago. <br />I noticed that suddenly everything stopped working.

No matter which id i tried to use, every request resulted in failure (single tracks).
When i was running some tests week ago, everything was working just fine.

![obraz](https://user-images.githubusercontent.com/44427021/113221708-deba7780-9285-11eb-8ffd-1536c8da65a7.png)

**Comment by Speyd3r** [comment]
I got those TransientExceptions yesterday sporadically, today they're constant.
So I looked a bit into it and it seems Youtube changed the watchpage. the IDs its looking for to check if the page is "ok" don't exist anymore. 
For testing I commented both checks at [WatchPage.cs#L130](https://github.com/Tyrrrz/YoutubeExplode/blob/cb115a9319e19cdbfc6cde610df146524f6e44be/YoutubeExplode/ReverseEngineering/Responses/WatchPage.cs#L130) and I got metadata again (Title, thumbnails etc.) but getting the streams is broken

**Comment by Speyd3r** [comment]
I got it! So youtube changed the `yt.SetConfig` to `ytcfg.set` on the embed page!

**Comment by Speyd3r** [comment]
Found another thing that hinders one from getting channels for example (I just ran the tests and assumed there was a similar "id being removed" thing, but this is a bit bigger)
![image](https://user-images.githubusercontent.com/37484974/113269395-b0b25300-92d8-11eb-94aa-1db1ca89b09a.png)

**Comment by Isayso** [comment]
FYI, I experienced yesterday the same. This new privacy page appears and right after that getAsync failed.

**Comment by Speyd3r** [comment]
Yea it needs a CONSENT Cookie now `new Cookie("CONSENT", $"YES+cb", "/", ".youtube.com")` I tried a bit and this is the shortest version of it that works, normally YouTube also adds a date and region codes to it but it seems they aren't necessary

**Comment by Speyd3r** [comment]
Yay almost all the tests pass now, cookie of doom

**Comment by Tyrrrz** [comment]
Uploaded version `6.0.0-alpha2` to NuGet with the fix (thanks @Speyd3r). A stable version will be released once I'm done with refactoring, which will hopefully be end of this week.
