### ISSUE TITLE
Missing CONSENT Cookie and change of variable name

### ISSUE THREAD

**Issue by Speyd3r** [Tyrrrz/YoutubeExplode#522]
Making a new issue to put it all my findings in one. (coming from #521)

So the TransientException is caused by YouTube changing IDs in the Watchpage it seems, probably need to find new ones to make a ok and/or video available.
The embed page got a change so it cant find **`yt.setConfig`** [EmbedPage#L44](https://github.com/Tyrrrz/YoutubeExplode/blob/cb115a9319e19cdbfc6cde610df146524f6e44be/YoutubeExplode/ReverseEngineering/Responses/EmbedPage.cs#L44) anymore, now its **`ytcfg.set`**

A lot of pages not need a "Consent Cookie"
the shortest version I found that worked is
```
Name: CONSENT
Value: YES+cb
Path: /
Domain: .youtube.com
```

**Comment by Speyd3r** [comment]
After some more testing it seems that **`yt.setConfig`** has not changed, rather **`ytcfg.set`** is a new one

**Comment by Speyd3r** [comment]
Theory confirmed! So ytcfg.set seems to be some new thing that they also use in the EmbedPage:
without `ytcfg.set` parsing fallback:
![image](https://user-images.githubusercontent.com/37484974/113289968-3f32ce80-92f1-11eb-9013-0cf2edc85860.png)
(it fails on the agerestricted + embed allowed)

with `ytcfg.set` as 3rd fallback:
![image](https://user-images.githubusercontent.com/37484974/113290179-89b44b00-92f1-11eb-9c05-6cfda0f0dc8c.png)

**Comment by Speyd3r** [comment]
I think the CONSENT cookie thing is also what caused the sporadic TransientException

**Comment by Tyrrrz** [comment]
Uploaded version `6.0.0-alpha2` to NuGet with the fix (thanks @Speyd3r). A stable version will be released once I'm done with refactoring, which will hopefully be end of this week.
