### ISSUE TITLE
Video watch page is broken.

### ISSUE THREAD

**Issue by bozali** [Tyrrrz/YoutubeExplode#524]
Hello,

I wanted to test this library by using the example code and I get this error.
I used some different YouTube Urls and the one in the example and I get the same error.

**NuGet-Package Version:** 5.1.9

**Code:**
```
var youtube = new YoutubeClient();

// You can specify video ID or URL
var video = await youtube.Videos.GetAsync("https://youtube.com/watch?v=u_yIGGhubZs");

var title = video.Title; // "Collections - Blender 2.80 Fundamentals"
var author = video.Author; // "Blender"
var duration = video.Duration; // 00:07:20
```

**Exception:**
```
Video watch page is broken.
In most cases, this error indicates that the problem is on YouTube's side and this is not a bug in the library.
To resolve this error, please wait some time and try again.
If this issue persists, please report it on the project's GitHub page.
```

**Comment by ChristopherTwelvetrees** [comment]
I've been getting the same error for around 24 hours now. Mine's in some existing software which had been working fine.

I too am now on v5.1.9. I get the error both here

`video = await youtube.Videos.GetAsync(VideoKey);`

and if I skip getting title etc and go straight to this:

`streamManifest = await youtube.Videos.Streams.GetManifestAsync(VideoKey);`

**Comment by Speyd3r** [comment]
I'd suggest updating to the latest preview for now, YouTube has added a privacy site that causes this if there isn't a specific Cookie present.
It might also work again if you supply a HttpClient yourself and add a Cookie with the following values:
Name: CONSENT
Value: YES+cb
Path: /
Domain: .youtube.com

**Comment by ChristopherTwelvetrees** [comment]
Just out of interest, as I'd never tried it before with YouTubeExplode, I tried setting up an HttpClient of my own with that Cookie, and that seems to work fine. Thanks for the help.

**Comment by bozali** [comment]
Thanks, its working!
