### ISSUE TITLE
System.AggregateException: YoutubeExplode.Exceptions.TransientFailureException: Video watch page is broken.

### ISSUE THREAD

**Issue by ManamanaTheReal499** [Tyrrrz/YoutubeExplode#525]
In most cases, this error indicates that the problem is on YouTube's side and this is not a bug in the library.
To resolve this error, please wait some time and try again.
This error persists for 2 days

**Comment by Speyd3r** [comment]
Update to Version 6 preview 2, I'm not sure if my fix from a few days ago will be backported

**Comment by ManamanaTheReal499** [comment]
> 
> 
> Update to Version 6 preview 2, I'm not sure if my fix from a few days ago will be backported
yes it solved the problem
