### ISSUE TITLE
Video watch page is broken

### ISSUE THREAD

**Issue by zoltantajti** [Tyrrrz/YoutubeExplode#527]
Hey.
I have an issue, the var 

`video = await youtube.Videos.GetAsync("s1cF85dukUg")`

line return the error:

> YoutubeExplode.Exceptions.TransientFailureException: 'Video watch page is broken.
> In most cases, this error indicates that the problem is on YouTube's side and this is not a bug in the library.
> To resolve this error, please wait some time and try again.
> If this issue persists, please report it on the project's GitHub page.'

any fix this problem? 

Thank you.

**Comment by Speyd3r** [comment]
Are you using stable? If so try using the Preview, YouTube made some changes that broke this a bit.

If you really need to use version 5 you can give the YoutubeClient a HttpClient that has following Cookie set:
Name: CONSENT
Value: YES+cb
Path: /
Domain: .youtube.com
