### ISSUE TITLE
Target CliWrap 3.3.2 instead of 3.2.4 when downloading videos

### ISSUE THREAD

**Issue by alipex** [Tyrrrz/YoutubeExplode#531]
When downloading videos with CliWrap 3.3.2 - 3.3.0 installed, it throws a `System.IO.FileLoadException`.
With 3.2.4 it works fine, since it is targeting that version.

Exception details:
`System.IO.FileLoadException: 'Could not load file or assembly 'CliWrap, Version=3.2.4.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.`

![image](https://user-images.githubusercontent.com/80337966/115201326-81cc1780-a0f5-11eb-8ae9-0422417915dc.png)

**Comment by Tyrrrz** [comment]
YoutubeExplode doesn't use CliWrap, are you talking about YoutubeExplode.Converter? In that case, it's targeting 3.3.2 so it should work:

https://github.com/Tyrrrz/YoutubeExplode.Converter/blob/24428eda4cd7c391054579f2a66dcce6dbbbe5e9/YoutubeExplode.Converter/YoutubeExplode.Converter.csproj#L24

Make sure all your packages are updated to latest.

**Comment by alipex** [comment]
All of my packages are updated to the latest version - including YoutubeExplode and YoutubeExplode.Converter.

However - if I want to update YoutubeExplode.Converter, it lowers the version of YoutubeExplode itself to 6.0.0, which for me, does not work for downloading videos - consent cookie doesn't send... The only version, that works for me, is YoutubeExplode 6.0.0-alpha2 and YoutubeExplode.Converter 2.0.2

My code:

```
using System;
using System.Windows.Forms;
using YoutubeExplode;
using YoutubeExplode.Converter;

namespace DownloadTest
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private async void btn_downloadVideo_Click(object sender, EventArgs e)
        {
            try
            {
                var url = txtbox_videoURL.Text;
                var yclient = new YoutubeClient();

                await yclient.Videos.DownloadAsync(url, "video.mp4");

                MessageBox.Show("Task completed.");
            }
            catch (ArgumentException)
            {
                MessageBox.Show("Invalid URL. Please use a valid YouTube URL.");
                txtbox_videoURL.Clear();
            }

            catch (YoutubeExplode.Exceptions.YoutubeExplodeException)
            {
                MessageBox.Show("Cannot download video - probably due to YouTube's implementation of consent.");
                txtbox_videoURL.Clear();
            }
        }
    }
}
```

Packages installed: YoutubeExplode, YoutubeExplode.Converter and dependencies

**Comment by Tyrrrz** [comment]
So you don't get "Cannot load file or assembly" error anymore?

**Comment by alipex** [comment]
> 
> 
> So you don't get "Cannot load file or assembly" error anymore?

With the setup I currently have, no.
When I update, yes.

**Comment by Tyrrrz** [comment]
Sorry, can't reproduce it.

**Comment by alipex** [comment]
Alright, I'll check if my dependencies are correctly functioning. For now, I am going to close this.
