### ISSUE TITLE
limit hits in search and playlist

### ISSUE THREAD

**Issue by jasonspar** [Tyrrrz/YoutubeExplode#532]
Is there a new way to limit the search hit count in 6.0 release?
We used to have this:

client.Search.GetVideosAsync(query);  //.BufferAsync (MAX_HITS); 
client.Playlists.GetVideosAsync(id);     //.BufferAsync (GM_LIMIT);

looks like BufferAsync is not longer available.

**Comment by jasonspar** [comment]
I found it. Got renamed to CollectAsync ().

**Comment by Tyrrrz** [comment]
Yes, sorry. Forgot to mention it in the changelog.
