### ISSUE TITLE
How to use search?

### ISSUE THREAD

**Issue by hunterofsouls** [Tyrrrz/YoutubeExplode#533]
I am having problems using Final version 6.0 to search for videos on youtube and it returns the search list. Thanks for your support.
![error](https://user-images.githubusercontent.com/56051072/115416060-0a61bb00-a1bd-11eb-91db-00e170018159.png)

 Private Async Sub Get_YoutubeAsync()
        Dim youtube As New YoutubeClient
        Dim streaminfo As New List(Of String)

        streaminfo = Await youtube.Search.GetVideosAsync("Minutos")

        RadGridView1.DataSource = 
    End Sub

**Comment by mon3104** [comment]
@hunterofsouls  youtube.Search.GetVideosAsync does not return a list of string and cannot be directly used as you are trying.

Best is to use a foreach loop like where searchResult is of type PlaylistVideo
```
foreach (var searchResult in await youtube.Search.GetVideosAsync("On my Way"))
{
    var a = searchResult.Title;
    .
    .
}
```

**Comment by hunterofsouls** [comment]
> @hunterofsouls youtube.Search.GetVideosAsync does not return a list of string and cannot be directly used as you are trying.
> 
> Best is to use a foreach loop were searchResult is of type PlaylistVideo
> 
> ```
> foreach (var searchResult in await youtube.Search.GetVideosAsync("On my Way"))
> {
>     var a = searchResult.Title;
>     .
>     .
> }
> ```

**Comment by hunterofsouls** [comment]
> @hunterofsouls youtube.Search.GetVideosAsync does not return a list of string and cannot be directly used as you are trying.
> 
> Best is to use a foreach loop were searchResult is of type PlaylistVideo
> 
> ```
> foreach (var searchResult in await youtube.Search.GetVideosAsync("On my Way"))
> {
>     var a = searchResult.Title;
>     .
>     .
> }
> ```

Thanks for taking the time to answer me, I keep getting the error that a parameter is missing in the GetVideosAsync (cancellationtoken) function, I don't know what it refers to, I hope you can support me, thank you.
![error2](https://user-images.githubusercontent.com/56051072/115457492-3d6e7380-a1ea-11eb-9ed3-dc6e0e901f73.png)

**Comment by Tyrrrz** [comment]
I don't know VB enough to help you, but there's now an example on readme:

https://github.com/Tyrrrz/YoutubeExplode#searching

**Comment by hunterofsouls** [comment]
Thanks for taking the time to write, "using YoutubeExplode.Common" solved the problem. Thanks for the project.

**Comment by hunterofsouls** [comment]
Thanks for taking the time to write, "using YoutubeExplode.Common" solved the problem. Thanks for the project.
