### ISSUE TITLE
Imporove SearchClient by adding filters

### ISSUE THREAD

**Issue by MeteorBurn** [Tyrrrz/YoutubeExplode#539]
I suggest adding the ability to filter search results.
A bit of information on how YouTube generates an sp parameter to filter search results.
https://github.com/TeamNewPipe/NewPipeExtractor/issues/106

Perhaps it will help you.

Sorry if it has already been discussed.

**Comment by Tyrrrz** [comment]
Yeah I was thinking about the same thing. Good idea.
