### ISSUE TITLE
Get Youtube Red preview video

### ISSUE THREAD

**Issue by Tyrrrz** [Tyrrrz/YoutubeExplode#54]

**Comment by Tyrrrz** [comment]
Good news, @spoiledtechie.
This is extremely easy to do.

**Comment by Tyrrrz** [comment]
The new version will now have `PreviewVideoId` as one of the properties inside `VideoRequiresPurchaseException`. You can then handle the exception and request video info on the preview video instead.

**Comment by Tyrrrz** [comment]
Update package is uploaded

**Comment by spoiledtechie** [comment]
this is great!  thank you!  Ill let you know how it goes with the current issue.

**Comment by spoiledtechie** [comment]
@Tyrrrz  it looks like you removed this exception and took it out of the code base.  Any reason why?  I would still LOVE to get the PreviewVideoId of this file....

**Comment by Tyrrrz** [comment]
@spoiledtechie this is unfortunately true, that information is missing from `player_response` which is the current approach used for parsing all of the data. It's still may be possible to get this info somehow, I will have to look into it.

**Comment by spoiledtechie** [comment]
thanks for this!!!
