### ISSUE TITLE
Some video cannot download caption

### ISSUE THREAD

**Issue by u8621011** [Tyrrrz/YoutubeExplode#545]
### Version

6.0, 5.1.9

### Details

GetManifestAsync will return empty manifest but we can see from youtube which contains caption

### Steps to reproduce

```
using YoutubeExplode;

var youtube = new YoutubeClient();

var trackManifest = await youtube.Videos.ClosedCaptions.GetManifestAsync("vU4HomMP-bg");
var trackManifest = await youtube.Videos.ClosedCaptions.GetManifestAsync("FXbwv_IvxXQ");

```

**Comment by Tyrrrz** [comment]
Looks like for these videos closed captions are not stored in player response. Will need to investigate.
