### ISSUE TITLE
streamClient.GetHttpLiveStreamUrlAsync(videoId) randomly throws an error 404.

### ISSUE THREAD

**Issue by KubaZ2** [Tyrrrz/YoutubeExplode#547]
### Version

6.0.0

### Details

I want to play a livestream but the GetHttpLiveStreamUrlAsync method often throws an error:
`Response status code does not indicate success: 404 (Not Found).`
It can throw an exception or not for the same video link.

### Steps to reproduce

Use StreamClient.GetHttpLiveStreamUrlAsync(VideoId) a couple of times.

**Comment by thisistorsten** [comment]
Seems same behavior as here. https://github.com/Tyrrrz/YoutubeExplode/issues/549

**Comment by KubaZ2** [comment]
The 6.0.1 version fixed this issue for me, I will close it.

**Comment by Tyrrrz** [comment]
This issue has returned as a side effect of #565.
