### ISSUE TITLE
Failed Error - almost 99/100 attempts. but I can use the get request and read the resulting file. 

### ISSUE THREAD

**Issue by inetmarketeers** [Tyrrrz/YoutubeExplode#548]
### Version

Alpha 6.0.2

### Details

Here is my code, and an example error triggered on the last line of code

Code //
            List<Captions> captions = new List<Captions>();
            //gridControl1.DataSource = captions;
            if (barEditItem3.EditValue != null)
            {
                BeginInvoke(new Action(() =>
                {
                    barStaticItem7.Caption = "Status: Downloading Video Data";
                    barEditItem9.Visibility = DevExpress.XtraBars.BarItemVisibility.Always;
                }));
                string vidID = "";
                try
                {
                    vidID = GetYouTubeVideoIdFromUrl(barEditItem3.EditValue.ToString());
                }
                catch (Exception ex) { }
                
                try
                {
                    if (youtube != null)    
                        youtube = new YoutubeClient();
                    navigationPane1.SelectedPage = navigationPage2;
                    // You can specify video ID or URL
                    string videoURL = barEditItem3.EditValue.ToString();
                    var video = await youtube.Videos.GetAsync(videoURL);
//

Failed to perform an HTTP request to YouTube due to a fatal failure.
In most cases, this error indicates that YouTube most likely changed something, which broke the library.
If this issue persists, please report it on the project's GitHub page.

Method: GET, RequestUri: 'https://www.youtube.com/get_video_info?video_id=_j4Rpx-VPTg&el=embedded&eurl=https://youtube.googleapis.com/v/_j4Rpx-VPTg&hl=en&sts=', Version: 1.1, Content: <null>, Headers:
{
  User-Agent: Mozilla/5.0
  User-Agent: (Windows NT 10.0; Win64; x64)
  User-Agent: AppleWebKit/537.36
  User-Agent: (KHTML, like Gecko)
  User-Agent: Chrome/86.0.4240.111
  User-Agent: Safari/537.36
}

StatusCode: 404, ReasonPhrase: 'Not Found', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  X-Frame-Options: SAMEORIGIN
  X-Content-Type-Options: nosniff
  Strict-Transport-Security: max-age=31536000
  X-XSS-Protection: 0
  Alt-Svc: h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
  Cache-Control: no-cache
  Date: Tue, 18 May 2021 18:02:30 GMT
  Server: YouTube
  Server: Frontend
  Server: Proxy
  Content-Length: 0
  Content-Type: text/html; charset=utf-8
  Expires: Tue, 27 Apr 1971 19:44:06 GMT
}

### Steps to reproduce

I get the error with every video I try.

I tried the 6.00 release build and adjusted my code, but got the page is broken error.

**Comment by Tyrrrz** [comment]
Can you try latest stable instead of alpha?

**Comment by Hexer10** [comment]
This was reported in  `youtube_explode_dart` as well, most likely youtube removed that endpoint (if you try to manually open it in the browser it returns 404)

**Comment by TaoziDB** [comment]
add &html5=1 at the end of https://www.youtube.com/get_video_info api call should work for now

**Comment by markledwich2** [comment]
> add &html5=1 at the end of https://www.youtube.com/get_video_info api call should work for now

🙏 this is a life-saver for me!  Can I ask how you worked that out?

**Comment by Tyrrrz** [comment]
Duplicate of #549

**Comment by Tyrrrz** [comment]
@Hexer10 @TaoziDB 
Thanks for help!
In the future, I think we will drop get_video_info and replace it with their internal endpoint that returns player response directly.
