### ISSUE TITLE
Could not extract player response.

### ISSUE THREAD

**Issue by illyaz** [Tyrrrz/YoutubeExplode#549]
### Version

6.0.0

### Details

it seem like incomplete json data cause by `.Pipe(Json.Extract)` in `VideoWatchPageExtractor.TryGetPlayerResponse`
i tried multiple video but got error on video id `gKL9xv2VykM`

![Screenshot 2021-05-20 220308](https://user-images.githubusercontent.com/26743376/119002594-35574e80-b9b7-11eb-9a81-4f5af4d1be68.png)

### Steps to reproduce

`.Videos.GetAsync("gKL9xv2VykM")` and getting error

**Comment by illyaz** [comment]
i think a problem is `}` in string

here is another videos:
`kQaSVmFA7NE` contains `}`  in title 
`fR2_Z6A0qnQ` contains `}`  in description

**Comment by marcojoao** [comment]
Youtube removed the access to "/get_video"  I believe

**Comment by thisistorsten** [comment]
> Youtube removed the access to "https://www.youtube.com/get_video_info" I believe

No they changed the access. I will commit an updated get_video_info link this night here: https://github.com/thisistorsten/YouTubeApiSharp

**Comment by thisistorsten** [comment]
This line will solve the problem 🥇 

https://github.com/thisistorsten/YouTubeApiSharp/blob/main/src/YouTubeApiSharp/YouTubeApiSharp/API/DownloadUrlResolver.cs#L347

**Comment by fi-da** [comment]
TOP
This means row 137 in YoutubeController.cs is

 `$"?html5=1&video_id={videoId}" +`

**Comment by thisistorsten** [comment]
Yes. This will fix it.

fi-da ***@***.***> schrieb am Fr., 21. Mai 2021, 10:43:
