### ISSUE TITLE
possible to queue downloads and start them if < then 2 downloads active ?

### ISSUE THREAD

**Issue by anideath** [Tyrrrz/YoutubeExplode#55]
Hello,

at first, thanks for this library,  it's the best I've found :)

Now i want to code a download queue. I tried some things with the C# queue class but I'm relatively new to programming and I dont understand how most things work. Anyone has some tipps to integrate a download queue ? Heres my download code at the moment.

` private async void tUrl_TextChanged(object sender, EventArgs e)
        {
            int counter = Convert.ToInt32(label1.Text);

            if (cbAutoDownload.Checked)
            {
                try
                {

                    var client = new YoutubeClient();                       
                
                    string id = tUrl.Text;
                    id = NormalizeId(id);

                    var videoInfo = await client.GetVideoInfoAsync(id);
                    var streamInfo = videoInfo.MixedStreams.OrderBy(s => s.VideoQuality).Last();

                    grösse = videoInfo.MixedStreams[0].ContentLength;
                    NormalizeFileSize(grösse);
                    grösse = grösse;
                    realSize = grösse / 1024;
                    realSize2 = realSize / 1024;
                    lblSize.Text = realSize2.ToString() + " MB";
                   
                    gesamtSög += realSize2;
                    lblGesamt.Text = gesamtSög.ToString() + " MB";

                    string fileExtension = streamInfo.Container.GetFileExtension();
                    string fileName = $"{ videoInfo.Title}.{ fileExtension}";
                    string EndDirectory = tPath.Text + @"\";
                    fileName = fileName.Except(Path.GetInvalidFileNameChars());
                    var videoFilePath = Path.Combine(EndDirectory, fileName);
                    
                    string fullFileName = Path.Combine(EndDirectory, fileName);

                    if (!File.Exists(fullFileName))
                    {
                    
                        string[] arr = new string[4];
                        ListViewItem itm;
                        arr[0] = fileName;
                        arr[1] = "Downloading...";
                        arr[2] = EndDirectory;
                        arr[3] = tUrl.Text;
                        itm = new ListViewItem(arr);
                        listVideo.Text = arr[0];
                        downloading += 1;

                        label1.Text = downloading.ToString();
                        int senf = Convert.ToInt32(listFinished.Items.Count);
                        listFinished.Items.Add(itm);
                        
                        integer = senf;
                                           

                        var progressHandler = new Progress<double>(p => pbar = Convert.ToInt32(p * 100 ));
                        
                        await client.DownloadMediaStreamAsync(streamInfo, videoFilePath, progressHandler);
                                          
                        pBar.Value = 0;
                        downloading -= 1;
                        label1.Text = downloading.ToString();
                      

                        string countList = listFinished.Items.Count.ToString();
                        lblCount.Text = countList;
                       
                        listFinished.Items[0].SubItems[1].Text = "Fertig";
                        listFinished.Items[integer].SubItems[1].Text = "Fertig";
                        integer++;

                        ListItemsHelper listItemsHelper = new ListItemsHelper();
                        listItemsHelper.saveListViewItems(path23, listFinished);
                        path23 = AppDomain.CurrentDomain.BaseDirectory + "DownloadList.txt";
                        path23 = path23;
                        Properties.Settings.Default.Speicherpfad = tPath.Text;
                        Properties.Settings.Default.Save();

                    }
                }
                   
                catch (Exception) { }
            }
        }
`

**Comment by Tyrrrz** [comment]
What do you mean by download queue?

**Comment by anideath** [comment]
I have a download list here. [https://vgy.me/NlgrGW.png](url)
I can add the downloads manually when I put the Youtube link to the URL box and click on download or I can check the checkbox in the lower left corner. When the checkbox is checked, the download will start automatically when I copy a Youtube link. It doesnt matter how many downloads I add, they will start all immediately. I'm looking for a way that only 4 downloads can start at the same time. The other downloads should be added to the list but they should start when one of the 4 downloads are finished. Just like a standard download queue that we have in download managers like FDM or jdownloader. Sorry for bad english xD

**Comment by Tyrrrz** [comment]
This has nothing to do with YoutubeExplode, but you can use [SemaphoreSlim](https://docs.microsoft.com/en-us/dotnet/standard/threading/semaphore-and-semaphoreslim)

**Comment by anideath** [comment]
mhh ok thanks. I will try to get to work :)

**Comment by Tyrrrz** [comment]
No problem :)
