### ISSUE TITLE
GetMuxedStreams always returns only two resolution 1. 720p and 2. 360

### ISSUE THREAD

**Issue by vikashhd** [Tyrrrz/YoutubeExplode#550]
### Version

6.0.1

### Details

GetMuxedStreams always returns only two resolution 1. 720p and 2. 360. How we can get other resolution of videos like 240 or 480.
Can we get all of these, is there any way to do this

### Steps to reproduce

var streamInfo = streamManifest.GetMuxedStreams()

**Comment by Tyrrrz** [comment]
Likely not in muxed form, those are pretty rare.

**Comment by vikashhd** [comment]
Hi am not getting you. I tried on various videos which are showing on youtube with 240,360,480,720,1080 but from this api am always able to find out only 360 and 720

**Comment by Tyrrrz** [comment]
The problem is that YouTube itself does not use muxed streams anymore. You might even find some videos don't have them at all.

You can read more about it in the readme: https://github.com/Tyrrrz/YoutubeExplode#downloading-video-streams (the note at the bottom)
