### ISSUE TITLE
Closed captions stopped working

### ISSUE THREAD

**Issue by Tyrrrz** [Tyrrrz/YoutubeExplode#564]
### Version

6.0.2

### Details

See nightly CI: https://github.com/Tyrrrz/YoutubeExplode/actions/runs/944665604

![image](https://user-images.githubusercontent.com/1935960/122451744-59c62c80-cf5d-11eb-88e3-4d3075312dda.png)

### Steps to reproduce

Run test: `User can get the list of available closed caption tracks on a video`

**Comment by Tyrrrz** [comment]
Most likely caused by #565 because we use `get_video_info` to resolve closed captions:
https://github.com/Tyrrrz/YoutubeExplode/blob/7813e3a2b44e81a6361c4c6250d75081ceda9711/YoutubeExplode/Videos/ClosedCaptions/ClosedCaptionClient.cs#L36

**Comment by thisistorsten** [comment]
Here you can see the patch. https://github.com/snakx/YouTubeApiSharp/commit/e7dd7720f34e7f454d44a625f5fe39c5535ec9fb
