### ISSUE TITLE
YouTube removed get_video_info endpoint

### ISSUE THREAD

**Issue by Tyrrrz** [Tyrrrz/YoutubeExplode#565]
### Version

6.0.2

### Details

It finally happened 🙂 

This now returns 404:

https://github.com/Tyrrrz/YoutubeExplode/blob/7813e3a2b44e81a6361c4c6250d75081ceda9711/YoutubeExplode/Bridge/YoutubeController.cs#L128-L154

In my last investigations I think I saw that there's an endpoint on the new API that can retrieve player response directly, so that could be used as replacement. Not sure if it can still be used as fallback for age-restricted videos though.

Related tests are failing:

![image](https://user-images.githubusercontent.com/1935960/122559782-a0b33100-cff4-11eb-8891-460129507021.png)

https://github.com/Tyrrrz/YoutubeExplode/actions/runs/948204086

### Steps to reproduce

Run test: `User can get a specific stream from a video(videoId: "SkRSXFQerZs")`

**Comment by thisistorsten** [comment]
I have fixed it here https://github.com/snakx/YouTubeApiSharp
