### ISSUE TITLE
Cannot retrieve HLS manifest for live streams

### ISSUE THREAD

**Issue by Tyrrrz** [Tyrrrz/YoutubeExplode#566]
### Version

6.0.2, 6.0.3

### Details

```
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:52.11]     User can get HTTP live stream URL from a video [FAIL]
Error: User can get HTTP live stream URL from a video: YoutubeExplode.Exceptions.YoutubeExplodeException : Could not extract HTTP Live Stream manifest URL. Video '5qap5aO4i9A' is likely not a live stream.
  Failed User can get HTTP live stream URL from a video [388 ms]
  Error Message:
   YoutubeExplode.Exceptions.YoutubeExplodeException : Could not extract HTTP Live Stream manifest URL. Video '5qap5aO4i9A' is likely not a live stream.
  Stack Trace:
     at YoutubeExplode.Videos.Streams.StreamClient.GetHttpLiveStreamUrlAsync(VideoId videoId, CancellationToken cancellationToken) in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Videos\Streams\StreamClient.cs:line 344
   at YoutubeExplode.Tests.StreamsSpecs.User_can_get_HTTP_live_stream_URL_from_a_video() in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode.Tests\StreamsSpecs.cs:line 231
--- End of stack trace from previous location ---
```

### Steps to reproduce

Run test: `User can get HTTP live stream URL from a video`

**Comment by TaoziDB** [comment]
for live streams, such as https://www.youtube.com/watch?v={videoId}
in html data using newest browser user-agent:
between "var ytInitialPlayerResponse = " and ";var meta =", 
you can get json string of player response,
and "hlsManifestUrl" is the master m3u8 url of all resolutions

**Comment by vikashhd** [comment]
GetHttpLiveStreamUrlAsync returning error 404

**Comment by Hexer10** [comment]
Seems like the hls manifest url is present in the `WatchPage`'s player response. In my dart port I managed to make this working by using getting the watchpage and using its player response.

**Comment by Tyrrrz** [comment]
> Seems like the hls manifest url is present in the `WatchPage`'s player response. In my dart port I managed to make this working by using the watchpage and its player response.

Thanks!

**Comment by Joseph-Nathan** [comment]
any exp code please ,
i do not found player response in scraping .
