### ISSUE TITLE
Unable to open som of the projects in the solution

### ISSUE THREAD

**Issue by proff001** [Tyrrrz/YoutubeExplode#57]
So i have downloaded the source and i can only load the DemoWpf so i can't make small changes to the exemple because it can't load

Error:
`The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored on the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convet it to MSBuild 2003 format.
C:\Userthomasmel.hole\Desktop\YouTubeExplode-3.2\(DemoConsole, Tests or YoutubeExplode)\the .csprj file in the folder`

**Comment by Tyrrrz** [comment]
The other projects use the new csproj format and you need VS2017 for it.

**Comment by proff001** [comment]
Oh that explanes everything
