### ISSUE TITLE
Livestream audio is not audible for some videos

### ISSUE THREAD

**Issue by sukhesh24** [Tyrrrz/YoutubeExplode#575]
### Version

6.0.4.0

### Details

I am using vlc player version 3.0.8 for playback. for few links the audio is audible at the beginning for few sec, but afterwords it is not audible.
i observed this for following URL
https://www.youtube.com/watch?v=odmHZVWb7ws [](url)

### Steps to reproduce

Step 1 - use youtubeExplode version 6.0.4 to get streaming URL for link https://www.youtube.com/watch?v=odmHZVWb7ws 
Step 2 - play stream obtained from youtubeExplode using Vlc player.
Step 3 - stream audio is Audible at the beginning but afterwords it is not audible

**Comment by Tyrrrz** [comment]
Please try it out with new version, it might have been fixed
