### ISSUE TITLE
GetWithHighestVideoQuality downloads standard (360p) quality?

### ISSUE THREAD

**Issue by dahanj95** [Tyrrrz/YoutubeExplode#577]
### Version

6.0.4

### Details

Downloading a video with the snippet below and opened it, the quality wasn't as expected to be high quality.

### Steps to reproduce

```
  var streamManifest = await _ytClient.Videos.Streams.GetManifestAsync(id);
            var streamInfo = streamManifest.GetMuxedStreams().GetWithHighestVideoQuality();
            await _ytClient.Videos.Streams.DownloadAsync(streamInfo, path);
```

This is the code i'm using to download the video, which downloads the 480p version and not 1080p (or 4K)

Edit: My bad, after examining the manifest the muxed is 360p only and the rest are video/audio only. This can be closed.

**Comment by Tyrrrz** [comment]
Yeah, muxed streams never go to 1080p or higher, they are capped at 720p. But sometimes they might be even lower, as you noticed.
