### ISSUE TITLE
DemoConsole errors out when saving file if user passed in full video url instead of VideoId

### ISSUE THREAD

**Issue by jungjanos** [Tyrrrz/YoutubeExplode#579]
### Version

latest

### Details

I couldnt do git push/pull request. If error is on my side, sorry.

Program.cs:41:
~~var fileName = $"{videoIdOrUrl}.{streamInfo.Container.Name}";~~ current
var fileName = $"{VideoId.Parse(videoIdOrUrl).Value}.{streamInfo.Container.Name}"; <= proposed

VideoIdSpec:27:
[InlineData("https://www.youtube.com/watch?v=yIVRs6YSbOM", "yIVRs6YSbOM")] <= proposed

### Steps to reproduce

1. sart DemoConsole
2. provide: video in url format, like: https://www.youtube.com/watch?v=u_yIGGhubZs

**Comment by Tyrrrz** [comment]
Thanks, fixed :)
