### ISSUE TITLE
Progress reporting "100" twice

### ISSUE THREAD

**Issue by rqnn** [Tyrrrz/YoutubeExplode#58]
Hello!

I've recently started using the progress functionality of your library, and was a bit surprised that the following code

    private void ProgressHandler_ProgressChanged(object sender, double args, VideoInfo videoInfo) {
        if (args * 100 == 100) {
            MessageBox.Show($"video {videoInfo.Title} 100%!");
        }
    }

would send me two MessageBoxes.

Is this a bug? Am I doing it wrong?
Even though it's probably the latter, I'd really appreciate some help/info on this one.

Kind regards and thanks in advance! :)

**Comment by Tyrrrz** [comment]
Equality comparing two doubles is a bad idea.
Also why are you doing what you are doing? If you just want a message box to trigger when download is completed you can simply execute something after `await`.

**Comment by rqnn** [comment]
Oh wow, this is embarrassing. I'll probably do that, yea. Thank you!
