### ISSUE TITLE
Severe throttling on videos

### ISSUE THREAD

**Issue by tarunlightup** [Tyrrrz/YoutubeExplode#599]
### Version

latest

### Details

Starting a couple weeks ago, the high quality muxed stream we get seems to be throttled by youtube. After some research it seems like it maybe could be related to changes in descrambling (https://code.videolan.org/videolan/vlc/-/issues/26174#note_286445). I noticed that YT explode does seem to have a method UnscrambleStreamUrl, but I'm not sure if this is the same thing mentioned in that post or we should try to update this method or implement something new to handle this. Hitting the android endpoint did yield a stream that isn't throttled. 

### Steps to reproduce

Try to play a video and it either fails completely or buffers a lot due to throttling

**Comment by Tyrrrz** [comment]
Not a duplicate, I mixed up repos 🤦🏻‍♂️
