### ISSUE TITLE
Add an API for searching

### ISSUE THREAD

**Issue by Tyrrrz** [Tyrrrz/YoutubeExplode#60]
The old `SearchAsync` was removed because it returned weird results, not in line with the actual Youtube search, however having a search API would be very useful.

**Comment by djdynamix** [comment]
In case it helps anyone, I'm currently successfully using the library here: https://github.com/mrklintscher/YoutubeSearch along with YoutubeExplode, and it seems to be working well. Using this code with a WPF ListView:

listView.Items.Clear();
            string querystring = txtSearch.Text;
            int querypages = 3;

            var items = new VideoSearch();

            string vidLink = "";
            
            foreach (var item in items.SearchQuery(querystring, querypages))
            { 
                listView.Items.Add(new vidItem { Name = HttpUtility.HtmlDecode(item.Title), Url = item.Url });
            }

I then just pull a URL from the ListView into Youtube Explode with a mouse event handler.

I hope this helps.

**Comment by SlowLogicBoy** [comment]
@djdynamix nice catch, but it's a GPL -.-

**Comment by Tyrrrz** [comment]
That library just uses the normal search (https://www.youtube.com/results?search_query=test) and parses the HTML for results. This can be replicated easily but I'm not sure how volatile it is.

**Comment by SlowLogicBoy** [comment]
I think it's better to use that library separately, if you want and if there is a need just map ones model to another. I would prefer ajax/api calls instead of html parsing.

**Comment by Tyrrrz** [comment]
You can probably parse mobile version of the site: https://m.youtube.com/results?search_query=dogs&app=m. It's very compact and hasn't been changed in a long time from what I can see. You would just need to regex all video links (/watch?v=) and continuation token for next page.

**Comment by Tyrrrz** [comment]
I got it working somehow, with pages, although it's still not the same as YouTube's search but it's kinda close and better than nothing I guess.

**Comment by Tyrrrz** [comment]
Worth noting that the `Video` objects returned by the search lack keywords and their description is trimmed. This is how the request returns them...
