### ISSUE TITLE
Seek not working properly

### ISSUE THREAD

**Issue by rhom6us** [Tyrrrz/YoutubeExplode#602]
### Version

6.0.5

### Details

In SegmentedHttpStream.cs:

Currently, if I manually seek the stream ([line 76](https://github.com/Tyrrrz/YoutubeExplode/blob/8e00a5ffd552e757f0c537dc746a1870f082071c/YoutubeExplode/Utils/SegmentedHttpStream.cs#L76) == true), it will correctly read one chunk from the new position, but then [line 86](https://github.com/Tyrrrz/YoutubeExplode/blob/8e00a5ffd552e757f0c537dc746a1870f082071c/YoutubeExplode/Utils/SegmentedHttpStream.cs#L86) resets it back to the unseeked position.

### Steps to reproduce

- Step 1
  ```
  var stream = _get a stream somehow_
  stream.Seek(stream.Length / 2, SeekOrigin.Begin);
  stream.CopyTo(File.OpenWrite(...));
  ```
- Step 2
  Do this with and without the seek. Notice the outputs are the same length.

**Comment by rhom6us** [comment]
FYI, while I'm sure of the problem, I'm just eyeballing the code for my diagnosis.

I believe a `_actualPosition = Position;` after line 77 will fix it.

I would load it up, confirm what I've said, and make a PR myself, but I'm on a company machine at the moment and we're not allowed :-(

**Comment by Tyrrrz** [comment]
Thanks, I got it :)
