### ISSUE TITLE
YoutubeExplode.Convert cant be used

### ISSUE THREAD

**Issue by derech1e** [Tyrrrz/YoutubeExplode#608]
### Version

6.0.6

### Details

I recently updated my YoutubeExplode and removed the YoutubeExplode.Convert package. If I understand it correctly, then, according to the readme, I can just leave everything as it was until now. Right?

The Readme says:

```csharp
using YoutubeExplode;
using YoutubeExplode.Videos.Streams;
using YoutubeExplode.Converter; // <-- Import here. Right?

var youtube = new YoutubeClient();

// Get stream manifest
var streamManifest = await youtube.Videos.Streams.GetManifestAsync("u_yIGGhubZs");

// Select streams (1080p60 / highest bitrate audio)
var audioStreamInfo = streamManifest.GetAudioStreams().GetWithHighestBitrate();
var videoStreamInfo = streamManifest.GetVideoStreams().First(s => s.VideoQuality.Label == "1080p60");
var streamInfos = new IStreamInfo[] { audioStreamInfo, videoStreamInfo };

// Download and process them into one file
await youtube.Videos.DownloadAsync(streamInfos, new ConversionRequestBuilder("video.mp4").Build()); // <--- and use here. Right?
```
![image](https://user-images.githubusercontent.com/39240736/145602819-68296f30-9455-460f-8345-9e419bbc20c3.png)

But my IDE cant find the class.

Can you help me? What am I doing wrong?

### Steps to reproduce

- Step 1: Try to use "YoutubeExplode.Converter"
- Step 2: Try to use "ConversionRequestBuilder"

**Comment by Tyrrrz** [comment]
The package is still there. It's just part of this repository now.

![image](https://user-images.githubusercontent.com/1935960/145629581-e1e7395b-eec9-4b74-b6fb-f0489a01a958.png)
