### ISSUE TITLE
Very slow search results

### ISSUE THREAD

**Issue by hondek** [Tyrrrz/YoutubeExplode#613]
### Version

6.0.7

### Details

Hi,

When i just try search for videos, i must wait about 30 second and more for results.

Thanks for help!

### Steps to reproduce

```
var youtube = new YoutubeClient();
var results = await youtube.Search.GetResultsAsync("blender");
```

**Comment by Tyrrrz** [comment]
That just means there are a lot of results. What you're doing is loading all of them.

**Comment by DomiFchs** [comment]
Can you somehow limit the results?

**Comment by Tyrrrz** [comment]
> Can you somehow limit the results?

https://github.com/Tyrrrz/YoutubeExplode#retrieving-videos-included-in-a-playlist
