### ISSUE TITLE
GetPlaylistAsync on a YoutubeMix wont return first Video in the mix

### ISSUE THREAD

**Issue by Kriste00** [Tyrrrz/YoutubeExplode#63]
If you call `GetPlaylistAsync` on a YoutubeMix  the result wont contain the first video and it will return one extra song that is not even in the mix.

**Comment by Tyrrrz** [comment]
That's weird, can you give an example?

**Comment by Kriste00** [comment]
Of code?

**Comment by Tyrrrz** [comment]
No, of a playlist

**Comment by Kriste00** [comment]
https://www.youtube.com/watch?v=1fu3Q1giB94&index=9&list=RDEXH2AkEMLrs

**Comment by Tyrrrz** [comment]
Thanks for reporting. I'll check it out tomorrow.

**Comment by Kriste00** [comment]
Thanks :)

**Comment by Tyrrrz** [comment]
It seems like in most cases the difference is that the returned videos don't have the base video (from which the rest are mixed) and also have 1 extra video in the end.
However, in some cases like [this](https://www.youtube.com/watch?v=zcq4c0I_sVk&list=RDzcq4c0I_sVk) the returned videos appear to be completely different with the exception of few entries.

**Comment by Kriste00** [comment]
Does youtube return the wrong videos or the API?

**Comment by Tyrrrz** [comment]
It's not exactly API, it's using the backend for the embed player: https://www.youtube.com/embed?listType=playlist&list=RDEXH2AkEMLrs

**Comment by Kriste00** [comment]
How are you going to fix it then?

**Comment by Tyrrrz** [comment]
I don't know yet

**Comment by SlowLogicBoy** [comment]
Since the url gives you first videos Id maybe as a workaround we could reuse that? They probably did that to minimize response size?

**Comment by Tyrrrz** [comment]
We would have to run `GetVideoAsync` on the first video then and the user might not want that maybe

**Comment by TheOneAmir** [comment]
I used the playlist from the URL:
https://www.youtube.com/watch?v=EXH2AkEMLrs&index=1&list=RDEXH2AkEMLrs

and called:
            var playlists = _client.GetPlaylistAsync("RDEXH2AkEMLrs");
            var playlist = playlists.Result;

and got the right list of videos with the correct first video as well. Can this still be reproduced?

**Comment by Tyrrrz** [comment]
I can confirm the issue is no longer reproducible. Looks like YouTube updated their embed player to show playlists the same way their normal watch page does, so now this is working properly.
