### ISSUE TITLE
Error on Android when trying to serialize a Dictionary to HttpRequest

### ISSUE THREAD

**Issue by matheussouza97** [Tyrrrz/YoutubeExplode#630]
### Version

ver 6.1.0

### Details

This issue occurs when trying to serialize a Dictionary with the Android linker set to link all assemblies.

Changing the all dictionary by an object should solve the problem.

https://github.com/dotnet/runtime/issues/67782

### Steps to reproduce

- Install the YoutubeExplode
- Change the linker options to Link all assemblies
- Try get a GetManifestAsync.

**Comment by Tyrrrz** [comment]
Did you try the suggested workaround, namely "Add the System.Text.Json to ignore assemblies option."?

**Comment by matheussouza97** [comment]
> Did you try the suggested workaround, namely "Add the System.Text.Json to ignore assemblies option."?

Yes, i did the workaround and works, i was create this issue just to suggest the fix. :)

**Comment by Tyrrrz** [comment]
Seeing as the bug is on .NET's side, I'm just going to advise affected users to rely on the workaround mentioned in the original thread. Implementing workarounds on the side of the library doesn't seem like a good idea.

**Comment by matheussouza97** [comment]
Hello @Tyrrrz according to .NET's @eiriktsarpalis this is an expected behavior, and to fix the problem the correct solution would be this https://github.com/dotnet/runtime/issues/67782#issuecomment-1099273090

**Comment by Tyrrrz** [comment]
I disagree with him then. If the contract of the serializer breaks only on Android where it happens to use trimming (which should be an implementation detail, not a developer concern), then it's a bug in the implementation of said serializer or the trimmer. It's not the library authors' job to find workaround for obscure bugs in the BCL. The attitude of the .NET team where they continue to push their responsibility on the community is annoying but at the same time neither new or surprising.

**Comment by Tyrrrz** [comment]
I changed the dictionaries to anonymous object, see if that helps.
