### ISSUE TITLE
exception on Streams.DownloadAsyn

### ISSUE THREAD

**Issue by romidi** [Tyrrrz/YoutubeExplode#631]
### Version

6.1.0

### Details

I get following exception after calling this method for some videos for example: https://www.youtube.com/watch?v=JSio_757YVc

       youtube.Videos.Streams.DownloadAsync(streamInfo, System.IO.Path.Combine(path, filename));

Exception:
Received an unexpected EOF or 0 bytes from the transport stream.

            

### Steps to reproduce

https://www.youtube.com/watch?v=JSio_757YVc

**Comment by Tyrrrz** [comment]
It's a transient issues on Youtube's side.
