### ISSUE TITLE
Connection with generated URL closes unexpectedly

### ISSUE THREAD

**Issue by josago97** [Tyrrrz/YoutubeExplode#634]
### Version

6.0.6

### Details

I am using ffmpeg to change the audio format of a video. However, from version 6.0.6 (included) the connection with the url generated by the library closes unexpectedly. It does not happen in previous versions and it always happens after converting the first 50 seconds.
The error that appears is the following:

[tls @ 0000015f6ec9b4c0] Unable to read from sockets/s speed=1.02x
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000015f709e3180] Packet corrupt (stream = 0, dts = 2312192).
https://rr1---sn-h5q7knel.googlevideo.com/videoplayback?expire=1650303414&ei=Vk1dYpTQJvqFvdIPycCgyAY&ip=81.37.155.153&id=o-AP5TwzLiNID0l79SnoWu5Pb9auaq2eksqKX2oWFleemh&itag=140&source=youtube&requiressl=yes&mh=o-&mm=31%2C26&mn=sn-h5q7knel%2Csn-4g5lznez&ms=au%2Conr&mv=m&mvi=1&pl=17&initcwndbps=1190000&vprv=1&mime=audio%2Fmp4&gir=yes&clen=3062623&dur=192.772&lmt=1507744950113941&mt=1650281355&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgQfVnMFhpRAtZyVKRf2bsxGLVEWtLGwJv7GAXCGZW5T8CIQDBebz4d6wxqAQJnIb7jlMHDQsvvdWW7gHpNlF7e7EleA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgVJ9jzzrViN6fTt8JjftKCBdzKRuWLYvhUJWwf0c4W40CIDv4xv5knYIUgtzZABozl-QZd77MuvLNckGsusRZVDko: corrupt input packet in stream 0
[aac @ 0000015f709e7a80] Input buffer exhausted before END element found
Error while decoding stream #0:0: Invalid data found when processing input
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000015f709e3180] stream 0, offset 0xcc019: partial file
https://rr1---sn-h5q7knel.googlevideo.com/videoplayback?expire=1650303414&ei=Vk1dYpTQJvqFvdIPycCgyAY&ip=81.37.155.153&id=o-AP5TwzLiNID0l79SnoWu5Pb9auaq2eksqKX2oWFleemh&itag=140&source=youtube&requiressl=yes&mh=o-&mm=31%2C26&mn=sn-h5q7knel%2Csn-4g5lznez&ms=au%2Conr&mv=m&mvi=1&pl=17&initcwndbps=1190000&vprv=1&mime=audio%2Fmp4&gir=yes&clen=3062623&dur=192.772&lmt=1507744950113941&mt=1650281355&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgQfVnMFhpRAtZyVKRf2bsxGLVEWtLGwJv7GAXCGZW5T8CIQDBebz4d6wxqAQJnIb7jlMHDQsvvdWW7gHpNlF7e7EleA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgVJ9jzzrViN6fTt8JjftKCBdzKRuWLYvhUJWwf0c4W40CIDv4xv5knYIUgtzZABozl-QZd77MuvLNckGsusRZVDko: Unknown error
size=    9831kB time=00:00:52.43 bitrate=1536.0kbits/s speed=1.02x
video:0kB audio:9831kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000775%
[tls @ 0000015f6ec9b4c0] Failed to send close message

### Steps to reproduce

```csharp

VideoSearchResult result = await _client.Search.GetVideosAsync("Running Scared Ell & Niki") .FirstAsync();

StreamManifest streamManifest = await _client.Videos.Streams.GetManifestAsync(result.Id);
IStreamInfo streamInfo = streamManifest.GetAudioOnlyStreams().Where(a => a.Container == Container.Mp4).GetWithHighestBitrate();

Process process = Process.Start(new ProcessStartInfo
{
    FileName = "ffmpeg",
    Arguments = $"-hide_banner -i \"{streamInfo.Url}\" -ac 2 -f wav -ar 48000 pipe:1",
    UseShellExecute = false,
    RedirectStandardOutput = true,
});

**Comment by Tyrrrz** [comment]
Nothing changed about URL resolving in a while. You sure it's not a transient error?

**Comment by josago97** [comment]
I don't think so, I have tried all versions from 6.0.0 to the current one (6.1.2). From 6.0.0 to 6.0.5 (inclusive) all executions were successful; however, from 6.0.6 to 6.1.2 they all failed with the same error and at the same time (at about 50 seconds).

**Comment by Tyrrrz** [comment]
Does this still happen?

**Comment by josago97** [comment]
No, now it performs the conversion without problems
