### ISSUE TITLE
Can't rebuild the libraries in VS

### ISSUE THREAD

**Issue by Bahaa-Sobhy** [Tyrrrz/YoutubeExplode#635]
### Version

6.1.2

### Details

In Visual Studio 2022 we have problem building the libraries YouTubeExplode.dll and YouTubeExplode.Convereter.dll

When loaded the solution, I got a request to install .NET 5 and so I did, then I was told that .NET Framework 4.6.1 doesn't exist, so I changed it into .NET Framework 4.7.2

We get such errors:

'IReadOnlyDictionary<string, string>' does not contain a definition for 'GetValueOrDefault' and no accessible extension method 'GetValueOrDefault' accepting a first argument of type 'IReadOnlyDictionary<string, string>' could be found (are you missing a using directive or an assembly reference?)	YoutubeExplode (net5.0)	C:\repos\YoutubeExplode-master_v6.1.2\YoutubeExplode\Bridge\PlayerStreamInfoExtractor.cs	39	Active

'IReadOnlyDictionary<string, string>' does not contain a definition for 'GetValueOrDefault' and no accessible extension method 'GetValueOrDefault' accepting a first argument of type 'IReadOnlyDictionary<string, string>' could be found (are you missing a using directive or an assembly reference?)	YoutubeExplode (net472)	C:\repos\YoutubeExplode-master_v6.1.2\YoutubeExplode\Bridge\PlayerResponseExtractor.cs	129	Active

Argument 1: cannot convert from 'string' to 'char'	YoutubeExplode (net5.0)	C:\repos\YoutubeExplode-master_v6.1.2\YoutubeExplode\Utils\Url.cs	58	Active

The name 'HashCode' does not exist in the current context	YoutubeExplode (net5.0)	C:\repos\YoutubeExplode-master_v6.1.2\YoutubeExplode\Common\Resolution.cs	49	Active

Metadata file 'E:\My Codes\source\repos\YoutubeExplode-master_v6.1.2\YoutubeExplode\bin\Debug\net472\YoutubeExplode.dll' could not be found	YoutubeExplode.Converter (net5.0)	C:\repos\YoutubeExplode-master_v6.1.2\YoutubeExplode.Converter\CSC	1	Active

I removed the duplicated errors (from other lines).

What do we need to do in order to rebuild the libraries?

### Steps to reproduce

- Load the Solution on Visual Studio 2022
- Install .NET 5 (if it's not already installed on the System.
- Changed the requested .NET Framework4.6.1 (net461) into .NET Framework 4.7.2 (net472).
- Rebuild the Solution or the Libraries projects
![Bahaa_sshot_94](https://user-images.githubusercontent.com/7080504/163821534-e6f6afcf-835d-47ce-9d12-adfeb9ff2383.png)
.

**Comment by Tyrrrz** [comment]
You need .NET 6 SDK and .NET Framework 4.7.2 SDK (you can skip this, but you will need to remove `net472` from target frameworks in all relevant projects). If it doesn't work in VS, try to see if it works with `dotnet build`.

The errors you get don't really make sense to me.

**Comment by Tyrrrz** [comment]
Maybe also try installing this NuGet package: https://www.nuget.org/packages/Microsoft.NETFramework.ReferenceAssemblies/

**Comment by Bahaa-Sobhy** [comment]
> If it doesn't work in VS, try to see if it works with `dotnet build`.

I tried it but still I get the same errors.


> Maybe also try installing this NuGet package: https://www.nuget.org/packages/Microsoft.NETFramework.ReferenceAssemblies/

I installed it in the solution, it didn't make any difference.


> You need .NET 6 SDK and .NET Framework 4.7.2 SDK (you can skip this, but you will need to remove `net472` from target frameworks in all relevant projects).

I have SDKs installed for .NET 6, .NET Framework 4.8, 4.7.2 and 4.6.1 .

If I remove net472 and build the libraries, the libraries are built successfully in different folders, can I take the one from .NET 6 folder and use it inside a project that targets .NET framework 4.7.2? will it work or it will require my project to target .NET 6?

**Comment by Tyrrrz** [comment]
You can use the .NET Standard library in your .NET fx project

**Comment by Bahaa-Sobhy** [comment]
@Tyrrrz For some reasons, I removed the whole solution and extracted it again from the downloaded the .zip file, and it worked without any problem!

Thanks Oleksi for your attention, replies and efforts to make such library!

Slava Ukraine 🇺🇦

**Comment by Tyrrrz** [comment]
Glad it's working :)
