### ISSUE TITLE
Channels.GetUploadsAsync does not allow await keyword

### ISSUE THREAD

**Issue by raelb** [Tyrrrz/YoutubeExplode#638]
### Version

6.1.2

### Details

I'm using vs 2022. There seems to be a problem in the code

![image](https://user-images.githubusercontent.com/13108198/170106001-cffcb1f3-758d-4a50-83cf-26c02e8f9ac4.png)

### Steps to reproduce

    private static async Task<int> GetChannelVideos()
    {
        var youtube = new YoutubeClient();
        var obj = await youtube.Channels.GetUploadsAsync("UCSMOQeBJ2RAnuFungnQOxLg");
        return 0;
    }

**Comment by Tyrrrz** [comment]
Make sure to include all using statements from the readme.

**Comment by raelb** [comment]
Sorry about that, my mistake - thanks
