### ISSUE TITLE
How to extract the download link without downloading?

### ISSUE THREAD

**Issue by djdynamix** [Tyrrrz/YoutubeExplode#64]
I am trying to add YouTube video to a media player I'm building, based on the VLC libraries.

To do that I need to pass the actual link for the chosen quality stream to my media player without downloading it.

Having tried with links obtained from online "converters", streaming to my media player works perfectly, so long as the "ratebypass=true" is set, but I can't for the life of me work out how to get YouTubeExplode to spit out a link string instead of downloading it.

Please can you help?

(I'm sure this is something really simple, so sorry for using Issues for what is undoubtedly going to turn out to be a "stupid question"!)

**Comment by Tyrrrz** [comment]
When you get a `MediaStreamInfo` object, it should have a `Url` property.

**Comment by djdynamix** [comment]
Thanks Tyrrrz. That works perfectly! And thank you for a great project, and your brilliant support.

**Comment by Tyrrrz** [comment]
You are welcome, thank you for using it 😉
