### ISSUE TITLE
High ram consumption when downloading in high resolution

### ISSUE THREAD

**Issue by david127cu** [Tyrrrz/YoutubeExplode#640]
### Version

6.1.2

### Details

High ram consumption when downloading in high resolution. For cloud servers app free consumes too much.

### Steps to reproduce

Download videos in 1440p60

**Comment by Tyrrrz** [comment]
Can you post code?

**Comment by david127cu** [comment]
var youtube = new YoutubeClient();

                var video = await youtube.Videos.GetAsync(VY_URL);

                var title = video.Title; // "Collections - Blender 2.80 Fundamentals"
                var author = video.Author.Title; // "Blender"
                var duration = video.Duration; // 00:07:20


                

                
                title = ToolsBot.LimpiarCadena(title);
                //////////////////////////////////////
				
				
				var streamManifest = await youtube.Videos.Streams.GetManifestAsync(VY_URL);
				
				var audioStreamInfo = streamManifest.GetAudioStreams().OrderBy(s => s.Bitrate).Take(2).First();
                    var videoStreamInfo = streamManifest.GetVideoStreams().First(s => s.VideoQuality.Label == UL.youtube_quality); //in UL.youtube_quality is save specific resolition
                    var streamInfos = new IStreamInfo[] { audioStreamInfo, videoStreamInfo };

                    // Download and process them into one file
                    await youtube.Videos.DownloadAsync(streamInfos, new ConversionRequestBuilder(CarpetaDestino + title + ".mp4").Build());
                    UL.TheFilePath = CarpetaDestino + title + ".mp4";
                    FileInfo theFile = new FileInfo(CarpetaDestino + title + ".mp4");

                    ///////////

**Comment by Tyrrrz** [comment]
What do you qualify as "high ram consumption"? Did you test it on an isolated sample, outside of your app?
Also, you're download with conversion, which uses FFmpeg. It is known to be very resource-heavy, although it mostly relies on your CPU.
