### ISSUE TITLE
GetResultBatchesAsync will run until the infinite

### ISSUE THREAD

**Issue by pictos** [Tyrrrz/YoutubeExplode#642]
### Version

6.1.2

### Details

When you call

```csharp
await foreach (var video in youtube.Search.GetVideosAsync("cicero", token))
{
	// Some code here
}
```

this can run forever until we want to cancel the `token`, but what if I want to do some pagination? In that case, when I cancel the method I'll lose everything else.

So I would like to suggest the support for `startPage` and `endPage`, with that the method will execute during the delta between these two values and we can do pagination.

I've a code working for this feature, if you want I can submit a PR. Added new overloads to avoid breaking changes and too much modification in the API.

### Steps to reproduce

- Install the package
- Call using a very popular query
```csharp
await foreach (var video in youtube.Search.GetVideosAsync("cicero", token))
{
	// Some code here
}
```
- It can take forever

**Comment by Tyrrrz** [comment]
There is no concept of pages. Use `GetResultBatchesAsync` and end the loop at whichever point you need. One iteration corresponds to one batch returned by YouTube (roughly translates to a page, but not directly).

https://github.com/Tyrrrz/YoutubeExplode#getting-videos-included-in-a-playlist

```csharp
using YoutubeExplode;

var youtube = new YoutubeClient();

// Each batch corresponds to one request
var maxPages = 5
var curPage = 0;
await foreach (var batch in youtube.Playlists.GetVideoBatchesAsync("PLa1F2ddGya_-UvuAqHAksYnB0qL9yWDO6"))
{
    if (curPage++ >= maxPages)
	break;
}
```

**Comment by pictos** [comment]
@Tyrrrz, taking your snippet as a reference, what if I want to continue the research? For example I present a list of results and I have a button "Load More", in this case I'll need to Batch all the 5 pages again, right? Or am I missing something?

**Comment by Tyrrrz** [comment]
It's an `IAsyncEnumerable<>` so just do `GetEnumerator()` and work with the enumerator manually.

**Comment by pictos** [comment]
> It's an IAsyncEnumerable<> so just do GetEnumerator() and work with the enumerator manually.

@Tyrrrz do you have a snippet code for that? I can't see how the code will be and how that will fix the issue

**Comment by pictos** [comment]
Thanks @Tyrrrz
