### ISSUE TITLE
GetResultsAsync build problem

### ISSUE THREAD

**Issue by enderdursun** [Tyrrrz/YoutubeExplode#643]
### Version

6.2

### Details

  var youtube = new YoutubeClient();

            await foreach (var result in youtube.Search.GetResultsAsync("blender tutorials"))
            {
                // Use pattern matching to handle different results (videos, playlists, channels)
                switch (result)
                {
                    case VideoSearchResult video:
                        {
                            var id = video.Id;
                            var title = video.Title;
                            var duration = video.Duration;
                            break;
                        }
                    case PlaylistSearchResult playlist:
                        {
                            var id = playlist.Id;
                            var title = playlist.Title;
                            break;
                        }
                    case ChannelSearchResult channel:
                        {
                            var id = channel.Id;
                            var title = channel.Title;
                            break;
                        }
                }
            }

### Steps to reproduce

build errors:
- foreach statement cannot operate on variables of type 'IAsyncEnumerable<ISearchResult>' because 'IAsyncEnumerable<ISearchResult>' does not contain a public instance definition for 'GetEnumerator'
- Invalid expression term 'foreach'

**Comment by Tyrrrz** [comment]
Add the required using statements as shown in the readme
