### ISSUE TITLE
"The following content is not available on this app."

### ISSUE THREAD

**Issue by codedbycurtis** [Tyrrrz/YoutubeExplode#647]
### Version

6.2.0

### Details

When playing a video, occasionally the message "The following content is not available on this app. Watch this content on the latest version of YouTube" will appear. It does not seemed to be linked to any specific videos, and only occurs every 10 or so videos.

[It seems this is occurring due to an outdated client version being sent with the request.](https://github.com/TeamNewPipe/NewPipe/issues/8713)

### Steps to reproduce

1. Create a `YoutubeClient`.
2. Use `YoutubeClient.Videos.Streams.GetManifestAsync` with any video ID.
3. Get the URL from one of the muxed streams (although I believe this issue also occurs with audio/video-only streams) and begin playback.
4. You may need to do this up to 20 times to get the message to appear.

**Comment by Tyrrrz** [comment]
Probably need to update client version strings everywhere to whatever is latest: https://github.com/Tyrrrz/YoutubeExplode/search?q=clientVersion

Should be easy PR if so

**Comment by codedbycurtis** [comment]
Unfortunately, changing the `ANDROID` client version to `17.29.35` (which is the latest according to [APKPure](https://apkpure.com/youtube/com.google.android.youtube)) doesn't seem to have made much of a difference.
