### ISSUE TITLE
Age-restricted videos don't work anymore

### ISSUE THREAD

**Issue by Tyrrrz** [Tyrrrz/YoutubeExplode#65]
YouTube has changed something so now `get_video_info` endpoint returns an error for age-restricted videos.

**Comment by SlowLogicBoy** [comment]
Yea... You now have to be logged in to access age restricted videos...

**Comment by Tyrrrz** [comment]
After some investigation, it looks like the issue only appears when `el=info` is passed as a parameter to `get_video_info`. On the other hand, if it's omitted, some tests fail due to lack of data returned by the response.
