### ISSUE TITLE
Download the audio's small part. Is this possible with this nuget package

### ISSUE THREAD

**Issue by anirugu** [Tyrrrz/YoutubeExplode#650]
### Version

latest

### Details

I want to download the mp3 from YouTube from only from x to y. for example if there is a song that is 4 min long.  I want to download from 2:09 to 2:40.

Till now I tried to download the mp4 and later convert it to mp3 by giving ffmpeg start and end point. Now the problem is when I tried to do same I see it's download the whole video. Is it possible that I can download only the part of audio that I am looking for.

Downloading video for only small part look waste of bandwidth. If I can get the audio by giving marker, it will save a lot of time and complexity.

Is this possible now in nuget package. Is there a better way to achieve this.

### Steps to reproduce

I download video> convert it to mp3 by ffmpeg. the file I download is video. I am looking for audio only solution (partial of audio).

**Comment by anirugu** [comment]
```
static async Task GetDetails()
        {
            var youtube = new YoutubeClient();

            var streamManifest = await youtube.Videos.Streams.GetManifestAsync("https://youtube.com/watch?v=4NRXx6U8ABQ");

            var streamInfo = streamManifest.GetAudioOnlyStreams();
            //var streamInfo = streamManifest.GetAudioOnlyStreams().GetWithHighestBitrate();

            var mp4 = streamInfo.Where(x => x.Container == Container.Mp4)?.OrderByDescending(x => x.Bitrate)?.First();

        }
```

This is the code I used currently to get a MP3 file. I see ?dur in querystring of URL which is length of audiofile. Is there any querystring part  which I can modify to get the part of video I want to download

**Comment by Tyrrrz** [comment]
You'd need to get the `Stream` via `GetStreamAsync()` and then read only an X number of bytes from the stream. Calculate the required number of bytes and offset based on the stream's bitrate. This is not easy but doable. Good luck.
