### ISSUE TITLE
TypeInitializationException and FileLoadException on youtube.Channels.GetAsync()

### ISSUE THREAD

**Issue by JulioImolesi** [Tyrrrz/YoutubeExplode#651]
### Version

6.2.1

### Details

Im trying to get Channel info using below code as exemple, but an exception is thrown.

```
var youtube = new YoutubeClient();
var channel = await youtube.Channels.GetAsync(
    "https://youtube.com/channel/UCSMOQeBJ2RAnuFungnQOxLg"
);
```
1st Exception:
TypeInitializationException: The type initializer of 'YoutubeExplode.Utils.Html' threw an exception.

2nd Exception:
FileLoadException: Could not load file or assembly 'System.Text.Encoding.CodePages, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The localized assembly manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

![image](https://user-images.githubusercontent.com/14364765/187131566-627f85db-755e-47fd-9343-e26e152f16a0.png)

![image](https://user-images.githubusercontent.com/14364765/187131601-7bf48015-e353-4023-b966-1d2a4cf31095.png)

### Steps to reproduce

1: Start new project with .net Framework v4.7.2 or 4.6.1
2: Get NuGet Reference
3: Try to use this code:

`using YoutubeExplode;
`
```
var youtube = new YoutubeClient();

            var channel = await youtube.Channels.GetAsync(
                "https://youtube.com/channel/UCSMOQeBJ2RAnuFungnQOxLg"
            );

```

**Comment by Tyrrrz** [comment]
Don't use .NET Framework. If you do, install the missing dependencies (`System.Text.Encoding.CodePages` in this case) yourself. But seriously, don't use .NET Framework, it's 2022 outside.
