### ISSUE TITLE
Audio downloaded with conversion is capped at 160kbps bitrate

### ISSUE THREAD

**Issue by BlyZeYT** [Tyrrrz/YoutubeExplode#666]
### Version

6.2.4

### Details

YouTube Video Link: [https://www.youtube.com/watch?v=g6jK6blyPc4](https://www.youtube.com/watch?v=g6jK6blyPc4)

I get an 237kbps webm audio stream but when I download it the file properties show it as 160kbps.

I guess this a limitation from YouTube but how do I even get this 237kbps stream in the first place?

### Steps to reproduce

Get the stream:
`var audioStream = manifest.GetAudioOnlyStreams().First(x => (int)x.Bitrate.KiloBitsPerSecond == kbpsBitrate);`

Download it (Tried saving as webm and mp3):
```
await Videos.DownloadAsync(fullStream, new ConversionRequestBuilder($"{filePathAndTitle}.{(onlyAudio ? ".mp3" : ".mp4")}")
                .SetFFmpegPath(FFmpegPath).SetPreset(ConversionPreset.UltraFast).SetContainer(onlyAudio ? "mp3" : "mp4").Build(),
                new Progress<double>(x => progress(x)), _cts.Token);
```

See in file properties only 160kbps bitrate

**Comment by Tyrrrz** [comment]
Birate is hard-capped here to work around a bug in FFmpeg: https://github.com/Tyrrrz/YoutubeExplode/blob/fe9a32f0dc59896e2c3b2f4bea2491fc250ef0e7/YoutubeExplode.Converter/Converter.cs#L69-L72

It should probably be raised to whatever is the maximum bitrate YouTube supports.

**Comment by BlyZeYT** [comment]
> Bitrate is hard-capped here to work around a bug in FFmpeg:
> 
> https://github.com/Tyrrrz/YoutubeExplode/blob/fe9a32f0dc59896e2c3b2f4bea2491fc250ef0e7/YoutubeExplode.Converter/Converter.cs#L69-L72
> 
> It should probably be raised to whatever is the maximum bitrate YouTube supports.
> 
> That's for mp3. I don't know what happens with webm.

When I do it with webm the exact same happens

**Comment by Tyrrrz** [comment]
Are you sure the original audio stream is actually 237kbps? I was under the impression it tops out at 165kbps for webm containers.

**Comment by BlyZeYT** [comment]
> Are you sure the original audio stream is actually 237kbps? I was under the impression it tops out at 165kbps for webm containers.

Yes I made a breakpoint an kbps is 237 i'll send a screen in a second :)

**Comment by BlyZeYT** [comment]
> Are you sure the original audio stream is actually 237kbps? I was under the impression it tops out at 165kbps for webm containers.

![Bild_2022-11-08_075233488](https://user-images.githubusercontent.com/95288041/200494877-cd05f93d-ef94-46b0-b4e9-93312702ae3f.png)

That's the audio stream.

**Comment by Tyrrrz** [comment]
Interesting, maybe they raised it.

If you download the stream without conversion (i.e. not through `YoutubeExplode.Converter`), does the player still show 237kbps?

**Comment by BlyZeYT** [comment]
> Interesting, maybe they raised it.
> 
> If you download the stream without conversion (i.e. not through `YoutubeExplode.Converter`), does the player still show 237kbps?

When I download only the audio stream without conversion the bitrate is the same

**Comment by BlyZeYT** [comment]
With that download method thats from FFmpegCore its also the same

```
await FFMpegArguments
                    .FromUrlInput(new Uri(audioStream.Url))
                    .OutputToFile(filePathAndTitle + ".mp3", true, x =>
                    {
                        x.WithArgument(new FFMpegCore.Arguments.SpeedPresetArgument(FFMpegCore.Enums.Speed.UltraFast));
                        x.WithCustomArgument($"-ss {startTime} -t {endTime}");
                        x.WithFastStart();
                        x.UsingShortest(true);
                        x.UsingMultithreading(true);
                    })
                    .NotifyOnProgress(x => progress(x), endTime)
                    .CancellableThrough(_cts.Token)
                    .ProcessAsynchronously();
```

**Comment by Tyrrrz** [comment]
Might be some default setting in FFmpeg that we could override?

**Comment by BlyZeYT** [comment]
> Might be some default setting in FFmpeg that we could override?

I have no idea😅

**Comment by BlyZeYT** [comment]
> Might be some default setting in FFmpeg that we could override?

When I do it like this I get 224kbps instead of 237kbps xD

```
await FFMpegArguments
                    .FromUrlInput(new Uri(audioStream.Url))
                    .OutputToFile(filePathAndTitle + ".mp3", true, x =>
                    {
                        x.WithArgument(new FFMpegCore.Arguments.SpeedPresetArgument(FFMpegCore.Enums.Speed.UltraFast));
                        x.WithArgument(new FFMpegCore.Arguments.AudioBitrateArgument(kbpsBitrate));
                        x.WithCustomArgument($"-ss {startTime} -t {endTime}");
                        x.WithFastStart();
                        x.UsingShortest(true);
                        x.UsingMultithreading(true);
                    })
                    .NotifyOnProgress(x => progress(x), endTime)
                    .CancellableThrough(_cts.Token)
                    .ProcessAsynchronously();
```

**Comment by Tyrrrz** [comment]
I think what might be happening is that FFmpeg converts the media from constant bitrate to variable bitrate, to reduce file size while keeping quality more or less lossless.

As for this:

> When I do it like this I get 224kbps instead of 237kbps xD

It might be because FFmpegCore and YoutubeExplode counts units differently (1024 bytes in kilobyte vs 1000)?
