### ISSUE TITLE
client.GetVideoAsync("id"); stopped working

### ISSUE THREAD

**Issue by Kadosa-Peter** [Tyrrrz/YoutubeExplode#67]
Hi

client.GetVideoAsync is throwing the following exception: 
Response status code does not indicate success: 404 (Not Found).

**Comment by TheInsaneBro** [comment]
I have this problem too since about 40 minutes.
[Example video](https://www.youtube.com/watch?v=Mq5ZyeIsDQ8)

**Comment by HiradNikoo** [comment]
Hi I have the same issue. It says the video exist in checking method but in this method give the exact error 404

**Comment by darkdoctor** [comment]
https://github.com/Tyrrrz/YoutubeExplode/issues/66

**Comment by Tyrrrz** [comment]
Since the issues are the same, i'll move the discussion to #66.
