### ISSUE TITLE
Error: Get the channel metadata by handle URL

### ISSUE THREAD

**Issue by PhapHanh** [Tyrrrz/YoutubeExplode#676]
### Version

6.2.5

### Details

Use browser, on the website: https://www.youtube.com/user/PhatPhapUngDungTVTV
click VIDEO, will go to URL: https://www.youtube.com/@PhatPhapUngDungPPUD/videos
Now, try get by handle of link: https://www.youtube.com/@PhatPhapUngDungPPUD

### Steps to reproduce

`using YoutubeExplode;

var youtube = new YoutubeClient();

var channel = await youtube.Channels.GetByHandleAsync("https://www.youtube.com/@PhatPhapUngDungPPUD");`

Exception:
HttpRequestException: Response status code does not indicate success: 404 (NotFound).
Request: Method: GET,
RequestUri: 'https://www.youtube.com/c/phatphapungdungppud?hl=en'

**Comment by Tyrrrz** [comment]
> Use browser, on the website: [youtube.com/user/PhatPhapUngDungTVTV](https://www.youtube.com/user/PhatPhapUngDungTVTV) click VIDEO, will go to URL: [youtube.com/@PhatPhapUngDungPPUD/videos](https://www.youtube.com/@PhatPhapUngDungPPUD/videos) Now, try get by handle of link: [youtube.com/@PhatPhapUngDungPPUD](https://www.youtube.com/@PhatPhapUngDungPPUD)

https://www.youtube.com/@PhatPhapUngDungPPUD returns 404 for me

![image](https://user-images.githubusercontent.com/1935960/210160778-8d459a27-f4c1-45c5-bbfb-619023f8c81f.png)
