### ISSUE TITLE
Response status code does not indicate success: 404 (Not Found)

### ISSUE THREAD

**Issue by Mds92** [Tyrrrz/YoutubeExplode#68]
It works well, from today this lib dropped in an exception for each YouTube links:
e.g:
You can test `https://www.youtube.com/watch?v=6pxRHBw-k8M` in your demo project

**Comment by MeteorBurn** [comment]
No longer download a video. This error occurs.

**Comment by Mds92** [comment]
So how should I write the code to work?

**Comment by Tyrrrz** [comment]
Same as #66
