### ISSUE TITLE
Streams are throttled down to a very low speed

### ISSUE THREAD

**Issue by Tyrrrz** [Tyrrrz/YoutubeExplode#688]
### Version

v6.2.7

### Details

It seems that YouTube has pushed changes on February 28 that caused existing anti-throttling measures to stop working.

Right now, media streams are served at a reduced rate. The test suite takes 16x longer to run, from 15 minutes on average to 3.5 hours.

Need to investigate, but it seems that the currently employed chunking workaround is no longer effective.

### Steps to reproduce

Run any tests from `StreamSpecs`

**Comment by shaked6540** [comment]
Hey, I was wondering if there is any way to help you with this task

**Comment by raelb** [comment]
Maybe this gives a clue
https://github.com/pytube/pytube/issues/1489

**Comment by Tyrrrz** [comment]
Thanks a lot @raelb. I tried to implement the fix they mentioned in that thread.
