### ISSUE TITLE
Getting `YoutubeExplodeException: Could not extract video upload date.` for some videos

### ISSUE THREAD

**Issue by NimaAra** [Tyrrrz/YoutubeExplode#699]
### Version

6.2.11

### Details

I have found some videos which throw `YoutubeExplodeException` when doing:

```csharp
Video vid = await _yt.Videos.GetAsync("Rbt2NFCtBh4");
```

Here's another example: `riXacPUAqCk`

### Steps to reproduce

Example above.

**Comment by NimaAra** [comment]
Thank you for fixing this. When will the new _nupkg_ land on _NuGet_?

**Comment by Tyrrrz** [comment]
Yes, later today
