### ISSUE TITLE
How to use this library for Windows 10 Universal App?

### ISSUE THREAD

**Issue by yeejmeem** [Tyrrrz/YoutubeExplode#7]
Hi,
I want use your library for windows 10 app universal app, but how to? It seem doesn't support for windows 10 universal app?  It is really good library. 
Thanks,

**Comment by Tyrrrz** [comment]
Hi
I have no idea actually, don't have much experience with UWP. Perhaps the library has to be converted to PCL? 🤔

**Comment by Tyrrrz** [comment]
@yeejmeem I pushed a new nuget package (v2.1) which is built against .NET Standard 1.1. Should work on Windows 10 UWP.
