### ISSUE TITLE
Getting `YoutubeExplodeException: Could not extract video title.` for some channels.

### ISSUE THREAD

**Issue by NimaAra** [Tyrrrz/YoutubeExplode#700]
### Version

6.2.11

### Details

I have found some channels which throw `YoutubeExplodeException` when doing:

```csharp
IAsyncEnumerable<PlaylistVideo> channels = _yt.Channels.GetUploadsAsync("UC6nSFpj9HTCZ5t-N3Rm3-HA");
IReadOnlyList<PlaylistVideo> videos = await channels.CollectAsync();
```

### Steps to reproduce

Example above.

**Comment by Tyrrrz** [comment]
The problematic video is https://www.youtube.com/watch?v=4ZJWv6t-PfY, which somehow doesn't have a title
