### ISSUE TITLE
GetAudioOnlyStreams() downloaded file SampleRate and AverageBytesPerSecond are incorrect

### ISSUE THREAD

**Issue by Tivium1** [Tyrrrz/YoutubeExplode#717]
### Version

6.2.15

### Details

I downloaded a youtube video like this:
```csharp
var youtube = new YoutubeClient();
var videoId = VideoId.Parse(youtubeUrl);
var streamManifest = (await youtube.Videos.Streams.GetManifestAsync(videoId,
    cancellationToken));
var streamInfo = streamManifest.GetAudioOnlyStreams().GetWithHighestBitrate();
string pathWithDefaultExtension = $"{path}.{streamInfo.Container}";
await youtube.Videos.Streams.DownloadAsync(streamInfo, pathWithDefaultExtension,
    progress, cancellationToken);
```

it downloaded a `.webm` file and I loaded it with Naudio AudioFileReader `audioFileReader = new AudioFileReader(filePath);` but when I looked at the `AudioFileReader.WaveFormat` and the values `SampleRate` and `AverageBytesPerSecond` were not correct.

I think it is an issue with `GetAudioOnlyStreams()` because when I use `GetAudioStreams()`, it downloads `.mp4` file and when I load it again, it shows the correct values `SampleRate` and `AverageBytesPerSecond`.  

What causes this issue and how can I fix it?

### Steps to reproduce

- Install YoutubeExplode from Nuget,
- Install NAudio from Nuget,
- Download a Youtube video with YoutubeExplode using `GetAudioOnlyStreams()`
- Load the downloaded file using NAudio.Wave.AudioFileReader
- Download a Youtube video with YoutubeExplode using `GetAudioStreams()`
- Load the downloaded file using NAudio.Wave.AudioFileReader
- Compare the 2 AudioFileReader.WaveFormat values.

**Comment by Tyrrrz** [comment]
`GetAudioStreams()` can return either audio-only or muxed streams, so it really depends on what is the actual stream that you're getting. I'm not entirely sure how `NAudio` calculates bitrate, but the values that YoutubeExplode provides are extracted from YouTube's metadata.
