### ISSUE TITLE
Stream transmission error with ffmpeg

### ISSUE THREAD

**Issue by AntonioGuillen123** [Tyrrrz/YoutubeExplode#720]
### Version

6.2.15

### Details

I am using the Youtube explode library to download an audio and play it via streaming using Ffmpeg. In certain videos the transmission is cut off when an error occurs. Attached at the end of the comment a link to the repository with a project to reproduce the bug. The error is the following:

```
Output #0, s16le, to 'pipe:1':
  Metadata:
    encoder         : Lavf60.3.100
  Stream #0:0(eng): Audio: pcm_s16le, 48000 Hz, stereo, s16, 1536 kb/s (default)
    Metadata:
      encoder         : Lavc60.3.100 pcm_s16le
[tls @ 0000022735afc000] Error in the pull function./s speed=0.366x
[tls @ 0000022735afc000] IO error: Error number -10054 occurred
[tls @ 0000022735afc000] The specified session has been invalidated for some reason.
    Last message repeated 1 times
Error demuxing input file 0: I/O error
https://rr1---sn-gxqpgpn-h5ql.googlevideo.com/videoplayback?expire=1687888451&ei=482aZJ-YHtCAp-oPos-DqAo&ip=185.197.91.132&id=o-AMcAlraUZ7YIPKPqDLSU0hBm3sTPkZaqipGdZi6LUVhk&itag=251&source=youtube&requiressl=yes&mh=9c&mm=31%2C29&mn=sn-gxqpgpn-h5ql%2Csn-h5qzened&ms=au%2Crdu&mv=m&mvi=1&pl=22&initcwndbps=1465000&vprv=1&mime=audio%2Fwebm&gir=yes&clen=3165047&dur=191.461&lmt=1655824444374162&mt=1687866565&fvip=3&keepalive=yes&fexp=24007246%2C24362685&beids=24350017&c=ANDROID_TESTSUITE&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgEowVydFXc-vV2RjNr0IiqfbCH0esaJ7actp9NOE1ewcCIQDr1C-sx2rtKpmp-FvU-s3Osg9YKcOi8XAUcRqRavroQQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgQ_mAoKXQRDhidSbxT8Is3NQNIym0j36MovqWljcgiFUCIH-48zHJfB9Vluut6u5AOElPWBhlI0UAAclCtGfAbG4b: I/O error
size=   20808kB time=00:01:50.96 bitrate=1536.2kbits/s speed=0.365x
```

Ffmpeg version: 6.0
SO version: Windows 10 Pro 22H2
Project with error: https://github.com/AntonioGuillen123/YoutubeExplodeBug

### Steps to reproduce

1. Get the audio only link of a youtube video
2. Create process with ffmpeg to transform the audio
3. Read the audio like a streaming

**Comment by Tyrrrz** [comment]
Piping a YouTube stream via URL like that is, at the very least, suboptimal because FFmpeg won't be able to perform throttling workarounds to download it efficiently. You should fetch the stream using YoutubeExplode and pipe it at the byte level to FFmpeg. That way you should get a better error message too, should it occur.

**Comment by josago97** [comment]
I have encountered this bug too. What happens is that if you download the audio from the video and then pass it to ffmpeg it works. What doesn't work is streaming from a url (as in this case). In addition, the time that passes until the transmission is cut off by the bug varies depending on the video.

**Comment by Tyrrrz** [comment]
> I have encountered this bug too. What happens is that if you download the audio from the video and then pass it to ffmpeg it works. What doesn't work is streaming from a url (as in this case). In addition, the time that passes until the transmission is cut off by the bug varies depending on the video.

It's not a bug, YouTube stream URLs are just not meant to be used directly

**Comment by josago97** [comment]
> > También me he encontrado con este error. Lo que pasa es que si descargas el audio del video y luego lo pasas a ffmpeg funciona. Lo que no funciona es el streaming desde una url (como en este caso). Además, el tiempo que transcurre hasta que el bug corta la transmisión varía según el video.
> 
> No es un error, las URL de transmisión de YouTube simplemente no están destinadas a usarse directamente

Do these urls have a lifetime then?

**Comment by Tyrrrz** [comment]
> Do these urls have a lifetime then?

Yes, but most importantly, they need a lot of different workarounds to deal with transient failures and throttling. If you fetch a stream through `Youtube.Videos.Streams.GetAsync(...)`, the returned stream object takes care of all that for you:

https://github.com/Tyrrrz/YoutubeExplode/blob/015c0030c6e5568cf5639fe5202062377d99be70/YoutubeExplode/Videos/Streams/MediaStream.cs#L56-L122

**Comment by josago97** [comment]
Oh I see, thank you very much
