### ISSUE TITLE
Inheritance security rules violated while overriding member

### ISSUE THREAD

**Issue by marcom1978** [Tyrrrz/YoutubeExplode#723]
### Version

6.2.15

### Details

When I test the project in visual studio everything works, once published to the server I get the error "Inheritance security rules violated while overriding member".

### Steps to reproduce

            // Get video id
            string id = context.Request.QueryString["Id"];

            // Get YouTube stream
            var youtube = new YoutubeClient();
            var videoUrl = "https://www.youtube.com/watch?v=" + id;
            var streamManifest = await youtube.Videos.Streams.GetManifestAsync(videoUrl);
            var streamInfo = streamManifest.GetAudioOnlyStreams().GetWithHighestBitrate();
            var stream = await youtube.Videos.Streams.GetAsync(streamInfo);

            // Copy YouTube stream in memorystream
            var memoryStream = new MemoryStream();
            await stream.CopyToAsync(memoryStream);
            var bytes = memoryStream.ToArray();

**Comment by Tyrrrz** [comment]
That has nothing to do with the library. Sounds like a C# compile error and the library is already precompiled so it can't trigger it.
