### ISSUE TITLE
Video 'QkOphlGvKss' does not contain any playable streams

### ISSUE THREAD

**Issue by tomsorokaleaware** [Tyrrrz/YoutubeExplode#726]
### Version

6.3.1

### Details

when I try to get video streams( streamManifest = await youtube.Videos.Streams.GetManifestAsync(video.Id);)

for https://www.youtube.com/watch?v=QkOphlGvKss

I get exception.

YoutubeExplode.Exceptions.VideoUnplayableException: Video 'QkOphlGvKss' does not contain any playable streams.
   at YoutubeExplode.Videos.Streams.StreamClient.GetManifestAsync(VideoId videoId, CancellationToken cancellationToken) in /_/YoutubeExplode/Videos/Streams/StreamClient.cs:line 227
   at YouTubeDownloader.Program.DownloadYouTubeVideo(String videoUrl, String outputDirectory) in /Users/tomaszsoroka/stp/MediaDownloader/YoutubeTester/Program.cs:line 49

With yt-dlp I can download this video 

### Steps to reproduce

-  var youtube = new YoutubeClient();
            var video = await youtube.Videos.GetAsync("https://www.youtube.com/watch?v=QkOphlGvKss");

            // Sanitize the video title to remove invalid characters from the file name
            string sanitizedTitle = string.Join("_", video.Title.Split(Path.GetInvalidFileNameChars()));

            // Get all available muxed streams
            var streamManifest = await youtube.Videos.Streams.GetManifestAsync(video.Id);

**Comment by mikaoka25** [comment]
Hey there, this issue also came up for me, why was this labeled as invalid?

**Comment by Tyrrrz** [comment]
> Hey there, this issue also came up for me, why was this labeled as invalid?

Because it was closed by the original author
