### ISSUE TITLE
Tests fails on PlaylistIds.MusicMix and PlaylistIds.VideoMix with PlaylistUnavailableException

### ISSUE THREAD

**Issue by tmm360** [Tyrrrz/YoutubeExplode#732]
### Version

v6.3.2

### Platform

Linux

### Steps to reproduce

Run tests

### Details

Tests should pass, and instead they fails

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that that this bug is reproducible on the latest version of the package
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by Tyrrrz** [comment]
Can't reproduce it locally or on CI, so need more details

**Comment by Tyrrrz** [comment]
Okay seems like it's reproducible now

**Comment by Tyrrrz** [comment]
Looks like you used the "Reject All" consent cookie and some playlists cannot be accessed. I changed the value to use the "Accept All" consent cookie instead.
