### ISSUE TITLE
Assigning video.Title to a variable is readonly and can't be modified

### ISSUE THREAD

**Issue by martingrgv** [Tyrrrz/YoutubeExplode#733]
### Version

v6.3.2

### Platform

Windows 10

### Steps to reproduce

I tried editing the title that is assigned from YouTube URL
```
var title = video.Title;

if (title.Contains('/'))
{
    title.Replace('/', '|');
}
```
Unfortunately, the `var title` is a readonly when assigned from `video.Title`

### Details

I expect the `video.Title` to be writable when assigned to a variable

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that that this bug is reproducible on the latest version of the package
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by tmm360** [comment]
Strings are immutable value types. You have to assign back to have an updated string:

```
var title = video.Title;
title = title.Replace('/', '|');
```

**Comment by Tyrrrz** [comment]
This is what you're probably trying to do:

```csharp
title = title.Replace('/', '|');
```

You can't assign `video.Title` because you're not supposed to change it.
