### ISSUE TITLE
Search feature crashes on mobile devices

### ISSUE THREAD

**Issue by jerry08** [Tyrrrz/YoutubeExplode#735]
### Version

v6.3.3

### Platform

Android

### Steps to reproduce

Executing a simple search query now crashes on mobile devices (Android and most likely iOS as well). You can replicate the issue by downloading an android emulator and running the following code:

```c#
using YoutubeExplode;
using YoutubeExplode.Common;

var youtube = new YoutubeClient();

var videos = await youtube.Search.GetVideosAsync("blender tutorials");
```

### Details

It only crashes (returns an Http 400 Bad Request message) in the latest version (v6.3.3) because of the `NonDisposableHttpContent` class in [HttpExtensions](https://github.com/Tyrrrz/YoutubeExplode/blob/master/YoutubeExplode/Utils/Extensions/HttpExtensions.cs). To be more specific, it would be [this line](https://github.com/Tyrrrz/YoutubeExplode/blob/master/YoutubeExplode/Utils/Extensions/HttpExtensions.cs#L20) in the class that was added. I haven't researched why exactly it crashes on Android but apparently copying a string content instead of copying the stream works.

### Checklist

- [x] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that that this bug is reproducible on the latest version of the package
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by imememani** [comment]
Can confirm this is happening on Android 13, search returns a `Http 400 Bad Request`.
