### ISSUE TITLE
Audio files are downloaded as WebM, Mp3 does not work

### ISSUE THREAD

**Issue by ReenigneArcher** [Tyrrrz/YoutubeExplode#738]
### Version

v6.3.4

### Platform

.NET 6.0 (Linux and macOS... maybe Windows)

### Steps to reproduce

```csharp
using YoutubeExplode;
using YoutubeExplode.Videos.Streams;

// ...

        private static void SaveMp3(string destination, string videoUrl)
        {
            Task.Run(async () =>
            {
                var youtube = new YoutubeClient();
                var streamManifest = await youtube.Videos.Streams.GetManifestAsync(videoUrl);

                // highest bitrate audio stream
                var streamInfo = streamManifest.GetAudioOnlyStreams().GetWithHighestBitrate();

                // Download the stream to a file
                await youtube.Videos.Streams.DownloadAsync(streamInfo, destination);
            });
        }

// ...
```

### Details

I am a super beginner with C#, so this could possibly be a problem with my code... although I have had this released for seven months so far, and this is a new issue that has not been reported before.

This issue is from Themerr-jellyfin (plugin for Jellyfin that adds theme songs to Movies). We use YoutubeExplode to get the audio from YouTube videos.

Anyway, a user is reporting that the downloaded audio files are corrupt and unplayable with standard media players (they at least tested in Quick Time). And Jellyfin throws an error when it tries to play as well, so the files are surely corrupted.

Original code: https://github.com/LizardByte/Themerr-jellyfin/blob/6e72a1708cf7248a7a91276cc56ebec5ba2db446/Jellyfin.Plugin.Themerr/ThemerrManager.cs#L37-L50

Original issue: https://github.com/LizardByte/Themerr-jellyfin/issues/97

I can provide further info if requested, just not sure what else you might need at this point.

P.S. They also tested my plugin with v6.3.3 of YoutubeExplode with the same results.

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that that this bug is reproducible on the latest version of the package
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by ReenigneArcher** [comment]
Some additional information. I don't think the file is actually corrupted, but I think it is downloading a `WebM` file instead of an `mp3` as it used to.

**Comment by Tyrrrz** [comment]
YouTube does not provide MP3 streams, only WEBM and MP4. Therefore, you need to convert those streams to MP3 yourself, for example using [**YoutubeExplode.Converter**](https://github.com/Tyrrrz/YoutubeExplode/tree/master/YoutubeExplode.Converter). This is not new, it has always been like that.

**Comment by ReenigneArcher** [comment]
Interesting, maybe be some changes to YouTube itself where the highest bitrate item is now a WebM stream instead of Mp4. Anyway, thanks for this library!
