### ISSUE TITLE
Live streams?

### ISSUE THREAD

**Issue by IcecreamBurglar** [Tyrrrz/YoutubeExplode#74]
Just a quick question, would this work with live-streaming videos?

**Comment by DominicMaas** [comment]
In my pull request [here](https://github.com/Tyrrrz/YoutubeExplode/pull/73) I've exposed the ability to get the `hlsvp` tag. This returns a HTTP live streaming playlist ([Wikipedia Article](https://en.wikipedia.org/wiki/HTTP_Live_Streaming)) which you can then use to live stream videos. I use it for audio, have not done much testing with video.

**Comment by IcecreamBurglar** [comment]
Thanks, I might need that for a current project.

**Comment by Tyrrrz** [comment]
Feature implemented by @DominicMaas in #73 is now in pre-release 4.1.0-alpha.
