### ISSUE TITLE
403 (Forbidden)

### ISSUE THREAD

**Issue by NetoBatista** [Tyrrrz/YoutubeExplode#742]
### Version

6.3.4

### Platform

.Net 6.0 / Windows 11

### Steps to reproduce

var streamManifest = await _youtube.Videos.Streams.GetManifestAsync(request.UrlYoutube);
var streamInfo = streamManifest.GetMuxedStreams().GetWithHighestVideoQuality();
return await _youtube.Videos.Streams.GetAsync(streamInfo);

### Details

Erro: System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden). at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode() at YoutubeExplode.Videos.Streams.StreamClient.GetManifestAsync(VideoId videoId, CancellationToken cancellationToken) in /_/YoutubeExplode/Videos/Streams/StreamClient.cs:line 255

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that that this bug is reproducible on the latest version of the package
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [X] I have sponsored this project

**Comment by Tyrrrz** [comment]
Not actionable bug report
