### ISSUE TITLE
Extracting images from livestream?

### ISSUE THREAD

**Issue by IcecreamBurglar** [Tyrrrz/YoutubeExplode#75]
If anybody would care to take the time to explain these two points to me, I'd appreciate it.
So using the alpha release with the livestream support, how would one go about actually

1) Getting the stream
2) Decoding frames from it

**Comment by Tyrrrz** [comment]
@DominicMaas

**Comment by DominicMaas** [comment]
It really depends on what platform your developing for. 

The live-steam url exposed in the new alpha update is a "HLS playlist" url. See more [here](https://en.wikipedia.org/wiki/HTTP_Live_Streaming). I don't know much about the inner workings of it (as UWP handles most of the work for me) so you will have to research how to play HLS videos/streams with your development platform.

You can see a simple UWP app using this live stream functionality [here](https://github.com/DominicMaas/YouTubeExplode-UWP-Example/blob/master/YouTubeExplodeLiveStreamTest/MainPage.xaml.cs), but I don't think it will help you that much.

What platform are you developing for? I can maybe help you get started.

**Comment by IcecreamBurglar** [comment]
Hmm. Well, I'm writing this animated wallpaper engine using MonoGame as its back-end. So I'ds have to extract each frame and deserialize it into a Texture that can be rendered on-screen. Theoretically, I could embed a winforms control over the monogame window though, which would probably be easier.

**Comment by Tyrrrz** [comment]
Is it possible to do what UWP does natively and expose the playlist as a list of `MediaStream` that the user can work with?

**Comment by IcecreamBurglar** [comment]
Not sure I understand at all what you're saying, but I'm waiting for the issue https://github.com/unosquare/ffmediaelement/issues/110 to get fixed then I'll just use that along with the HLS url gathered from youtubeexplode

**Comment by Tyrrrz** [comment]
Alright, in that case can I close the issue?

**Comment by IcecreamBurglar** [comment]
Ah yeah, sure. Tbh I forgot about it, sorry 'bout that.

**Comment by mariodivece** [comment]
@IcecreamBurglar unosquare/ffmediaelement#110 should be fixed now. could you test and post your results please?
