### ISSUE TITLE
GetManifestAsync silent crash on Android

### ISSUE THREAD

**Issue by Speed258** [Tyrrrz/YoutubeExplode#752]
### Version

6.3.7

### Platform

.NET 7.0

### Steps to reproduce

1, Create latest .NET MAui project 2023-11-13
2. Load video list from playlist
3. Using any video url try get manifest
4. Launch application in ANDROID emulator mine is Pixed 5 API 33

![image](https://github.com/Tyrrrz/YoutubeExplode/assets/22223298/b6675c19-bcc0-47f0-a478-657e67c3acc6)
This is how I call manifest

Crash occur in YotubeHttpHandler:
![image](https://github.com/Tyrrrz/YoutubeExplode/assets/22223298/da830961-429d-40b9-8eae-0eb4cd202183)
And after that code hungs up in infinity loading

Windows:
- Works everything ok.

### Details

Bug only appears in Android platform(didnt tested on ios). But here is interesting part I'm able to retrieve list from playlist on both platforms, but GetManifestAsync only works in windows

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that that this bug is reproducible on the latest version of the package
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by Tyrrrz** [comment]
Do any of the older versions work?

**Comment by Speed258** [comment]
> Do any of the older versions work?

Tested from 6.3.4 to 6.3.7 none worked on Android, windows everything fine

**Comment by Tyrrrz** [comment]
That's weird

**Comment by Speed258** [comment]
> That's weird

At first I thought issue is with HttpClient, but if that would be true none http request would worked, but 
![image](https://github.com/Tyrrrz/YoutubeExplode/assets/22223298/3f1f443c-7dfa-446c-8a4a-e5deb23eea3f)
this part of the code works on all platforms, so theory with HttpClient was quickly denied

**Comment by hanssonfredrik** [comment]
Having the same issues with .NET MAUI on Android
Using version 6.3.11 of YoutubeExplode.

Getting the following errors on GetManifest:

`Exception of type 'Android.OS.NetworkOnMainThreadException' was thrown.`

Have tried adding ConfigureAwait(false) as someone suggested without luck:

`            var streamManifest = await youtube.Videos.Streams.GetManifestAsync(videoUrl).ConfigureAwait(false);
`

Works fine on iOS.

**Comment by Tyrrrz** [comment]
Does `await Task.Run(async () => await youtube.Videos.Streams.GetManifestAsync(videoUrl))` do anything to alleviate the issue?

**Comment by hanssonfredrik** [comment]
@Tyrrrz , that did it! Works on both Android and iOS. Thanks! :)

**Comment by Tyrrrz** [comment]
@Speed258 did you get the same error as above?

**Comment by Nickk888SAMP** [comment]
I can confirm! That did fix the issue! Thanks @Tyrrrz !
