### ISSUE TITLE
Extract video published date

### ISSUE THREAD

**Issue by darkdoctor** [Tyrrrz/YoutubeExplode#76]
Greetings Dear Tyrrrz. 

First of all, thanks for your great job with this library. It is very helpful to me. 

I would like to ask if there is any possibility to get the published date for a video with your library, or if this feature is going to be released in next released. 

Thanks.

**Comment by Tyrrrz** [comment]
Greetings Dear DarkDoctor.
I'll look into it. As long as it's available for playlist videos, it should be doable.

**Comment by Tyrrrz** [comment]
Playlist videos have `<added>` element which seems to correspond to the publish date, although it's culture-sensitive. For the normal videos, there is no metadata value for this but it can be extracted from the watch page.

**Comment by Tyrrrz** [comment]
Seems like culture-specifics can be eliminated with `&hl=en` for playlists as well. Looks doable.

**Comment by Tyrrrz** [comment]
Enjoy testing https://www.nuget.org/packages/YoutubeExplode/4.1.0-alpha2
