### ISSUE TITLE
Doesn't work on Xamarin Android

### ISSUE THREAD

**Issue by hibrahimsahin** [Tyrrrz/YoutubeExplode#78]
can you add an example project of xamarin?

**Comment by Tyrrrz** [comment]
What problems are you having?

**Comment by hibrahimsahin** [comment]
Actually working but not downloading videos.There is no error.

**Comment by Tyrrrz** [comment]
Show us the code you're using to download.

**Comment by hibrahimsahin** [comment]
using Android.App;
using Android.Widget;
using Android.OS;
using System;
using System.IO;
using System.Threading.Tasks;
using Tyrrrz.Extensions;
using YoutubeExplode;
using YoutubeExplode.Models.MediaStreams;

namespace App14
{
    [Activity(Label = "App14", MainLauncher = true)]
    public class MainActivity : Activity
    {
       protected override void OnCreate(Bundle savedInstanceState)
        {
            base.OnCreate(savedInstanceState);

            // Set our view from the "main" layout resource
            SetContentView(Resource.Layout.Main);
            EditText editText = FindViewById<EditText>(Resource.Id.edit1);

            Button button = FindViewById<Button>(Resource.Id.button1);
            button.Click += Button_Click;

           
        }

        public static string NormalizeId(string input)
            {
                if (!YoutubeClient.TryParseVideoId(input, out var id))
                    id = input;
                return id;
            }

           public static string NormalizeFileSize(long fileSize)
            {
                string[] units = { "B", "KB", "MB", "GB", "TB", "PB", "EB", "ZB", "YB" };
                double size = fileSize;
                var unit = 0;

                while (size >= 1024)
                {
                    size /= 1024;
                    ++unit;
                }

                return $"{size:0.#} {units[unit]}";
            }

       
            

           
        public static async Task MainAsync()
        {

            var client = new YoutubeClient();

            var id = "https://www.youtube.com/watch?v=IL4TBwUUd0Q";
            id = NormalizeId(id);
            var video = await client.GetVideoAsync(id);
            var streamInfoSet = await client.GetVideoMediaStreamInfosAsync(id);
            var streamInfo = streamInfoSet.Muxed.WithHighestVideoQuality();
            var normalizedFileSize = NormalizeFileSize(streamInfo.Size);
            var fileExtension = streamInfo.Container.GetFileExtension();
            var fileName = $"{video.Title}.{fileExtension}";


            fileName = fileName.Replace(Path.GetInvalidFileNameChars(), '_');


            var progress = new Progress<double>(p => Console.Title = $"YoutubeExplode Demo [{p:P0}]");
            await client.DownloadMediaStreamAsync(streamInfo, fileName, progress);
        }
        public void Button_Click(object sender, EventArgs e)
        {
            MainAsync().GetAwaiter().GetResult();
        }

    }
}

**Comment by Tyrrrz** [comment]
I'm pretty sure your filename is the problem, try saving it somewhere like `Environment.SpecialFolder.Personal`

**Comment by hibrahimsahin** [comment]
I try but  video does not downlod . I'm a new software developer. Could you tell me more clearly? Please...

**Comment by Tyrrrz** [comment]
https://developer.xamarin.com/guides/xamarin-forms/application-fundamentals/files/#Loading_and_Saving_Files

**Comment by hibrahimsahin** [comment]
I tried. I could not . I have updated the code above .Thank you everything

**Comment by Tyrrrz** [comment]
Try replacing your button handler

```csharp
public async void Button_Click(object sender, EventArgs e)
{
    await MainAsync();
}
```

**Comment by hibrahimsahin** [comment]
When I do :

public async void Button_ClickAsync(object sender, EventArgs e)
        {
            await MainAsync();
        }

it gives "An unhandled exception occured." error.

**Comment by Tyrrrz** [comment]
And what's the message?

**Comment by hibrahimsahin** [comment]
that is all "An unhandled exception occured."

**Comment by Tyrrrz** [comment]
Try putting a try/catch and debug the exception
