### ISSUE TITLE
500 error when calling GetManifestAsync

### ISSUE THREAD

**Issue by krispy52** [Tyrrrz/YoutubeExplode#782]
### Version

6.3.13

### Platform

.NET 8.0/Windows 11

### Steps to reproduce

var youtube = new YoutubeClient();
var streamManifest = await youtube.Videos.Streams.GetManifestAsync($"https://www.youtube.com/watch?v=IA3WxTTPXqQ");

### Details

Expected Behavior: Returns valid StreamManifest
Actual Behavior: HttpRequestException thrown

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the package
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by Tyrrrz** [comment]
500 errors can happen sometimes and they're indicative of transient failures on YouTube's side

**Comment by krispy52** [comment]
@Tyrrrz This is not a transient failure, I am able to reproduce it. The issue might be specific to long duration videos, YouTube video id: IA3WxTTPXqQ is 37hrs. I was able to get manifest for videos up to 30hrs in the past without any issues.

**Comment by Tyrrrz** [comment]
Indeed, I can reproduce this too.

**Comment by RamiroGarrido** [comment]
I'm having the same issue with any URL...help please

**Comment by Tyrrrz** [comment]
This seems to have been fixed, either by #818 or by YouTube themselves (seeing as 500 error would indicate their fault).

![image](https://github.com/user-attachments/assets/c7547bf0-e448-480a-8da8-58948d29550a)
