### ISSUE TITLE
Xml documentation

### ISSUE THREAD

**Issue by darkdoctor** [Tyrrrz/YoutubeExplode#79]
Greetings dear Tyrrz. 

Hope you are doing fine.

I am studying your code and looks very well structured. 

Can you please teach me how to use xml documentation to display in intellisense: Usage, Exceptions from a method. 

I have tried many ways but unsuccessful. 

Best Regards.

**Comment by Tyrrrz** [comment]
https://docs.microsoft.com/en-us/dotnet/csharp/codedoc

Please avoid asking questions not related directly to YoutubeExplode here.

**Comment by darkdoctor** [comment]
Thanks Dear.
