### ISSUE TITLE
Can't retrieve Muxed  720p quality in any video

### ISSUE THREAD

**Issue by muhamedRadwan** [Tyrrrz/YoutubeExplode#797]
### Version

6.3.16

### Platform

windows 11

### Steps to reproduce

720p quality dropped from 5 days .

### Details

720p quality dropped from 5 days .

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the package
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by Tyrrrz** [comment]
Don't rely on muxed streams too much. They are rare and will get rarer. I wouldn't be surprised if YouTube removes them altogether at some point.

**Comment by moazelsawaf** [comment]
@Tyrrrz 

Thank you for your efforts in developing and maintaining this package 🙏🏻

Could you please provide more clarity on what alternatives to **muxed** streams we should consider? The `adaptiveFormats` list seems to return either **video-only** or **audio-only** streams. What would you recommend as the best approach moving forward?

**Comment by Tyrrrz** [comment]
> The `adaptiveFormats` list seems to return either **video-only** or **audio-only** streams. What would you recommend as the best approach moving forward?

Depends on what you're trying to achieve. If your goal is to stream the video as if playing on YouTube proper, you should play the audio-only and the video-only stream simultaneously.

If your goal is to download the video, then you should download each of the streams and mux them yourself, using a tool like `ffmpeg` via [YoutubeExplode.Converter](https://github.com/Tyrrrz/YoutubeExplode/blob/master/YoutubeExplode.Converter).
