### ISSUE TITLE
List of Extensions

### ISSUE THREAD

**Issue by ajurga** [Tyrrrz/YoutubeExplode#81]
Hi, I would like to list of video extensions in ComboBox to download choose version without using XAML, like you did.  
I used:
var ext = streamInfo.Container.GetFileExtension();
but it gives only mp4 format.
Can you help me?
I will be greatly appreciated :)

**Comment by Tyrrrz** [comment]
`GetFileExtension` returns the file extension for the given container. You're calling it on one stream. If you want all of them, you can do `streamInfoSet.GetAll().Select(s => s.Container.GetFileExtension()).Distinct()`

**Comment by ajurga** [comment]
Thank you very much :)
