### ISSUE TITLE
Exception: Video watch page is broken. Please try again in a few minutes.

### ISSUE THREAD

**Issue by kcrg** [Tyrrrz/YoutubeExplode#810]
### Version

6.4.0

### Platform

.NET 9 / Ubuntu 24.04

### Steps to reproduce

- Step 1
Call await youtubeClient.Videos.GetAsync(youtubeId);

- Step 2 
Observe exception like below:
```
YoutubeExplode.Exceptions.YoutubeExplodeException: Video watch page is broken. Please try again in a few minutes.
   at YoutubeExplode.Videos.VideoController.GetVideoWatchPageAsync(VideoId videoId, CancellationToken cancellationToken) in /_/YoutubeExplode/Videos/VideoController.cs:line 33
   at YoutubeExplode.Videos.VideoClient.GetAsync(VideoId videoId, CancellationToken cancellationToken) in /_/YoutubeExplode/Videos/VideoClient.cs:line 37
```

### Details

Fundametal method stopped working randomly around 0:00 CET 15.09 so I guess youtube change something at their end.

"Please try again in a few minutes." I was trying again in 30min, nothing changes

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the package
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by Dariush-Tasdighi** [comment]
Hi, I've got this error too! Please fix it bro...

**Comment by kcrg** [comment]
> Please fix it bro...

Ok

**Comment by Zent01** [comment]
Will the issue be resolved?

**Comment by Duc558** [comment]
I had this problem today
Video video = null;
 try
 {
         video = await youtube.Videos.GetAsync(YTVideoLINK);
 }
 catch (YoutubeExplode.Exceptions.YoutubeExplodeException exc)
 {
        exc.Message=Video watch page is broken. Please try again in a few minutes.
  }
