### ISSUE TITLE
 Watch page is broken please try again in few minutes 

### ISSUE THREAD

**Issue by Zent01** [Tyrrrz/YoutubeExplode#812]
### Version

v6.4.0

### Platform

.NET8.0/Windows 10

### Steps to reproduce

Since yesterday and today, I've been experiencing an issue where the watch page is broken, and I receive a 'Please try again in a few minutes' message when attempting to convert video or audio. My code is not the problem, as it worked perfectly in the previous days.

### Details

I have confirmed that I'm using the latest update and even tried reinstalling it, but the issue persists. Any help or suggestions would be greatly appreciated. Thank you!

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the package
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by mugnap** [comment]
It started to happen to me too...

**Comment by kcrg** [comment]
I'm not sure but propably it's duplicate of #810

**Comment by mugnap** [comment]
> I'm not sure but propably it's duplicate of #810

When new release 6.4x with bug-fix will be released on NuGet? Thanks.

**Comment by kcrg** [comment]
> When new release 6.4x with bug-fix will be released on NuGet? Thanks.

idk, you always can build it yourself with fix and add dll to ur project.

**Comment by Tyrrrz** [comment]
Duplicate of #810
