### ISSUE TITLE
Closed captions not returned for video udfEVj4a9to

### ISSUE THREAD

**Issue by mikethea1** [Tyrrrz/YoutubeExplode#814]
### Version

6.4.1

### Platform

.NET 8 / Windows 11

### Steps to reproduce

```
YoutubeClient client = new();
VideoId id = new("udfEVj4a9to");
var captions = (await client.Videos.ClosedCaptions.GetManifestAsync(id));
Console.WriteLine(captions.Tracks.Count); // 0
```

### Details

Thanks for creating this great library!

The video https://www.youtube.com/watch?v=udfEVj4a9to has closed captions enabled and they work for me in the browser, so I would expect that caption track to be returned. However, I get an empty closed caption manifest.

This functionality works for other videos I've tried, so I wonder what might be different about this one. Apologies in advance if I'm just not using the API correctly.

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the package
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by mikethea1** [comment]
Here's another video where it doesn't work: https://www.youtube.com/watch?v=xR549adx5Go

**Comment by Tyrrrz** [comment]
For both videos I see only the auto-generated captions available in my browser (Hindi and Portuguese respectively). It sounds like you see more than just those? In any case, it's true that they don't seem to be available through YoutubeExplode so I'll investigate.

**Comment by mikethea1** [comment]
> It sounds like you see more than just those?
Nope those are all I see, but like you said YouTubeExplode wasn't finding them.

@Tyrrrz I just pulled down 6.4.2 and tested it out on those links. It works now!

Thanks so much for the quick fix!
