### ISSUE TITLE
HttpRequestException: 403 (Forbidden)

### ISSUE THREAD

**Issue by cata76** [Tyrrrz/YoutubeExplode#817]
### Version

v6.4.1

### Platform

.NET 4.7.2 / Windows Server 2016

### Steps to reproduce

Calling 'YoutubeClient.Videos.Streams.GetManifestAsync' for any video link returns HttpRequestException: 403 (Forbidden)
Last video downloaded using the same code 09/24/2024

### Details

Calling 'YoutubeClient.Videos.Streams.GetManifestAsync' for any video link returns HttpRequestException: 403 (Forbidden)

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the package
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by Zent01** [comment]
I have the same issue

**Comment by nazar067** [comment]
same

**Comment by sergiodomingo** [comment]
Same here, but .NET 8 on Linux./x64.

**Comment by Anjoland** [comment]
Same, started yesterday for me.

**Comment by Jeager2** [comment]
Same issue here. This has worked for well over a year for me. the line that fails is: 
StreamManifest streamManifest = await client.Videos.Streams.GetManifestAsync("https://youtu.be/" + id); 
The exception: 
System.Net.Http.HttpRequestException: 'Response status code does not indicate success: 403 (Forbidden).'
Suggestions? cookie? Login? Not sure where to go from here.

**Comment by mikethea1** [comment]
It's worth trying whether some other solutions like https://github.com/yt-dlp/yt-dlp work from the same IP. If they don't work, then potentially the IP is blocked by YouTube.

**Comment by AITYunivers** [comment]
Yeah sometime yesterday it seems YouTube Explode broke entirely. While yt-dlp still works fine.

**Comment by ijowett3** [comment]
Same here, getting 403 unauthorised at following code:
      
        var streamManifest = await youtube.Videos.Streams.GetManifestAsync(video.Id);

**Comment by ijowett3** [comment]
Try changing the download url to: https://www.youtube.com/watch?v=XXXXXXXXXX

**Comment by ijowett3** [comment]
I debugged the error in the code, seems the streams are not coming through, might be the user agent in the request to get the stream manifest. 

![image](https://github.com/user-attachments/assets/3748b6ef-74ba-47e2-b7d8-aec593c89ed8)

**Comment by Tyrrrz** [comment]
I'm not going to be able to investigate for a while, so open to outside help IRT investigations/fixes.

**Comment by ijowett3** [comment]
> I'm not going to be able to investigate for a while, so open to outside help IRT investigations/fixes.

I am happy to help debug this, I need to get a beer and get my head around the underlying youtube/google API.

**Comment by xBaank** [comment]
Some things i discovered while testing:
- `ANDROID_TESTSUITE` client seems to result in 403 for most of the streams.
- `ANDROID` client works but this is still an issue https://github.com/Tyrrrz/YoutubeExplode/issues/705.
- `ANDROID_VR` seems to work, but it obviously doesn't have the same formats.

**Comment by Aequitas00** [comment]
Since https://github.com/yt-dlp/yt-dlp works I looked how they were handling the user agent.

These are some of the user agents they use in the random_user_agent() function https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/utils/networking.py.

**Comment by Jeager2** [comment]
I was able to comment out the offending line and replace by yt-dlp calling this: 

 string YTAPP = "yt-dlp";
 string YTAPPExt = "yt-dlp.exe";

private int DownloadVideoAsyncExternal(string path, string id, int Counter, int MaxNumLength, String SortType, String Arguments, SyncBehavior syncBehavior)
{
    int ReturnMe = 0;
    // 2= success
    // 3= Failure
    // 0= error


    String URL = @"https://www.youtube.com/watch?v=";
    path = (char)34 + path + (char)34;
    URL = (char)34 + URL + id + (char)34;

    String AllArguments = "-o " + path + " " + Arguments + " " + URL;

    // Start the child process.
    Process p = new Process();
    // Redirect the output stream of the child process.
    p.StartInfo.RedirectStandardOutput = false;

    // Make serial instead of seperate thread
   if (syncBehavior == SyncBehavior.Asynchronous)
    {
        p.StartInfo.UseShellExecute = false;
    }
    else
    { 
        p.StartInfo.UseShellExecute = true; 
    }

    p.StartInfo.FileName = @"c:\Download\" + YTAPPExt;
    p.StartInfo.Arguments = AllArguments;
    p.Start();

    if (syncBehavior == SyncBehavior.Synchronous)
    {
        p.WaitForExit(); // WAIT!
    }

    QueuedFlag = true;
  
    return ReturnMe;
}

Hope this helps some of you.

**Comment by ijowett3** [comment]
It's an out of the box suggestion, but does anyone have a android emulator/ be able to run a fidler session while running the yout8be android app? And report on the user agent it's passing?

**Comment by Tyrrrz** [comment]
> Some things i discovered while testing:
> 
> * `ANDROID_TESTSUITE` client seems to result in 403 for most of the streams.
> * `ANDROID` client works but this is still an issue [Sporadic 403 errors in the middle of reading a stream #705](https://github.com/Tyrrrz/YoutubeExplode/issues/705).
> * `ANDROID_VR` seems to work, but it obviously doesn't have the same formats.

If I had to guess, it's because they finally removed `ANDROID_TESTSUITE`. YoutubeExplode probably falls back to the `TVHML5-...` client which requires `n`-signature deciphering, which is currently not supported (also why restricted videos stopped working, e.g. #795).

Need to find a replacement client that works, taking into account #705. Maybe iOS works?

Here's a list of available clients from 2 years ago, but it might be outdated: https://github.com/zerodytrash/YouTube-Internal-Clients

**Comment by ijowett3** [comment]
> > Some things i discovered while testing:
> > 
> > * `ANDROID_TESTSUITE` client seems to result in 403 for most of the streams.
> > * `ANDROID` client works but this is still an issue [Sporadic 403 errors in the middle of reading a stream #705](https://github.com/Tyrrrz/YoutubeExplode/issues/705).
> > * `ANDROID_VR` seems to work, but it obviously doesn't have the same formats.
> 
> If I had to guess, it's because they finally removed [`ANDROID_TESTSUITE`](https://github.com/Tyrrrz/YoutubeExplode/blob/1c6611085a9f786aa64d937b32d77ae04633541a/YoutubeExplode/Videos/VideoController.cs#L50-L79). YoutubeExplode probably falls back to the [`TVHML5-...`](https://github.com/Tyrrrz/YoutubeExplode/blob/1c6611085a9f786aa64d937b32d77ae04633541a/YoutubeExplode/Videos/VideoController.cs#L107-L139) client which requires `n`-signature deciphering, which is currently not supported (also why restricted videos stopped working earlier this year, e.g. #795).
> 
> Need to find a replacement client that works, taking into account #705. Maybe iOS works?
> 
> Here's a list of available clients from 2 years ago, but it might be outdated: https://github.com/zerodytrash/YouTube-Internal-Clients
> 
> Note that finding a working client that doesn't support the full range of video qualities is okay as an interim solution so that at least the library is somewhat working.

What about a pull request that allows  the developer to override the client user agent when making the post request to the underlying google/YouTube api?

**Comment by Tyrrrz** [comment]
> What about a pull request that allows the developer to override the client user agent when making the post request to the underlying google/YouTube api?

It's not that simple. There's too many peculiarities for each client that requires them to be handled differently. It's not as easy as just replacing one string value with another.

**Comment by ijowett3** [comment]
> > What about a pull request that allows the developer to override the client user agent when making the post request to the underlying google/YouTube api?
> 
> It's not that simple. There's too many peculiarities for each client that requires them to be handled differently. It's not as easy as just replacing one string value with another.

Ok, fair enough, when I was debugging the code earlier, I got as far as reading the main payload from the underlying api, it returned the links to the underlying urls for each stream, however, I was struggling to read the stream of each one. Is this what you mean? 

Could it be possible that the main json payload has changed? The json from their API doesn't fully reflect the response object, although admittedly I do wonder if it's trying to load one of those stream urls and that's where it's getting the 403. I'll probably need to spend a bit of time looking at the stack traces

**Comment by Aequitas00** [comment]
Same forbidden problem with https://github.com/omansak/libvideo. Not sure if that can help limit down possibilities.

**Comment by ijowett3** [comment]
I'm assuming this client library emulates the android player api / uses that under the hood. If that's the case, it looks like YouTube have completely turned it off. 

https://developers.google.com/youtube/android/player

This SDK has been fully deprecated. It is no longer supported or maintained by YouTube. Please use the [YouTube IFrame Player API](https://developers.google.com/youtube/iframe_api_reference) instead

**Comment by Zent01** [comment]
will it be solved soon?

**Comment by EBTYX2809** [comment]
I thought my code was wrong, but yeah, after add try/catch block saw same message.

**Comment by EBTYX2809** [comment]
> I was able to comment out the offending line and replace by yt-dlp calling this:
> 
> string YTAPP = "yt-dlp"; string YTAPPExt = "yt-dlp.exe";
> 
> private int DownloadVideoAsyncExternal(string path, string id, int Counter, int MaxNumLength, String SortType, String Arguments, SyncBehavior syncBehavior) { int ReturnMe = 0; // 2= success // 3= Failure // 0= error
> 
> ```
> String URL = @"https://www.youtube.com/watch?v=";
> path = (char)34 + path + (char)34;
> URL = (char)34 + URL + id + (char)34;
> 
> String AllArguments = "-o " + path + " " + Arguments + " " + URL;
> 
> // Start the child process.
> Process p = new Process();
> // Redirect the output stream of the child process.
> p.StartInfo.RedirectStandardOutput = false;
> 
> // Make serial instead of seperate thread
> ```
> 
> if (syncBehavior == SyncBehavior.Asynchronous) { p.StartInfo.UseShellExecute = false; } else { p.StartInfo.UseShellExecute = true; }
> 
> ```
> p.StartInfo.FileName = @"c:\Download\" + YTAPPExt;
> p.StartInfo.Arguments = AllArguments;
> p.Start();
> 
> if (syncBehavior == SyncBehavior.Synchronous)
> {
>     p.WaitForExit(); // WAIT!
> }
> 
> QueuedFlag = true;
> 
> return ReturnMe;
> ```
> 
> }
> 
> Hope this helps some of you.



> I was able to comment out the offending line and replace by yt-dlp calling this:
> 
> string YTAPP = "yt-dlp"; string YTAPPExt = "yt-dlp.exe";
> 
> private int DownloadVideoAsyncExternal(string path, string id, int Counter, int MaxNumLength, String SortType, String Arguments, SyncBehavior syncBehavior) { int ReturnMe = 0; // 2= success // 3= Failure // 0= error
> 
> ```
> String URL = @"https://www.youtube.com/watch?v=";
> path = (char)34 + path + (char)34;
> URL = (char)34 + URL + id + (char)34;
> 
> String AllArguments = "-o " + path + " " + Arguments + " " + URL;
> 
> // Start the child process.
> Process p = new Process();
> // Redirect the output stream of the child process.
> p.StartInfo.RedirectStandardOutput = false;
> 
> // Make serial instead of seperate thread
> ```
> 
> if (syncBehavior == SyncBehavior.Asynchronous) { p.StartInfo.UseShellExecute = false; } else { p.StartInfo.UseShellExecute = true; }
> 
> ```
> p.StartInfo.FileName = @"c:\Download\" + YTAPPExt;
> p.StartInfo.Arguments = AllArguments;
> p.Start();
> 
> if (syncBehavior == SyncBehavior.Synchronous)
> {
>     p.WaitForExit(); // WAIT!
> }
> 
> QueuedFlag = true;
> 
> return ReturnMe;
> ```
> 
> }
> 
> Hope this helps some of you.

yt-dlp is good, but it is 2 times slower than YouTubeExplode.

**Comment by xBaank** [comment]
> > Some things i discovered while testing:
> > 
> > * `ANDROID_TESTSUITE` client seems to result in 403 for most of the streams.
> > * `ANDROID` client works but this is still an issue [Sporadic 403 errors in the middle of reading a stream #705](https://github.com/Tyrrrz/YoutubeExplode/issues/705).
> > * `ANDROID_VR` seems to work, but it obviously doesn't have the same formats.
> 
> If I had to guess, it's because they finally removed [`ANDROID_TESTSUITE`](https://github.com/Tyrrrz/YoutubeExplode/blob/1c6611085a9f786aa64d937b32d77ae04633541a/YoutubeExplode/Videos/VideoController.cs#L50-L79). YoutubeExplode probably falls back to the [`TVHML5-...`](https://github.com/Tyrrrz/YoutubeExplode/blob/1c6611085a9f786aa64d937b32d77ae04633541a/YoutubeExplode/Videos/VideoController.cs#L107-L139) client which requires `n`-signature deciphering, which is currently not supported (also why restricted videos stopped working earlier this year, e.g. #795).
> 
> Need to find a replacement client that works, taking into account #705. Maybe iOS works?
> 
> Here's a list of available clients from 2 years ago, but it might be outdated: https://github.com/zerodytrash/YouTube-Internal-Clients
> 
> Note that finding a working client that doesn't support the full range of video qualities is okay as an interim solution so that at least the library is somewhat working.

With `IOS` client I was able to retrieve formats up to 1080p 60 fps but only in mp4 (no webm support), this caused the tests to fail.
With `ANDROID_VR` tests passed and it seems that https://github.com/Tyrrrz/YoutubeExplode/issues/705 is not an issue, the only problem is that this client doesn't work with `kids` videos like baby shark.

For IOS i used 
https://github.com/yt-dlp/yt-dlp/blob/fa2be9a7c63babede07480151363e54eee5702bd/yt_dlp/extractor/youtube.py#L220-L231

**Comment by ijowett3** [comment]
request.Content = new StringContent(
     // lang=json
     $$"""
     {
       "videoId": {{Json.Serialize(videoId)}},
       "context": {
         "client": {
          'clientName': 'IOS',
          'clientVersion': '19.29.1',
          'deviceMake': 'Apple',
          'deviceModel': 'iPhone16,2',
          'userAgent': 'com.google.ios.youtube/19.29.1 (iPhone16,2; U; CPU iOS 17_5_1 like Mac OS X;)',
          'osName': 'iPhone',
          'osVersion': '17.5.1.21F90'
         }
       }
     }
     """
 );

This seems to work. Nice one @xBaank

**Comment by ijowett3** [comment]
Results of the TDD Tests using the IOS settings above. I'd create a branch but I don't have permissions to push.  

![image](https://github.com/user-attachments/assets/8204cdd3-4d83-40f9-b909-2f99feda09a1)

**Comment by 6accOnThe6locc** [comment]
I think it will be easy to implement, I just don't do it because I don't have the confidence to code in C#. But as you can see in the code below the API response doesn't change that much from the Android API.
![image](https://github.com/user-attachments/assets/58381c5f-88cc-48de-8029-c472a8c9deb2)
```
var adaptiveStreams = StreamingData
                ?.GetPropertyOrNull("adaptiveFormats")
                ?.EnumerateArrayOrNull()
                ?.Select(j => new StreamData(j));
```


[code used](https://gist.github.com/6accOnThe6locc/7bc4f2ee6b255a02780ecdc9c20fd68d)

**Comment by aarushpatilt** [comment]
yt dl core seems to be working as well, i just pivoted mine from yt explode to yt dl core ( for backend nodejs script) for now until issue is fixed.

**Comment by xBaank** [comment]
> I think it will be easy to implement, I just don't do it because I don't have the confidence to code in C#. But as you can see in the code below the API response doesn't change that much from the Android API. ![image](https://private-user-images.githubusercontent.com/87585339/370960108-58381c5f-88cc-48de-8029-c472a8c9deb2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNDMyMTAsIm5iZiI6MTcyNzM0MjkxMCwicGF0aCI6Ii84NzU4NTMzOS8zNzA5NjAxMDgtNTgzODFjNWYtODhjYy00OGRlLTgwMjktYzQ3MmE4YzlkZWIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA5MjgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4MjVlZDBiN2ZiOGQ4YzQ0NjNiZjUyZjUyM2EzZDlhM2JiN2RlMTRhNzM1YzVhZjMyNjVkMTQyMTA5ZjkyZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EvSPrtKPN_Za3wuqlJYpJh67URxA_Rygud70ZIg6jPE)
> 
> ```
> var adaptiveStreams = StreamingData
>                 ?.GetPropertyOrNull("adaptiveFormats")
>                 ?.EnumerateArrayOrNull()
>                 ?.Select(j => new StreamData(j));
> ```
> 
> You can retrieve formats up to 1080p60 (mp4 and webm) ![image](https://private-user-images.githubusercontent.com/87585339/370961605-3e1f76e7-81b8-4528-a761-7288f73b302f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNDMyMTAsIm5iZiI6MTcyNzM0MjkxMCwicGF0aCI6Ii84NzU4NTMzOS8zNzA5NjE2MDUtM2UxZjc2ZTctODFiOC00NTI4LWE3NjEtNzI4OGY3M2IzMDJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA5MjgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmZWQyNzMyODhiZjZmZjFmMGQ1Y2RhN2VhZmUxNjk0Njc3YmNhMmQyMzRjZjVjMjU3NWUxOWM5ZjM0MzBmNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4jtBaCW46JiiAKeO2Hn-GTiQa79iDkBhYCYrTI4Yz4E)
> 
> [code used](https://gist.github.com/6accOnThe6locc/7bc4f2ee6b255a02780ecdc9c20fd68d)

You are right, i missed the headers and I was only getting mp4

**Comment by 6accOnThe6locc** [comment]
I think you need the signatureTimestamp and the x-goog-visitor-id. Did you see my code? It's pretty easy to get.

**Comment by pietronr** [comment]
Yeah, ran into this problema today. Was really confused about it, cuz it was working normally 2 days ago.
Hope it gets fixed soon.

**Comment by dpvdberg** [comment]
Same issue here, unfortunate :(

**Comment by Xxxxmmm** [comment]
When can it be repaired?

> I'm not going to be able to investigate for a while, so open to outside help IRT investigations/fixes.

When can it be repaired? My respected author

**Comment by ijowett3** [comment]
Just update the code with the iOS headers, I don't think it's working with muxed streams tho.

**Comment by Tyrrrz** [comment]
Indeed, muxed streams are no longer available with the `IOS` client. The rest seems to work, from my basic quick testing. I think it's not realistic to expect muxed streams to be available going forward, seeing as YouTube itself doesn't use them.
