### ISSUE TITLE
Library stopped working....

### ISSUE THREAD

**Issue by DanieSpreeth** [Tyrrrz/YoutubeExplode#82]
Since a few days ago my code just suddenly halts without returning any errors on the `"var streamInfoSet = await ytClient.GetVideoMediaStreamInfosAsync(parsedVideoId);"` command. Execution just never returns to the calling thread, ie. any and all of the commands following this `await` never executes....

Any ideas?

PS: At first I thought it could be because I was running it in multiple threads (think I tested 5 max at some stage), but even after bringing it back to just 1 thread, the issue persisted.

**Comment by ndt0126** [comment]
Same issue for me

**Comment by DanieSpreeth** [comment]
Its important that I add - if I try running the ConsoleDemo the author provided then it works, but somehow in my code somewhere is something that stops this from working - what could there be interfering here?

And I need to add - my code DID work and then it stopped working.... This is weird....

**Comment by Tyrrrz** [comment]
Are you sure you both are having the same issue?

@ndt0126 `YoutubeExplode.Exceptions.VideoNotAvailableException` has a `Reason` property, what does it say?

@DanieSpreeth you would have to show some code, it's hard to say. The tests are still working and like you said the demo as well, so it's really weird.

**Comment by DanieSpreeth** [comment]
Nothing weird with the code (I think - see below)... Just added the try~catch now to see if anything gets caught but nothing (breakpoint was at the "pointless" line of code in the catch block). Code executes up to the first line in the `try` block then never returns.

`private async Task StartVideoDownloader()
        {
            this.DownloadStartTimeStamp = DateTime.Now;
            if (!Directory.Exists(m_listItemToDownload.SavePath))
                Directory.CreateDirectory(m_listItemToDownload.SavePath);
            var ytClient = new YoutubeClient();
            try
            {
                m_streamInfoSet = await ytClient.GetVideoMediaStreamInfosAsync(m_parsedVideoId);
                var streamInfo = m_streamInfoSet.Muxed.First(si => si.VideoQuality == VideoQuality.High720);
                var ext = streamInfo.Container.GetFileExtension();
                m_progressList = new Progress<double>(p => UpdateProgressBar(p));
                await ytClient.DownloadMediaStreamAsync(streamInfo,
                                                          Path.Combine(m_listItemToDownload.SavePath,
                                                                            MakeValidFileName(string.Format("{0}.{1}",
                                                                                m_listItemToDownload.YouTubeVideo.Title,
                                                                                ext))),
                                                          m_progressList);
            }
            catch(Exception ex)
            {
                int i = 0;
            }            
        }`

Unless you can see something I missed, I doubt the code above will help - what else can be an interference here?

**Comment by TheInsaneBro** [comment]
The problem probably lies within `UpdateProgressBar`. Can you show us more of that?

**Comment by DanieSpreeth** [comment]
nope - as I said - first reference to that method (and the 2 lines above it) never gets executed.
Nothing gets executed after the first statement in the TRY block:

m_streamInfoSet = await ytClient.GetVideoMediaStreamInfosAsync(m_parsedVideoId);

**Comment by TheInsaneBro** [comment]
Hm, indeed this is pretty weired. On what video are you testing it? In a submethod called by `GetVideoMediaStreamInfosAsync` there is a [`TODO: check if video is available`](https://github.com/Tyrrrz/YoutubeExplode/blob/master/YoutubeExplode/YoutubeClient.Video.cs#L33). Could have something to do with it.

**Comment by Tyrrrz** [comment]
@TheInsaneBro that todo is for a more coherent exception, it still shouldn't freeze. There are only a few reasons it can freeze like that, especially beyond the timeout.

@DanieSpreeth can you add `ServicePointManager.DefaultConnectionLimit = 999;` somewhere before the try/catch and see if it "helps". If it does, someone wasn't disposing things properly. 😛

**Comment by ndt0126** [comment]
OK so I didn't update YoutubeExplode since the work-around last time, until it stopped working today. So after I cloned the repo and re-added it directly, it works again.

**Comment by Tyrrrz** [comment]
@ndt0126 you can also just update it to 4.0.0

**Comment by DanieSpreeth** [comment]
Sorry for taking this long to respond - sorry but adding "ServicePointManager.DefaultConnectionLimit = 999;" had no effect whatsoever. Problem still persists... I actually implemented another Youtube downloader component with success but still would prefer using this one...

**Comment by Tyrrrz** [comment]
Can you make a minimal project that reproduces this issue and put it on github?

**Comment by patrux** [comment]
I had this same problem. After some fiddling I managed to make GetVideoMediaStreamInfosAsync give me an error stating my Json version differed from the one in this project. Removing the reference in my project made it work like a charm.

**Comment by Kriste00** [comment]
For me everything works, but `DownloadMediaStreamAsync` takes about a minute to download a video thats only 2-3 minutes long.

**Comment by Tyrrrz** [comment]
@Kriste00 video id? does it download faster if you open the media stream via URL?

**Comment by Kriste00** [comment]
I use `GetVideoMediaStreamInfosAsync(VidId)`, but should i use an url instead of the id?

**Comment by Kriste00** [comment]
It happens on all videos i try to download.

**Comment by Tyrrrz** [comment]
Seems to be the case, create a separate issue

**Comment by Tyrrrz** [comment]
@DanieSpreeth still having issues?
