### ISSUE TITLE
Input stream collection is empty 

### ISSUE THREAD

**Issue by Zent01** [Tyrrrz/YoutubeExplode#822]
### Version

 v6.4.2

### Platform

.NET8.0/Windows 10

### Steps to reproduce

Today, I  tried to download a video, but I encountered an error

### Details

Expected Behavior
The application should start downloading the video and the input stream collection should not be empty.
Actual Behavior
The input stream collection is empty, and the application does not initiate the download.

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the package
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by Tyrrrz** [comment]
![image](https://github.com/user-attachments/assets/aa86f5ab-4891-4a59-9ca2-283e3364fbe4)
