### ISSUE TITLE
crashing in my app

### ISSUE THREAD

**Issue by TariqAlsunaydih** [Tyrrrz/YoutubeExplode#828]
### Version

6.4.3

### Platform

Visual Studio for Mac

### Steps to reproduce

Hi, I'm finding a problem stream video in my app
once I click play button it shows this kind of problem 
<img width="932" alt="‏لقطة الشاشة ١٤٤٦-٠٤-١٠ في ٩ ١٥ ٠٢ م" src="https://github.com/user-attachments/assets/bead1494-11da-4093-9e06-8f1293dd8e1a">

### Details

<img width="864" alt="‏لقطة الشاشة ١٤٤٦-٠٤-١٠ في ٩ ١٦ ٣٣ م" src="https://github.com/user-attachments/assets/8697ea51-942d-43d2-9198-4d6f6a751023">
This is the class

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the package
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [X] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by Tyrrrz** [comment]
Muxed streams don't exist
