### ISSUE TITLE
Unable to fetch stream using GetMuxedStreams

### ISSUE THREAD

**Issue by apreet81** [Tyrrrz/YoutubeExplode#833]
### Version

6.4.3

### Platform

Windows 10

### Steps to reproduce

trying to download below 2 videos but GetMuxedStreams is not returning any stream.

https://www.youtube.com/watch?v=uMtJgN0prME
https://www.youtube.com/watch?v=lWZIHoAwu2c

### Details
**Code used**
var streamInfo = streamManifest.GetMuxedStreams().Where(s => s.Container == Container.Mp4).GetWithHighestVideoQuality();

**Exception Message**
Input stream collection is empty.

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the package
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by apreet81** [comment]
Just noticed it started happening on almost all videos

**Comment by mixail167** [comment]
StreamManifest returns "Video-Only" and "Audio-Only" streams.

**Comment by apreet81** [comment]
In version 6.3.13 GetMuxedStreams was working fine until signin error.

Any option to get Video combined with Audio?

**Comment by mixail167** [comment]
![image](https://github.com/user-attachments/assets/9a569f7f-8c52-4665-b38f-94e5ef79363b)
