### ISSUE TITLE
Doesn't work on Windows Form App

### ISSUE THREAD

**Issue by HenglyEver** [Tyrrrz/YoutubeExplode#92]
I tried it in Console App first and it worked perfectly so I started to do it again on Windows Form App and it turned out not working at all. When the method like GetVideoAsync() or GetVideoMediaStreamInfosAsync() run, the whole thing is not running, I tried to create a thread just for it the program is stopped immediately.
Anyone know the solution?

**Comment by Tyrrrz** [comment]
Can you post code that replicates it?

**Comment by HenglyEver** [comment]
Yes, of course. The one that I did is so messy now. After I knew there might be some problem I created a new project and just want the title of a video when I click a button but it stops running after that method I mention above.

Here's the code:

`using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using YoutubeExplode;
namespace Test
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private async Task TheTask()
        {
            var url = "https://www.youtube.com/watch?v=MwtvktjEuOM";
            var id = YoutubeClient.ParseVideoId(url);
            var client = new YoutubeClient();
            var video = await client.GetVideoAsync(id);
            MessageBox.Show(video.Title);
        }

        private void btnTest_Click(object sender, EventArgs e)
        {
            Task T = TheTask();
            T.Wait();
        }
    }
}
`

**Comment by Tyrrrz** [comment]
You are probably deadlocking the UI. Remove `T.Wait();`.

**Comment by Tyrrrz** [comment]
Or replace this line `var video = await client.GetVideoAsync(id);` with `var video = await client.GetVideoAsync(id).ConfigureAwait(false);`

**Comment by HenglyEver** [comment]
I accidentally removed my comment.
Here is link to the photo of the code : https://ibb.co/koy3g6

**Comment by HenglyEver** [comment]
Oh wow! Both solutions work very well, but I have a question, if I remove `T.Wait();`, will the code below it run before the asynchrous method complete?

**Comment by Tyrrrz** [comment]
Yeah it will. The second solution is better in this case. The mistake you were making is waiting on the same thread as the one that was executing, so you entered a deadlock.

**Comment by HenglyEver** [comment]
I did the same thing on Console App and it worked, that's why I did it in Windows Form App, but anyway, Thank you.

**Comment by Tyrrrz** [comment]
You're welcome!

**Comment by HenglyEver** [comment]
And one more thing beside this problem, why doesn't the Muxed have 1080p?

**Comment by Tyrrrz** [comment]
Well that's just how it is, they are deprecated and YouTube doesn't use them AFAIK, so they are restricted in quality.

**Comment by HenglyEver** [comment]
I tried to put the video that only has 144p resolution but there're two 360p and also 240p, can you explain that?

**Comment by Tyrrrz** [comment]
Nope, but if it works -- enjoy ;)

**Comment by Tyrrrz** [comment]
Actually, one of the 360ps is probably misidentified. Can you give video ID?

**Comment by HenglyEver** [comment]
Here is the video ID : qo8iYgVmKl8

**Comment by Tyrrrz** [comment]
Nope, they're not misidentified, that's just how it is.

**Comment by HenglyEver** [comment]
Okay, I'm just asking because there is no 360p. Like in this photo [https://ibb.co/jyQVuR](url)
Thank you for replying :) It's 4 AM in my country now, I should get some sleep.

**Comment by Tyrrrz** [comment]
You'd have to ask YouTube that question :p
