### ISSUE TITLE
Download M4A instead of WebM

### ISSUE THREAD

**Issue by Kajirinn** [Tyrrrz/YoutubeExplode#93]
Hey there,

First of all I'd like to thank you for making this; it made my life a whole lot easier.
I was wondering how to download an audio stream as M4A. Even though it might not have the highest bitrate, I haven't found anything that can play WebM files in Visual studio 2017.

I'd also like to know if it's possible to ' stream ' the audio instead of downloading.

Thanks in advance,

_Kaji-_

**Comment by Tyrrrz** [comment]
Yeah most videos also have M4A streams. You can filter them out by doing `mediaStreamInfoSet.Audio.Where(s => s.Container == Container.M4A)`. You can get the media stream using `await youtubeClient.GetMediaStreamAsync(...)`.

**Comment by Kajirinn** [comment]
Thanks for your fast reply, sorry if I sound like an idiot but Container doesn't have an option for M4A.

`var audioInfo = streamInfoSet.Audio.Where(s => s.Container == YoutubeExplode.Models.MediaStreams.Container.M4A);
`
That however does but generates the following error:

'IEnumerable<AudioStreamInfo>' does not contain a definition for 'Container' and no extension method 'Container' accepting a first argument of type 'IEnumerable<AudioStreamInfo>' could be found (are you missing a using directive or an assembly reference?)'

I am using 'using YoutubeExplode.Models.MediaStreams;' so I can't get head around the problem here. I'm fairly new to mediastreams and all; so sorry to bother you with this.

`await youtubeClient.GetMediaStreamAsync(...)` and with that I can play the audio? I'm not sure how to but thanks nonetheless.

**Comment by Tyrrrz** [comment]
That shouldn't give an error, can you post the full code?

You can use `GetMediaStreamAsync` to get the media stream which is essentially a stream of raw bytes that you can feed to a media player. Or you can use the `Url` property on the `MediaStreamInfo` if your player supports playing over https.

**Comment by Kajirinn** [comment]
Ah I see, thanks alot!

`var id = YoutubeClient.ParseVideoId(url);
dlext = string.Empty;

var client = new YoutubeClient();
var streamInfoSet = await client.GetVideoMediaStreamInfosAsync(id);

var audioInfo = streamInfoSet.Audio.Where(s => s.Container == Container.M4A);

dlext = audioInfo.Container.GetFileExtension();

var progress = new Progress<double>(p => HeaderLabel.Text = $"Progress: {p:P0}");

await client.DownloadMediaStreamAsync(audioInfo, $@"D:\Downloads\{title}.{dlext}", progress);

mediaPlayer.URL = $@"D:\Downloads\{title}.{dlext}";`

[The error](https://i.imgur.com/o5SzlFz.png)

**Comment by Tyrrrz** [comment]
You have some other type called `IContainer`?

**Comment by Kajirinn** [comment]
[Well, its the first time I've ever used containers but it does state here that it is.](https://i.imgur.com/9q1Iuf7.png)

**Comment by Tyrrrz** [comment]
That's a different type, from some other library.

**Comment by Kajirinn** [comment]
I haven't added any myself, is it a problem that I'm using it in a windows form application?

**Comment by Tyrrrz** [comment]
Seems like it. Add `using Container = YoutubeExplode.Models.MediaStreams.Container` at the top.

**Comment by Kajirinn** [comment]
Yea that isn't working, it works when I remove using `System.Windows.Forms;` but that obviously isn't a solution. I'll look more into it and update once I found something; thanks o/

**Comment by Kajirinn** [comment]
Is there another way to do this? If not I'll just have to live with converting the WebM to M4A outside of YoutubeExplode.

**Comment by Tyrrrz** [comment]
What I said should fix it, that or use fully qualified names when referring to `YoutubeExplode.Models.MediaStreams.Container`.

**Comment by Kajirinn** [comment]
I tried that but its giving me [this](https://i.imgur.com/R9iZbBF.png) error...

**Comment by Tyrrrz** [comment]
Well that's because `Where` returns an `IEnumerable<T>`. If you want one, call `First`.

**Comment by Kajirinn** [comment]
I see! It works now; thanks alot :)
