### ISSUE TITLE
5K video support

### ISSUE THREAD

**Issue by jasonspar** [Tyrrrz/YoutubeExplode#95]
It doesn't seem to return the correct resolution for 2880p / 5K videos like this one:

https://www.youtube.com/watch?v=WJ30W-K7gbY

**Comment by Tyrrrz** [comment]
It appears itag 272 can have multiple video qualities. :/

**Comment by Tyrrrz** [comment]
Looks like it's attributed to videos from [1440p](https://www.youtube.com/watch?v=RtoitU2A-3E) to [4320p](https://www.youtube.com/watch?v=sLprVF6d7Ug). Parsing quality labels from metadata is possible but it involves a lot of overhead that itag matching was supposed to eliminate. I'm still not sure what's an appropriate solution, but as a workaround you can use the `VideoResolution` property to match videos of desired quality.

**Comment by Tyrrrz** [comment]
I found a clean way to fix this. Interestingly, the 5k video stream is almost half the bitrate and size of the 4k video stream. I double checked and it seems to be correct.
